      SUBROUTINE SOSOPN(IUNIT, FNAME)
      INTEGER IUNIT
      CHARACTER*(*) FNAME
      OPEN(UNIT=IUNIT, FILE=FNAME, STATUS='REPLACE',
     $     FORM='FORMATTED', ACTION='WRITE')
      RETURN
      END

      SUBROUTINE SOSCLS(IUNIT)
      INTEGER IUNIT
      CLOSE(UNIT=IUNIT)
      RETURN
      END
