
      SUBROUTINE BADSET(CLWR,CUPR,CVEC,VECLAM,VECNU,XLWR,XUPR,XVEC,
     $    ISTATC,ISTATV,CONTOL,MCON,MDIM,NDIM,BADACT)
C
C ======================================================================
C     BADSET===>BADSET   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         PURPOSE:  CHECK ACTIVE SET TO SEE IF IT IS CORRECT 
C
C         INPUT:
C
C            CLWR   CONSTRAINT LOWER BOUND (MDIM)
C            CUPR   CONSTRAINT UPPER BOUND (MDIM)
C            CVEC   CONSTRAINT VECTOR (MDIM)
C            VECLAM LAGRANGE MULTIPLIERS (MDIM)
C            VECNU  INDEP. VARIABLE MULTIPLIERS (NDIM)
C            XLWR   VARIABLE LOWER BOUNDS (NDIM)
C            XUPR   VARIABLE UPPER BOUNDS (NDIM)
C            XVEC   VARIABLES (NDIM)
C            ISTATC CONSTRAINT STATUS ARRAY (MDIM)
C            ISTATV VARIABLE STATUS ARRAY (NDIM)
C            CONTOL CONSTRAINT TOLERANCE
C            MCON   NUMBER OF CONSTRAINTS
C            MDIM   DIMENSION OF CONSTRAINT ARRAYS
C            NDIM   NUMBER OF VARIABLES
C
C         OUTPUT:
C
C            BADACT LOGICAL FLAG
C                   = TRUE  ACTIVE SET DEFINED BY CURRENT 
C                           ISTATC AND/OR ISTATV IS NOT CORRECT
C                   = FALSE ACTIVE SET DEFINED BY ISTATC AND ISTATV 
C                           IS OK
C
      DIMENSION CLWR(MDIM),CUPR(MDIM),CVEC(MDIM),VECLAM(MDIM),
     $    VECNU(NDIM),XLWR(NDIM),XUPR(NDIM),XVEC(NDIM),
     $    ISTATC(MDIM),ISTATV(NDIM)
C
      COMMON /KONSTN/ 
     *  ZEROMN  ,ZEROOT  ,BIGNUM  ,BGROOT  ,BIGBND  ,BIGCND
C
      LOGICAL BADACT
      PARAMETER (ZERO=0.0D0,ONE=1.0D0)
C
      BADACT = .FALSE.
C
C         VARIABLE BOUNDS
C
C         COMPUTE LARGEST MAGNITUDE MULTIPLIER
C         COMPUTE CONSTRAINT ERRORS AND CHECK MULTIPLIERS
C
      ERBINQ = ZERO
      XNUMAX = ZERO
      SMALNU = BIGNUM
      BIGNU = -BIGNUM
      DO I = 1,NDIM
C
        XNUMAX = MAX(XNUMAX,ABS(VECNU(I)))
        IF(ISTATV(I).EQ.0) THEN
C
C         CHECK VIOLATION FOR (CURRENTLY) INACTIVE BOUNDS
C
          IF(XVEC(I).LT.XLWR(I)+CONTOL) THEN
C
C         LOWER BOUND INEQUALITY CONSTRAINT
C
            ERBINQ = MAX(ERBINQ, XLWR(I) - XVEC(I) )
C
          ELSEIF(XVEC(I).GT.XUPR(I)-CONTOL) THEN
C
C         UPPER BOUND INEQUALITY CONSTRAINT
C
            ERBINQ = MAX(ERBINQ, XVEC(I) - XUPR(I) )
C
          ENDIF
C
        ELSEIF(ISTATV(I).EQ.1) THEN
C
          SMALNU = MIN(SMALNU, VECNU(I))
C
        ELSEIF(ISTATV(I).EQ.2) THEN
C
          BIGNU = MAX(BIGNU, VECNU(I))
C
        ENDIF
C
      ENDDO
C
C         NONLINEAR CONSTRAINT CALCULATIONS
C
C         COMPUTE LARGEST MAGNITUDE MULTIPLIER
C         COMPUTE CONSTRAINT ERRORS AND CHECK MULTIPLIERS
C
      ERRINQ = ZERO
      XLAMAX = ZERO
      SMALAM = BIGNUM
      BIGLAM = -BIGNUM
      DO I = 1,MCON
C
        XLAMAX = MAX(XLAMAX,ABS(VECLAM(I)))
        IF(ISTATC(I).EQ.0) THEN
C
C         CHECK VIOLATION FOR (CURRENTLY) INACTIVE BOUNDS
C
          IF(CVEC(I).LT.CLWR(I)+CONTOL) THEN
C
C         LOWER BOUND INEQUALITY CONSTRAINT
C
            ERRINQ = MAX(ERRINQ, CLWR(I) - CVEC(I) )
C
          ELSEIF(CVEC(I).GT.CUPR(I)-CONTOL) THEN
C
C         UPPER BOUND INEQUALITY CONSTRAINT
C
            ERRINQ = MAX(ERRINQ, CVEC(I) - CUPR(I) )
C
          ENDIF
C
        ELSEIF(ISTATC(I).EQ.1) THEN
C
          SMALAM = MIN(SMALAM, VECLAM(I))
C
        ELSEIF(ISTATC(I).EQ.2) THEN
C
          BIGLAM = MAX(BIGLAM, VECLAM(I))
C
        ENDIF
C
      ENDDO
C
C         COMBINE CONSTRAINT AND BOUND ERRORS 
C
      ERRINQ = MAX(ERRINQ,ERBINQ)
C
C         ARE THE INEQUALITIES IN THE ACTIVE SET STILL SATISFIED?
C
      IF(ERRINQ.GE.CONTOL) BADACT = .TRUE.
C
C         DO THE MULTIPLIERS IN THE ACTIVE SET HAVE THE CORRECT SIGN?
C
      SMTEST = (XLAMAX + SMALAM) - XLAMAX
      BGTEST = (XLAMAX + BIGLAM) - XLAMAX
      TSTSNU = (XNUMAX + SMALNU) - XNUMAX
      TSTBNU = (XNUMAX + BIGNU) - XNUMAX
C
      IF(SMTEST.GT.ZERO.AND.BGTEST.LT.ZERO.AND.
     $         TSTSNU.GT.ZERO.AND.TSTBNU.LT.ZERO) THEN
C
C         LAGRANGE MULTIPLIERS HAVE CORRECT SIGN
C
      ELSEIF(SMTEST.GT.-ZEROOT.AND.BGTEST.LT.ZEROOT.AND.
     $         TSTSNU.GT.-ZEROOT.AND.TSTBNU.LT.ZEROOT) THEN
C
C         WEAK SOLUTION -- MULTIPLIERS NEAR ZERO, BUT OTHERWISE
C         OPTIMALITY CONDITIONS ARE SATISFIED
C
      ELSE
C
C         MULTIPLIER SIGNS ARE NOT CORRECT
C
        BADACT = .TRUE.
C
      ENDIF
C
      RETURN
      END
