      SUBROUTINE BRSRCH( NVAR, NEQNS, NRES, MSUBE, MSUBB, NSLK, 
     $                   DIAGNL, LINEAR, USEW, IPU, IPC, 
     $                   NONZR, IROWR, JCOLR, RMAT,
     $                   NONZB, IROWB, JCOLB, BMAT, 
     $                   NONZC, IROWC, JCOLC, CMAT, NONZW, IROWW,
     $                   JCOLW, WMAT, MU, BVEC, MAXBND, CVEC,
     $                   MAXCON, GRADL, GVEC, ETA, LAMBDA,    
     $                   LNRWRK, RWORK,
     $                   ITEMP, NZROWB, ROWSCL, COLSCL, 
     $                   RTHBKT, SOLNKT, LNSYMB, CNDNUM, NEEDED,
     $                   DY, DZ, MAXRES, DETA, DLMBDA, EIGMIN, EIGMAX, 
     $                   ADDHSS, RESET,  ITERM  ) 
C
C
C =====================================================================
C     BRSRCH===>brsrch   J.T. Betts
C =====================================================================
C
C
C         PURPOSE:  SETUP THE CALL TO BARKKT,
C                   FACTORS AND SOLVES THE INTERNAL FORM
C                   OF THE INTERIOR POINT KKT SYSTEM.
C                   BRSRCH WILL INCREASE THE VALUE
C                   OF THE INPUT LEVENBERG PARAMETER DIAGNL
C                   IN CASE OF FACTORIZATION OR SOLVE FAILURES IN 
C                   BARKKT. AS A LAST RESORT, WHEN DIAGNL REACHES
C                   ITS MAX VALUE OF 1.0, BRSRCH RESETS THE UPPER
C                   LEFT BLOCK OF THE HESSIAN (CORRESPONDING TO
C                   THE NON-SLACK VARS) TO THE IDENTITY.
C
C         INPUT:    
C
C             NVAR      NUMBER OF VARIABLES (I.E. THE DIMENSION OF Y
C                       VECTOR)
C             NEQNS     NUMBER OF EQUATIONS IN KKT SYSTEM=NVAR+NRES+
C                       MSUBE+MSUBB
C             NRES      NUMBER OF LEAST-SQUARES EQUATIONS
C             MSUBE     NUMBER OF EQUALITY CONSTRAINTS (ALSO, THE
C                       NUMBER OF ROWS IN CMAT)
C             MSUBB     NUMBER OF BOUNDS CONSTRAINTS (ALSO, THE NUMBER
C                       OF ROWS IN BMAT)
C             NSLK      NUMBER OF SLACK VARS, I.E. NUMBER OF
C                       INEQUALITITES IN THE EXTERNAL PROBLEM
C                       FORMULATION
C
C             DIAGNL    LEVENBERG PARAMETER (0 .LE. DIAGNL .LE. 1) 
C                       WHEN DIAGNL = 1, HESSIAN IS POS. DEF.
C             LINEAR    LOGICAL FLAG SET TRUE FOR PROBLEMS WITH
C                       LINEAR LAGRANGIANS
C             USEW      LOGICAL FLAG: TRUE WHEN USING WMAT, FALSE OTHERWISE
C
C             IPU       OUTPUT UNIT NO.
C             IPC       OUTPUT CONTROL FLAG
C
C
C             NONZR     DIMENSION OF RMAT (GE. JCOLR(NVAR+1) - 1)
C             IROWR     INTEGER ROW INDEX VECTOR (NONZR)
C             JCOLR     INTEGER COLUMN START VECTOR (NVAR+1)
C             RMAT      NONZERO ELEMENTS OF LINEAR SYSTEM (NONZR)
C
C             NONZB     DIMENSION OF BMAT (GE. JCOLB(NVAR+1) - 1)
C             IROWB     INTEGER ROW INDEX VECTOR (NONZB)
C             JCOLB     INTEGER COLUMN START VECTOR (NVAR+1)
C             BMAT      NONZERO ELEMENTS OF LINEAR SYSTEM (NONZB)
C
C             NONZC     DIMENSION OF CMAT (GE. JCOLC(NVAR+1) - 1)
C             IROWC     INTEGER ROW INDEX VECTOR (NONZC)
C             JCOLC     INTEGER COLUMN START VECTOR (NVAR+1)
C             CMAT      NONZERO ELEMENTS OF LINEAR SYSTEM (NONZC)
C
C             NONZW     DIMENSION OF WMAT (.GE. JCOLW(NVAR+1)-1 )
C             IROWW     INTEGER ROW INDEX VECTOR (NONZW)
C             JCOLW     INTEGER COLUMN START VECTOR (NVAR+1)
C             WMAT      NONZERO ELEMENTS OF LOWER TRIANGLE OF WMAT
C                       (NONZW)
C
C             MU        AMOUNT OF RELAXATION OF COMPLEMENTARITY
C                       CONDITIONS
C
C             BVEC      BOUNDS CONSTR VALUES AT POINT Y (MAXBND)
C             MAXBND    MAX NUMBER OF BOUNDS 
C             CVEC      EQUALITY CONTRAINT VALUES AT POINT Y
C                       (MAXCON)
C             MAXCON    MAX NUMBER OF CONSTRAINTS
C
C             GRADL     GRADIENT OF THE LAGRANGIAN AT PT Y, 
C                       I.E. G(Y) -C(TR)*ETA -B(TR)*LAMBDA
C                       (NVAR VECTOR) 
C             GVEC      GRADIENT OF OBJECTIVE AT Y (NVAR)
C             ETA       MULIPLIERS FOR THE EQUALITY CONSTRS
C                       (MAXCON)
C             LAMBDA    MULIPLIERS FOR THE BOUNDS CONSTRS
C                       (MAXBND)
C
C             LNRWRK    LENGTH OF RWORK ARRAY (SEE BELOW)
C             RWORK     REAL WORK ARRAY (LNRWRK)
C
C                       LOWER BOUNDS FOR THE WORK ARRAYS
C                       REAL:
C                         LNRWRK > NKT + 4*NEQNS + 150
C                       WHERE
C                         NKT  > NRES + MSUBB + MSUBE + 1 + NONZW
C                                + NONZC + NONZR
C                         NEQNS = NVAR + NRES + MSUBE + MSUBB
C
C             ITEMP     INTEGER WORK ARRAY (NEQNS)
C             NZROWB    INTEGER UTILITY ARRAY TO STORE COUNTS OF
C                       NONZEROS IN ROWS OF BMAT (MSUBB VECTOR)
C
C
C        INPUT/OUTPUT:
C
C             DIAGNL    BRSRCH MAY MODIFY THIS LEVENBERG PARAMETER
C             LINEAR    ON OUTPUT, LINEAR IS SET TRUE WHEN IT IS 
C                       DETERMINED THAT THE LAGRANGIAN IS (NEARLY)
C                       LINEAR
C
C
C         OUTPUT:
C
C             ROWSCL    ROW SCALING VECTOR FOR KKT SYSTEM (NEQNS)
C             COLSCL    COLUMN SCALING VECTOR FOR KKT SYSTEM (NEQNS)
C             RTHBKT    RIGHT HAND SIDE OF THE KKT SYSTEM (NEQNS)
C             SOLNKT    SOLUTION OF THE KKT SYSTEM (NEQNS)
C
C             RWORK     WORK ARRAY CONTAINING MULTIFRONTAL
C                       FACTORIZATION INFORMATION FOR SUBSEQUENT USE
C                       STORED AS FOLLOWS
C                       RWORK(1) -- SYMBOLIC FACTORIZATION DATA
C                                   (LNSYMB)
C                       RWORK(LNSYMB+1) -- NUMERIC FACTORIZATION DATA 
C                                          (LNRWRK)
C
C             LNSYMB    LENGTH OF RWORK ARRAY NEEDED FOR SYMBOLIC
C                       FACTORIZATION
C             CNDNUM    CONDITION NUMBER OF MATRIX
C             NEEDED    STORAGE REQUIRED WHEN LNRWRK IS TOO SMALL
C
C             DY        STEP IN THE VARIABLES, Y (NVAR VECTOR)
C             DZ        STEP IN THE LEAST SQUARES VARIABLES (MAXRES
C                       VECTOR). NOTE THAT DZ SHOULD = R*DY
C             DETA      STEP IN THE EQUALITY CONSTR MULTIPLIERS, 
C                       ETA (MAXCON)
C             DLMBDA    STEP IN THE BOUNDS CONSTR MULTIPLIERS, 
C                       LAMBDA (MAXBND)
C
C             EIGMIN    MINIMUM EIGENVALUE ESTIMATE
C             EIGMAX    MAXIMUM EIGENVALUE ESTIMATE
C             ADDHSS    THE AMOUNT ADDED TO THE UPPER BLOCK (CORRES TO 
C                       TO NON-SLACK VARS) OF THE HESSIAN MATRIX WMAT
C
C             RESET     LOGICAL FLAG SET TRUE WHEN HESSIAN AND
C                       LAGRANGE MULTIPLIERS ARE RESET
C
C             ITERM     TERMINATION CODE HAS THE FOLLOWING MEANING:
C                         0   SUCCESSFUL FACTORIZATION AND SOLVE OF KKT
C                             SYSTEM
C                        -6   I/O ERROR DURING MULTIFRONTAL
C                        -8   MORE WORKING STORAGE NEEDED (SEE
C                             "NEEDED")
C                       -10   BARKKT FAILED AND HESSIAN HAS BEEN RESET.
C                             PERHAPS THE CONSTRAINTS ARE LOCALLY 
C                             INCONSISTENT. 
C                       -11   INPUT ERROR TO MULTIFRONTAL
C                       -12   INTERNAL ERROR IN SYMBOLIC FACTORIZATION
C                             (FROM MULTIFRONTAL CODE)
C                       -13   AN ERROR FROM BARKKT, OTHER THAN THOSE
C                             LISTED ABOVE
C
C
C     ...COMMON BLOCKS
C
      INCLUDE '../commons/NLPSPR.CMN'
      INCLUDE '../commons/BARNLP.CMN'
C
      INTEGER INSTAT
      DOUBLE PRECISION RLSTAT 
      COMMON /STATIS/ INSTAT(30),RLSTAT(20)
C
      DOUBLE PRECISION ZEROMN, ZEROOT, BIGNUM, BGROOT, BIGBND, BIGCND
      COMMON /KONSTN/  ZEROMN, ZEROOT, BIGNUM, BGROOT, BIGBND, BIGCND
C
C
      INTEGER MAXLVN, LEVNIT
      PARAMETER (MAXLVN=15)
      CHARACTER(LEN=60) LEVNDY(MAXLVN)
      COMMON /LEVNP1/ LEVNIT
      COMMON /LEVNP2/ LEVNDY
C
C
C
C     ...SUBROUTINE CALLING ARGUMENTS
C
      LOGICAL RESET
      LOGICAL LINEAR,USEW
C
      INTEGER MAXBND, MAXCON, MAXRES
      INTEGER NVAR, NEQNS, NRES, MSUBE, MSUBB, NSLK
      INTEGER NEQNCB
      INTEGER IPU, IPC
      INTEGER LNSYMB, IERBKT
      INTEGER LNRWRK, NEEDED, ITERM
      INTEGER NONZR, NONZB, NONZC, NONZW
      INTEGER IROWR(NONZR), JCOLR(NVAR+1)
      INTEGER IROWB(NONZB), JCOLB(NVAR+1)
      INTEGER IROWC(NONZC), JCOLC(NVAR+1)
      INTEGER IROWW(NONZW), JCOLW(NVAR+1)
      INTEGER ITEMP(NEQNS)
      INTEGER NZROWB(*)
C
      DOUBLE PRECISION DIAGNL, ADDHSS, MU, CNDNUM
      DOUBLE PRECISION BVEC(MAXBND), CVEC(MAXCON), GRADL(NVAR), 
     $                 GVEC(NVAR), ETA(MAXCON), LAMBDA(MAXBND)
      DOUBLE PRECISION DY(NVAR), DZ(MAXRES), DETA(MAXCON), 
     $                 DLMBDA(MAXBND)
      DOUBLE PRECISION RMAT(NONZR), BMAT(NONZB)
      DOUBLE PRECISION CMAT(NONZC), WMAT(NONZW)
      DOUBLE PRECISION RTHBKT(NEQNS), SOLNKT(NEQNS)
      DOUBLE PRECISION ROWSCL(NEQNS), COLSCL(NEQNS)
      DOUBLE PRECISION RWORK(LNRWRK)
C
C
C
C     ...LOCAL VARIABLES
C
      INTEGER I, KCOL, NEEDRW, NCALL, NUMFAC, IPCBKT
C
      DOUBLE PRECISION DAMAX,  GNORM
      DOUBLE PRECISION EIGMIN, EIGMAX, EIGBND, EIGLIM
      DOUBLE PRECISION HMTNRM, HDIAG, DIAGNW
C
      DOUBLE PRECISION ZERO, ONE, TWO, TEN
      PARAMETER ( ZERO=0.0D0, ONE=1.0D0, TWO=2.0D0, TEN=1.0D1 )
C
      CHARACTER(LEN=60) BLANK
      DATA BLANK(1:60) / ' '/
C
C
C         START BRSRCH TIMING CLOCKS
C
      CALL CLKBEG(4)
      CALL CLKBEG(5)
C
C     SET OUTPUT FOR BARKKT
C
      IPCBKT = 0
      IF(IPC.GE.30) IPCBKT = IPC
C 
C     INITIALIZE IERBKT (SO IT HAS A VALUE IN THE "IF" TEST BELOW
C     STATEMENT LABELED 140. ALSO, INITIALIZE NUMFAC AND RESET.
C
      IERBKT = 0
      NUMFAC = 0
      RESET = .FALSE.
C
      GNORM = DAMAX( NVAR, GRADL, 1 )
C
C     DETERMINE IF SIZE OF REAL WORK ARRAY IS LARGE ENOUGH FOR
C     GERSCHGORIN BOUND COMPUTATION.
C
      NEEDRW = NVAR-NSLK
      IF( LNRWRK .LE. NEEDRW ) THEN
        NEEDED =  NEEDRW + 2
        ITERM = -8
        GO TO 10000
      ENDIF
C 
C
C ---------------------------------------------------------------------
C
C             COMPUTE SEARCH DIRECTION
C
C     COMPUTE THE ROW NORMS FOR THE 1ST NVAR-NSLK ROWS OF WMAT.
C     THAT IS, THE ROWS THAT CORRESPOND TO EXTERNAL PROBLEM VARIABLES.
C     NOTE FOR I = 1,...,NVAR-NSLK ,
C       RWORK(I) = 2|WMAT(I,I)| + SUM (I.NE.J) |WMAT(I,J)|
C         
      IF(USEW) THEN
C
        RWORK(1:NVAR-NSLK) = ZERO
C
C
        DO KCOL = 1, NVAR-NSLK
C
          DO I = JCOLW(KCOL), JCOLW(KCOL+1)-1
C
C         CONTRIBUTION FOR THIS ROW
C
            RWORK(IROWW(I)) = RWORK(IROWW(I)) + ABS(WMAT(I))
C
C         CONTRIBUTION FOR UPPER TRIANGULAR PART
C
            RWORK(KCOL) = RWORK(KCOL) + ABS(WMAT(I))
C
          enddo
C
        enddo
C
C     COMPUTE GERSCHGORIN BOUNDS ON EIGENVALUES
C
        EIGMIN = BIGNUM
        EIGMAX = -BIGNUM
        HMTNRM = ZERO
        DO KCOL = 1, NVAR-NSLK 
          HDIAG  = WMAT(JCOLW(KCOL))
          EIGBND = HDIAG + TWO*ABS(HDIAG) - RWORK(KCOL)
          EIGMIN = MIN(EIGMIN,EIGBND)
          EIGBND = HDIAG - TWO*ABS(HDIAG) + RWORK(KCOL)
          EIGMAX = MAX(EIGMAX,EIGBND)
          HMTNRM = MAX(HMTNRM,RWORK(KCOL)-ABS(HDIAG))
        enddo
C
C
        EIGLIM = ONE - MIN(EIGMIN,ZERO)
C
C     CHECK FOR (NEAR) ZERO HESSIAN
C
        IF(HMTNRM.LT.ZEROOT*(ONE+GNORM)) THEN
          IF ( .NOT. LINEAR ) THEN
            DIAGNL = ZEROOT
            LINEAR = .TRUE.
          ENDIF
        ENDIF
C
      ELSE
C
        EIGMIN = ZERO
        EIGMAX = ZERO
        EIGLIM = ONE
C
      ENDIF
C
C
C     ---START OF LEVENBERG PARAMETER INCREASE LOOP
 140  CONTINUE
C
      IF(IOFLAG.GE.20.AND.LEVNIT.LT.MAXLVN) THEN
        IF(IERBKT.EQ.-731) THEN
          LEVNIT = LEVNIT + 1
          LEVNDY(LEVNIT) = BLANK
          WRITE(LEVNDY(LEVNIT)(1:16),'(SP,1PG16.6)') DIAGNL
          LEVNDY(LEVNIT)(20:38) = 'Singular KKT matrix'
        ELSEIF(IERBKT.EQ.-732) THEN
          LEVNIT = LEVNIT + 1
          LEVNDY(LEVNIT) = BLANK
          WRITE(LEVNDY(LEVNIT)(1:16),'(SP,1PG16.6)') DIAGNL
          LEVNDY(LEVNIT)(20:33) = 'Pivot failure--increase panel size'
        ELSEIF(IERBKT.EQ.-736) THEN
          LEVNIT = LEVNIT + 1
          LEVNDY(LEVNIT) = BLANK
          WRITE(LEVNDY(LEVNIT)(1:16),'(SP,1PG16.6)') DIAGNL
          LEVNDY(LEVNIT)(20:33) = 'Excessive fill'
        ELSEIF(IERBKT.EQ.-737) THEN
          LEVNIT = LEVNIT + 1
          LEVNDY(LEVNIT) = BLANK
          WRITE(LEVNDY(LEVNIT)(1:16),'(SP,1PG16.6)') DIAGNL
          LEVNDY(LEVNIT)(20:36) = 'Incorrect inertia'
        ELSEIF(IERBKT.EQ.-743) THEN
          LEVNIT = LEVNIT + 1
          LEVNDY(LEVNIT) = BLANK
          WRITE(LEVNDY(LEVNIT)(1:16),'(SP,1PG16.6)') DIAGNL
          LEVNDY(LEVNIT)(20:47) = 'Max iter in itr refine solve'
        ENDIF
      ENDIF
C
C
C     USING CURRENT VALUE FOR DIAGNL, COMPUTE AUGMENTATION TO HESSIAN
C     DIAGONAL THAT WILL BE DONE IN SUBROUTINE BARKKT.
C
      ADDHSS = DIAGNL*EIGLIM
C
      IF ( NUMFAC .EQ. 0 ) THEN
C
C       DO ALL PHASES OF THE MULTIFRONTAL METHOD
C
        NCALL = 1
      ELSE
C
C       SKIP THE MULTIFRONTAL SYMBOLIC STUFF. JUST DO VALUE INPUT,
C       NUMERICAL FACTORIZATION, AND SOLVE.
C
        NCALL = 2
      ENDIF
C
C       NUMBER OF KKT CALLS
C
      INSTAT(12) = INSTAT(12) + 1
C
      IF(KTOPTN.EQ.'LARGE ') THEN
C
        CALL BARKKT( NVAR, NEQNS, NRES, MSUBE, MSUBB, NSLK, IPU,
     $            IPCBKT, NCALL, NONZR, IROWR, JCOLR, RMAT,
     $            NONZB, IROWB, JCOLB, BMAT, 
     $            NONZC, IROWC, JCOLC, CMAT, NONZW, IROWW,       
     $            JCOLW, WMAT, USEW, ADDHSS, MU, BVEC, CVEC,
     $            GRADL, ETA, LAMBDA,    
     $            LNRWRK, RWORK,
     $            ITEMP, NZROWB, ROWSCL, COLSCL, 
     $            RTHBKT, SOLNKT, LNSYMB, CNDNUM, NEEDED,
     $            DY, DZ, DETA, DLMBDA, IERBKT         )
C
      ELSEIF(KTOPTN.EQ.'SMALL ') THEN
C
        NEQNCB = NVAR + NRES + MSUBE
C
C       NOTE:  SOLNKT HAS LENGTH NEQNS = NEQNCB + MSUBB
C
        CALL CBRKKT( NVAR, NEQNCB, NRES, MSUBE, MSUBB, NSLK, IPU,
     $            IPCBKT, NCALL, NONZR, IROWR, JCOLR, RMAT,
     $            NONZB, IROWB, JCOLB, BMAT, 
     $            NONZC, IROWC, JCOLC, CMAT, NONZW, IROWW,       
     $            JCOLW, WMAT, USEW, ADDHSS, MU, BVEC, CVEC,
     $            GRADL, ETA, LAMBDA,    
     $            LNRWRK, RWORK,
     $            ITEMP, NZROWB,  
     $            RTHBKT, SOLNKT, LNSYMB, CNDNUM, NEEDED,
     $            DY, DZ, DETA, DLMBDA, IERBKT         )
C
      ELSE
        PRINT *,'KTOPTN =',KTOPTN
        STOP
      ENDIF
C
      NUMFAC = NUMFAC + 1
C
C       NUMBER OF KKT FAILURES
C
      IF(IERBKT.NE.0) INSTAT(11) = INSTAT(11) + 1
C
      IF(IERBKT.EQ.0) THEN
C
C       BARKKT WAS SUCCESSFUL 
C
        ITERM = 0
C
      ELSEIF(  IERBKT .LE. -901 .AND. IERBKT .GE. -999
     $         .AND. IERBKT .NE. -921 ) THEN
C
C       INADEQUATE WORKING STORAGE. NOTE THAT "NEEDED"
C       IS PASSED BACK TO A HIGHER LEVEL.
C
        ITERM = -8
        IF(IPC.GE.1) WRITE(IPU,1005) IERBKT
        GO TO 10000
C
      ELSEIF( IERBKT .EQ. -921 ) THEN
C
C       INTERNAL ERROR DURING SYMBOLIC FACT IN MULTIFRONTAL
C
        ITERM = -12
        IF(IPC.GE.1) WRITE(IPU,1006) IERBKT
        GO TO 10000
C
      ELSEIF( IERBKT .LE. -601 .AND. IERBKT .GE. -699 ) THEN
C
C       I/O ERROR DURING MULTIFRONTAL
C
        ITERM = -6
        IF(IPC.GE.1) WRITE(IPU,1007) IERBKT
        GO TO 10000
C
      ELSEIF( IERBKT .LE. -801 .AND. IERBKT .GE. -899 ) THEN
C
C       INPUT ERROR TO MULTIFRONTAL
C
        ITERM = -11
        IF(IPC.GE.1) WRITE(IPU,1008) IERBKT
        GO TO 10000
C
      ELSEIF( IERBKT .EQ. -731 .OR. IERBKT .EQ. -736 .OR. 
     $        IERBKT .EQ. -737 .OR. IERBKT .EQ. -743 .OR.
     $        IERBKT .EQ. -732 ) THEN
C
C         KKT SYSTEM ERRORS:
C         IERBKT = -731   SINGULAR KT MATRIX
C         IERBKT = -732   PIVOT FAILURE; INCREASE PANEL SIZE
C         IERBKT = -736   EXCESSIVE FILL DURING NUMERIC FACTORIZATION
C         IERBKT = -737   WRONG INERTIA 
C         IERBKT = -743   MAX. ITERATION DURING ITERATIVE REFINEMENT.
C                         POSSIBLY DUE TO AN ILL-CONDITIONED KKT MATRIX
C
        IF(DIAGNL.EQ.ONE) THEN
C
C         KKT SOLVE FAILED; INCORRECT MULTIPLIERS AND/OR HESSIAN MAY
C         BE THE CAUSE. RESET HESSIAN TO IDENTITY, AND RESET
C         MULTIPLIERS.
C
          RESET = .TRUE.
          WMAT(1:NONZW) = ZERO
C
C         PUT AN IDENTITY MATRIX ON THE DIAGONAL OF THAT PART OF THE
C         HESSIAN CORRESPONDING TO THE VARIABLES IN THE EXTERNAL
C         PROBLEM FORM (I.E., THE NON-SLACK VARS).
C
          DO I=1, NVAR-NSLK
            WMAT(JCOLW(I)) = ONE
          enddo
C
          DIAGNL = ZERO
C
C         RESET THE (EQUALITY) MULTIPLIERS AND THEN SET GRADL = 0
C         THIS IS A "NORMAL" STEP TOWARD THE QUASI-CENTRAL PATH.
C
          ETA(1:MSUBE) = ZERO
          GRADL(1:NVAR) = ZERO
C
C         TRY BARKKT AGAIN WITH AN IDENTITY IN THE (1,1) BLOCK OF W.
C
          GO TO 140
C
        ELSE
C
          IF(RESET) THEN
C
C           ERROR RETURN: BARKKT FAILED AND HESSIAN HAS BEEN RESET.
C           PERHAPS THE CONSTRAINTS ARE LOCALLY INCONSISTENT. 
C
            ITERM = -10
C
            IF(IPC.GE.10) THEN
              IF(IERBKT.EQ.-731) WRITE(IPU,1001)
              IF(IERBKT.EQ.-732) WRITE(IPU,1010)
              IF(IERBKT.EQ.-736) WRITE(IPU,1002)
              IF(IERBKT.EQ.-737) WRITE(IPU,1003)
              IF(IERBKT.EQ.-743) WRITE(IPU,1004)
            ENDIF
C
            GO TO 10000
C
          ELSE
C
C           AUGMENT THE HESSIAN DIAGONAL 
C
            DIAGNW = TEN*MAX(DIAGNL,ZEROOT)
            DIAGNW = MIN(DIAGNW,ONE)
            DIAGNL = DIAGNW
C
C           TRY BARKKT AGAIN WITH A NEW VALUE FOR DIAGNL.
C
            GO TO 140
C
          ENDIF
C
        ENDIF
C
      ELSE
C
C       OTHER ERRORS FROM BARKKT
C
        ITERM = -13
        IF(IPC.GE.1) WRITE(IPU,1009) IERBKT
        GO TO 10000
C
      ENDIF
C
10000 CONTINUE
C
C
C         STOP BRSRCH TIMING CLOCKS
C
      CALL CLKSUM(4)
      CALL CLKMAX(5)
C
 1001 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....HESSIAN HAS BEEN RESET',
     $       ' AND KT MATRIX IS SINGULAR',T106,'*')
 1002 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....HESSIAN HAS BEEN RESET',
     $       ' AND FILL WAS EXCESSIVE',T106,'*')
 1003 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....HESSIAN HAS BEEN RESET',
     $       ' AND KT MATRIX HAS WRONG INERTIA',T106,'*')
 1004 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....HESSIAN HAS BEEN RESET',
     $       ' AND > MAX ITER KT SOLVE (ILL-CONDITIONED?)',T106,'*')
 1005 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....MORE WORK STORAGE',
     $       ' NEEDED, BARKKT IER =', I6,T106,'*')
 1006 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....INTERNAL ERROR',
     $       ' DURING SYMBOLIC FACT., BARKKT IER =', I6,T106,'*')
 1007 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....I/O ERROR',
     $       ' IN MULTIFRONTAL, BARKKT IER =', I6,T106,'*')
 1008 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....INPUT ERROR',
     $       ' TO MULTIFRONTAL, BARKKT IER =', I6,T106,'*')
 1009 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....BARKKT ERROR RETURN;',
     $       ' IER =', I6,T106,'*')
 1010 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....HESSIAN HAS BEEN RESET',
     $       ' AND KT MATRIX PIVOTING FAILED',T106,'*')
C
C
      RETURN
      END
