

      SUBROUTINE CLKSET(NCLOCK)
C
C ======================================================================
C     CLKSET===>clkset   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C       PURPOSE:  INITIALIZE THE DATA FOR CLOCK NUMBER NCLOCK
C
C       INPUT:
C
C         NCLOCK  NUMBER OF THE CLOCK TO BE INITIALIZED
C
C                 WHEN NCLOCK > 0, CLOCK NUMBER NCLOCK
C                 IS INITIALIZED FOR SUMMATION;  I.E. IT
C                 IS ASSUMED THAT STATISTICS WILL BE GATHERED 
C                 USING SUBROUTINE CLKSUM
C
C                 WHEN NCLOCK < 0, CLOCK NUMBER NCLOCK
C                 IS INITIALIZED FOR MAXIMUM VALUES;  I.E. IT
C                 IS ASSUMED THAT STATISTICS WILL BE GATHERED 
C                 USING SUBROUTINE CLKMAX
C
C                 CURRENTLY THE MAXIMUM NUMBER OF CLOCKS IS MAXCLK
C                 AS DEFINED IN THE PARAMETER STATEMENT BELOW
C
C       USAGE OF THE TIMING ROUTINES:
C
C         TO COMPUTE THE TOTAL TIME SPENT IN SUBROUTINE BLAH(..) ON CLOCK 3
C
C       CALL CLKSET(3)
C       ...CODE...
C       CALL CLKBEG(3)
C         CALL BLAH(..)
C       CALL CLKSUM(3)
C       ...CODE...
C       CALL CLKOUT(3,TIMBLH,NBLAH)
C       
C         WHERE TIMBLH = TIME SPENT IN ALL CALLS TO BLAH
C               NBLAH  = NUMBER OF TIMES BLAH WAS CALLED
C
C         TO TIME THE MOST EXPENSIVE CALL TO BLAH ON CLOCK 3
C
C       CALL CLKSET(-3)
C       ...CODE...
C       CALL CLKBEG(3)
C         CALL BLAH(..)
C       CALL CLKMAX(3)
C       ...CODE...
C       CALL CLKOUT(3,TIMBLH,NBLAH)
C       
C         WHERE TIMBLH = MOST EXPENSIVE CALL TO BLAH
C               NBLAH  = INDEX OF MOST EXPENSIVE CALL
C
      PARAMETER (MAXCLK=40,ZERO=0.0D0)
C
      DOUBLE PRECISION INTCLK,INTOLD
      COMMON /CLKCOM/ CLKOLD(MAXCLK),CLKVAL(MAXCLK),INTCLK(MAXCLK),
     $    INTOLD(MAXCLK),IERCLK(MAXCLK)
C
      IF(NCLOCK.EQ.0.OR.NCLOCK.GT.MAXCLK) THEN
        PRINT *,'ILLEGAL VALUE FOR NCLOCK =',NCLOCK
        STOP
      ELSEIF(NCLOCK.GT.0) THEN
        INTCLK(NCLOCK) = 0
        CLKVAL(NCLOCK) = ZERO
        IERCLK(NCLOCK) = 0
      ELSE
        INTCLK(-NCLOCK) = 0
        INTOLD(-NCLOCK) = 0
        CLKVAL(-NCLOCK) = -HDMCON(2)
        IERCLK(-NCLOCK) = 0
      ENDIF 
C
      RETURN
      END
