
     
      SUBROUTINE CNVRTR(ICNVRT,NDIM,NCON,NZERO,AMAT,IROW,
     $    JCOLST,LNJCOL,BUPR,BLWR,ISTATC,IWORK,LNIWRK,
     $    NONZA,IPRM,IPRMC,IER)
C
C ======================================================================
C     CNVRTR===>cnvrtr   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      SAVE
C
C         PURPOSE:  THIS ROUTINE CONVERTS A QUADRATIC PROGRAM
C                   FROM EXTERNAL TO INTERNAL FORMAT.  EXTERNAL
C                   FORMAT PERMITS SPECIFICATION OF CONSTRAINTS AS
C
C                     BLWR .LE. AMAT*XVEC .LE. BUPR
C
C                   EQUALITY CONSTRAINTS ARE SPECIFIED BY SETTING
C                   BLWR(I) = BUPR(I).  INTERNAL FORMAT REQUIRES
C                   THE EQUALITY CONSTRAINTS BE FIRST, FOLLOWED
C                   BY THE INEQUALITIES.  FURTHERMORE CONSTRAINTS
C                   IN THE EXTERNAL FORMAT MAY BE IGNORED AS SPECIFIED
C                   BY THE ARRAY "ISTATC".  IGNORED CONSTRAINTS ARE
C                   SHIFTED TO THE BOTTOM OF THE STACK AND DIMENSIONS
C                   ADJUSTED APPROPRIATELY.  THIS ROUTINE CONVERTS
C                   THE CONSTRAINTS TO INTERNAL FORMAT,  AND SAVES
C                   PERTINENT INFORMATION IN THE MASTER PERMUTATION
C                   ARRAYS IPRM AND IPRMC.
C
C         INPUT:
C
C            ICNVRT INTEGER CONVERSION CODE
C                   = 0  PREVIOUSLY COMPUTED IPRM AND IPRMC APPLIED
C                        TO CONSTRAINT ARRAYS
C                   = 1  CONSTRAINT JACOBIAN INPUT IN COLUMN FORMAT
C                   = 2  CONSTRAINT JACOBIAN INPUT IN TRIPLE FORMAT
C            NDIM   NUMBER OF VARIABLES
C            NCON   NUMBER OF CONSTRAINTS (.GT. 0)
C            NZERO  NUMBER OF JACOBIAN NONZEROS
C            AMAT   NONZERO JACOBIAN ELEMENTS (NZERO)
C            IROW   INTEGER ROW INDEX ARRAY OF JACOBIAN NONZEROS (NZERO)
C            JCOLST INTEGER COLUMN START ARRAY OF JACOBIAN (LNJCOL)
C                   INTEGER COLUMN INDEX ARRAY WHEN ICNVRT = 2
C                   NOTE: JCOLST(NDIM+1)-1 = NZERO
C            LNJCOL LENGTH OF JCOLST MAX(NZERO,NDIM+1)
C            BUPR   UPPER BOUND ARRAY (NCON)
C            BLWR   LOWER BOUND ARRAY (NCON)
C            ISTATC CONSTRAINT STATUS ARRAY (NCON)
C            IWORK  INTEGER WORK ARRAY (LNIWRK)
C            LNIWRK LENGTH OF IWORK = MAX(2*NCON,NZERO,NDIM)
C            IPRM   MASTER JACOBIAN PERMUTATION ARRAY (NZERO)
C            IPRMC  MASTER CONSTRAINT PERMUTATION ARRAY (NCON)
C
C         OUTPUT:
C            JCOLST INTEGER COLUMN START ARRAY OF JACOBIAN (LNJCOL)
C                   WHEN ICNVRT = 2
C            NONZA  NUMBER OF NONZEROS IN NONIGNORED PART OF JACOBIAN
C            IPRM   MASTER JACOBIAN PERMUTATION ARRAY (NZERO)
C            IPRMC  MASTER CONSTRAINT PERMUTATION ARRAY (NCON)
C            IER    INTEGER ERROR FLAG
C                   0       NORMAL RETURN
C                   .LT. 0  ERROR;  RESULTS NOT COMPUTED
C
      DIMENSION AMAT(NZERO),IROW(NZERO),JCOLST(LNJCOL),BUPR(NCON),
     $    BLWR(NCON),IWORK(LNIWRK),IPRM(NZERO),IPRMC(NCON),
     $    ISTATC(NCON)
C
      PARAMETER (ZERO=0.D0,ONE=1.D0)
      LOGICAL TRIPLE
C
C     ===================================================================
C
      IER = 0
C
C         SPECIAL FOR UNCONSTRAINED PROBLEMS
C
      IF(NCON.EQ.0) THEN
        MEQUAL = 0
        RETURN
      ENDIF
C
C         CHECK IF THE PERMUTATION ARRAYS NEED TO BE CONSTRUCTED
C
      IF(ICNVRT.EQ.0) THEN 
C
C ----------------------------------------------------------------------
C
C         CONVERT ALL EXTERNAL QUANTITIES TO INTERNAL ORDER
C         EQUALITY CONSTRAINTS FIRST
C
        CALL HJPRMX(ISTATC,NCON,IPRMC,IER)
        IF(IER.LT.0) RETURN
        CALL HDPRMX(BLWR,NCON,IPRMC,IER)
        IF(IER.LT.0) RETURN
        CALL HDPRMX(BUPR,NCON,IPRMC,IER)
        IF(IER.LT.0) RETURN
        CALL HDPRMX(AMAT,NZERO,IPRM,IER)
        IF(IER.LT.0) RETURN
        CALL HJPRMX(IROW,NZERO,IPRM,IER)
        IF(IER.LT.0) RETURN
        IF(TRIPLE) THEN
          CALL HJPRMX(JCOLST,NZERO,IPRM,IER)
          IF(IER.LT.0) RETURN
          CALL STORCH(1,NONZA,NDIM,JCOLST,IWORK,LNJCOL,IER)
          IF(IER.LT.0) RETURN
        ENDIF
C     
      ELSE
C
C ----------------------------------------------------------------------
C
C         CHECK IF JACOBIAN IS IN COLUMN FORMAT -- IF SO CONVERT IT
C         TO TRIPLE FORMAT
C
C
C         SET FLAG TO INDICATE WHICH FORMAT IS USED FOR INPUT
C
        TRIPLE = ICNVRT.EQ.2
        IF(ICNVRT.EQ.1) CALL STORCH(2,NZERO,NDIM,JCOLST,
     $                              IWORK,LNJCOL,IER)
C
        IF(IER.LT.0) RETURN
C
C         COMPUTE NUMBER OF IGNORED CONSTRAINTS
C
C         CONSTRUCT PERMUTATION TO PUT EQUALITY CONSTRAINTS AS THE 
C         FIRST ROWS OF THE JACOBIAN MATRIX 
C
        MIGNOR = 0
        MEQUAL = 0
        DO I = 1,NCON
          IF (ISTATC(I).EQ.4) THEN
            MIGNOR = MIGNOR + 1
          ELSEIF (BLWR(I).EQ.BUPR(I)) THEN
            MEQUAL = MEQUAL + 1
          ENDIF
C
        enddo
        MINEQL = NCON - MEQUAL - MIGNOR
C
        K1 = 0
        K2 = 0
        K3 = 0
        DO I = 1,NCON
C
          IF(ISTATC(I).EQ.4) THEN
C
C         PUT IGNORED CONSTRAINTS AT THE BOTTOM OF THE STACK
C
            K3 = K3 + 1
            IPRMC(MEQUAL+MINEQL+K3) = I
C
          ELSEIF(BLWR(I).EQ.BUPR(I)) THEN
C
C         PUT EQUALITY CONSTRAINTS INTO ACTIVE SET
C
            K1 = K1 + 1
            IPRMC(K1) = I
C 
          ELSE 
C
C         PUT INEQUALITY CONSTRAINTS INTO SET
C
            K2 = K2 + 1
            IPRMC(MEQUAL+K2) = I
C
          ENDIF
C
        enddo
C
C         INITIALIZE MASTER JACOBIAN PERMUTATION RECORD
C
        DO I = 1,NZERO
          IPRM(I) = I
        enddo
C
C         CONSTRUCT ORDERING FOR INITIAL ACTIVE SET
C
        CALL PRMMAT(1,NZERO,AMAT,IROW,JCOLST,
     $    IPRM,IPRMC,NCON,IWORK,IER)
        IF(IER.LT.0) RETURN
C
C         APPLY ORDERING TO BUPR, BLWR, AND ISTATC
C
        CALL HJPRMX(ISTATC,NCON,IPRMC,IER)
        IF(IER.LT.0) RETURN
        CALL HDPRMX(BUPR,NCON,IPRMC,IER)
        IF(IER.LT.0) RETURN
        CALL HDPRMX(BLWR,NCON,IPRMC,IER)
        IF(IER.LT.0) RETURN
C
C         COMPUTE NUMBER OF ELEMENTS IN UPPER PART OF JACOBIAN
C
        NONZA = 0
        DO I=1,NZERO
          IF(IROW(I).LE.MEQUAL+MINEQL)  NONZA = NONZA + 1
        ENDDO
C
C         INITIALIZE IWORK TO NATURAL ORDER
C
        DO I = 1,NZERO
          IWORK(I) = I
        enddo
C
C         REORDER UPPER PART OF JACOBIAN INTO COLUMN FORMAT
C
        IOPT = 0
        ISTBLE = 0
        CALL HJSRTN(JCOLST,NONZA,IOPT,ISTBLE,IWORK,IER)
        IF(IER.LT.0) RETURN
C
C         APPLY THE SORT TO THE OTHER ARRAYS
C
        CALL HJPRMX(IROW,NZERO,IWORK,IER)
        IF(IER.LT.0) RETURN
        CALL HJPRMX(IPRM,NZERO,IWORK,IER)
        IF(IER.LT.0) RETURN
        CALL HDPRMX(AMAT,NZERO,IWORK,IER)
        IF(IER.LT.0) RETURN
C
C         CONVERT JACOBIAN TO COLUMN FORMAT
C
        CALL STORCH(1,NONZA,NDIM,JCOLST,IWORK,LNJCOL,IER)
        IF(IER.LT.0) RETURN
C
      ENDIF
C
      RETURN
C
      END
