
      SUBROUTINE CONERR(CLWR,CUPR,CVEC,XLWR,XUPR,XVEC,MCON,MDIM,NDIM,
     $    ERBEQL,ERBINQ,ERREQL,ERRINQ,CVIOLN)
C
C ======================================================================
C     CONERR===>conerr   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         PURPOSE:  PERFORM CONVERGENCE TESTS 
C
C         INPUT:
C
C            CLWR   CONSTRAINT LOWER BOUND (MDIM)
C            CUPR   CONSTRAINT UPPER BOUND (MDIM)
C            CVEC   CONSTRAINT VECTOR (MDIM)
C            XLWR   VARIABLE LOWER BOUNDS (NDIM)
C            XUPR   VARIABLE UPPER BOUNDS (NDIM)
C            XVEC   VARIABLES (NDIM)
C            MCON   NUMBER OF CONSTRAINTS
C            MDIM   DIMENSION OF CONSTRAINT ARRAYS
C            NDIM   NUMBER OF VARIABLES
C
C         OUTPUT:
C
C            ERBEQL ERROR IN BOUND EQUALITY CONSTRAINTS
C            ERBINQ ERROR IN BOUND INEQUALITY CONSTRAINTS
C            ERREQL ERROR IN EQUALITY CONSTRAINTS
C            ERRINQ ERROR IN INEQUALITY CONSTRAINTS
C            CVIOLN TOTAL CONSTRAINT VIOLATION
C
      DIMENSION CLWR(MDIM),
     $    CUPR(MDIM),CVEC(MDIM),XLWR(NDIM),XUPR(NDIM),XVEC(NDIM)
C
C-------------------------------------------------------------
      INCLUDE '../commons/NLPSPR.CMN'
C-------------------------------------------------------------
C
      PARAMETER (ZERO=0.0D0)
C
C         COMPUTE CONSTRAINT ERRORS AND CHECK MULTIPLIERS
C
      ERBEQL = ZERO
      ERBINQ = ZERO
      DO I = 1,NDIM
        IF(XLWR(I).EQ.XUPR(I)) THEN
C
C         EQUALITY CONSTRAINT
C
          ERBEQL = MAX(ERBEQL,ABS(XVEC(I) - XLWR(I)))
C
        ELSE
C
          IF(XVEC(I).LT.XLWR(I)+CONTOL) THEN
C
C         LOWER BOUND INEQUALITY CONSTRAINT
C
            ERBINQ = MAX(ERBINQ, XLWR(I) - XVEC(I) )
C
          ELSEIF(XVEC(I).GT.XUPR(I)-CONTOL) THEN
C
C         UPPER BOUND INEQUALITY CONSTRAINT
C
            ERBINQ = MAX(ERBINQ, XVEC(I) - XUPR(I) )
C
          ENDIF
C
        ENDIF
      ENDDO
C
C         NONLINEAR CONSTRAINT CALCULATIONS
C
      ERREQL = ZERO
      ERRINQ = ZERO
      DO I = 1,MCON
        IF(CLWR(I).EQ.CUPR(I)) THEN
C
C         EQUALITY CONSTRAINT
C
          ERREQL = MAX(ERREQL,ABS(CVEC(I) - CLWR(I)))
C
        ELSE
C
          IF(CVEC(I).LT.CLWR(I)+CONTOL) THEN
C
C         LOWER BOUND INEQUALITY CONSTRAINT
C
            ERRINQ = MAX(ERRINQ, CLWR(I) - CVEC(I) )
C
          ELSEIF(CVEC(I).GT.CUPR(I)-CONTOL) THEN
C
C         UPPER BOUND INEQUALITY CONSTRAINT
C
            ERRINQ = MAX(ERRINQ, CVEC(I) - CUPR(I) )
C
          ENDIF
C
        ENDIF
      ENDDO
C
C         COMBINE CONSTRAINT AND BOUND ERRORS TO DEFINE TOTAL VIOLATION
C
      CVIOLN = MAX(ERREQL,ERBEQL,ERRINQ,ERBINQ)
C
      RETURN
      END
