
      SUBROUTINE DCNVRT(NDIM,NCON,MEQUAL,MINEQL,MIGNOR,NZERO,
     $    AMAT,IROW,JCOLST,LNJCOL,BUPR,BLWR,CONMLT,IWORK,
     $    LNIWRK,IPRM,IPRMC,ISTATC,IER)
C
C ======================================================================
C     DCNVRT===>dcnvrt   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         PURPOSE:  THIS ROUTINE RESTORES THE CONSTRAINT RELATED 
C                   DATA OF A QUADRATIC PROGRAM
C                   FROM INTERNAL TO EXTERNAL FORMAT.  
C
C         INPUT:
C
C            NDIM   NUMBER OF VARIABLES
C            NCON   NUMBER OF CONSTRAINTS (.GT. 0)
C            MEQUAL NUMBER OF EQUALITIES
C            MINEQL NUMBER OF INEQUALITIES
C            MIGNOR NUMBER OF IGNORED CONSTRAINTS
C            NZERO  NUMBER OF JACOBIAN NONZEROS
C            AMAT   NONZERO JACOBIAN ELEMENTS (NZERO)
C            IROW   INTEGER ROW INDEX ARRAY OF JACOBIAN NONZEROS (NZERO)
C            JCOLST INTEGER COLUMN START ARRAY OF JACOBIAN (LNJCOL)
C                   NOTE: JCOLST(NDIM+1)-1 = NONZA .LE. NZERO
C            LNJCOL LENGTH OF JCOLST MAX(NZERO,NDIM+1)
C            BUPR   UPPER BOUND ARRAY (NCON)
C            BLWR   LOWER BOUND ARRAY (NCON)
C            CONMLT CONSTRAINT MULTIPLIERS (NCON)
C            IWORK  INTEGER WORK ARRAY (LNIWRK)
C            LNIWRK LENGTH OF IWORK = MAX(2*NCON,NZERO,NDIM)
C            IPRM   MASTER JACOBIAN PERMUTATION ARRAY (NZERO)
C            IPRMC  MASTER CONSTRAINT PERMUTATION ARRAY (NCON)
C            ISTATC CONSTRAINT STATUS ARRAY (NCON)
C
C         OUTPUT:
C
C            AMAT   NONZERO JACOBIAN ELEMENTS IN EXTERNAL ORDER (NZERO)
C            IROW   INTEGER ROW INDEX ARRAY IN EXTERNAL ORDER  (NZERO)
C            JCOLST INTEGER COLUMN START ARRAY OF JACOBIAN (LNJCOL)
C                   NOTE: JCOLST(NDIM+1)-1 = NZERO
C            BUPR   UPPER BOUND ARRAY IN EXTERNAL ORDER (NCON)
C            BLWR   LOWER BOUND ARRAY IN EXTERNAL ORDER (NCON)
C            CONMLT CONSTRAINT MULTIPLIERS (NCON)
C            ISTATC CONSTRAINT STATUS ARRAY (NCON)
C            IER    INTEGER ERROR FLAG
C                   0       NORMAL RETURN
C                   .LT. 0  ERROR;  RESULTS NOT COMPUTED
C
      DIMENSION AMAT(NZERO),IROW(NZERO),JCOLST(LNJCOL),BUPR(NCON),
     $    BLWR(NCON),IWORK(LNIWRK),IPRM(NZERO),IPRMC(NCON),
     $    CONMLT(NCON),ISTATC(NCON)
C
      PARAMETER (ZERO=0.D0,ONE=1.D0)
C
      IER = 0
C
C         SPECIAL FOR UNCONSTRAINED PROBLEMS
C
      IF(NCON.EQ.0) THEN
        RETURN
      ENDIF
C
      MCON = NCON - MIGNOR
      NONZA = JCOLST(NDIM+1) - 1
C
C ----------------------------------------------------------------------
C
C         RESTORE CONSTRAINT QUANTITIES TO EXTERNAL ORDER
C
      IF(NCON.GT.0) THEN
        CALL HDPRMY(BLWR,NCON,IPRMC,IER)
        IF(IER.LT.0) RETURN
        CALL HDPRMY(BUPR,NCON,IPRMC,IER)
        IF(IER.LT.0) RETURN
        CALL HJPRMY(ISTATC,NCON,IPRMC,IER)
        IF(IER.LT.0) RETURN
      ENDIF
C
      IF(NZERO.GT.1) THEN
C
C         CONVERT JCOLST FOR NONIGNORED ROWS TO TRIPLE FORMAT
C
        CALL STORCH(2,NONZA,NDIM,JCOLST,IWORK,LNJCOL,IER)
        IF(IER.LT.0) RETURN
C
        CALL HDPRMY(AMAT,NZERO,IPRM,IER)
        IF(IER.LT.0) RETURN
        CALL HJPRMY(IROW,NZERO,IPRM,IER)
        IF(IER.LT.0) RETURN
        CALL HJPRMY(JCOLST,NZERO,IPRM,IER)
        IF(IER.LT.0) RETURN
C
C         CONSTRUCT PERMUTATION TO RESTORE EQUALITY CONSTRAINTS TO THEIR
C         ORIGINAL POSITIONS
C
        K1 = 0
        K2 = 0
        K3 = 0
        DO I = 1,NCON
C
          IF(ISTATC(I).EQ.4) THEN
C
C         BRING IGNORED CONSTRAINTS FROM THE BOTTOM OF THE STACK
C
            K3 = K3 + 1
            IWORK(I) = MEQUAL+MINEQL+K3
C
          ELSEIF(BLWR(I).EQ.BUPR(I)) THEN
C
C         PUT EQUALITY CONSTRAINTS INTO ORIGINAL POSITION 
C
            K1 = K1 + 1
            IWORK(I) = K1
C 
          ELSE 
C
C         PUT INEQUALITY CONSTRAINTS INTO ORIGINAL POSITION
C
            K2 = K2 + 1
            IWORK(I) = MEQUAL+K2
C
          ENDIF
C
        enddo
C
C         CONSTRUCT THE INDEX ARRAY WHICH WILL PUT THE PERMUTATION 
C         ARRAY KPERM INTO ASCENDING ORDER -- RESTORE KPERM TO 
C         ORIGINAL ORDER 
C
        CALL HJSRTN(IWORK,NCON,1,0,IWORK(NCON+1),IER)
        IF(IER.LT.0) RETURN
C
C         ***ROW PERMUTATION***
C
C         APPLY ROW PERMUTATION TO ROW INDICES
C
        DO I = 1,NZERO
          IROW(I) = IWORK(NCON+IROW(I))
        enddo
C
      ENDIF
C
C         CONVERT FULL JACOBIAN TO COLUMN FORMAT
C
      CALL STORCH(1,NZERO,NDIM,JCOLST,IWORK,LNJCOL,IER)
      IF(IER.LT.0) RETURN
C
C         LOAD CLOBBER CONSTANT INTO IGNORED CONSTRAINT MULTIPLIERS
C
      IF(MIGNOR.GT.0) CONMLT(MCON+1:MCON+MIGNOR) = HDMCON(1)
C
C         RESTORE MULTIPLIERS TO EXTERNAL ORDER
C
      IF(NCON.GT.0) CALL HDPRMY(CONMLT,NCON,IPRMC,IER)
      IF(IER.LT.0) RETURN
C
      RETURN
C
      END
