
      SUBROUTINE ECNVRG(GMAT,IROWG,JSTRG,NONZG,CLWR,CUPR,CVEC,DELF,
     $    VECLAM,VECNU,VECP,XLWR,XUPR,XVEC,ISTATC,ISTATV,ALFA,DELFNM,
     $    FNOM,FMIN,FREDUC,CONTOL,OBJTOL,PGDTOL,
     $    IT,MCON,MDIM,MINOPT,NDIM,NITMAX,NITMIN,IFUNER,ITERM,IOFLAG,
     $    IPU,PGRAD,ERREQL,ERRINQ,PGNORM)
C
C ======================================================================
C     ECNVRG===>ecnvrg   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         PURPOSE:  PERFORM CONVERGENCE TESTS 
C
C         INPUT:
C
C            GMAT   JACOBIAN MATRIX (NONZG)
C            IROWG  JACOBIAN ROW INDEX ARRAY (NONZG)
C            JSTRG  JACOBIAN COLUMN START ARRAY (NDIM+1)
C            NONZG  LENGTH OF GMAT ARRAY
C            CLWR   CONSTRAINT LOWER BOUND (MDIM)
C            CUPR   CONSTRAINT UPPER BOUND (MDIM)
C            CVEC   CONSTRAINT VECTOR (MDIM)
C            DELF   GRADIENT VECTOR (NDIM)
C            VECLAM LAGRANGE MULTIPLIERS (MDIM)
C            VECNU  INDEP. VARIABLE MULTIPLIERS (NDIM)
C            VECP   SEARCH DIRECTION VECTOR (NDIM)
C            XLWR   VARIABLE LOWER BOUNDS (NDIM)
C            XUPR   VARIABLE UPPER BOUNDS (NDIM)
C            XVEC   VARIABLES (NDIM)
C            ISTATC CONSTRAINT STATUS ARRAY (MDIM)
C            ISTATV VARIABLE STATUS ARRAY (NDIM)
C            ALFA   STEP LENGTH
C            DELFNM GRADIENT NORM
C            FNOM   OBJECTIVE FUNCTION AT X.
C            FMIN   PREDICTED MINIMUM OF F.
C            FREDUC PREVIOUS FUNCTION CHANGE
C            CONTOL CONSTRAINT TOLERANCE
C            OBJTOL OBJECTIVE FUNCTION TOLERANCE
C            PGDTOL PROJECTED GRADIENT TOLERANCE
C            IT     THE CURRENT ITERATION
C            MCON   NUMBER OF CONSTRAINTS
C            MDIM   DIMENSION OF CONSTRAINT ARRAYS
C            MINOPT MINIMIZATION OPTION
C            NDIM   NUMBER OF VARIABLES
C            NITMAX THE MAXIMUM NUMBER OF ITERATIONS
C            IFUNER INTEGER FUNCTION ERROR FLAG
C            ITERM  TERMINATION FLAG.  MUST BE INPUT.  SEE BELOW
C            IOFLAG OUTPUT CONTROL FLAG
C            IPU    OUTPUT UNIT NO.
C
C         OUTPUT:
C
C            PGRAD  PROJECTED GRADIENT VECTOR (NDIM)
C            ERREQL ERROR IN EQUALITY CONSTRAINTS
C            ERRINQ ERROR IN INEQUALITY CONSTRAINTS
C            PGNORM NORM OF PROJECTED GRADIENT
C            ITERM  TERMINATION FLAG
C                   =0        NO TERMINATION.
C                   =1        NORMAL TERMINATION.  SEE CODE
C                   =2        WEAK SOLUTION (NEAR ZERO MULTIPLIERS)
C                             ABNORMAL TERMINATION
C                   =3        SMALL CHANGES
C                   =4        MAX. NUMBER OF ITERATIONS
C                   =5        FUNCTION ERROR ON GRAD. EVAL.
C                   .LT.0     USER ABORT
C
      DIMENSION GMAT(NONZG),IROWG(NONZG),JSTRG(NDIM+1),CLWR(MDIM),
     $    CUPR(MDIM),CVEC(MDIM),DELF(NDIM),VECLAM(MDIM),VECNU(NDIM),
     $    VECP(NDIM),XLWR(NDIM),XUPR(NDIM),XVEC(NDIM),PGRAD(NDIM),
     $    ISTATC(MDIM),ISTATV(NDIM)
C
      COMMON /KONSTN/ 
     *  ZEROMN  ,ZEROOT  ,BIGNUM  ,BGROOT  ,BIGBND  ,BIGCND
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0)
C
C         COMPUTE ERROR IN KUHN-TUCKER CONDITION AND RESOLUTION
C         TEST QUANTITIES
C
      CALL MVPSPR(11,NDIM,MCON,GMAT,IROWG,JSTRG,VECLAM,PGRAD)
C
      STPLNG = ZERO
      RESTST = ZERO
      PGNORM = ZERO
      DO I = 1,NDIM
        PGRAD(I) = DELF(I) - PGRAD(I) - VECNU(I)
        PGNORM = MAX(PGNORM,ABS(PGRAD(I)))
        DELX = ALFA*ABS(VECP(I))
        STPLNG = MAX(STPLNG,DELX)
        RESTST = MAX(RESTST,DELX/(ONE + ABS(XVEC(I))))
      ENDDO
C
C         VARIABLE BOUNDS
C
C         COMPUTE LARGEST MAGNITUDE MULTIPLIER
C         COMPUTE CONSTRAINT ERRORS AND CHECK MULTIPLIERS
C
      ERBEQL = ZERO
      ERBINQ = ZERO
      XNUMAX = ZERO
      SMALNU = BIGNUM
      BIGNU = -BIGNUM
      DO I = 1,NDIM
        XNUMAX = MAX(XNUMAX,ABS(VECNU(I)))
        IF(XLWR(I).EQ.XUPR(I)) THEN
C
C         EQUALITY CONSTRAINT
C
          ERBEQL = MAX(ERBEQL,ABS(XVEC(I) - XLWR(I)))
C
        ELSE
C
          IF(XVEC(I).LT.XLWR(I)+CONTOL) THEN
C
C         LOWER BOUND INEQUALITY CONSTRAINT
C
            ERBINQ = MAX(ERBINQ, XLWR(I) - XVEC(I) )
            IF(ISTATV(I).EQ.1) SMALNU = MIN(SMALNU, VECNU(I))
C
          ELSEIF(XVEC(I).GT.XUPR(I)-CONTOL) THEN
C
C         UPPER BOUND INEQUALITY CONSTRAINT
C
            ERBINQ = MAX(ERBINQ, XVEC(I) - XUPR(I) )
            IF(ISTATV(I).EQ.2) BIGNU = MAX(BIGNU, VECNU(I))
C
          ENDIF
C
        ENDIF
      ENDDO
C
C         NONLINEAR CONSTRAINT CALCULATIONS
C
C         COMPUTE LARGEST MAGNITUDE MULTIPLIER
C         COMPUTE CONSTRAINT ERRORS AND CHECK MULTIPLIERS
C
      ERREQL = ZERO
      ERRINQ = ZERO
      XLAMAX = ZERO
      SMALAM = BIGNUM
      BIGLAM = -BIGNUM
      DO I = 1,MCON
        XLAMAX = MAX(XLAMAX,ABS(VECLAM(I)))
        IF(CLWR(I).EQ.CUPR(I)) THEN
C
C         EQUALITY CONSTRAINT
C
          ERREQL = MAX(ERREQL,ABS(CVEC(I) - CLWR(I)))
C
        ELSE
C
          IF(CVEC(I).LT.CLWR(I)+CONTOL) THEN
C
C         LOWER BOUND INEQUALITY CONSTRAINT
C
            ERRINQ = MAX(ERRINQ, CLWR(I) - CVEC(I) )
            IF(ISTATC(I).EQ.1) SMALAM = MIN(SMALAM, VECLAM(I))
C
          ELSEIF(CVEC(I).GT.CUPR(I)-CONTOL) THEN
C
C         UPPER BOUND INEQUALITY CONSTRAINT
C
            ERRINQ = MAX(ERRINQ, CVEC(I) - CUPR(I) )
            IF(ISTATC(I).EQ.2) BIGLAM = MAX(BIGLAM, VECLAM(I))
C
          ENDIF
C
        ENDIF
      ENDDO
C
C         COMBINE CONSTRAINT AND BOUND ERRORS 
C
      ERREQL = MAX(ERREQL,ERBEQL)
      ERRINQ = MAX(ERRINQ,ERBINQ)
C
C ----------------------------------------------------------------------
C
C         NORMAL TERMINATION TESTS
C
C ----------------------------------------------------------------------
C
      IF(MINOPT.EQ.5.AND.IT.GE.2) THEN
C
        ITERM = 1
C
      ELSEIF(ERREQL.LT.CONTOL.AND.ERRINQ.LT.CONTOL
     $   .AND.IT.GT.NITMIN) THEN
C
C         CONSTRAINTS ARE WITHIN TOLERANCE
C
        RHSTST = PGDTOL*MAX(ONE,DELFNM)
C
        IF(PGNORM.LT.RHSTST) THEN
C
C         PROJECTED GRADIENT IS WITHIN TOLERANCE 
C
          TAU = OBJTOL/(ONE + ABS(FNOM))
          TOLTST = SQRT(TAU)
C
          IF( (ABS(FNOM-FMIN).LT.OBJTOL.AND.RESTST.LT.TOLTST).OR.
     $     (PGNORM.LT.ZEROOT)) THEN
C
C         EITHER 
C         (A) OBJECTIVE FUNCTION AND STEP ARE WITHIN TOLERANCE OR
C         (B) PROJECTED GRADIENT ERROR IS SO SMALL 
C             THAT A RESOLUTION TEST IS UNWARRANTED
C
            SMTEST = (XLAMAX + SMALAM) - XLAMAX
            BGTEST = (XLAMAX + BIGLAM) - XLAMAX
            TSTSNU = (XNUMAX + SMALNU) - XNUMAX
            TSTBNU = (XNUMAX + BIGNU) - XNUMAX
C
            IF(SMTEST.GT.ZERO.AND.BGTEST.LT.ZERO.AND.
     $         TSTSNU.GT.ZERO.AND.TSTBNU.LT.ZERO) THEN
C
C         LAGRANGE MULTIPLIERS HAVE CORRECT SIGN
C
              ITERM = 1
C 
            ELSEIF(SMTEST.GT.-ZEROOT.AND.BGTEST.LT.ZEROOT.AND.
     $         TSTSNU.GT.-ZEROOT.AND.TSTBNU.LT.ZEROOT) THEN
C
C         WEAK SOLUTION -- INEQUALITY MULTIPLIERS NEAR ZERO, BUT OTHERWISE
C         OPTIMALITY CONDITIONS ARE SATISFIED
C
              ITERM = 2
C 
            ENDIF
C
          ENDIF
C
        ENDIF
C      
      ENDIF
C
      IF(ITERM.EQ.0) THEN
C
C ----------------------------------------------------------------------
C
C         ABNORMAL TERMINATION TESTS
C
C ----------------------------------------------------------------------
C
C
        IF(IT.GT.NITMAX) THEN
C
C         MAXIMUM NUMBER OF ITERATIONS
C
          ITERM = 4
          IF(IOFLAG.GE.10) WRITE(IPU,1002)
C
        ELSEIF(IFUNER.EQ.1) THEN
C
C         FUNCTION ERROR OCCURRED ON A PERTURBED POINT DURING
C         NUMERICAL GRADIENT EVALUATION. SINCE NOMINAL POINT
C         WAS OK, FUNCTION IS NOT LOCALLY DIFFERENTIABLE.
C
          ITERM = 5
          IF(IOFLAG.GE.10) WRITE(IPU,1003)
C
        ELSEIF(IT.GT.2.AND.(ABS(FREDUC).LT.ZEROMN
     $                     .OR.STPLNG.LT.ZEROMN) ) THEN
C
C         SMALL STEP TERMINATION
C
          ITERM = 3
          IF(IOFLAG.GE.10) WRITE(IPU,1001)
C
        ENDIF
C
      ENDIF
C
 1001 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'SMALL STEP TERMINATION',
     $    T106,'*')
 1002 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'MAXIMUM NUMBER OF ITERATIONS',
     $    T106,'*')
 1003 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'FUNCTION ERROR ON GRADIENT EVAL
     $UATION',T106,'*')
C
      RETURN
      END
