
      SUBROUTINE EQCMIN(ISTATC,CLWR,CUPR,CVEC,CBAR,DELF,PGRAD,
     $    GMAT,IROWG,JSTRG,RESVEC,RMAT,IROWR,JSTRR,HMAT,IROWH,JSTRH,
     $    PENVEC,VECLAM,VECP,TVEC,UVEC,VECXI,VECQ,VECS,VECMU,VECNU,
     $    VLAMBR,VECSBR,VCNUBR,ISTATV,XLWR,XUPR,XVEC,XBAR,XOLD,
     $    ISTATO,FHFLTR,ISCRTC,LNFLTR,MXFLTR,CMAX,FILTUR,
     $    WORK,IWORK,PGNORM,DELFNM,FNOM,FBAR,FXTRAP,FMIN,
     $    SNORM,IFUNER,IPU,ISTART,ITERM,
     $    MCON,MDIM,MINOPT,NONZH,NONZG,NONZR,NRES,MAXRES,MEQUAL,
     $    NDIM,NWORK,NIWORK,NEEDED,EXTRAP,IREVRS,
     $    REFPNT,SRCPNT)
C
C ======================================================================
C     EQCMIN===>eqcmin   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      SAVE
C
C         PURPOSE:  CONSTRAINED MINIMIZATION OF THE FUNCTION F(XVEC)
C                   USING A SUCCESSIVE QUADRATIC PROGRAMMING APPROACH
C
C         INPUT-OUTPUT:
C
C         --ARRAYS
C
C            ISTATC CONSTRAINT STATUS ARRAY (MDIM)
C            CLWR   CONSTRAINT LOWER BOUNDS (MDIM)
C            CUPR   CONSTRAINT UPPER BOUNDS (MDIM)
C            CVEC   CONSTRAINTS AT XVEC (MDIM)
C            CBAR   CONSTRAINTS AT XBAR (MDIM)
C            DELF   GRADIENT OF F (NDIM)
C            PGRAD  PROJECTED GRADIENT VECTOR OF F (NDIM)
C            GMAT   JACOBIAN MATRIX NONZERO ELEMENTS (NONZG)
C            IROWG  INTEGER ARRAY OF ROW INDICES FOR GMAT (NONZG)
C            JSTRG  INTEGER ARRAY OF COLUMN STARTS FOR GMAT (NDIM+1)
C                   NONZG = JSTRG(NDIM+1)-1
C            RESVEC RESIDUAL VECTOR (MAXRES)
C            RMAT   RESIDUAL JACOBIAN MATRIX STORED AS AN ARRAY (NONZR)
C            IROWR  ROW INDEX OF NONZEROS IN RMAT (NONZR)
C            JSTRR  COLUMN START INDEX (NDIM+1)
C            HMAT   SPARSE HESSIAN MATRIX OF THE LAGRANGIAN (NONZH)
C            IROWH  INTEGER VECTOR OF ROW INDICES OF HESSIAN NONZEROS (NONZH)
C            JSTRH  INTEGER VECTOR OF START OF COLUMN INDICES (NDIM+1)
C                   NONZH = JSTRH(NDIM+1)-1
C            PENVEC PENALTY WEIGHT VECTOR (NDIM+MCON)
C            VECLAM SECOND ORDER MULTIPLIER ESTIMATES (MDIM)
C            VECP   REAL VARIABLE SEARCH DIRECTION VECTOR (NDIM)
C            TVEC   SECOND ORDER SEARCH CORRECTION VECTOR (NDIM)
C            UVEC   THIRD ORDER SEARCH CORRECTION VECTOR (NDIM)
C            VECXI  LAGRANGE MULTIPLIER SEARCH DIRECTION (MCON+NDIM)
C            VECQ   SLACK VARIABLE SEARCH DIRECTION (MCON+NDIM)
C            VECS   SLACK VARIABLE (MCON+NDIM)
C            VECMU  QUADRATIC PROGRAM MULTIPLIERS (MDIM)
C            VECNU  QP BOUND MULITPLIERS (NDIM)
C            VLAMBR LAGRANGE MULTIPLIERS AT NEW POINT (MDIM)
C            VECSBR SLACK VARIABLES AT NEW POINT (MCON+NDIM)
C            VCNUBR BOUND MULTIPLIERS AT NEW POINT (NDIM)
C            ISTATV VARIABLE STATUS ARRAY (NDIM)
C            XLWR   VARIABLE LOWER BOUNDS (NDIM)
C            XUPR   VARIABLE UPPER BOUNDS (NDIM)
C            XVEC   INDEPENDENT VARIABLES (NDIM)
C            XBAR   NEW ESTIMATE OF XVEC (NDIM)
C            XOLD   OLD ESTIMATE OF VARIABLES (NDIM)
C            ISTATO OLD VARIABLE/CONSTRAINT STATUS (NDIM+MDIM)
C            FHFLTR FILTER ARRAY (MXFLTR*3)
C            ISCRTC INTEGER SCRATCH ARRAY (MXFLTR)
C            LNFLTR LENGTH OF CURRENT FILTER
C            MXFLTR MAX LENGTH OF FHFLTR AND ISCRTC
C            CMAX   UPPER BOUND ON CONSTRAINT VIOLATION IN FILTER
C            FILTUR LOGICAL FLAG; TRUE WHEN USING FILTER, FALSE FOR MERIT FUNCTION
C            WORK   WORK ARRAY (NWORK)
C            IWORK  INTEGER WORK ARRAY (NIWORK)
C
C         -- REAL QUANTITIES
C
C            PGNORM NORM OF PROJECTED GRADIENT
C            DELFNM NORM OF GRADIENT
C            FNOM   OBJECTIVE FUNCTION AT XVEC
C            FBAR   FNOM AT XBAR
C            FXTRAP EXTRAPOLATED OBJECTIVE FUNCTION
C            FMIN   PREDICTED MIN. FUNCTION VALUE
C            SNORM  LENGTH OF VECP 
C
C         --INTEGER QUANTITIES
C
C            IFUNER FUNCTION ERROR FLAG
C                   = 0    FUNCTION EVALUATED
C                   = 1    FUNCTION EVALUTION IMPOSSIBLE
C                   = 2    CONSTRAINT ELIMINATION IMPOSSIBLE
C                   = -100 MAX. NO. OF FUNCTION EVALS.
C            IREVRS (1) =1 WHEN EVALUATING FUNCTION
C                   (2) .GE.1 WHEN EVALUATING GRADIENT
C                   (3) .GE.1 WHEN EVALUATING HESSIAN
C                   (4) =1 WHEN SYSTEM PRINT IS REQUIRED
C                   (5) =2 WHEN HESSIAN RESET IS REQUIRED
C            IPU    OUTPUT UNIT NO.
C            ISTART QP START OPTION
C                   = -1   HOT START
C                   = 0    WARM START
C                   = 1    COLD START
C            ITERM  TERMINATION FLAG
C                   .LT.0  USER ABORT
C                   = 0    NO TERMINATION
C                   = 1    NORMAL TERMINATION
C                   = 2    WEAK SOLUTION
C                   .GE.3  ABNORMAL TERMINATION
C            MCON   NUMBER OF CONSTRAINTS
C            MDIM   DIMENSION OF CONSTRAINT ARRAYS
C            MINOPT MINIMIZATION OPTION
C            NONZH  NUMBER OF HESSIAN NONZEROS
C            NONZG  NUMBER OF NONZEROS IN JACOBIAN
C            NONZR  NUMBER OF NONZEROS IN RESIDUAL JACOBIAN
C            NRES   NUMBER OF RESIDUALS
C            MAXRES DIMENSION OF RESIDUAL ARRAY
C            MEQUAL NUMBER OF EQUALITY CONSTRAINTS
C            NDIM   NUMBER OF VARIABLES IN OVERALL PROBLEM
C            NWORK  LENGTH OF WORK ARRAY 
C            NIWORK LENGTH OF IWORK ARRAY
C
C         --LOGICAL QUANTITIES
C
C            EXTRAP TRUE FOR EXTRAPOLATION
C            REFPNT TRUE IF CURRENT XVEC IS REFERENCE POINT.
C            SRCPNT TRUE IF CURRENT XVEC IS SEARCH POINT.
C
C         --INPUT COMMONS
C
C            CONTOL CONSTRAINT TOLERANCE
C            OBJTOL OBJECTIVE FUNCTION TOLERANCE
C            PGDTOL PROJECTED GRADIENT TOLERANCE
C            IOFLAG OUTPUT CONTROL FLAG
C                   = 0    NO OUTPUT
C                   = 10   NORMAL OUTPUT
C                   .GE.20 DIAGNOSTIC OUTPUT
C            IT1MAX MAX. NO. OF ITERATIONS IN SEARCH
C            NITMAX MAX. NO. OF UNCONSTRAINED ITERATIONS
C
C         INTERNAL: THE "SAVE" STATEMENT IS USED TO SAVE QUANTITIES FROM
C                   ITERATION TO ITERATION.
C
      COMMON /ITEREF/ MAXREF,MAXRFN,IREFIN
      COMMON /KONSTN/ 
     *  ZEROMN  ,ZEROOT  ,BIGNUM  ,BGROOT  ,BIGBND  ,BIGCND
C-------------------------------------------------------------
      INCLUDE '../commons/NLPSPR.CMN'
      INCLUDE '../commons/BARNLP.CMN'
C-------------------------------------------------------------
      LOGICAL LINEAR
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0,TWO=2.0D0,FOUR=4.0D0,
     $    ONEEP1=1.0D1,ONEEP2=1.0D2,ONEEP3=1.0D3,ONEEP5=1.0D5,
     $    ONEEM1=1.0D-1,ONEEM2=1.0D-2,ONEEM3=1.0D-3,ONEEM5=1.0D-5,
     $    POINT2=2.0D-1,POINT5=5.0D-1,POINT8=8.0D-1,POINT9=9.0D-1,
     $    THREE=3.0D0)
      PARAMETER (ONQRTR = ONE/FOUR, THQRTR = THREE/FOUR)
      PARAMETER (REDTOL=ONEEM5)
      DIMENSION CVEC(MDIM),CBAR(MDIM),DELF(NDIM),PGRAD(NDIM),
     $    GMAT(NONZG),IROWG(NONZG),JSTRG(NDIM+1),RESVEC(MAXRES),
     $    RMAT(NONZR),IROWR(NONZR),JSTRR(NDIM+1),HMAT(NONZH),
     $    IROWH(NONZH),JSTRH(NDIM+1),VECP(NDIM),
     $    TVEC(NDIM),UVEC(NDIM),XVEC(NDIM),XBAR(NDIM),XOLD(NDIM),
     $    WORK(NWORK),VECLAM(MDIM),IWORK(NIWORK),
     $    VECXI(MCON+NDIM),VECQ(MCON+NDIM),VECS(MCON+NDIM),VECMU(MDIM),
     $    VLAMBR(MDIM),VECSBR(MCON+NDIM),XLWR(NDIM),XUPR(NDIM),
     $    VECNU(NDIM),CLWR(MDIM),CUPR(MDIM),ISTATC(MDIM),ISTATV(NDIM),
     $    VCNUBR(NDIM),PENVEC(MCON+NDIM),ISTATO(NDIM+MDIM)
      DIMENSION IREVRS(5)
      DIMENSION FHFLTR(MXFLTR,3),ISCRTC(MXFLTR)
C
      LOGICAL ACCEPT,EQPSTP,FILTUR
      LOGICAL CURVLN,EXTRAP,HSNSTR,REFPNT,SRCPNT
      LOGICAL KHNCHK,HESEVL,GRDEVL,RESET,GOODGR
      LOGICAL OLDSET
      CHARACTER(LEN=6)  CHITER
C
      PARAMETER (MAXLVN=15)
      COMMON /LEVNP1/ LEVNIT
      COMMON /LEVNP2/ LEVNDY
      COMMON /TYMQP/ NQPITR
      CHARACTER(LEN=60) LEVNDY(MAXLVN)
      CHARACTER(LEN=60) BLANK,CHWORK
      COMMON /CONDLB/ CNDLBL
      CHARACTER(LEN=17) CNDLBL
      CHARACTER(LEN=16) LFTVAL,RITVAL
C
C         COMMON FOR ITERATION LOG QUANTITIES
C
C     ------------------------------------------------------------------
      INCLUDE  '../commons/NLPOUT.CMN'
C     ------------------------------------------------------------------
C
      DATA BLANK(1:60) / ' '/
C
C     ******************************************************************
C
      IF (IMAX(4,IREVRS,1).GE.1) THEN
        IF (IFESR.EQ.1) THEN
          GO TO 501
        ELSEIF (IFESR.EQ.2) THEN
          GO TO 502
        ELSEIF (IFESR.EQ.3) THEN
          GO TO 503
        ENDIF
      ENDIF
C
C ----------------------------------------------------------------------
C
C         ALGORITHM INITIALIZATION
C
C         LOGICAL QUANTITIES
C
      CURVLN = MINOPT.EQ.2
      EQPSTP = .FALSE.
      REFPNT = .FALSE.
      KHNCHK = .FALSE.
      RESET = .FALSE.
      OLDSET = RESET
C
C         SET GRADIENT AND HESSIAN EVALUATION FLAGS BASED ON MINOPT
C
      IF(MINOPT.LE.3) THEN
        GRDEVL = .TRUE.
        HESEVL = .TRUE.
      ELSE
        GRDEVL = .FALSE.
        HESEVL = .FALSE.
      ENDIF
C
      IF(NEWTON.EQ.2) THEN
        HESEVL = .FALSE.
        HMAT(1:NONZH) = ZERO
      ENDIF
C
C         SET HESSIAN INITIALIZATION FLAG 
C
      IF(IHESHN.LT.0) THEN
        HSNSTR = .TRUE.
        IHESHN = -IHESHN
      ELSE
        HSNSTR = .FALSE.
      ENDIF
C
C         SET GOOD GRADIENT FLAG BASED ON HESSIAN OPTION
C
      IF(IHESHN.EQ.0) THEN
        GOODGR = .TRUE.
      ELSE
        GOODGR = .FALSE.
      ENDIF
C
C         INTEGER QUANTITIES
C
      IT = 1
      ITP = IT    
      IT1 = 1
      ITERM = 0
      ITURM = 0
C
C         REAL QUANTITIES
C
      FBAR = FNOM
      FMIN = FNOM
      FREDUC = BIGNUM
      ALFA = ONE
      CNDNUM = ONE
      DIAGNL = ZERO
      EIGMAX = ZERO
      EIGMIN = ZERO
      PGRATE = POINT5
      PENRHO = ZEROOT
C
C             INITIALIZE TERSE OUTPUT IF NECESSARY
C
      NPRFLG = -2
C
      IF  ( QPOPTN.NE.'SPARSE' )  THEN
        CNDLBL = 'Cond(Z''HZ).......'
      ELSE
        CNDLBL = 'Cond(K)..........'
      ENDIF
C
C         INITIALIZE PENALTY WEIGHT VECTOR
C
      PENVEC(1:MCON+NDIM) = PENRHO
C
C         INITIALIZE STEP LIMIT
C
      STPLIM = ZERO
      DO KK=1,NDIM
        STPLIM = STPLIM + XVEC(KK)**2
      ENDDO
      STPLIM = SQRT(STPLIM)
      IF(MINOPT.LE.3) THEN
        SNORM = BIGBND
      ELSE
        TAU = OBJTOL/(ONE + ABS(FNOM))
        SNORM = ONEEM1*SQRT(TAU)*(ONE + STPLIM)
      ENDIF
C
C         INITIALIZE XBAR AND VECS
C
      DO KK = 1,NDIM
        XBAR(KK) = XVEC(KK)
        VECP(KK) = ZERO
      ENDDO
      VECS(1:MCON) = ZERO
C
C ----------------------------------------------------------------------
C
C         BEGIN ITERATION
C
 110  CONTINUE
C
C ----------------------------------------------------------------------
C
C         COMPUTE PROJECTED GRADIENT
C
      IREVRS(1) = 0
C
C         SET GRADIENT CALL FLAG BASED ON THE FLAG GOODGR.  IF GOODGR 
C         IS TRUE REQUEST GOOD (I.E CENTRAL DIFFERENCE) GRADIENTS.  IF
C         GOODGR IS FALSE REQUEST CHEAP (I.E. FORWARD DIFFERENCE) GRADIENTS.
C         SET HESSIAN CALL FLAG TO COMPUTE THE HESSIAN DIAGONAL (OR GET
C         READY FOR A SUBSEQUENT FULL HESSIAN CALL).
C
      IF(.NOT.GRDEVL) GO TO 501
C
      IF(GOODGR) THEN
        IREVRS(2) = 2
        IREVRS(5) = 3
      ELSEIF(HSNSTR.AND.IT.EQ.1) THEN
        IREVRS(2) = 2
        IREVRS(5) = 5
      ELSEIF(IHESHN.NE.0.AND.IT.EQ.1) THEN
        IREVRS(2) = 0
      ELSE
        IREVRS(2) = 1
      ENDIF
C
      IF(HESEVL) THEN
        IREVRS(3) = 1
      ELSE
        IREVRS(3) = 0
      ENDIF
C
      IF(RESET) IREVRS(5) = 2
C
      IF (IOFLAG.GE.10) THEN
        IREVRS(4) = 1
      ELSE
        IREVRS(4) = 0
      ENDIF
      IFESR = 1
C
C         RETURN FOR FUNCTION AND GRADIENT EVALUATION
C
      RETURN
C
C         FUNCTION EVALUATION RETURN POINT
C
 501  CONTINUE
C
      IREVRS(1:4) = 0
      IF(IREVRS(5).EQ.5) IREVRS(5) = 1
C
      IF(IFUNER.EQ.-100) THEN
C
C         MAX. NO. OF FUNCTION EVALS.
C
        ITERM = 6
        GO TO 150
C
      ENDIF
C
C ----------------------------------------------------------------------
C
C         CONVERGENCE TESTS
C
      CALL ECNVRG(GMAT,IROWG,JSTRG,NONZG,CLWR,CUPR,CVEC,DELF,VECLAM,
     $    VECNU,VECP,XLWR,XUPR,XVEC,ISTATC,ISTATV,ALFA,DELFNM,
     $    FNOM,FMIN,FREDUC,CONTOL,OBJTOL,PGDTOL,
     $    IT,MCON,MDIM,MINOPT,NDIM,NITMAX,NITMIN,IFUNER,ITERM,IOFLAG,
     $    IPU,PGRAD,ERREQL,ERRINQ,PGNORM)
C
C         IF GRADIENTS ARE SMALL AND POSSIBLY INACCURATE REDO THE
C         GRADIENT EVALUATION WITH ACCURATE GRADIENTS
C
      IF(GOODGR.AND.IT.LE.9999) THEN
        CHITER = '(    )'
        IF(EQPSTP) CHITER = '[    ]'
        WRITE(CHITER(2:5),'(I4)') IT
      ELSEIF(HSNSTR.AND.IT.EQ.1.AND.IT.LE.9999) THEN
        CHITER = '(    )'
        IF(EQPSTP) CHITER = '[    ]'
        WRITE(CHITER(2:5),'(I4)') IT
      ELSE
        CHITER = '      '
        WRITE(CHITER(1:6),'(I6)') IT
        IF(PGNORM.LT.PGDTOL) THEN
          GOODGR = .TRUE.
          GO TO 110
        ENDIF
      ENDIF
      CALL HHSDEL(CHITER,' ',' ',6,NDEL,IERDEL)
C
C         IF A FUNCTION ERROR OCCURED DURING GRADIENT EVALUATION TERMINATE
C
      IF(ITERM.EQ.5) GO TO 150
C
C         ITERATION PRINT
C
      IF(IOFLAG.GE.10) THEN
        CALL HHCPRS(CHITER,' ','-')
        WRITE(IPU,1001) CHITER
        WRITE(LFTVAL,'(SP,1PG14.6)') PGNORM
        WRITE(RITVAL,'(SP,1PG14.6)') FNOM
        CALL DBLSTR('Projected Gradient',LFTVAL,
     $               'Objective Function',RITVAL,IPU)
        WRITE(LFTVAL,'(SP,1PG14.6)') ERREQL
        WRITE(RITVAL,'(SP,1PG14.6)') ERRINQ
        CALL DBLSTR('Equality Error',LFTVAL,
     $               'Inequality Error',RITVAL,IPU)
      ENDIF
C
C         TRANSFER TO TERMINATION PROCEDURE BLOCK IF CONVERGENCE
C         TESTS ARE SATISFIED
C
      IF(ITERM.NE.0) THEN
        MACTIV = 0
        PENMAG = PENRHO
        DO I=1,MCON
          IF (ISTATC(I).GE.1 .AND. ISTATC(I).LE.3)  MACTIV = MACTIV + 1
          PENMAG = MAX(PENMAG,ABS(PENVEC(I)))
        ENDDO
        DO I=1,NDIM
          IF (ISTATV(I).GT.0)  MACTIV = MACTIV + 1
          PENMAG = MAX(PENMAG,ABS(PENVEC(MCON+I)))
        ENDDO
        NDOF = NDIM - MACTIV
        IF(IOFLAG.GE.10) THEN
          WRITE(LFTVAL,'(SP,1PG14.6)') FMRT
          WRITE(RITVAL,'(SP,1PG14.6)') PENMAG
          CALL DBLSTR('Merit Function',LFTVAL,
     $               'Penalty Weight Norm',RITVAL,IPU)
          WRITE(LFTVAL,'(SP,1PG14.6)') DIAGNL
          WRITE(RITVAL,'(SP,1PG14.6)') CNDNUM
          CALL DBLSTR('Levenberg Parameter',LFTVAL,
     $               CNDLBL,RITVAL,IPU)
          WRITE(LFTVAL,'(SP,1PG14.6)') EIGMIN
          WRITE(RITVAL,'(SP,1PG14.6)') EIGMAX
          CALL DBLSTR('Min. Eigenvalue',LFTVAL,
     $               'Max. Eigenvalue',RITVAL,IPU)
          WRITE(LFTVAL,'(I8)') MACTIV
          WRITE(RITVAL,'(I8)') NDOF
          CALL DBLSTR('Active Constraints',LFTVAL,
     $               'Degrees of Freedom',RITVAL,IPU)
          WRITE(LFTVAL,'(I8)') 0
          WRITE(RITVAL,'(I8)') 0
          CALL DBLSTR('QP Iterations',LFTVAL,
     $               'Matrix Factorizations',RITVAL,IPU)
          IF(FILTUR) CALL PRFLTR('   ',FHFLTR,LNFLTR,MXFLTR)
        ENDIF
        IF(IOFLAG.GT.0.AND.IOFLAG.LT.10) THEN
          CVIOLN = ERREQL + ERRINQ
          CALL WRTURS(NPRFLG,CHITER,0,NDOF,ALFA,SNRMN,FMRT,0,PGNORM,
     $    CVIOLN,PENMAG,DIAGNL,CNDNUM,IPU) 
        ENDIF
C
C       ----------------------------------------------------------------
C
C         SAVE ITERATION LOG QUANTITIES
C
        ITP    = IT    
        KEYMP  = 1 
        PPGNOR = PGNORM
        PFNOM  = FNOM  
        PERREQ = ERREQL
        PERRIN = ERRINQ
        PFMRT  = FMRT  
        PPENMA = PENMAG
        PDIAGN = DIAGNL
        PCNDNU = CNDNUM
        PEIGMI = EIGMIN
        PEIGMA = EIGMAX
        MACTIP = MACTIV
        NDOFP  = NDOF  
        NQPITP = 0
        NUMKTP = 0
C
C       ----------------------------------------------------------------
C
        GO TO 150
      ENDIF
C
C ----------------------------------------------------------------------
C ----------------------------------------------------------------------
C ----------------------------------------------------------------------
C
C         COMPUTE FINITE DIFFERENCE HESSIAN MATRIX
C
      IREVRS(1) = 0
      IREVRS(2) = 0
      IREVRS(4) = 0
C
C        SET HESSIAN CALL FLAG
C
      IREVRS(3) = 2
C
      IFESR = 2
C
C         IF HESSIAN IS NOT NEEDED GO ON
C
      IF(.NOT.HESEVL) GO TO 502
C
C         RETURN FOR HESSIAN EVALUATION
C
      RETURN
C
C         FUNCTION EVALUATION RETURN POINT
C
 502  CONTINUE
C
      IREVRS(1:4) = 0
      IREVRS(5) = 1
C
      IF(IFUNER.EQ.-100) THEN
C
C         MAX. NO. OF FUNCTION EVALS.
C
        ITERM = 6
        GO TO 150
C
      ELSEIF(IFUNER.NE.0) THEN
C
C         FUNCTION ERROR DURING HESSIAN EVALUATION...TERMINATE
C
        ITERM = 5
        GO TO 150
C
      ENDIF
C
C ----------------------------------------------------------------------
C
      LEVNIT = 0
      IF(IT.EQ.1) THEN
C
        PGNOLD = MAX(ZEROMN,PGNORM)
C
      ELSE
C
C         ---TRUST REGION UPDATE FOR LEVENBERG CORRECTION 
C
C
C         COMPARE PREDICTED REDUCTION TO ACTUAL REDUCTION
C
        BADSTP = ONQRTR
        GOODST = THQRTR
C
        IF(ACTRED.LE.BADSTP*PRERED.AND.ALFA.LT.ONE) THEN
C
C         BAD STEP WITH CURRENT TRUST RADIUS -- REDUCE THE SIZE
C         OF THE TRUST RADIUS (INCREASE HESSIAN DIAGONAL) 
C         FOR SUBSEQUENT STEPS
C
          DIAGOL = DIAGNL
          DIAGNL = TWO*MAX(DIAGNL,ZEROOT)
          DIAGNL = MIN(DIAGNL,ONE)
C
          IF(IOFLAG.GE.20.AND.LEVNIT.LT.MAXLVN.AND.DIAGOL.LT.ONE) THEN
            LEVNIT = LEVNIT + 1
            LEVNDY(LEVNIT) = BLANK
            WRITE(LEVNDY(LEVNIT)(1:16),'(SP,1PG16.6)') DIAGNL
            LEVNDY(LEVNIT)(20:49) = 'Bad step...reduce trust radius'
          ENDIF
C 
        ELSEIF((ACTRED.GE.GOODST*PRERED.OR.KHNCHK).AND.ALFA.GE.ONE) THEN
C
C         GOOD STEP WITH CURRENT TRUST RADIUS -- INCREASE THE
C         SIZE (REDUCE HESSIAN DIAGONAL) FOR SUBSEQUENT STEPS
C
          REDUCT = MIN(POINT5,PGNORM/PGNOLD)
          DIAGOL = DIAGNL
          DIAGNW = DIAGNL*REDUCT
          IF(DIAGNW.GE.ZEROOT) THEN
            DIAGNL = DIAGNW
          ELSE
            DIAGNL = ZERO
          ENDIF
C
          IF(IOFLAG.GE.20.AND.LEVNIT.LT.MAXLVN.AND.DIAGOL.GT.ZERO) THEN
            LEVNIT = LEVNIT + 1
            LEVNDY(LEVNIT) = BLANK
            WRITE(LEVNDY(LEVNIT)(1:16),'(SP,1PG16.6)') DIAGNL
            LEVNDY(LEVNIT)(20:52) = 'Good step...increase trust radius'
          ENDIF
C
        ENDIF
C
        PGRATE = PGNORM/PGNOLD
        PGNOLD = MAX(ZEROMN,PGNORM)
C
      ENDIF
C     
C         SOLVE WITHOUT ITERATIVE REFINEMENT UNLESS NEAR THE ANSWER
C         (I.E. KHNCHK = TRUE)
C
      IF(KHNCHK) THEN
        IREFIN = 2
      ELSE
        IREFIN = 0
      ENDIF
C
C         COMPUTE SEARCH DIRECTION
C
      CALL SRCHDR(MCON,MEQUAL,MDIM,NDIM,GMAT,IROWG,JSTRG,NONZG,
     $    NRES,RMAT,IROWR,JSTRR,NONZR,HMAT,IROWH,JSTRH,NONZH,
     $    DELF,DELFNM,CLWR,CUPR,CVEC,ISTATC,VECLAM,ISTATV,XVEC,XLWR,
     $    XUPR,ISTATO,DIAGNL,FNOM,PENRHO,PENVEC,WORK,NWORK,IWORK,
     $    NIWORK,NEEDED,ISTART,IT,IPU,IOFLAG,VECP,VECXI,VECQ,VECS,
     $    VECMU,VECNU,VECSBR,CNDNUM,DF0,D2F0,EIGMIN,EIGMAX,FMIN,
     $    ITERM,NQPITR,NUMKTF,LINEAR,RESET,EQPSTP)
C
C         TRANSFER TO TERMINATION PROCEDURE BLOCK IF SEARCH
C         DIRECTION CALCULATION FAILED
C
      IF(OLDSET.AND.RESET) ITERM = -10
      OLDSET = RESET
      IF(ITERM.NE.0) THEN
        IF(IOFLAG.GE.20.AND.LEVNIT.LT.MAXLVN.AND.LEVNIT.GT.0) THEN
          WRITE(IPU,1007)
          CHWORK = BLANK
          CHWORK(4:16) = 'New Levenberg'
          CHWORK(20:25) = 'Reason'
          WRITE(IPU,1011) CHWORK
          WRITE(IPU,1011) (LEVNDY(II),II = 1,LEVNIT)
          WRITE(IPU,1007)
        ENDIF
        GO TO 150
      ENDIF
C
C         COMPUTE SNRMN
C
      SNRMN = ZERO
      DO I=1,NDIM
        SNRMN = SNRMN + VECP(I)**2
      ENDDO
      SNRMN = SQRT(SNRMN)
C
C ----------------------------------------------------------------------
C ----------------------------------------------------------------------
C ----------------------------------------------------------------------
C
C
C         LINE SEARCH.  MINIMIZE MERIT(ALFA)
C
C         INITIALIZE MERIT FUNCTION FOR UNIVARIATE SEARCH
C
      CALL MERIT (VECLAM,VECNU,VECS,PENVEC,FNOM,CVEC,XVEC,
     $    MCON,NDIM,FMRT)
C
C         ITERATION PRINT
C
      PENMAG = PENRHO
      MACTIV = 0
      DO I=1,MCON
        IF (ISTATC(I).GE.1 .AND. ISTATC(I).LE.3)  MACTIV = MACTIV + 1
        PENMAG = MAX(PENMAG,ABS(PENVEC(I)))
      ENDDO
      DO I=1,NDIM
        IF (ISTATV(I).GT.0)  MACTIV = MACTIV + 1
        PENMAG = MAX(PENMAG,ABS(PENVEC(MCON+I)))
      ENDDO
      NDOF = NDIM - MACTIV
      CVIOLN = ERREQL + ERRINQ
C
C         SPECIAL KUHN-TUCKER CHECK WHEN NEAR CONVERGENCE
C
      IF( ABS(FREDUC).LT.ZEROOT .OR.
     $    ABS(FNOM-FMIN).LT.OBJTOL .OR.
     $    (IT.GT.1.AND.NDOF.EQ.0.AND.CVIOLN.LT.CONTOL) .OR.
     $    PGNORM.LT.PGDTOL .OR.
     $    REDTOL*ABS(DF0).LT.ZEROMN ) KHNCHK = .TRUE.
C
      IF(IOFLAG.GE.10) THEN
        WRITE(LFTVAL,'(SP,1PG14.6)') FMRT
        WRITE(RITVAL,'(SP,1PG14.6)') PENMAG
        CALL DBLSTR('Merit Function',LFTVAL,
     $             'Penalty Weight Norm',RITVAL,IPU)
        WRITE(LFTVAL,'(SP,1PG14.6)') DIAGNL
        WRITE(RITVAL,'(SP,1PG14.6)') CNDNUM
        CALL DBLSTR('Levenberg Parameter',LFTVAL,
     $             CNDLBL,RITVAL,IPU)
        WRITE(LFTVAL,'(SP,1PG14.6)') EIGMIN
        WRITE(RITVAL,'(SP,1PG14.6)') EIGMAX
        CALL DBLSTR('Min. Eigenvalue',LFTVAL,
     $             'Max. Eigenvalue',RITVAL,IPU)
        WRITE(LFTVAL,'(I8)') MACTIV
        WRITE(RITVAL,'(I8)') NDOF
        CALL DBLSTR('Active Constraints',LFTVAL,
     $             'Degrees of Freedom',RITVAL,IPU)
        WRITE(LFTVAL,'(I8)') NQPITR
        WRITE(RITVAL,'(I8)') NUMKTF
        CALL DBLSTR('QP Iterations',LFTVAL,
     $             'Matrix Factorizations',RITVAL,IPU)
        IF(FILTUR) CALL PRFLTR('   ',FHFLTR,LNFLTR,MXFLTR)
        IF(RESET) WRITE(IPU,1003)
      ENDIF
C
      IF(IOFLAG.GE.20.AND.LEVNIT.LT.MAXLVN.AND.LEVNIT.GT.0) THEN
        WRITE(IPU,1007)
        CHWORK = BLANK
        CHWORK(4:16) = 'New Levenberg'
        CHWORK(20:25) = 'Reason'
        WRITE(IPU,1011) CHWORK
        WRITE(IPU,1011) (LEVNDY(II),II = 1,LEVNIT)
        WRITE(IPU,1007)
      ENDIF
C
      IF(IOFLAG.GT.0.AND.IOFLAG.LT.10) THEN
        CALL WRTURS(NPRFLG,CHITER,NQPITR,NDOF,ALFA,SNRMN,FMRT,NUMKTF,
     $    PGNORM,CVIOLN,PENMAG,DIAGNL,CNDNUM,IPU) 
      ENDIF
C
C       ----------------------------------------------------------------
C
C         SAVE ITERATION LOG QUANTITIES
C
      ITP    = IT    
C
C         ALGORITHM KEY INDICATOR
C         KEYMP = 0    ----FEASIBILITY PHASE
C         KEYMP = 1    ----OPTIMIZATION PHASE
C
      KEYMP  = 1 
      PPGNOR = PGNORM
      PFNOM  = FNOM  
      PERREQ = ERREQL
      PERRIN = ERRINQ
      PFMRT  = FMRT  
      PPENMA = PENMAG
      PDIAGN = DIAGNL
      PCNDNU = CNDNUM
      PEIGMI = EIGMIN
      PEIGMA = EIGMAX
      MACTIP = MACTIV
      NDOFP  = NDOF  
      NQPITP = NQPITR
      NUMKTP = NUMKTF
C
C       ----------------------------------------------------------------
C
C         INITIALIZE SEARCH CORRECTION VECTORS
C
      DO I=1,NDIM
        TVEC(I) = ZERO
        UVEC(I) = ZERO
      ENDDO
C
C         DEFINE INITIAL STEP LENGTH
C
C         ---------------------------------------------------
C
      ALFA = ONE
      SNORM = SNRMN
C
C         SAVE SLOPE AND CURVATURE OF MERIT FUNCTION 
C
      SLOPE = DF0
      CURVE = D2F0
C
C         SET LINE SEARCH SLOPE TOLERANCE
C
      TOLSLP = SLPTOL
      IF(LINEAR) TOLSLP = MIN(SLPTOL,ONEEM2)
C
 120  CONTINUE
C
      IF(IT.EQ.LYNPLT) THEN
C
        CALL PLTLYN(NDIM,MCON,ALFA,FBRMRT,FBAR,VECP,XVEC,XBAR,CBAR,
     $    VLAMBR,VECSBR,IREVRS(1),IERPLT)
C
        IF(IREVRS(1).EQ.0) THEN
          ITERM = -11
          GO TO 150
        ENDIF
C
      ELSE
C
        CALL LINSRC(VECP,TVEC,UVEC,XBAR,XVEC,XOLD,NDIM,DF0,D2F0,
     $    FBRMRT,FXTRAP,FREDUC,FMRT,ALFA,TOLSLP,SNORM,
     $    IT1,IT1MAX,CURVLN,EXTRAP,GOODGR,KHNCHK,IFUNER,IREVRS(1),
     $    IOFLIN,IPU,IERLIN)
C
      ENDIF
C
      IF(IREVRS(1).EQ.0) GO TO 140
C
C         COMPUTE LOCATION OF POINT 
C         XBAR = XVEC + ALFA*VECP + (ALFA**2)*TVEC + (ALFA**3)*UVEC
C
      DO I = 1,NDIM
        XBAR(I) = XVEC(I) + 
     $            ALFA*(ALFA*(ALFA*UVEC(I) + TVEC(I)) + VECP(I))
      ENDDO
C
      DO I=1,MCON
        VLAMBR(I) = VECLAM(I) + ALFA*VECXI(I)
        VECSBR(I) = VECS(I) + ALFA*VECQ(I)
      ENDDO
C
      DO I=1,NDIM
        VCNUBR(I) = VECNU(I) + ALFA*VECXI(MCON+I)
        VECSBR(MCON+I) = VECS(MCON+I) + ALFA*VECQ(MCON+I)
      ENDDO
C
C         RETURN FOR FUNCTION EVALUATION
C
      SRCPNT = .TRUE.
      IF(LYNPLT.EQ.IT) SRCPNT = .FALSE.
      IREVRS(4) = 0
      IF(IOFLAG.GE.10.AND.LYNPLT.NE.IT) IREVRS(4) = 1
      IFESR = 3
      RETURN
C
C         FUNCTION EVALUATION RETURN POINT
C
 503  CONTINUE
      SRCPNT = .FALSE.
      IF(IFUNER.EQ.0) THEN
C
C         CONSTRUCT MERIT FUNCTION FOR UNIVARIATE SEARCH
C
        CALL MERIT (VLAMBR,VCNUBR,VECSBR,PENVEC,FBAR,CBAR,
     $      XBAR,MCON,NDIM,FBRMRT)
C
C         CHECK THE KUHN-TUCKER CONDITIONS
C
        IF(KHNCHK) THEN
C
          FREDUK = FBRMRT - FMRT
C
C         NOTE:  NITMIN = 0 SINCE A STEP HAS BEEN TAKEN AT THIS POINT
C
          CALL ECNVRG(GMAT,IROWG,JSTRG,NONZG,CLWR,CUPR,CBAR,DELF,
     $      VLAMBR,VCNUBR,VECP,XLWR,XUPR,XBAR,ISTATC,ISTATV,ALFA,DELFNM,
     $      FBAR,FMIN,FREDUK,CONTOL,OBJTOL,PGDTOL,
     $      IT,MCON,MDIM,MINOPT,NDIM,NITMAX,0,IFUNER,ITURM,IOFLAG,
     $      IPU,PGRAD,ERREQL,ERRINQ,PGNORM)
C
C          IF KUHN-TUCKER CONDITIONS ARE SATISFIED OR THE STEP IS
C          TOO SMALL SET FLAG TO TERMINATE IMMEDIATELY (REGARDLESS 
C          OF THE MERIT FUNCTION VALUE)
C
          IF(ITURM.EQ.1.OR.ITURM.EQ.2.OR.ITURM.EQ.3) IFUNER = -1
C
        ENDIF
C
        IF(FILTUR) THEN
C
C          CHECK THE FILTER TO DECIDE WHETHER TO ACCEPT POINT
C
          CALL FLTRQP(CLWR,CUPR,CBAR,VECLAM,
     $      VECNU,XLWR,XUPR,XBAR,FBAR,CMAX,
     $      MCON,MDIM,NDIM,FHFLTR,LNFLTR,MXFLTR,ISCRTC,ACCEPT)
C
          IF(ACCEPT) THEN
C
C          IF POINT IS ACCEPTED TERMINATE SEARCH IMMEDIATELY
C
            KHNCHK = .TRUE.
            IFUNER = -1
C
          ELSE
C
C           IF POINT IS REJECTED AND MERIT FUNCTION INCREASED
C           DO A LINESEARCH TO REDUCE MERIT FUNCTION (EXTRAP = .FALSE.)
C           IF MERIT FUNCTION DECREASED, TAKE BACKTRACK STEP (EXTRAP = .TRUE.)
C
            IF(FBRMRT.LT.FMRT) THEN
              EXTRAP = .TRUE.
            ELSE
              EXTRAP = .FALSE.
            ENDIF
          ENDIF
C
        ENDIF
C
      ELSE
C
        FBRMRT = HDMCON(1)
C
      ENDIF
C
C         FUNCTION EVALUATED. REENTER ONE DIMENSIONAL SEARCH
C
      GO TO 120
C
C ----------------------------------------------------------------------
C
C         UPDATE INFORMATION
C
 140  CONTINUE
C
C         SET ITERM FLAG BASED ON LINE SEARCH ERROR INDICATOR IERLIN
C
      IF(IERLIN.EQ.3) THEN
        ITERM = -4
      ELSEIF(IFUNER.EQ.-1) THEN
        ITERM = 0
      ELSEIF(IFUNER.EQ.-100) THEN
        ITERM = 6
      ELSEIF(IERLIN.EQ.2) THEN
        IF(FILTUR) THEN
          ITERM = 8
        ELSE
          ITERM = 3
        ENDIF
      ELSEIF(IERLIN.EQ.-1) THEN
        ITERM = 7
      ENDIF
C
C         COMPUTE PREDICTED REDUCTION AND ACTUAL REDUCTION
C         USE FULL LENGTH STEP (ALFA=1) FOR PREDICTION IN ORDER TO
C         RESPOND TO VERY SMALL STEPS IN THE LINE SEARCH
C
      PRERED = -SLOPE - POINT5*CURVE
      ACTRED = FMRT - FBRMRT
C
      IF(MINOPT.EQ.5) THEN
C
C         COMPUTE GRADIENT VECTOR DELF = (RESVEC**T)(RMAT) 
C         AT CURRENT (FINAL) POINT.  DO NOT EVALUATE GRADIENT
C         AND HESSIAN AT FINAL POINT
C
        CVEC(1:MCON) = CBAR(1:MCON)
        CALL MVPSPR(11,NDIM,NRES,RMAT,IROWR,JSTRR,
     $                  RESVEC,DELF)
C
      ELSE
C
C         SET GRADIENT EVALUATION FLAG FOR NEXT ITERATION
C
        GRDEVL = .TRUE.
C
C         SET HESSIAN EVALUATION FLAG FOR NEXT ITERATION
C         THE OLD HESSIAN WILL BE USED IF THE ITERATION 
C         APPEARS TO BE PROGRESSING WELL--OTHERWISE A NEW HESSIAN
C         WILL BE COMPUTED.  GOOD PROGRESS IS INDICATED BY 
C         A) FULL LENGTH STEPS (ALFA = 1)
C         B) POSITIVE DEFINITE HESSIAN WITHOUT MODIFICATION (DIAGNL = 0)
C         C) REASONABLE REDUCTION IN THE PROJECTED GRADIENT (PGRATE .LE. 1/2)
C         D) HESSIAN HAS NOT BEEN RESET TO THE IDENTITY (RESET = .FALSE.)
C         E) A NEWTON METHOD HAS NOT BEEN SPECIFIED BY INPUT (NEWTON = 1)
C
        HESEVL = ALFA.LT.ONE.OR.DIAGNL.NE.ZERO.OR.PGRATE.GT.POINT5
     $        .OR.RESET.OR.NEWTON.EQ.1
        IF(NEWTON.EQ.2) HESEVL = .FALSE.
C
      ENDIF
C
C         CHECK FOR DISCONTINUOUS BEHAVIOR
C
      SMALLN = ONEEP2*ZEROMN
      RESNOR = DAMAX(NDIM,VECP,1) + DAMAX(NDIM+MCON,VECXI,1)
      IF(ABS(ALFA)*RESNOR.LE.SMALLN.AND.ABS(FREDUC).GT.SMALLN
     $    .AND.IOFLAG.GE.10) WRITE(IPU,1002)
C      
C         SET THE GRADIENT ACCURACY FOR THE NEXT ITERATION
C
      IF(.NOT.GOODGR) THEN
        SMALCH = MAX(OBJTOL,ZEROOT)
        IF(ABS(FREDUC).LT.SMALCH) THEN
          FREDUC = BIGNUM
          IF(ITERM.EQ.3) ITERM = 0
          GOODGR = .TRUE.
        ENDIF
        IF(ALFA*SNORM.LT.SMALLN) THEN
          ALFA = TWO
          IF(ITERM.EQ.3) ITERM = 0
          GOODGR = .TRUE.
        ENDIF
        IF(KHNCHK.AND..NOT.FILTUR) THEN
          IF(ITERM.EQ.3) ITERM = 0
          GOODGR = .TRUE.
        ENDIF
      ENDIF
C
      IT = IT + 1
      IT1 = 1
      FNOM = FBAR
      FMRT = FBRMRT
      REFPNT = .TRUE.
C
      DO I=1,NDIM
        XVEC(I) = XBAR(I)
        VECNU(I) = VCNUBR(I)
      ENDDO
      VECLAM(1:MCON) = VLAMBR(1:MCON)
C
C         IF ITERM =   6 MAX. NO. OF FUNCTION EVALS.
C         IF ITERM =  -1 (REDUCED OBJECTIVE FUNCTION IS LINEAR) OR;
C         IF ITERM =  -6 SCHUR-QP FAILED WITH UNEXPECTED ERROR
C         IF ITERM =  -7 SINGULAR MATRIX PREVENTED SEARCH DIRECTION 
C                        FROM BEING CALCULATED;
C         IF ITERM =  -8 INSUFFICIENT REAL STORAGE FOR SRCHDR
C         IF ITERM =  -9 SEARCH DIRECTION FAILED; SLOPE CONDITION
C         IF ITERM = -10 SEARCH DIRECTION FAILED; MAX. DIAGONAL VALUE.
C         IF ITERM = -12 INSUFFICIENT INTEGER STORAGE FOR SRCHDR
C         IF ITERM = -13 I/O ERROR (INSUFFICIENT DISK SPACE)
C 
C         THEN, TERMINATE IMMEDIATELY
C
      IF(ITERM.LE.-1.OR.ITERM.EQ.6) GO TO 150
C
C ----------------------------------------------------------------------
C
C         END OF ITERATION
C
      GO TO 110
C
C ----------------------------------------------------------------------
C
C         TERMINATION PROCEDURES
C
 150  CONTINUE
C
      FBAR = FNOM
      XBAR(1:NDIM) = XVEC(1:NDIM)
C
C
 1001 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'-------------------------------
     $------ Iteration ',A6,'----------------------------------',
     $   T106,'*')
 1002 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....FUNCTION MAY BE DISCONTINU
     $OUS',T106,'*')
 1003 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....RESET HESSIAN AND LAGRANGE
     $ MULTIPLIERS',T106,'*')
 1007 FORMAT(T3,'*',T11,88('-'),T106,'*')
 1011 FORMAT(T3,'*',T11,'|',T20,A60,T98,'|',T106,'*')
      RETURN
      END
