
      SUBROUTINE FILSHR(NDIM,MCON,HMAT,IROWH,JSTRH,LNHSN,CVCT,
     $      GZERO,AMAT,IROW,JCOLST,LNJAC,BUPR,BLWR,XVEC,XUPR,
     $      XLWR,WORK,NWORK,BIGBND,IPU,IPC,ISTART,IPRU,RYTE,FYLE)
C
C ======================================================================
C     FILSHR===>filshr   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         THIS SUBROUTINE IS DESIGNED TO READ OR WRITE A FILE
C         CONTAINING THE DATA TO DEFINE A SPARSE QUADRATIC PROGRAM
C         THE INPUT FORMAT IS DESIGNED TO BE IDENTICAL TO THE 
C         CALLING SEQUENCE OF SCHUR-QP, WITH THE EXCEPTION OF THE
C         FOLLOWING THREE ARGUMENTS
C
C         IPRU  OUTPUT UNIT NO.
C         RYTE  LOGICAL FLAG SET TRUE TO WRITE THE FILE
C               SET FALSE TO READ THE FILE
C         FYLE  FILE NAME
C
      DIMENSION HMAT(LNHSN),IROWH(LNHSN),JSTRH(*),CVCT(*),
     $    GZERO(*),AMAT(LNJAC),IROW(LNJAC),JCOLST(*),
     $    BUPR(*),BLWR(*),XVEC(*),XUPR(*),
     $    XLWR(*),WORK(*)
C
      CHARACTER(LEN=*) FYLE
      LOGICAL RYTE
C
      IF(RYTE) THEN
C
C         WRITE DATA FOR TEST PROBLEM
C
          OPEN(IPRU,FILE=FYLE,STATUS='UNKNOWN',FORM='FORMATTED')
C
          WRITE(IPRU,'(i25)') NDIM,MCON,NWORK,IPU,IPC,ISTART
C
          CALL IRITE (IPRU,JSTRH,NDIM+1)
          CALL IRITE (IPRU,JCOLST,NDIM+1)
          NZHMAT = JSTRH(NDIM+1)-1
          NZAMAT = JCOLST(NDIM+1)-1
C
          CALL RITE  (IPRU,HMAT,NZHMAT)
          CALL IRITE (IPRU,IROWH,NZHMAT)
          CALL RITE  (IPRU,CVCT,NDIM)
          CALL RITE  (IPRU,GZERO,NDIM)
          CALL RITE  (IPRU,AMAT,NZAMAT)
          CALL IRITE (IPRU,IROW,NZAMAT)
          CALL RITE  (IPRU,BUPR,MCON)
          CALL RITE  (IPRU,BLWR,MCON)
          CALL RITE  (IPRU,XVEC,NDIM)
          CALL RITE  (IPRU,XUPR,NDIM)
          CALL RITE  (IPRU,XLWR,NDIM)
          IF(ISTART.LE.0) THEN
            WRITE(IPU,*) 'WORK ARRAY NOT WRITTEN',WORK(1)
CCC         CALL RITE  (IPRU,WORK,NWORK)
          ENDIF
          WRITE(IPRU,'(d25.16)') BIGBND
C
      ELSE
C
C         READ IN DATA FOR TEST PROBLEM
C
          OPEN(IPRU,FILE=FYLE,STATUS='UNKNOWN',FORM='FORMATTED')
C
          READ(IPRU,'(i25)') NDIM,MCON,NWORK,IPU,IPC,ISTART
C
          CALL IREED (IPRU,JSTRH,NDIM+1)
          CALL IREED (IPRU,JCOLST,NDIM+1)
          NZHMAT = JSTRH(NDIM+1)-1
          NZAMAT = JCOLST(NDIM+1)-1
C
          CALL REED  (IPRU,HMAT,NZHMAT)
          CALL IREED (IPRU,IROWH,NZHMAT)
          CALL REED  (IPRU,CVCT,NDIM)
          CALL REED  (IPRU,GZERO,NDIM)
          CALL REED  (IPRU,AMAT,NZAMAT)
          CALL IREED (IPRU,IROW,NZAMAT)
          CALL REED  (IPRU,BUPR,MCON)
          CALL REED  (IPRU,BLWR,MCON)
          CALL REED  (IPRU,XVEC,NDIM)
          CALL REED  (IPRU,XUPR,NDIM)
          CALL REED  (IPRU,XLWR,NDIM)
          IF(ISTART.LE.0) THEN
            WRITE(IPU,*) 'WORK ARRAY NOT READ',WORK(1)
CCC         CALL REED  (IPRU,WORK,NWORK)
          ENDIF
          READ(IPRU,'(d25.16)') BIGBND
C
      ENDIF
C
      CLOSE(IPRU)
C
      RETURN
      END
