

      SUBROUTINE FILTER(FNOM,CERR,CMAX,SMLNBI,SMTUVW,ETAMAX,PENMU,
     $    PENRHO,FHFLTR,LNFLTR,MXFLTR,NWFLTR,ISCRTC,LNISCR)
C
C ======================================================================
C     FILTER===>FILTER   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         PURPOSE:  NLP FILTER ROUTINE 
C
C         INPUT:
C
C            FNOM   OBJECTIVE FUNCTION AT X.
C            CERR   CONSTRAINT ERROR
C            CMAX   ABSOLUTE UPPER BOUND ON CONSTRAINT
C            SMLNBI THE TERM SUM LN(B)
C            SMTUVW THE TERM SUM (|T|+|U|+|V|+|W|) 
C            ETAMAX MAXIMUM ABSOLUTE MULTIPLIER
C            PENMU  BARRIER PARAMETER
C            PENRHO RELAXATION PENALTY PARAMETER
C            FHFLTR ARRAY WITH FIVE COLUMNS, AND LNFLTR ROWS
C                   CONTAINING CURRENT FILTER VALUES
C                   (1)   (2)      (3)             (4)              (5)
C                    f   ||c||  sum ln(b)  sum (|t|+|u|+|v|+|w|)   |eta|
C            LNFLTR LENGTH OF THE CURRENT FILTER
C                   LNFLTR < 0 CAUSES CURRENT FILTER TO BE REFRESHED
C            MXFLTR MAXIMUM LENGTH OF THE FILTER
C            ISCRTC INTEGER SCRATCH ARRAY
C            LNISCR LENGTH OF ISCRTC
C        
C         OUTPUT:
C
C            FHFLTR UPDATED FILTER ARRAY
C            LNFLTR UPDATED LENGTH OF FILTER
C            NWFLTR NEW FILTER ENTRY INDICATOR
C                   = 0    IF FHNEW IS ACCEPTED BY FILTER
C                   = -1   IF FHNEW IS REJECTED BY NORTHWEST CORNER
C                   = -2   IF FHNEW IS REJECTED BY SOUTHEAST CORNER
C                   = BLOCKING FILTER ENTRY OTHERWISE
C
      DIMENSION FHFLTR(MXFLTR,5),FHNEW(5),ISCRTC(LNISCR)
C
      COMMON /KONSTN/ 
     *  ZEROMN  ,ZEROOT  ,BIGNUM  ,BGROOT  ,BIGBND  ,BIGCND
C
C-------------------------------------------------------------
      INCLUDE '../commons/NLPSPR.CMN'
      INCLUDE '../commons/BARNLP.CMN'
C-------------------------------------------------------------
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0)
      PARAMETER (TOLCON=ONE,SMLMLT=1.D-6,BIGMLT=1.D6)
      PARAMETER (TOLMLT=1.D-5,TOLNRW=1.D3)
C
      IF(LNFLTR.LT.0) THEN
C
C         REFRESH THE CURRENT FILTER (BEFORE UPDATING)
C
        LENFLT = - LNFLTR
C
C         LOOP THROUGH TO REMOVE DOMINATED ENTRIES
C
        INEW = 1
        DO I = 2,LENFLT
C
C         CHECK TO SEE IF ROW I DOMINATES THE NEW VALUE
C
          OBJOLD = FHFLTR(I-1,1) - PENMU*FHFLTR(I-1,3) 
     $           + PENRHO*FHFLTR(I-1,4) 
     $           - TOLMLT*FHFLTR(I-1,2)*FHFLTR(I-1,5)
          CONOLD = TOLCON*FHFLTR(I-1,2)
C
          OBJFLT = FHFLTR(I,1) - PENMU*FHFLTR(I,3) + PENRHO*FHFLTR(I,4) 
     $           - TOLMLT*FHFLTR(I,2)*FHFLTR(I,5)
          CONFLT = TOLCON*FHFLTR(I,2)
          IF(OBJFLT.GE.OBJOLD.AND.CONFLT.GE.CONOLD) THEN
C
C         NEW VALUE DOMINATES ROW I--REMOVE ROW I FROM THE NEW FILTER
C
          ELSE
            INEW = INEW + 1
            FHFLTR(INEW,1) = FHFLTR(I,1)
            FHFLTR(INEW,2) = FHFLTR(I,2)
            FHFLTR(INEW,3) = FHFLTR(I,3)
            FHFLTR(INEW,4) = FHFLTR(I,4)
            FHFLTR(INEW,5) = FHFLTR(I,5)
          ENDIF
C
        enddo
C
        LNFLTR = INEW
C
      ENDIF
C
      FHNEW(1) = FNOM
      FHNEW(2) = CERR
      FHNEW(3) = SMLNBI
      FHNEW(4) = SMTUVW
      FHNEW(5) = MAX(SMLMLT,MIN(ETAMAX,BIGMLT))
C
      OBJNEW = FHNEW(1) - PENMU*FHNEW(3) + PENRHO*FHNEW(4)
C
C         INITIALIZE THE FILTER 
C
      CNRWST = BIGNUM
C
      DO I = 1,LNFLTR
C
C         SAVE NORTHWEST CORNER POINT
C
        IF(FHFLTR(I,2).LT.CNRWST) THEN
          FNRWST = FHFLTR(I,1) - PENMU*FHFLTR(I,3) + PENRHO*FHFLTR(I,4)
          CNRWST = FHFLTR(I,2)
          PNRWST = FHFLTR(I,5)
        ENDIF
C
C         DOES ANY POINT IN THE CURRENT FILTER DOMINATE THE NEW VALUE?
C         CHECK TO SEE IF ROW I DOMINATES THE NEW VALUE
C
        OBJFLT = FHFLTR(I,1) - PENMU*FHFLTR(I,3) + PENRHO*FHFLTR(I,4) 
     $           - TOLMLT*FHFLTR(I,2)*FHFLTR(I,5)
        CONFLT = TOLCON*FHFLTR(I,2)
        IF(OBJFLT.LE.OBJNEW.AND.CONFLT.LE.FHNEW(2)) THEN
C
C         ROW I DOMINATES NEW VALUE --- DO NOT ACCEPT IT
C
          NWFLTR = I
          GO TO 1000
        ENDIF
C
      enddo
C
C         COMPUTE "VIRTUAL" POINT AT SOUTHEAST CORNER WITH 
C         FILTER VALUES (-INFINITY,CMAX) WHERE CMAX IS SPECIFIED 
C         CHECK NEW VALUE AGAINST SOUTHEAST CORNER
C
      IF(CMAX.LE.FHNEW(2)) THEN
        NWFLTR = -2
        GO TO 1000
      ENDIF
C
C         CHECK THE NEW VALUE AGAINST THE NORTHWEST CORNER
C
      IF(LNFLTR.GT.0) THEN
C
C         COMPUTE "VIRTUAL" POINT AT NORTHWEST CORNER WITH 
C         FILTER VALUES (FLTNRW,0) WHERE FLTNRW IS PREDICTED 
C
        FLTNRW = FNRWST + TOLNRW*MAX(ONE,MIN(ONE/CONTOL,PNRWST))*CNRWST
        IF(FLTNRW.LE.OBJNEW.AND.CONTOL.LE.FHNEW(2)) THEN
          NWFLTR = -1
          GO TO 1000
        ENDIF      
      ENDIF
C
      NWFLTR = 0
C
C         LOOP THROUGH TO REMOVE VALUES DOMINATED BY NEW ONE
C
      INEW = 0
      DO I = 1,LNFLTR
C
C         CHECK TO SEE IF ROW I DOMINATES THE NEW VALUE
C
        OBJFLT = FHFLTR(I,1) - PENMU*FHFLTR(I,3) + PENRHO*FHFLTR(I,4) 
     $           - TOLMLT*FHFLTR(I,2)*FHFLTR(I,5)
        CONFLT = TOLCON*FHFLTR(I,2)
        IF(OBJFLT.GE.OBJNEW.AND.CONFLT.GE.FHNEW(2)) THEN
C
C         NEW VALUE DOMINATES ROW I--REMOVE ROW I FROM THE NEW FILTER
C
        ELSE
          INEW = INEW + 1
          FHFLTR(INEW,1) = FHFLTR(I,1)
          FHFLTR(INEW,2) = FHFLTR(I,2)
          FHFLTR(INEW,3) = FHFLTR(I,3)
          FHFLTR(INEW,4) = FHFLTR(I,4)
          FHFLTR(INEW,5) = FHFLTR(I,5)
        ENDIF
C
      enddo
C
C         ADD THE NEW VALUE TO THE FILTER
C
      INEW = INEW + 1
      FHFLTR(INEW,1) = FHNEW(1)
      FHFLTR(INEW,2) = FHNEW(2)
      FHFLTR(INEW,3) = FHNEW(3)
      FHFLTR(INEW,4) = FHNEW(4)
      FHFLTR(INEW,5) = FHNEW(5)
C
C         UPDATE THE LENGTH OF THE NEW FILTER
C
      LNFLTR = INEW
C
C         SORT THE FILTER ENTRIES SO THAT CONSTRAINT ERROR IS 
C         MONOTONICALLY INCREASING
C
      CALL HDSRTN(FHFLTR(1,2),LNFLTR,0,0,ISCRTC,IERSRT)
C
C         REORDER THE OTHER VALUES
C
      CALL HDPRMX(FHFLTR(1,1),LNFLTR,ISCRTC,IERPRM)
      CALL HDPRMX(FHFLTR(1,3),LNFLTR,ISCRTC,IERPRM)
      CALL HDPRMX(FHFLTR(1,4),LNFLTR,ISCRTC,IERPRM)
      CALL HDPRMX(FHFLTR(1,5),LNFLTR,ISCRTC,IERPRM)
C
 1000 CONTINUE
C
      RETURN
      END
