

      SUBROUTINE FLTRQP(CLWR,CUPR,CVEC,VECLAM,VECNU,XLWR,XUPR,XVEC,
     $   FNOM,CMAX,MCON,MDIM,NDIM,FHFLTR,LNFLTR,MXFLTR,ISCRTC,
     $   ACCEPT)
C
C ======================================================================
C     FLTRQP===>fltrqp   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         PURPOSE:  NLP FILTER ROUTINE 
C
C         INPUT:
C
C            CLWR   CONSTRAINT LOWER BOUND (MDIM)
C            CUPR   CONSTRAINT UPPER BOUND (MDIM)
C            CVEC   CONSTRAINT VECTOR (MDIM)
C            VECLAM CONSTRAINT MULTIPLIERS (MDIM)
C            VECNU  BOUND MULTIPLIERS (NDIM)
C            XLWR   VARIABLE LOWER BOUNDS (NDIM)
C            XUPR   VARIABLE UPPER BOUNDS (NDIM)
C            XVEC   VARIABLES (NDIM)
C            FNOM   OBJECTIVE FUNCTION AT X.
C            MCON   NUMBER OF CONSTRAINTS
C            MDIM   DIMENSION OF CONSTRAINT ARRAYS
C            NDIM   NUMBER OF VARIABLES
C            FHFLTR ARRAY WITH THREE COLUMNS, AND LNFLTR ROWS
C                   CONTAINING CURRENT FILTER VALUES
C            LNFLTR LENGTH OF THE CURRENT FILTER
C            MXFLTR MAXIMUM LENGTH OF THE FILTER
C            ISCRTC INTEGER SCRATCH ARRAY
C        
C         OUTPUT:
C
C            FHFLTR UPDATED FILTER ARRAY
C            LNFLTR UPDATED LENGTH OF FILTER
C            ACCEPT LOGICAL VARIABLE
C                   = TRUE    IF FHNEW IS ACCEPTED BY FILTER
C                   = FALSE   IF FHNEW IS REJECTED BY FILTER
C
      DIMENSION CLWR(MDIM),CUPR(MDIM),CVEC(MDIM),
     $    VECLAM(MDIM),VECNU(NDIM),XLWR(NDIM),XUPR(NDIM),XVEC(NDIM)
      DIMENSION FHFLTR(MXFLTR,3),FHNEW(3),ISCRTC(MXFLTR)
C
      COMMON /KONSTN/ 
     *  ZEROMN  ,ZEROOT  ,BIGNUM  ,BGROOT  ,BIGBND  ,BIGCND
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0)
      PARAMETER (TOLMLT=1.D-5,TOLNRW=1.D3,TOLCON=.99D0)
C
      LOGICAL ACCEPT
C
C         COMPUTE CONSTRAINT ERRORS
C
      CALL CONERR(CLWR,CUPR,CVEC,XLWR,XUPR,XVEC,MCON,MDIM,NDIM,
     $    ERBEQL,ERBINQ,ERREQL,ERRINQ,CVIOLN)
C
C         COMPUTE LARGEST MULTIPLIERS
C
      XNUMAX = ZERO
      DO I=1,NDIM
        XNUMAX = MAX(XNUMAX,ABS(VECNU(I)))
      ENDDO
      XLAMAX = ZERO
      DO I=1,MCON
        XLAMAX = MAX(XLAMAX,ABS(VECLAM(I)))
      ENDDO
C
      FHNEW(1) = FNOM
      FHNEW(2) = CVIOLN
      FHNEW(3) = MAX(XNUMAX,XLAMAX)
C
C         INITIALIZE THE FILTER 
C
      ACCEPT = .FALSE.
      INEW = 0
C
      HNRWST = BIGNUM
      FNRWST = BIGNUM
      DO I = 1,LNFLTR
C
C         DOES ANY POINT IN THE CURRENT FILTER DOMINATE THE NEW VALUE?
C         CHECK TO SEE IF ROW I DOMINATES THE NEW VALUE
C
        OBJFLT = FHFLTR(I,1) - TOLMLT*FHFLTR(I,2)*FHFLTR(I,3)
        CONFLT = TOLCON*FHFLTR(I,2)
        IF(OBJFLT.LE.FHNEW(1).AND.CONFLT.LE.FHNEW(2)) THEN
C
C         ROW I DOMINATES NEW VALUE --- DO NOT ACCEPT IT
C
          NWFLTR = I
          GO TO 1000
        ENDIF
C
C         SAVE NORTH WEST CORNER CONSTRAINT ERROR
C
        IF(FHFLTR(I,2).LE.HNRWST) THEN
          HNRWST = FHFLTR(I,2)
          FNRWST = FHFLTR(I,1) + FHFLTR(I,2)*FHFLTR(I,3)
          PNRWST = FHFLTR(I,3)
        ENDIF
C
      ENDDO
C
C         CHECK NEW VALUE AGAINST NORTHWEST CORNER
C
      IF(LNFLTR.GT.0) THEN
C
C         COMPUTE "VIRTUAL" POINT AT NORTHWEST CORNER WITH 
C         FILTER VALUES (FLTNRW,0) WHERE FLTNRW IS PREDICTED 
C
        FLTNRW = FNRWST + TOLNRW*MAX(ONE,MIN(ONE/ZEROOT,PNRWST))*HNRWST
        IF(FLTNRW.LE.FHNEW(1).AND.ZEROOT.LE.FHNEW(2)) THEN
          NWFLTR = -1
          GO TO 1000
        ENDIF      
      ENDIF
C
C         CHECK NEW VALUE AGAINST SOUTHEAST CORNER
C
      IF(CMAX.LE.FHNEW(2)) THEN
        NWFLTR = -2
        GO TO 1000
      ENDIF
C
      NWFLTR = 0
      ACCEPT = .TRUE.
C
C         LOOP THROUGH TO REMOVE VALUES DOMINATED BY NEW ONE
C
      DO I = 1,LNFLTR
C
C         CHECK TO SEE IF ROW I DOMINATES THE NEW VALUE
C
        OBJFLT = FHFLTR(I,1) - TOLMLT*FHFLTR(I,2)*FHFLTR(I,3)
        CONFLT = TOLCON*FHFLTR(I,2)
        IF(OBJFLT.GE.FHNEW(1).AND.CONFLT.GE.FHNEW(2)) THEN
C
C         NEW VALUE DOMINATES ROW I--REMOVE ROW I FROM THE NEW FILTER
C
        ELSE
          INEW = INEW + 1
          FHFLTR(INEW,1) = FHFLTR(I,1)
          FHFLTR(INEW,2) = FHFLTR(I,2)
          FHFLTR(INEW,3) = FHFLTR(I,3)
        ENDIF
C
      ENDDO
C
C         ADD THE NEW VALUE TO THE FILTER
C
      INEW = INEW + 1
      FHFLTR(INEW,1) = FHNEW(1)
      FHFLTR(INEW,2) = FHNEW(2)
      FHFLTR(INEW,3) = FHNEW(3)
C
C         UPDATE THE LENGTH OF THE NEW FILTER
C
      LNFLTR = INEW
C
C         SORT THE FILTER ENTRIES SO THAT CONSTRAINT ERROR IS 
C         MONOTONICALLY INCREASING
C
      CALL HDSRTN(FHFLTR(1,2),LNFLTR,0,0,ISCRTC,IERSRT)
C
C         REORDER THE OTHER VALUES
C
      CALL HDPRMX(FHFLTR(1,1),LNFLTR,ISCRTC,IERPRM)
      CALL HDPRMX(FHFLTR(1,3),LNFLTR,ISCRTC,IERPRM)
C
 1000 CONTINUE
C
      RETURN
      END
