
      SUBROUTINE FRSTPN(AMAT,IROW,JCOLST,NONZA,
     $    MCON,MEQUAL,MINEQL,NFRSLK,NFEZ,NRLFR,NEQNS,NDIM,XSTD,
     $    HMAT,IROWH,JSTRH,NONZH,CVCT,GZERO,TEMP,LNTEMP,
     $    SFEZ,RHOFEZ,CHIFEZ,IVSTAT,PVEC,PIVEC,
     $    RTHSKT,SOLNKT,RWORK,LNRWRK,NEEDED,IFREE,ITEMP,CNDNUM,
     $    IPU,IPC,ISTART,NAINQL,ACT2CN,CON2KT,IER)
C
C ======================================================================
C     FRSTPN===>frstpn   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         PURPOSE:
C
C             PERFORM OPERATIONS NECESSARY FOR THE FIRST
C             STEP OF THE SCHUR-COMPLEMENT QUADRATIC PROGRAMMING
C             METHOD.
C
C         INPUT:
C
C             AMAT    JACOBIAN MATRIX (NONZA)
C             IROW    INTEGER ROW INDEX FOR JACOBIAN (NONZA)
C             JCOLST  COLUMN START ARRAY FOR JACOBIAN (NDIM+1)
C             NONZA   NO. OF NONZEROS IN AMAT = JCOLST(NDIM+1)-1
C             MCON    NUMBER OF CONSTRAINTS
C             MEQUAL  NUMBER OF EQUALITIES
C             MINEQL  NUMBER OF INEQUALITIES
C             NFRSLK  NUMBER OF FREE SLACKS
C             NFEZ    NUMBER OF FEASIBILITY VARIABLES
C             NRLFR   NUMBER OF FREE REAL VARIABLES
C             NEQNS   NUMBER OF EQUATIONS IN KT SYSTEM
C             NDIM    NUMBER OF REAL VARIABLES
C             XSTD    STANDARD FORM VARIABLES (NSTD)
C                     NSTD = MINEQL + 1 + NDIM
C             HMAT    HESSIAN MATRIX (NONZH)
C             IROWH   INTEGER ROW INDEX FOR HESSIAN (NONZH) 
C             JSTRH   COLUMN START ARRAY FOR HESSIAN (NDIM+1)
C             NONZH   NO. OF NONZEROS IN HMAT =JSTRH(NDIM+1)-1
C             CVCT    OBJECTIVE FUNCTION LINEAR TERM (NDIM)
C             GZERO   GRADIENT OF OBJECTIVE AT INITIAL POINT (NDIM)
C             TEMP    WORK ARRAY (LNTEMP)
C             LNTEMP  LENGTH OF TEMP
C             SFEZ    SCALED FEASIBILITY RESIDUAL VECTOR (MCON)
C             RHOFEZ  FEASIBILITY PENALTY WEIGHT, LINEAR TERM
C             CHIFEZ  FEASIBILITY PENALTY WEIGHT, QUADRATIC TERM
C             IVSTAT  INTEGER VARIABLE STATUS FLAG (MCON+1+NDIM)
C             IPU     OUTPUT UNIT NO.
C             IPC     OUTPUT CONTROL FLAG
C             ISTART  INTEGER START OPTION
C                     = -1    --- HOT START
C                     .GE.0   --- COLD START
C
C             NAINQL NUMBER OF ACTIVE INEQUALITIES
C             ACT2CN MAP FROM THE MEQUAL+NAINQL ACTIVE CONSTRAINTS
C                    TO TE QP CONSTRAINT INDEX. THAT IS, ACT2CN(I) IS
C                    THE QP CONSTRAINT INDEX CORRESPONDING TO THE I-TH
C                    ACTIVE CONSTRAINT. (MEQUAL+NAINQL)
C             CON2KT MAP FROM THE QP CONSTRAINT INDEX TO THE ACTIVE
C                    CONSTRAINTS,I.E. THE CONSTRAINTS IN THE KKT MATRIX.
C                    CON2KT(J) = K (FOR K>0) IF QP CONSTRAINT J
C                    IS THE K-TH ACTIVE CONSTRAINT, AND CON2KT(J) = -1
C                    IF QP CONSTRAINT J IS INACTIVE. (MCON)
C                               
C
C         OUTPUT:
C
C             GZERO   GRADIENT OF OBJECTIVE AT INITIAL POINT (NDIM)
C             PVEC    FREE VARIABLE SEARCH DIRECTION (NSTD)
C             PIVEC   LAGRANGE MULTIPLIERS FOR STANDARD FORM EQUALITIES (MCON)
C             RTHSKT  RIGHT HAND SIDE OF KT SYSTEM (NEQNS)
C             SOLNKT  SOLUTION OF KT SYSTEM (NEQNS)
C             RWORK   K-T SYSTEM WORK ARRAY.  THIS MUST NOT BE CHANGED
C                     IF SUBSEQUENT USE OF THE FACTORIZATION IS NEEDED.
C             LNRWRK  LENGTH OF K-T WORK ARRAY.
C             NEEDED  STORAGE REQUIRED IF LNRWRK IS TOO SMALL
C             IFREE   INTEGER FREE VARIABLE ARRAY (MINEQL+1+NDIM)
C             ITEMP   INTEGER WORK ARRAY (NEQNS)
C             CNDNUM  CONDITION NUMBER OF K-T SYSTEM
C             IER     INTEGER ERROR RETURN FLAG
C                     = 0    --- SUCCESS
C                     .NE. 0 --- ERROR
C
C
      DIMENSION XSTD(MCON-MEQUAL+1+NDIM),HMAT(NONZH),IROWH(NONZH),
     $   JSTRH(NDIM+1),AMAT(NONZA),IROW(NONZA),JCOLST(NDIM+1),
     $   SFEZ(*),IVSTAT(MCON+1+NDIM),CVCT(NDIM),GZERO(NDIM),
     $   TEMP(LNTEMP),PVEC(MCON-MEQUAL+1+NDIM),PIVEC(*),
     $   RTHSKT(NEQNS),SOLNKT(NEQNS),RWORK(LNRWRK),
     $   IFREE(MCON-MEQUAL+1+NDIM),ITEMP(NEQNS)
C
      INTEGER ACT2CN(MEQUAL+NAINQL+1), CON2KT(MCON+1)
C
      INCLUDE '../commons/NLPSPR.CMN'
C
      COMMON /PERCOM/ ISQPER(20)
C
      COMMON /ITEREF/ MAXREF,MAXRFN,IREFIN
C
      PARAMETER (ZERO=0.D0,ONE=1.D0,ONEEM3=1.D-3)
C
      IF(LNTEMP.LT.MAX(MCON,NDIM)) THEN
        IER = -1101
        STOP
      ENDIF
C
C         COMPUTE THE GRADIENT AT XSTD
C
C         COMPUTE HMAT*XSTD = TEMP
C
      LCXSTD = MCON - MEQUAL + 2
      CALL SYMMVP(HMAT,IROWH,JSTRH,NDIM,XSTD(LCXSTD),TEMP)
C
C         COMPUTE GZERO = CVCT + TEMP
C
      GZERO(1:NDIM) = CVCT(1:NDIM) + TEMP(1:NDIM)
C
C         COMPUTE GRADIENT WITH RESPECT TO ARTIFICIAL VARIABLE
C
      GFEZ = RHOFEZ + CHIFEZ*XSTD(MCON-MEQUAL+1)
C
C         LOAD CONSTRAINT PORTION OF K-T RHS IN TEMP
C
      TEMP(1:MCON) = ZERO
C
C----------------------------------------------------------------------
C
C        SOLVE THE K-T SYSTEM
C
      IF(ISTART.EQ.-1) THEN
C
C        HOT START (DO NOT REFACTOR K-T SYSTEM; JUST SOLVE)
C
        NCALL = 3
C
      ELSE
C
C        COLD START
C
        NCALL = 1
C
      ENDIF
C
      ISQPER(10) = ISQPER(10) + 1
C
      CALL QPSKTN(MCON,NDIM,AMAT,IROW,JCOLST,NONZA,0
     $    ,HMAT,IROWH,JSTRH,NONZH,SFEZ,GFEZ,GZERO,TEMP,IVSTAT
     $    ,PVEC,PIVEC,RTHSKT,SOLNKT,RWORK,LNRWRK,NEEDED
     $    ,IFREE,ITEMP,NCALL,IPU,IPC,CNDNUM,IERKT,LNSYMB,MEQUAL,MINEQL
     $    ,NFRSLK,NFEZ,NRLFR,NEQNS,NAINQL,ACT2CN,CON2KT )
C
      IF(IERKT.NE.0) THEN
C
        select case(ierkt)
        case(:-900)
C
C         INSUFFICIENT REAL WORK STORAGE (LNRWRK TOO SMALL)
C
          IER = -1102
C
        case(-731,-732,750)
C
C         SINGULAR KT MATRIX
C
          IER = -1103
C
        case(-742)
C
C         EXCESSIVE FILL DURING NUMERIC SOLUTION
C
          IER = -1108
C
        case(-744)
C
C         INERTIA OF KT MATRIX IS NOT CORRECT
C
          IER = -1104
C
        case(-700:-600)
C
C         I/O ERROR (INSUFFICIENT DISK SPACE)
C
          IER = -1111
C
        case(-800)
C
C         EXTERNAL USER KILL
C
          IER = -1999
C
        case default
C
C         OTHER MULTIFRONTAL ERRORS
C
          IER = -1105
          WRITE(IPU,1001) IERKT
C
        end select
c
        GO TO 500
C
      ENDIF
C
C         CHECK FOR ILL-CONDITIONED KT MATRIX:  IF ITERATIVE REFINEMENT
C         IS PERMITTED CONTINUE; OTHERWISE SET ERROR FLAG AND TERMINATE
C
      IF(CNDNUM.GT.TOLKTC.AND.IREFIN.EQ.0) THEN
        IER = -1106
        GO TO 500
      ENDIF
C
C
 500  CONTINUE
C
C
 1001 FORMAT(T3,'*',T11,'.....QPSKTN ERROR RETURN; IERKT =',I6,T106,'*')
C
      RETURN
      END
