C
C
C
      SUBROUTINE GETDRP( NX, MINEQL, MEQUAL, IVSTAT, ALMNOI, IPC, 
     .                   IPU, ALMBDA, INDX, SMLMLT, NDROP, IDROP,
     .                   DRPLAM, ALMBIG, IER                    )
C
C ======================================================================
C     GETDRP===>getdrp   J.T. BETTS
C ======================================================================
C
C     ROUTINE TO DETERMINE WHICH, IF ANY, VARIABLE BOUNDS
C     ARE TO BE DROPPED. THE MAGNITUDES OF THE DROP CANDIDATE
C     LAGRANGE MUTLIPLIERS ARE STORED IN ASCENDING ORDER
C     IN DRPLAM. THE IDROP VECTOR STORES THE DROP CANDIDATE
C     INDICES IN ORDER CORRESPONDING TO DRPLAM. IF NDROP = 0
C     THEN ALL MULTIPLIERS HAVE OPTIMAL SIGN AND, IF SMLMLT
C     IS FALSE, THEN THERE ARE NO "ESSENTIALLY ZERO" MULTIPLIERS.
C
      DOUBLE PRECISION ZERO
      PARAMETER ( ZERO = 0.0D0 )
C
      LOGICAL SMLMLT, BIGMLT
C
      INTEGER NX, IPC, IPU, I, NDROP, MINEQL, MEQUAL
      INTEGER IVSTAT(MEQUAL+NX), IDROP(NX)
      INTEGER INDX(NX), IOPT, ISTBLE, JER1, JER2, IER
C
      DOUBLE PRECISION ALMNOI, ALMBDA(NX)
      DOUBLE PRECISION DRPLAM(NX), ALMBIG
C
C
      IER = 0
      NDROP = 0
      ALMBIG = ZERO
      SMLMLT = .FALSE.
      BIGMLT = .FALSE.
C
C     NOTE: IF VAR I HAS IVSTAT(I) = 3 IT IS PERMANENTLY FIXED
C           AT ITS INITIAL VALUE. THUS, IT IS NEVER CONSIDERED
C           FOR DROPPING.
C
      DO I = 1, NX
C
        IF ( IVSTAT(MEQUAL+I) .EQ. 1 ) THEN
C
C         VARIABLE I IS FIXED AT A LOWER BOUND.
C
          IF ( I. NE. MINEQL + 1 ) THEN
C           IF THE VARIABLE IS NOT THE FEASIBILITY VARIABLE,
C           CONSIDER DROPPING ITS LOWER BOUND.
C
            IF ( ABS( ALMBDA(I) ) .LT. ALMNOI ) THEN
C
C             NOT A DROP CANDIDATE BECAUSE THE MULTIPLIER
C             IS SO SMALL IT MAY BE A NOISE RESULT. HENCE, ITS SIGN
C             IS SUSPECT.
C
              SMLMLT = .TRUE.
C
            ELSEIF ( ALMBDA(I) .LT. ZERO ) THEN
C
C             A CANDIDATE FOR DROPPING WITH A SIGNIFICANT MULTIPLIER.
C
              BIGMLT = .TRUE.
C
              NDROP = NDROP + 1
              IDROP(NDROP) = I
              DRPLAM(NDROP) = ABS(ALMBDA(I))
C
              IF ( ABS(ALMBDA(I)) .GT. ALMBIG ) THEN
                ALMBIG = ABS( ALMBDA(I) )
              ENDIF
C
            ENDIF
          ENDIF
C
        ELSEIF ( IVSTAT(MEQUAL+I) .EQ. 2 ) THEN
C
C         VARIABLE I IS FIXED AT AN UPPER BOUND.
C
          IF ( ABS( ALMBDA(I) ) .LT. ALMNOI ) THEN
C
C
C           NOT A DROP CANDIDATE BECAUSE THE MULTIPLIER
C           IS SO SMALL IT MAY BE A NOISE RESULT. HENCE, ITS SIGN
C           IS SUSPECT.
C
            SMLMLT = .TRUE.
C
          ELSEIF ( ALMBDA(I) .GT. ZERO ) THEN
C
C           A CANDIDATE FOR DROPPING WITH A SIGNIFICANT MULTIPLIER.
C
              BIGMLT = .TRUE.
C
              NDROP = NDROP + 1
              IDROP(NDROP) = I
              DRPLAM(NDROP) = ABS(ALMBDA(I))
C
            IF ( ABS(ALMBDA(I)) .GT. ALMBIG ) THEN
              ALMBIG = ABS( ALMBDA(I) )
            ENDIF
C
          ENDIF
C
        ENDIF
      enddo
C
C     DECLARE THE DROP QUEUE EMPTY IF THERE ARE NO DROP
C     CANDIDATES WITH SIGNIFICANT MULTIPLIERS. OTHERWISE,
C     DROP ALL CANDIDATES, INCLUDING THOSE WITH INSIGNIFICANT
C     MULTIPLIERS.
C
      IF ( .NOT. BIGMLT ) THEN
        NDROP = 0
      ENDIF
C
      IF ( NDROP .GT. 0 ) THEN
C       SORT INTO ASCENDING MULTIPLIER MAGNITUDES FOR DROP
C       CANDIDATES.
C
        IOPT = 0
        ISTBLE = 0
        CALL HDSRTN( DRPLAM, NDROP, IOPT, ISTBLE, INDX, JER1 )
C
        IF ( JER1 .NE. 0 ) THEN
          IF ( IPC .GT. 0 ) THEN
            WRITE(IPU,*) ' GETDROP: JER FROM HDSRTN =', JER1
          ENDIF
          IER = 1
          GO TO 900
        ENDIF
C
        CALL HJPRMX( IDROP, NDROP, INDX, JER2 )
C
        IF ( JER2 .NE. 0 ) THEN
          IF ( IPC .GT. 0 ) THEN
            WRITE(IPU,*) ' GETDROP: JER FROM HJPRMX =', JER2
          ENDIF
          IER = 2
          GO TO 900
        ENDIF
C
      ENDIF
C
 900  CONTINUE
C
C
      RETURN
      END          
