       LOGICAL FUNCTION HDKILL()
C
C          THIS FUNCTION CAN BE USED TO IMPLEMENT A "USER EXTERNAL KILL"
C          FOR STANDARD FORTRAN IMPLEMENTATIONS IT DOES NOTHING
C
       HDKILL = .FALSE.
       RETURN
       END
