      SUBROUTINE HHADJP ( A, DROPCH, FILLCH, DIR, N, IER )
C
C .. PURPOSE:
C        HHADJP SHIFTS THE CONTENTS OF A CHARACTER VARIABLE IN
C        ITS STORAGE EITHER TO THE LEFT OR TO THE RIGHT, A
C        USER SPECIFIED NUMBER OF CHARACTER POSITIONS, BY
C        ELIMINATING THE 'DROPCH' CHARACTERS FROM THE END TO
C        WHICH THE STRING IS BEING ADJUSTED, AND FILLING ON THE
C        OPPOSITE END WITH 'FILLCH' CHARACTERS.
C
C ... INPUTS:
C        A        A CHARACTER VARIABLE CONTAINING THE DATA STRING
C                 WHICH IS TO BE SHIFTED TO EITHER THE LEFT OR THE
C                 RIGHT A USER SPECIFIED NUMBER OF CHARACTER
C                 POSITIONS IN THE VARIABLE 'A' STORAGE SPACE.
C        DROPCH   A CHARACTER(LEN=1) VARIABLE DEFINING THE CHARACTER
C                 WHICH IS TO BE DROPPED FROM THE 'ADJUSTED' END
C                 OF THE CHARACTER STRING 'A'.  (IF THIS VARIABLE
C                 IS NOT CHARACTER(LEN=1), DROPCH(1:1) WILL BE USED AS
C                 THE 'DROP-CHARACTER'.
C        FILLCH   A CHARACTER(LEN=1) VARIABLE DEFINING THE CHARACTER
C                 WHICH IS TO BE PADDED ON THE OPPOSITE END OF
C                 THE CHARACTER STRING IN 'A' AS 'DROPCH' CHARACTERS
C                 ARE BEING FROM THE 'ADJUST' END.  (IF THIS VAR.
C                 IS NOT CHARACTER(LEN=1), FILLLCH(1:1) WILL BE USED AS
C                 THE 'FILL-CHARACTER'.
C        DIR      A CHARACTER(LEN=1) VARIABLE CONTAINING THE DIRECTION
C                 OF ADJUSTMENT OF THE CHARACTER STRING IN CHARACTER
C                 VARIABLE 'A'.
C           ='L'  ADJUST THE STRING TO THE LEFT  IN 'A'.
C           ='R'  ADJUST THE STRING TO THE RIGHT IN 'A'.
C
C        N        AN INTEGER VARIABLE DEFINING THE NUMBER OF CHARACTER
C                 POSITIONS WHICH THE USER WISHES THE STRING TO BE
C                 SHIFTED.
C
C .. OUTPUTS:
C        A        THE INPUT CHARACTER VARIABLE WHICH CONTAINS THE
C                 SHIFTED (OR ADJUSTED) STRING (PROVIDING THAT
C                 VARIABLE 'IER' IS EQUAL TO ZERO).
C        IER = 0  AN ERROR FLAG.  ZERO INDICATES NO ERRORS.
C            =-1  INDICATES THAT THE DIRECTION SELECTION WAS
C                 NEITHER 'L' OR 'R'.  IN THIS CASE, NO
C                 STRING ADJUSTMENT IS PERFORMED.
C            =-2  INDICATES THAT THE SHIFT COUNT "N" IS NEGATIVE.
C            =-3  INDICATES THAT BOTH ERROR CONDITIONS -1 AND -2
C                   ARE PRESENT IN THE USER-S CALLING SEQUENCE.
C            =-4  INDICATES THAT IF THE SHIFTING PROCESS WAS ALLOWED
C                 TO BE PERFORMED FOR THE USER REQUESTED NUMBER OF
C                 CHARACTER POSITIONS 'N', THEN SOME 'NON-DROP-
C                 CHARACTER' WOULD BE LOST OFF OF THE END OF THE
C                 STRING IN 'A'.  IN THIS CASE, NO STRING
C                 ADJUSTMENT IS PERFORMED.
C
C .. LIMITATIONS AND WARNINGS:
C        THE CAPABILITIES OF THIS ROUTINE ARE LIMITED BY THE
C        MAXIMUM LENGTH OF A CHARACTER STRING ALLOWED BY THE
C        COMPILER OF THE MACHINE UPON WHICH IT IS IMPLENENTED.
C        HOWEVER, THAT RESTRICTION IS IMPOSED UPON THE CALLING
C        ROUTINE; NOT UPON THE CODE INTERNAL TO THIS ROUTINE.
C
C .. MODULES REQUIRED:
C        LEN      FORTRAN 77 INTRINSIC FUCTION TO DETERIME THE LENGTH
C                 OF A CHARACTER VARIABLE WHICH WAS PASSED THROUGH
C                 THE CALLING SEQUENCE (IN THIS APPLICATION).
C        HHERR    BCSLIB ERROR PROCESSING ROUTINE.
C
C .. NOTES:
C        THIS ROUTINE ADJUSTS THE CHARACTER STRING IN 'A' TO
C        THE LEFT OR RIGHT A USER SPECIFIED NUMBER OF CHARACTER
C        POSITIONS.  TO FULLY ADJUST THE CHARACTER STRING TO THE
C        CHARACTER VARIABLE 'A' LEFT OR RIGHT BOUNDARY, SEE
C        ROUTINE 'HHADJF'.
C
C .. PROGRAMMER/ORGANIZATION:
C        ALVIN C. MONG - G-7520 - NUMERICAL ANALYSIS -
C        ENGINEERING APPLICATIONS TECHNOLOGY, BCS, SEATTLE, WA.
C
C .. MODIFICATIONS:
C        ALVIN C. MONG - BCS - G-7520 - 25 APRIL 1985
C           ORIGINAL DESIGN AND CODING.
C        ALVIN C. MONG - BCS - G-7520 - 10 FEB.  1986
C           MODIFIED FOR FORTRAN 77 ERROR HANDLER.
C
C     ----------------------------------------------------------------
C
      CHARACTER(LEN=*)  A, DROPCH, FILLCH, DIR
      CHARACTER(LEN=1)        DCH,    FCH
      CHARACTER(LEN=8)  NAME
C
C  TEMP IS NEEDED BECAUSE THE CFT COMPILER IS NOT QUITE ANSI STANDARD
C
      CHARACTER(LEN=1)  TEMP
      DATA NAME / 'HHADJP' /
C
C     ----------------------------------------------------------------
C
C ... GET THE LENGTH OF THE STRING 'A'.
C     INITIALIZE THE WORKING VARIABLES.
C
      NS   = 0
      IER  = 0
      IER1 = 0
      IER2 = 0
      LENA = LEN ( A )
      DCH  = DROPCH(1:1)
      FCH  = FILLCH(1:1)
C
C ... DETERMINE WHICH DIRECTION ('L' OR 'R') THAT THE STRING SHIFT
C     IS TO PROCEED.
C
      IF ( DIR .EQ. 'L' ) THEN
C
         IBEG =  1
         IEND = LENA
         INCR = +1
C
      ELSEIF ( DIR .EQ. 'R' ) THEN
C
         IBEG = LENA
         IEND =  1
         INCR = -1
C
      ELSE
C
         IER  = -1
         IER1 = -1
C
      ENDIF
C
C ... A NEGATIVE NUMBER OF SHIFT POSITIONS IS AN ERROR.
C
      IF ( N .LT. 0 ) THEN
         IER  = -2
         IER2 = -2
      ENDIF
C
      IF ( IER .NE. 0 ) THEN
         IF ( IER1 .LT. 0  .AND.  IER2 .LT. 0 ) THEN
            IER = -3
         ENDIF
         CALL HHERR ( 1, NAME, IER, 0 )
         GO TO 3000
      ENDIF
C
      IF ( N .EQ. 0 ) GO TO 3000
C
C ... NOW SCAN ACROSS THE STRING 'A' IN THE CHOSEN DIRECTION LOOKING
C     FOR THE FIRST OCCURRENCE OF 'NOT' THE 'DROP-CHARACTER'.
C
      DO J = IBEG, IEND, INCR
         IF ( A(J:J) .NE. DCH ) GO TO 500
         NS = NS + 1
         IF (     NS .GE. N   ) GO TO 500
      ENDDO
C
C ... -----------------------------------------------------------------
C
C     IF MORE DROP CHARACTERS EXIST THAN THE REQUESTED NUMBER
C     OF SHIFTS, MOVE THE STRING IN 'A' IN THE DIRECTION 'DIR'
C     THE DISTANCE OF 'N' SPACES ELIMINATING 'DROP-CHARACTERS' FROM
C     THE 'ADJUST-END' OF THE STRING.  THEN, FILL IN THE OPPOSITE
C     END OF THE CHARACTER VARIABLE 'A' WITH AN EQUAL NUMBER OF
C     'FILL-CHARACTERS'.
C
  500 CONTINUE
      IF ( NS .GE. N ) THEN
C
         NP = N + 1
C
         IF ( DIR .EQ. 'L' ) THEN
C
            DO J = NP, LENA
               K = J - N
               TEMP = A(J:J)
               A(K:K) = TEMP
            ENDDO
C
            KP = K + 1
            DO J = KP, LENA
               A(J:J) = FCH
            ENDDO
C
C ..... SINCE IT IS NOT 'L', THEN THE 'ADJUST' MUST BE TO THE 'R'.
C       A TEST HAS ALREADY BEEN MADE TO INSURE THAT THE DIRECTION
C       IS ONE OR THE OTHER --- AND NOT ERRONEOUSLY SPECIFIED.
C
         ELSE
C ...         ( DIR .EQ. 'R' )
C
            LIM = LENA - N
            DO J = LIM, 1, -1
               K = J + N
               TEMP = A(J:J)
               A(K:K) = TEMP
            ENDDO
C
            DO J = 1, N
               A(J:J) = FCH
            ENDDO
C
         ENDIF
C
      ELSE
C ...      (SHIFTING WOULD RESULT IN THE LOSS OF SOME 'NON-DROP-
C           CHARACTER' DATA FROM THE USER'S STRING 'A').
C
         IER = -4
         CALL HHERR ( 1, NAME, IER, 0 )
C
      ENDIF
C
 3000 CONTINUE
C
      RETURN
      END
