      SUBROUTINE HHADJF ( A, DROPCH, FILLCH, DIR, N, IER )
C
C .. PURPOSE:
C        HHADJF SHIFTS THE CONTENTS OF A CHARACTER VARIABLE IN
C        ITS STORAGE EITHER TO THE LEFT OR TO THE RIGHT, BY
C        ELIMINATING THE 'DROPCH' CHARACTERS FROM THE END TO
C        WHICH THE STRING IS BEING ADJUSTED, AND FILLING ON THE
C        OPPOSITE END WITH 'FILLCH' CHARACTERS.
C
C ... INPUTS:
C        A        A CHARACTER VARIABLE CONTAINING THE DATA STRING
C                 WHICH IS TO BE SHIFTED TO EITHER THE LEFT OR THE
C                 RIGHT EXTREME OF THE VARIABLE 'A' STORAGE SPACE.
C        DROPCH   A CHARACTER(LEN=1) VARIABLE DEFINING THE CHARACTER
C                 WHICH IS TO BE DROPPED FROM THE 'ADJUSTED' END
C                 OF THE CHARACTER STRING 'A'.  (IF THIS VARIABLE
C                 IS NOT CHARACTER(LEN=1), DROPCH(1:1) WILL BE USED AS
C                 THE 'DROP-CHARACTER'.
C        FILLCH   A CHARACTER(LEN=1) VARIABLE DEFINING THE CHARACTER
C                 WHICH IS TO BE PADDED ON THE OPPOSITE END OF
C                 THE CHARACTER STRING IN 'A' AS 'DROPCH' CHARACTERS
C                 ARE BEING FROM THE 'ADJUST' END.  (IF THIS VAR.
C                 IS NOT CHARACTER(LEN=1), FILLLCH(1:1) WILL BE USED AS
C                 THE 'FILL-CHARACTER'.
C        DIR      A CHARACTER(LEN=1) VARIABLE CONTAINING THE DIRECTION
C                 OF ADJUSTMENT OF THE CHARACTER STRING IN CHARACTER
C                 VARIABLE 'A'.
C        DIR='L'  ADJUST THE STRING TO THE LEFT  BOUNDARY OF 'A'.
C        DIR='R'  ADJUST THE STRING TO THE RIGHT BOUNDARY OF 'A'.
C
C .. OUTPUTS:
C        A        THE INPUT CHARACTER VARIABLE WHICH CONTAINS THE
C                 SHIFTED (OR ADJUSTED) STRING.
C        N        AN INTEGER VARIABLE SPECIFYING THE NUMBER OF SPACES
C                 WHICH THE CHARACTER STRING IN 'A' WAS SHIFTED.
C        IER = 0  AN ERROR FLAG.  ZERO INDICATES NO ERRORS.
C            =-1  INDICATES THAT THE DIRECTION SELECTION WAS
C                 NEITHER 'L' OR 'R'.  IN THIS CASE, NO
C                 STRING ADJUSTMENT IS PERFORMED.
C
C .. LIMITATIONS AND WARNINGS:
C        THE CAPABILITIES OF THIS ROUTINE ARE LIMITED BY THE
C        MAXIMUM LENGTH OF A CHARACTER STRING ALLOWED BY THE
C        COMPILER OF THE MACHINE UPON WHICH IT IS IMPLEMENTED.
C        HOWEVER, THAT RESTRICTION IS IMPOSED UPON THE CALLING
C        ROUTINE; NOT UPON THE CODE INTERNAL TO THIS ROUTINE.
C
C .. MODULES REQUIRED:
C        LEN      FORTRAN 77 INTRINSIC FUCTION TO DETERIME THE LENGTH
C                 OF A CHARACTER VARIABLE WHICH WAS PASSED THROUGH
C                 THE CALLING SEQUENCE (IN THIS APPLICATION).
C        HHERR    BCSLIB ERROR PROCESSING ROUTINE.
C
C .. NOTES:
C        THIS ROUTINE FULLY ADJUSTS THE CHARACTER STRING IN 'A' TO
C        THE LEFT OR RIGHT BOUNDARY OF 'A'.  TO ADJUST A STRING A
C        SPECIFIED NUMBER OF CHARACTERS TO THE RIGHT OR LEFT, SEE
C        ROUTINE 'HHADJP'.
C
C .. PROGRAMMER/ORGANIZATION:
C        ALVIN C. MONG - G-7520 - NUMERICAL ANALYSIS -
C        ENGINEERING APPLICATIONS TECHNOLOGY, BCS, SEATTLE, WA.
C
C .. MODIFICATIONS:
C        ALVIN C. MONG - BCS - G-7520 - 25 APRIL 1985
C           ORIGINAL DESIGN AND CODING.
C
C     ----------------------------------------------------------------
C
      CHARACTER(LEN=*)  A, DROPCH, FILLCH, DIR
      CHARACTER(LEN=1)        DCH,    FCH
      CHARACTER(LEN=8)  NAME
C
C  TEMP IS NEEDED BECAUSE THE CFT COMPILER IS NOT QUITE ANSI STANDARD
C
      CHARACTER(LEN=1)  TEMP
      DATA NAME / 'HHADJF' /
C
C     ----------------------------------------------------------------
C
C ... GET THE LENGTH OF THE STRING 'A'.
C     INITIALIZE THE WORKING VARIABLES.
C
      N    = 0
      IER  = 0
      LENA = LEN ( A )
      DCH  = DROPCH(1:1)
      FCH  = FILLCH(1:1)
C
C
C ... DETERMINE WHICH DIRECTION ('L' OR 'R') THAT THE STRING SHIFT
C     IS TO PROCEED.
C
      IF ( DIR .EQ. 'L' ) THEN
C
         IBEG =  1
         IEND = LENA
         INCR = +1
C
      ELSEIF ( DIR .EQ. 'R' ) THEN
C
         IBEG = LENA
         IEND =  1
         INCR = -1
C
      ELSE
C
         IER  = -1
         CALL HHERR ( 1, NAME, IER, 0 )
         GO TO 3000
C
      ENDIF
C
C ... NOW SCAN ACROSS THE STRING 'A' IN THE CHOSEN DIRECTION LOOKING
C     FOR THE FIRST OCCURRENCE OF 'NOT' THE 'DROP-CHARACTER'.
C
      DO J = IBEG, IEND, INCR
         IF ( A(J:J) .NE. DCH ) GO TO 500
         N  = N + 1
      ENDDO
C
C ... IF WE FALL THROUGH THE ABOVE LOOP, THEN THE ENTIRE CHARACTER
C     STRING IS COMPOSED OF THE 'DROP-CHARACTER'.
C     IF THE 'DROP-CHARACTER' IS THE SAME AS THE 'FILL-CHARACTER',
C     THEN THERE IS NO WORK TO DO.  OTHERWISE, SIMPLY FILL THE
C     ENTIRE CHARACTER VARIABLE 'A' WITH THE 'FILL-CHARACTER'.
C
      IF ( DCH .NE. FCH ) THEN
C
         DO J = 1, LENA
            A(J:J) = FCH
         ENDDO
C
      ENDIF
C
      GO TO 3000
C
C ... -----------------------------------------------------------------
C
C ... SOME 'DROP-CHARACTERS' EXIST ON THE 'ADJUST-END' OF THE CHARACTER
C     STRING IN 'A'.  MOVE THE STRING IN 'A' IN THE DIRECTION 'DIR'
C     THE DISTANCE OF 'N' SPACES TO ELIMINATE THE 'DROP-CHARACTERS'
C     FROM THE 'ADJUST-END' OF THE STRING.  THEN, FILL IN THE OPPOSITE
C     END OF THE CHARACTER VARIABLE 'A' WITH AN EQUAL NUMBER OF
C     'FILL-CHARACTERS'.
C
  500 CONTINUE
         NP = N + 1
C
      IF ( DIR .EQ. 'L' ) THEN
C
         DO J = NP, LENA
            K = J - N
            TEMP = A(J:J)
            A(K:K) = TEMP
         ENDDO
C
         KP = K + 1
         DO J = KP, LENA
            A(J:J) = FCH
         ENDDO
C
C ..... SINCE IT IS NOT 'L', THEN THE 'ADJUST' MUST BE TO THE 'R'.
C       A TEST HAS ALREADY BEEN MADE TO INSURE THAT THE DIRECTION
C       IS ONE OR THE OTHER --- AND NOT ERRONEOUSLY SPECIFIED.
C
      ELSE
C ...      ( DIR .EQ. 'R' )
C
         LIM = LENA - N
         DO J = LIM, 1, -1
            K = J + N
            TEMP = A(J:J)
            A(K:K) = TEMP
         ENDDO
C
         DO J = 1, N
            A(J:J) = FCH
         ENDDO
C
      ENDIF
C
 3000 CONTINUE
C
      RETURN
      END
