      SUBROUTINE HHCNSP ( A, RVAL, IER )
C
C .. PURPOSE:
C        HHCNSP CONVERTS A CHARACTER REPRESENTATION OF A NUMERIC
C        VALUE TO ITS EQUIVALENT SINGLE PRECISION FLOATING POINT
C        REPRESENTATION.  THE CHARACTER NUMERIC REPRESENTATION MAY
C        BE FOR A SIGNED INTEGER, A SIGNED DECIMAL NOTATION VALUE,
C        A SIGNED SINGLE PRECISION SCIENTIFIC NOTATION, OR A SIGNED
C        DOUBLE PRECISION SCIENTIFIC NOTATION.
C
C ... INPUTS:
C        A        A CHARACTER VARIABLE CONTAINING THE CHARACTER STRING
C                 WHICH IS A CHARACTER REPRESENTATION OF A NUMERIC
C                 VALUE.
C
C .. OUTPUTS:
C        RVAL     THE SINGLE PRECISION FLOATING POINT EQUIVALENT OF
C                 THE CHARACTER REPRESENTATION OF THE NUMERIC VALUE
C                 WHICH WAS SUPPLIED AS THE INPUT ARGUMENT 'A'.
C        IER = 0  AN ERROR FLAG.  ZERO INDICATES THERE WERE NO ERRORS.
C            = 1  RVAL = 0 BUT THE NUMBER REPRESENTED BY A IS NOT
C                 EXACTLY 0; THIS IS PROBABLY DUE TO UNDERFLOW.
C            =-1  INDICATES THAT THE CHARACTER VARIABLE IN 'A' IS NOT
C                 A VALID INTEGER REPRESENTATION.  'RVAL' IS SET TO
C                 HSMCON(1).
C            =-2  THE LENGTH OF THE CHARACTER FIELD WAS GREATER THAN
C                 99 CHARACTERS.  'RVAL' IS SET TO HSMCON(1).
C            =-3  INTERNAL I/O FAILURE, PROBABLY DUE TO OVERFLOW,
C                 BUT POSSIBLE THEORETICALLY FOR UNDERFLOW AS WELL.
C            =-4  RVAL CANNOT BE PRINTED IN NUMERIC FORM, PROBABLY
C                 DUE TO OVERFLOW.
C
C .. LIMITATIONS AND WARNINGS:
C        THIS ROUTINE IS LIMITED TO A 99-CHARACTER MAXIMUM CHARACTER
C        LENGTH REPRESENTATION OF A SINGLE NUMERIC VALUE.
C
C        EXPONENT VALUES ON MACHINES SUCH AS THE CRAY ARE LIMITED TO
C        999 (BECAUSE THE ANSI STANDARD SAYS THAT "EW.D" FORMAT IS ONLY
C        VALID FOR EXPONENTS UP TO 999.  FOR THE CRAY, EXPONENTS UP TO
C        2466 ARE POSSIBLE, BUT THEY MUST BE READ USING A FORMAT LIKE
C        "EW.DE4".)
C
C .. MODULES REQUIRED:
C        LEN      FORTRAN 77 INTRINSIC FUCTION TO DETERIME THE LENGTH
C                 OF A CHARACTER VARIABLE WHICH WAS PASSED THROUGH
C                 THE CALLING SEQUENCE (IN THIS APPLICATION).
C        HHFCNR   BCS ROUTINE TO VERIFY THAT THE CHARACTER STRING IN
C                 'A' IS INDEED A CHARACTER NUMERIC REPRESENTATION.
C
C .. NOTES:
C        CONVERSION FROM CHARACTER TO SINGLE PRECISION FLOATING POINT
C        IS DONE THROUGH A FORTRAN-77 READ/WRITE INTERNAL STATEMENT.
C
C        THIS ROUTINE CONVERTS ANY CHARACTER NUMERIC REPRESENTATION TO
C        SINGLE PRECISION FLOATING POINT REPRESENTATION.  IT IS
C        RECOMMENDED THAT ROUTINE 'HHCNRI' BE USED TO CONVERT INTEGER
C        REPRESENTATIONS TO INTEGER VALUES AND 'HHCNDP' BE USED TO
C        CONVERT DOUBLE PRECISION CHARACTER NUMERIC REPRESENTATIONS TO
C        DOUBLE PRECISION FLOATING POINT REPRESENTATIONS.
C
C .. PROGRAMMER/ORGANIZATION:
C        ALVIN C. MONG - G-7520 - NUMERICAL ANALYSIS -
C        ENGINEERING APPLICATIONS TECHNOLOGY, BCS, SEATTLE, WA.
C
C .. MODIFICATIONS:
C        ALVIN C. MONG - BCS - G-7520 - 13 JUNE 1985
C           ORIGINAL DESIGN AND CODING.
C        ALVIN C. MONG - BCS - G-6520 - 24 FEB. 1986
C           CHANGES FOR ERROR HANDLER.
C
C     ----------------------------------------------------------------
C
      CHARACTER(LEN=*)    A
      CHARACTER(LEN=99)   B
      CHARACTER(LEN=10)   FMT
      CHARACTER(LEN=8)    NAME
      CHARACTER(LEN=1)    BLANK,   TYPE
      REAL             RVAL, HSMCON
      INTEGER          IER,  LCNRL,  LCNRR,   LENI
      INTEGER          LBST, IPOSA,  IPOSN,   LBEND
C
      DATA NAME  / 'HHCNSP'     /
      DATA FMT   / '(BZ,E  .0)' /
      DATA BLANK / ' '          /
C
C     ----------------------------------------------------------------
C
C ... EXAMINE THE STRING IN 'A' TO DETERMINE IF IT CONTAINS A
C     CHARACTER NUMERIC REPRESENTATION.
C
      CALL HHFCNR ( A, BLANK, LCNRL, LCNRR, TYPE )
C
      IF ( TYPE .NE. 'N' ) THEN
C
C ...... FILL THE 'FMT' FORMAT DATA STATEMENT WITH THE CORRECT SIZE.
C
         LENI = LCNRR - LCNRL + 1
         IF ( LENI .LT. 100 ) THEN
            WRITE (FMT(6:7),101) LENI
  101       FORMAT(I2)
C
C ......... CONVERT THE CHARACTER IN 'A' TO
C           SINGLE PRECISION FLOATING POINT.
C
            READ (A(LCNRL:LCNRR),FMT,ERR=900) RVAL
            IER  = 0
         ELSE
            IER  = -2
         ENDIF
      ELSE
         IER  = -1
      ENDIF
C
      IF ( IER .EQ. 0 ) THEN
 
C ........ CHECK RVAL VALIDITY.  FIRST WRITE IT TO CHARACTER
C          VARIABLE B, AND THEN DETERMINE IF B THEN CONTAINS
C          A VALID NUMERIC REPRESENTATION.
 
         WRITE(B,'(E20.6E5)',ERR=900) RVAL
         CALL HHFCNR ( B, BLANK, LBST, LBEND, TYPE )
         IF ( TYPE .EQ. 'I' .OR. TYPE .EQ. 'N' ) IER = -4
 
C ........ NOW CHECK FOR UNDERFLOW
 
         IF ( RVAL .EQ. 0.  .AND.  IER .EQ. 0 ) THEN
            CALL HHISCN ( A(LCNRL:LCNRR),'123456789',1,IPOSA,IPOSN )
            IF ( IPOSA .GT. 0 ) IER = 1
         ENDIF
      ENDIF
 
      IF ( IER .LT. 0 ) THEN
         CALL HHERR ( 1, NAME, IER, 0 )
         RVAL = HSMCON(1)
      ENDIF
      IF ( IER .GT. 0 ) CALL HHERR ( 0, NAME, IER, 0 )
C
      RETURN
 
 900  CONTINUE
      IER = -3
      CALL HHERR ( 1, NAME, IER, 0 )
      RVAL = HSMCON(1)
      RETURN
      END
