      SUBROUTINE HHCPRS ( A, B, FILLCH )
C
C .. PURPOSE:
C        HHCPRS COMPRESSES MULTIPLE OCCURRENCES OF ANY OF A POOL
C        OF CHARACTERS ENCOUNTERED IN A STRING 'A' TO A SINGLE
C        OCCURRENCE OF THAT CHARACTER.  COMPRESSION IS PERFORMED
C        FROM THE LEFT-MOST CHARACTER IN THE STRING 'A' TOWARD
C        THE RIGHT EXTREME OF THE STRING.  COMPRESSION HAS THE
C        EFFECT OF SHIFTING THE STRING TOWARD THE LEFT.  THEREFORE,
C        'FILL-CHARACTERS' ARE PADDED ONTO THE RIGHT END OF THE
C        STRING IN 'A'.
C
C ... INPUTS:
C        A        A CHARACTER VARIABLE CONTAINING THE DATA STRING
C                 WHICH IS TO BE COMPRESSED.
C        B        A CHARACTER(LEN=N) VARIABLE CONTAINING 'N' SINGLE
C                 CHARACTERS WHICH CONSTITUTE THE POOL OF 'N'
C                 CHARACTERS DEFINING THE COMPRESSION CANDIDATES.
C                 CAUTION:  THIS ROUTINE ASSUMES ALL 'N' CHARACTERS
C                           IN 'B' ARE 'COMPRESS CHARACTERS'.
C        FILLCH   A CHARACTER(LEN=1) VARIABLE DEFINING THE CHARACTER
C                 WHICH IS TO BE PADDED ON THE RIGHT END OF THE
C                 CHARACTER STRING IN 'A' AS COMPRESSION OCCURS.
C                 (IF THIS VARIABLE IS NOT CHARACTER(LEN=1),
C                 FILLCH(1:1) WILL BE USED AS THE 'FILL-CHARACTER'.
C
C ... OUTPUTS:
C        A        THE INPUT CHARACTER VARIABLE WHICH CONTAINS THE
C                 COMPRESSED STRING, PADDED ON THE RIGHT END WITH
C                 'FILLCH' FILL CHARACTERS.
C
C .. LIMITATIONS AND WARNINGS:
C     (1)THE CAPABILITIES OF THIS ROUTINE ARE LIMITED BY THE
C        MAXIMUM LENGTH OF A CHARACTER STRING ALLOWED BY THE
C        COMPILER OF THE MACHINE UPON WHICH IT IS IMPLEMENTED.
C        HOWEVER, THAT RESTRICTION IS IMPOSED UPON THE CALLING
C        ROUTINE; NOT UPON THE CODE INTERNAL TO THIS ROUTINE.
C     (2)THIS ROUTINE ASSUMES THAT ALL 'N' CHARACTERS IN 'B'
C        ARE 'COMPRESS' CHARACTERS.  THEREFORE, IF ONE FILLS,
C        FOR EXAMPLE, 4 CHARACTERS IN A CHARACTER(LEN=6) VARIABLE 'B',
C        THEN, THE TWO BLANK FILL CHARACTERS FOLLOWING THE
C        SPECIFIED FOUR SPECIAL CHARACTERS ARE ALSO ASSUMED TO
C        BE 'COMPRESS' CHARACTERS.
C
C .. MODULES REQUIRED:
C        LEN      FORTRAN 77 INTRINSIC FUCTION TO DETERIME THE LENGTH
C                 OF A CHARACTER VARIABLE WHICH WAS PASSED THROUGH
C                 THE CALLING SEQUENCE (IN THIS APPLICATION).
C        HHADJF   'CHARACTER PROCESSING' ROUTINE TO ADJUST A STRING
C                 FULLY TO THE LEFT OR THE RIGHT IN ITS IELD.
C
C .. NOTES:
C        THIS ROUTINE COMPRESSES MULTIPLE OCCURRENCES OF A CHARACTER
C        INTO A SINGLE OCCURRENCE OF THAT SAME CHARACTER.  IF A
C        STRING USED TO BEGIN WITH A SERIES OF BLANKS, AND BLANKS ARE
C        SQUEEZED OUT, ONE BLANK WILL REMAIN IN COLUMN 1.  THEREFORE,
C        IF YOU WISH TO ELIMINATE LEADING BLANKS, YOU MUST FIRST
C        'ADJUST' OR 'SHIFT' THE STRING WITH ROUTINE 'HHADJF'.
C
C .. PROGRAMMER/ORGANIZATION:
C        ALVIN C. MONG - G-7520 - NUMERICAL ANALYSIS -
C        ENGINEERING APPLICATIONS TECHNOLOGY, BCS, SEATTLE, WA.
C
C .. MODIFICATIONS:
C        ALVIN C. MONG - BCS - G-7520 - 26 APRIL 1985
C           ORIGINAL DESIGN AND CODING.
C
C     ----------------------------------------------------------------
C
      CHARACTER(LEN=*)   A, B, FILLCH
      CHARACTER(LEN=1)   BCH,    FCH
C
C     ----------------------------------------------------------------
C
C ... GET THE LENGTH OF THE STRING 'A'.
C     INITIALIZE THE WORKING VARIABLES.
C
      N    = 0
      IER  = 0
      LENA = LEN ( A )
      LENB = LEN ( B )
      FCH  = FILLCH(1:1)
      LEND = LENA
C
C ... LOOK THROUGH THE ENTIRE STRING 'A' FOR EACH INDIVIDUAL
C     'COMPRESS' CHARACTER IN 'B'.
C
      DO 900 I=1,LENB
C
         BCH  = B(I:I)
C
C ... NOW SCAN ACROSS THE STRING 'A' LOOKING FOR MULTIPLE OCCURRENCES
C     OF CHARACTER 'BCH'.  WHEN A SINGLE GROUP OF THE CHARACTER IS
C     ENCOUNTERED, CALL 'HHADJF' TO ADJUST THE REMAINDER OF THE STRING
C     SUCH THAT ONLY ONE OF 'BCH' REMAINS.
C
         DO J = 1, LENA
C
            IF (      J .GE. LEND ) GO TO 900
C
            IF ( A(J:J) .NE. BCH  ) CYCLE
C
C ...... THE BEGINNING OF A POTENTIAL STRING OF 'BCH' HAS BEEN E
C        ENCOUNTERED.  IF THE NEXT CHARACTER IS ALSO 'BCH', THEN
C        WE HAVE WORK TO DO.  ELSE, A SINGLE OCCURRENCE OF 'BCH'
C        HAS BEEN FOUND, BUT SINGLE OCCURRENCES ARE TO BE LEFT
C        ALONE.
C
            K = J+1
C
            IF ( A(K:K) .EQ. BCH ) THEN
C
C ......... THE START OF A MULTIPLE OCCURRENCE OF 'BCH' HAS BEEN FOUND.
C           FIND THE END OF THE STRING.  THEN SQUEEZE IT DOWN TO ONE
C           OCCURRENCE OF 'BCH'.
C
               DO L = K, LEND
                  IF ( A(L:L) .NE. BCH ) GO TO 500
               ENDDO
C
C ......... TO HAVE FALLEN THROUGH HERE MEANS THAT THE REMAINDER OF
C           THE STRING FROM 'L' TO THE 'LEND' IS ALL CHARACTER 'BCH'.
C           IF SO, THEN SQUEEZE OUT ALL BUT ONE OF 'BCH' IN STRING 'A',
C           AND REPLACE WITH THE 'FILLCH' FILL CHARACTER.  IF THE
C           'FILLCH' IS THE SAME AS 'BCH', THERE IS NOTHING MORE TO DO.
C
               IF ( BCH .NE. FCH ) THEN
C
                  DO L = K, LEND
                     A(L:L) = FCH
                  ENDDO
C
               ENDIF
C
               GO TO 900
C
C ......... THERE ARE 'BCH' CHARACTERS FROM INDEX 'J' TO 'L'.
C           ELIMINATE THE 'BCH' CHARACTERS FROM 'K' TO 'L'.
C           FILL IN THE HIGH END WITH 'FCH' FILL CHARACTER.
C
  500          CONTINUE
               CALL HHADJF ( A(K:LEND), BCH, FCH, 'L', N, IER )
C
               LEND = LEND - N
            ENDIF
C
         ENDDO
C
  900 CONTINUE
C
      RETURN
      END
