

      SUBROUTINE HHERRX(CHAR,X,NX)
C**** EXTRA MESSAGE ROUTINE FOR THE STANDARD ERROR HANDLER (HHERR)
C
      CHARACTER(LEN=*) CHAR
      DOUBLE PRECISION X(*)
      COMMON/HGERRC/IEUNIT,IEFLAG,NERRS,IPON,IXPAND(2)
C
C INPUT VARIABLES
C
C     CHAR   - A CHARACTER VARIABLE CONTAINING AN EXTRA
C              MESSAGE WHICH WILL BE PRINTED IN A FORMAT.
C              IF LEN(CHAR) .GT. 52, ONLY THE FIRST 52
C              CHARACTERS OF CHAR WILL BE PRINTED.
C
C     NX     - THE NUMBER OF WORDS OF DATA THAT WILL BE PRINTED.
C              IF NX.LE.0, NO DATA WILL BE PRINTED.
C
C     X      - AN ARRAY OF LENGTH NX WHICH WILL BE PRINTED
C              IN 4G15.5 FORMAT.
C
C     IEUNIT - WRITE UNIT FOR ERROR MESSAGES.
C
C     IEFLAG - SUPRESS MESSAGES IF IEFLAG.LT.0.
C
C USAGE OF HHERRX
C
C     CHARACTER(LEN=8) SUBNAM
C     REAL X(NX)
C     CALL HHERR (MODE,SUBNAM,IER,N)
C     CALL HHERRX(CHAR,X,NX)
C
C REMARK - IF THE CALL OF HHERR DOES NOT PRECEED THE CALL OF HHERRX,
C          USER CONTROL OF PRINTED OUTPUT MAY BE LOST.
C
C SUBROUTINE CALLED - HHERR
C
C
C * * * * * * * * * * * * * * * * * * * * * * * * * * * START OF CODE
C
C**** MAKE SURE IEUNIT AND IEFLAG HAVE BEEN SET.  THEN PRINT
C**** MESSAGE AND DATA AS APPROPRIATE.
C
      IF(IPON.GT.0) RETURN
      CALL HHERR(-1,CHAR,0,0)
      IF(IEFLAG.LT.0)RETURN
      NC = MIN(LEN(CHAR),52)
      WRITE(IEUNIT,10) CHAR(1:NC)
   10 FORMAT(' ***** ',A)
      IF(NX.GT.0)WRITE(IEUNIT,20)(X(I),I=1,NX)
   20            FORMAT(' ***** ',4G15.5)
      WRITE(IEUNIT,30)
   30 FORMAT(' ')
      RETURN
      END
