
      SUBROUTINE HHERRS(ITYP,IVAL)
C
C**** DEFAULT CHANGE ROUTINE FOR THE STANDARD ERROR HANDLER (HHERR)
C
C     MODIFIED FOR FTN5 BY V. SINGSAAS/G. EDGAR   11/85.
C
C INPUT VARIABLES
C
C     ITYP - THE TYPE OF DEFAULT TO BE CHANGED.
C
C     IVAL - THE REPLACEMENT VALUE (IGNORED IF ITYP.EQ.2)
C
C USAGE OF HHERRS
C
C     CALL HHERRS(ITYP,IVAL)
C
C
C     IF ITYP.EQ.1
C         SET THE HHERR PRINT UNIT TO IVAL IF IVAL.NE.0
C         SUPPRESS ERROR MESSAGES IF IVAL.EQ.0
C
C     IF ITYP.EQ.2
C         RESTORE THE DEFAULT VALUE OF THE HHERR PRINT UNIT.
C
C     IF ITYP.EQ.3
C         SET THE MAXIMUM NUMBER OF FUTURE ERROR AND WARNING
C         MESSAGES TO MAX(IVAL,0).
C
C     IF NONE OF THE ABOVE HOLD, DO NOTHING.
C
C
C SUBROUTINE CALLED - HHERR
C
C
      CHARACTER(LEN=8)  DUMMY
C
C * * * * * * * * * * * * * * * * * * * * * * * * * * * START OF CODE
C
C**** TEST INPUT AND CALL HHERR TO PERFORM ACTION
C
      N = IVAL
      IF(ITYP.EQ.1) THEN
          MODE = -2
          IF(N.NE.0)GO TO 30
          MODE = -3
          N    = -1
          GO TO 30
      ENDIF
C
      IF(ITYP.EQ.2) THEN
          MODE = -4
          GO TO 30
      ENDIF
C
      IF(ITYP.EQ.3) THEN
          IF(N.LE.0)N = -1
          MODE = -3
      ELSE
          RETURN
      ENDIF
C
   30 CONTINUE
      CALL HHERR(MODE,DUMMY,0,N)
      RETURN
      END
