
      SUBROUTINE HHFCNR ( A, B, LCNRL, LCNRR, TYPE )
C
C .. PURPOSE:
C        HHFCNR SEARCHES CHARACTER STRING 'A' FOR A CHARACTER SUBSTRING
C        WHICH REPRESENTS A VALID NUMERIC VALUE.  THE CHARACTER
C        SUBSTRING MUST BE BOTH PRECEEDED AND SUCCEEDED BY A SINGLE
C        CHARACTER THAT IS A MEMBER OF THE DELIMITER SUBSTRING POOL
C        IN 'B'.
C
C ... INPUTS:
C        A        A CHARACTER VARIABLE CONTAINING THE CHARACTER STRING
C                 WHICH IS TO BE SEARCHED FOR A CHARACTER REPRESENTATION
C                 OF A VALID NUMERIC VALUE.
C        B        A CHARACTER VARIABLE CONTAINING THE CHARACTER STRING
C                 DEFINITION OF THE POOL OF SINGLE CHARACTER DELIMITERS
C                 WHICH DELIMIT THE CHARACTER REPRESENTATION OF VALID
C                 NUMERIC VALUES.  CHARACTER POSITION 'ZERO' AND
C                 POSITION 'LENGTH-A PLUS ONE' ARE IMPLICITLY INCLUDED
C                 IN THE DEFINITION OF THESE DELIMITERS SUCH THAT A
C                 VALID NUMERIC REPRESENTATION FULLY ADJUSTED TO THE
C                 LEFT OR RIGHT IN CHARACTER STRING 'A' WILL BE
C                 RECOGNIZED AS A VALID NUMERIC REPRESENTATION.
C
C .. OUTPUTS:
C        LCNRL    AN INTEGER VARIABLE CONTAINING AN INDEX INTO STRING
C                 'A' WHERE THE LEFTMOST CHARACTER OF A VALID NUMERIC
C                 CHARACTER REPRESENTATION IS FOUND.
C        LCNRR    AN INTEGER VARIABLE CONTAINING AN INDEX INTO STRING
C                 'A' WHERE THE RIGHTMOST CHARACTER OF A VALID NUMERIC
C                 CHARACTER REPRESENTATION IS FOUND.
C        TYPE     CHARACTER(LEN=1) VARIABLE SET TO INDICATE THE TYPE OF
C                 NUMERIC REPRESENTATION THAT EXISTS BETWEEN INDICES
C                 'LCNRL' AND 'LCNRR'.  THE POSSIBILITIES ARE:
C                    "I" = SIGNED OR UNSIGNED INTEGER REPRESENTATION.
C                    "F" = SIGNED OR UNSIGNED DECIMAL NOTATION
C                          FLOATING POINT REPRESENTATION.
C                    "E" = SIGNED OR UNSIGNED SINGLE-PRECISION
C                          SCIENTIFIC NOTATION FLOATING POINT
C                          REPRESENTATION.
C                    "D" = SIGNED OR UNSIGNED DOUBLE-PRECISION
C                          SCIENTIFIC NOTATION FLOATING POINT
C                          REPRESENTATION.
C                    "N" = 'NONE'.  NO NUMERIC CHARACTER SUBSTRING,
C                          DELIMITED ON BOTH SIDES BY A MEMBER OF
C                          DELIMITER POOL 'B' WAS ENCOUNTERED
C                          IN STRING 'A'.  THIS INCLUDES THE ASSUMED
C                          VALID DELIMITER IN COLUMN 1 AND IN
C                          COLUMN "LEN(A)"+1.
C
C .. LIMITATIONS AND WARNINGS:
C        THE CAPABILITIES OF THIS ROUTINE ARE LIMITED BY THE
C        MAXIMUM LENGTH OF A CHARACTER STRING ALLOWED BY THE
C        COMPILER OF THE MACHINE UPON WHICH IT IS IMPLEMENTED.
C        HOWEVER, THAT RESTRICTION IS IMPOSED UPON THE CALLING
C        ROUTINE; NOT UPON THE CODE INTERNAL TO THIS ROUTINE.
C
C .. MODULES REQUIRED:
C        LEN      FORTRAN 77 INTRINSIC FUNCTION TO DETERIME THE LENGTH
C                 OF A CHARACTER VARIABLE WHICH WAS PASSED THROUGH
C                 THE CALLING SEQUENCE (IN THIS APPLICATION).
C        INDEX    FORTRAN 77 INTRINSIC FUNCTION TO FIND THE OCCURRENCE
C                 OF A CHARACTER SUBSTRING IN A CHARACTER STRING.
C
C .. NOTES:
C
C .. PROGRAMMER/ORGANIZATION:
C        ALVIN C. MONG - G-7520 - NUMERICAL ANALYSIS -
C        ENGINEERING TECHNOLOGY APPLICATIONS, BCS, SEATTLE, WA.
C
C .. MODIFICATIONS:
C        ALVIN C. MONG - BCS - G-7520 - 10 JUNE 1985
C           ORIGINAL DESIGN AND CODING.
C        ALVIN C. MONG - BCS - G-6520 - 24 FEB. 1986
C           MINOR CORRECTIONS TO THE COMMENTS.
C
C     ----------------------------------------------------------------
C
      CHARACTER(LEN=*)   A,      B
      CHARACTER(LEN=15)  NUMB
      CHARACTER(LEN=1)   TYPE,  BLANK
C
      LOGICAL       MWHNUM, MDECPT, MDECJF, MFRACT,  EXPDE,  EXPJF
     1            , EXPSGN, EXPSJF, EXPCHE, EXPCHD, EXPNUM
C
      INTEGER            I,      J,      K,      L,   LENA,   LENB
     1            ,  IPOSA,  IPOSN
     2            ,  LCNRL,  LCNRR,   LTOR
C
      DATA NUMB  / '0123456789.+-ED' /
      DATA BLANK / ' ' /
C
C     ----------------------------------------------------------------
C
C ... GET THE LENGTH OF THE STRINGS 'A' AND 'B'.
C     INITIALIZE THE WORKING VARIABLES.
C     LTOR IS 'LEFT-TO-RIGHT' FOR ROUTINE 'HHISCN'.
C
      LENA  = LEN ( A )
      LENB  = LEN ( B )
      LCNRL = 0
      LTOR  = +1
C
C     ----------------------------------------------------------------
C ... FIND THE FIRST NUMERIC CHARACTER OR PLUS OR MINUS IN STRING 'A'.
C     ----------------------------------------------------------------
C
  100 CONTINUE
      J = LCNRL + 1
      IF ( J .GT. LENA ) GO TO 800
      TYPE  = 'N'
C
      CALL HHISCN ( A(J:LENA), NUMB(1:13), LTOR, IPOSA, IPOSN )
C
C ... IF 'IPOSA' .NE. ZERO, THEN A NUMERIC REPRESENTATION HAS BEEN
C     FOUND IN STRING 'A'.  NOW, (IF IT IS NOT IN POSITION 1), IS
C     THE NUMERIC CHARACTER MUST BE PRECEEDED BY A DELIMITER CHARACTER
C     (THAT IS, A SINGLE CHARACTER MEMBER OF STRING 'B').
C
      IF ( IPOSA .LE. 0 ) GO TO 800
C
C ... FIRST COMPUTE AN ABSOLUTE INDEX INTO STRING 'A'.
C
      K     = J + IPOSA - 1
      L     = K - 1
      LCNRL = K
C
      IF ( K .EQ. 1 ) GO TO 180
C
         DO I=1,LENB
            IF ( A(L:L) .EQ. B(I:I) ) GO TO 180
         ENDDO
C
C ...... IF WE FELL THROUGH THIS LOOP, THEN THE NUMERIC CHARACTER WAS
C        NOT PRECEEDED BY A VALID DELIMITER.  THEREFORE, THE NUMBER
C        FOUND IS NOT PART OF A VALID NUMERIC REPRESENTATION.
C
         GO TO 100
C
C     ----------------------------------------------------------------
C ... THE BEGINNING OF A POSSIBLE NUMERIC REPRESENTATION HAS BEEN
C     FOUND.  SET THE FLAGS AND PROCEED TO SEARCH FOR A VALID
C     NUMERIC REPRESENTATION.
C     ----------------------------------------------------------------
C
  180 CONTINUE
      MWHNUM = .FALSE.
      MDECPT = .FALSE.
      MDECJF = .FALSE.
      MFRACT = .FALSE.
      EXPDE  = .FALSE.
      EXPJF  = .FALSE.
      EXPSGN = .FALSE.
      EXPSJF = .FALSE.
      EXPCHE = .FALSE.
      EXPCHD = .FALSE.
      EXPNUM = .FALSE.
C
      IF ( IPOSN .LE. 11 ) THEN
C
C ...... THE CHARACTER ENCOUNTERED IS 0-9 OR PERIOD.  THUS, THE 'SIGN'
C        IS ASSUMED PLUS, AND EITHER THE FIRST MANTISSA NUMBER OR THE
C        MANTISSA DECIMAL HAS BEEN FOUND.
C
         IF ( IPOSN .LE. 10 ) THEN
            MWHNUM = .TRUE.
         ELSE
            MDECPT = .TRUE.
            MDECJF = .TRUE.
         ENDIF
C
C ...... OTHERWISE, THE 'PLUS' OR 'MINUS' HAS BEEN ENCOUNTERED.
C        HOWEVER, NO FLAG IS SET FOR THE LEADING SIGN.
C
      ENDIF
C
C     ----------------------------------------------------------------
C ... NOW PROCEED THROUGH THE NUMERIC REPRESENTATION UNTIL THE END
C     OF THE NUMERIC REPRESENTATION IS REACHED, OR A NON-NUMERIC
C     CHARACTER IS REACHED.
C     ----------------------------------------------------------------
C
  260 CONTINUE
      K = K + 1
      IF ( K .GT. LENA ) GO TO 700
C
      DO I=1,15
         IF ( A(K:K) .EQ. NUMB(I:I) ) GO TO 400
      ENDDO
C
C ... TO HAVE FALLEN THROUGH THE ABOVE LOOP MEANS THAT THE CURRENT
C     CHARACTER A(K:K) IS NOT IN THE NUMERIC CHARACTER SET.  IT MUST,
C     HOWEVER, BE A MEMBER OF THE DELIMITER CHARACTER SET OR ELSE THE
C     PREVIOUSLY PROCESSED CHARACTER STRING FROM 'LCNRL' TO 'K' IS
C     NOT A VALID CHARACTER REPRESENTATION.
C
      DO I=1,LENB
         IF ( A(K:K) .EQ. B(I:I) ) GO TO 700
      ENDDO
C
C ... TO HAVE FALLEN THROUGH THIS LOOP MEANS THAT THE TRAILING
C     CHARACTER BEHIND AN APPARENTLY VALID NUMERIC REPRESENTATION
C     IS NOT IN THE DELIMITER SET, AND THEREFORE THE PREVIOUSLY
C     PROCESSED CHARACTER STRING MUST BE REJECTED FROM CONSIDERATION
C     AS A NUMERIC REPRESENTATION.
C
      GO TO 100
C
C     ----------------------------------------------------------------
C ... THE CHARACTER IS A VALID NUMERIC VALUE.  IS IT IN THE PROPER
C     ORDER IN REFERENCE TO PREVIOUSLY ENCOUNTERED NUMERIC CHARACTERS.
C     ----------------------------------------------------------------
C
C ... IF IT IS NUMERIC, IT MAY BE 'MORE MANTISSA WHOLE NUMBER', OR,
C     'MORE MANTISSA FRACTION', OR, PART OF THE 'EXPONENT'.
C     THE 'EXPONENT' IS LIMITED IN SIZE TO 2 OR 3 SIGNIFICANT FIGURES,
C     DEPENDING UPON THE HARDWARE ON WHICH THIS CODE IS RUNNING.
C
  400 CONTINUE
      IF ( ( I .LT. 11 ) .AND. ( .NOT. EXPDE ) ) THEN
C
C ...... 'MORE MANTISSA WHOLE NUMBER' OR 'MORE MANTISSA FRACTION'.
C
         IF ( MDECPT ) THEN
            IF ( MDECJF ) THEN
               MDECJF = .FALSE.
               MFRACT = .TRUE.
            ENDIF
         ELSE
            MWHNUM = .TRUE.
         ENDIF
C
      ELSEIF ( ( I .LT. 11 ) .AND. ( EXPJF .OR. EXPSJF ) ) THEN
C
C ...... NUMERIC VALUE IS THE FIRST NUMBER FOLLOWING 'D' OR 'E'
C        OR THE EXPONENT SIGN.
C
         EXPJF  = .FALSE.
         EXPSJF = .FALSE.
         EXPNUM = .TRUE.
C
      ELSEIF ( ( I .LT. 11 ) .AND. ( EXPNUM ) ) THEN
C
C ...... NEXT EXPONENT DIGIT -- THERE IS NOTHING TO DO HERE
C
         CONTINUE
C
      ELSEIF ( ( I .EQ. 11 ) .AND. ( .NOT. MDECPT ) ) THEN
C
C ...... THIS IS THE DECIMAL POINT BETWEEN THE MANTISSA WHOLE NUMBER
C        AND THE MANTISSA FRACTION.
C
         MDECPT = .TRUE.
         MDECJF = .TRUE.
C
      ELSEIF ( ( I.EQ.12 .OR. I.EQ.13 ) .AND. ( EXPJF ) ) THEN
C
C ...... THIS IS THE PLUS OR MINUS SIGN IMMEDIATELY FOLLOWING THE
C        'D' OR 'E' OF AN EXPONENTIAL NOTATION.
C
         EXPJF  = .FALSE.
         EXPSGN = .TRUE.
         EXPSJF = .TRUE.
C
      ELSEIF ( ( I.EQ.14 .OR. I.EQ.15 ) .AND.
     1         (  MWHNUM .OR. MFRACT  ) .AND. ( .NOT. EXPDE ) ) THEN
C
C ...... THIS IS A 'D' OR AN 'E' FOLLOWING A VALID MANTISSA.
C
         EXPDE  = .TRUE.
         EXPJF  = .TRUE.
         IF ( I.EQ.14 ) THEN
            EXPCHE = .TRUE.
         ELSE
            EXPCHD = .TRUE.
         ENDIF
C
      ELSE
C
C ...... WHATEVER IT IS, IT OCCURRED IN THE WRONG SEQUENCE TO BE PART
C        OF A VALID NUMERIC REPRESENTATION.  HOWEVER, IT MAY BE ONE OF
C        THE VALID DELIMITERS (LIKE PLUS OR MINUS).
C
         DO I=1,LENB
            IF ( A(K:K) .EQ. B(I:I) ) GO TO 700
         ENDDO
C
         GO TO 100
C
      ENDIF
C
C ... IF A VALID BRANCH OF THE ABOVE IF--ELSEIF--ENDIF SET WAS TAKEN,
C     THEN THE CHARACTER WAS VALID IN ITS POSITION.  LOOK AT THE NEXT
C     CHARACTER IN THE STRING.
C
      GO TO 260
C
C     ----------------------------------------------------------------
C ... A VALID NUMERIC REPRESENTATION HAS BEEN FOUND. SET THE 'TYPE'
C     FLAG AND RETURN TO THE CALLER.
C     ----------------------------------------------------------------
C
  700 CONTINUE
      LCNRR = MIN( K-1,LENA )
C
      IF ( ( MWHNUM ) .AND. ( .NOT. MDECPT ) .AND. ( .NOT. MFRACT )
     1                .AND. ( .NOT. EXPDE  ) .AND. ( .NOT. EXPSGN )
     2                .AND. ( .NOT. EXPNUM ) ) TYPE = 'I'
C
      IF ( ( MWHNUM .OR. MFRACT ) .AND. ( MDECPT ) .AND.
     1     ( .NOT. EXPDE  ) .AND. ( .NOT. EXPSGN ) .AND.
     2     ( .NOT. EXPNUM ) ) TYPE = 'F'
C
      IF ( EXPCHE .AND. EXPNUM ) TYPE = 'E'
C
      IF ( EXPCHD .AND. EXPNUM ) TYPE = 'D'
C
      IF ( TYPE .NE. 'N' ) GO TO 900
C
C ... EVIDENTLY ONLY A PLUS OR A MINUS WAS FOUND, DELIMITED BY VALID
C     DELIMITER CHARACTERS.  HOWEVER, THIS IS NOT SUFFICIENT TO BE
C     CALLED A VALID NUMERIC REPRESENTATION.
C
      GO TO 100
C
C     ----------------------------------------------------------------
C ... RETURN TO CALLER WITHOUT FINDING A VALID NUMERIC REPRESENTATION.
C     ----------------------------------------------------------------
C
  800 CONTINUE
C
      LCNRL = 0
      LCNRR = 0
C
C     ----------------------------------------------------------------
C ... DIRECT JUMP TO 900 MEANS THAT A VALID NUMERIC REPRESENTATION WAS
C     FOUND AND INDICES 'LCNRL' AND 'LCNRR' DELIMIT THAT NUMBER.
C     ----------------------------------------------------------------
C
  900 CONTINUE
C
      RETURN
      END
