      SUBROUTINE HHSDEL ( A, B, FILLCH, N, ND, IER )
C
C .. PURPOSE:
C        HHSDEL PERFORMS THE EDITING FUNCTION OF DELETING THE FIRST
C        'N' OCCURRENCES OF SUBSTRING 'B' FROM STRING 'A', AND
C        PADDING THE RIGHT-END OF THE STRING WITH 'FILLCH' FILL
C        CHARACTERS.
C
C ... INPUTS:
C        A        A CHARACTER VARIABLE CONTAINING THE DATA STRING
C                 IN WHICH THE FIRST 'N' OCCURRENCES OF SUBSTRING
C                 'B' ARE TO BE DELETED.
C        B        A CHARACTER VARIABLE CONTAINING THE DATA STRING
C                 DEFINITION OF THE CHARACTER STRING TO BE DELETED
C                 FROM STRING 'A'.
C        FILLCH   A CHARACTER(LEN=1) VARIABLE CONTAINING THE 'FILL
C                 CHARACTER' TO BE USED TO PAD THE RIGHT-END OF
C                 DATA STRING 'A' WHEN SUBSTRING 'B' IS DELETED
C                 FROM THE STRING.  IF 'FILCH' IS NOT CHARACTER(LEN=1),
C                 THE FIRST CHARACTER OF THE 'FILLCH' STRING IS
C                 USED AS THE 'FILL-CHARACTER'.
C        N        AN INTEGER VARIABLE CONTAINING THE MAXIMUM NUMBER
C                 OF TIMES THAT THE DELETION PROCESS IS TO OCCUR
C                 (OR BE REPEATED) ON STRING 'A'.
C
C .. OUTPUTS:
C        A        THE INPUT CHARACTER VARIABLE IN WHICH 'ND'
C                 OCCURRENCES OF SUBSTRING 'B' HAVE BEEN DELETED.
C                 'FILLCH' HAS BEEN PADDED ONTO THE RIGHT-END OF
C                 STRING 'A' TO REPLACE THE CHARACTERS THAT WERE
C                 DELETED.
C        ND       AN INTEGER VARIABLE CONTAINING THE ACTUAL NUMBER OF
C                 TIMES THAT SUBSTRING 'B' WAS DELETED FROM STRING 'A'.
C                 THIS VALUE MAY BE ANY NUMBER FROM ZERO TO AND
C                 INCLUDING 'N'.
C        IER      SUCCESS/ERROR CODE.
C        IER =  0 NO ERRORS.
C        IER = -1 THE NUMBER OF DELETIONS 'N' IS NON-POSITIVE.
C                 NO DELETIONS ARE PERFORMED.  ND IS SET TO ZERO.
C
C .. LIMITATIONS AND WARNINGS:
C        THE CAPABILITIES OF THIS ROUTINE ARE LIMITED BY THE
C        MAXIMUM LENGTH OF A CHARACTER STRING ALLOWED BY THE
C        COMPILER OF THE MACHINE UPON WHICH IT IS IMPLENENTED.
C        HOWEVER, THAT RESTRICTION IS IMPOSED UPON THE CALLING
C        ROUTINE; NOT UPON THE CODE INTERNAL TO THIS ROUTINE.
C
C .. MODULES REQUIRED:
C        LEN      FORTRAN 77 INTRINSIC FUCTION TO DETERIME THE LENGTH
C                 OF A CHARACTER VARIABLE WHICH WAS PASSED THROUGH
C                 THE CALLING SEQUENCE (IN THIS APPLICATION).
C        INDEX    FORTRAN 77 INTRINSIC FUNCTION TO FIND THE OCCURRENCE
C                 OF A CHARACTER SUBSTRING IN A CHARACTER STRING.
C        HHADJF   BCS ROUTINE TO ADJUST A STRING FULLY TO ONE BOUNDARY.
C
C .. NOTES:
C        THE DELETION PROCESS PROCEEDS FROM LEFT-TO-RIGHT ACROSS STRING
C        'A'.  DELETION OF A SET OF CHARACTERS IN 'A' WHICH MATCH THE
C        'DELETION CHARACTER DEFINITION STRING' IN 'B' RESULTS IN THE
C        LEFT-SHIFTING OF THE REMAINING CHARACTERS IN STRING 'A'
C        (WHERE "REMAINING" MEANS THOSE TO THE RIGHT OF THE DELETION
C        ACTION).  THE 'FILLCH' CHARACTER IS USED TO PAD THE RIGHT-END
C        OF STRING 'A'.
C
C .. PROGRAMMER/ORGANIZATION:
C        ALVIN C. MONG - G-7520 - NUMERICAL ANALYSIS -
C        ENGINEERING APPLICATIONS TECHNOLOGY, BCS, SEATTLE, WA.
C
C .. MODIFICATIONS:
C        ALVIN C. MONG - BCS - G-7520 - 29 APRIL 1985
C           ORIGINAL DESIGN AND CODING.
C        ALVIN C. MONG - BCS - G-6520 - 11 FEB.  1986
C           MODIFIED ERROR HANDLING AND REPORTING.
C
C     ----------------------------------------------------------------
C
      CHARACTER(LEN=*)  A, B, FILLCH
      CHARACTER(LEN=1)  BLANK, STAR, XCH, FCH
      CHARACTER(LEN=8)  NAME
      INTEGER       N, ND, IER
C
      DATA NAME / 'HHSDEL' /
      DATA BLANK/  ' '  /
      DATA STAR /  '*'  /
C
C     ----------------------------------------------------------------
C
C ... GET THE LENGTH OF THE STRING 'A'.
C     INITIALIZE THE WORKING VARIABLES.
C
      ND   = 0
      LENA = LEN ( A )
      LENB = LEN ( B )
      FCH  = FILLCH(1:1)
      K    = 1
      L    = LENA
C
C ... IF 'N' IS .LE. 0, NO WORK IS TO BE DONE.  SIMPLY REPORT
C     AN ERROR AND RETURN.
C
      IF ( N .LE. 0 ) THEN
         IER = -1
         CALL HHERR ( 1, NAME, IER, 0 )
         GO TO 900
      ENDIF
C
C ... NOW SCAN ACROSS THE STRING 'A' LOOKING FOR A MATCH OF THE
C     DELETION STRING DEFINITION 'B'.
C
      DO I=1,N
C
         J  = INDEX( A(K:L), B )
C
         IF ( J .EQ. 0 ) GO TO 900
C
C ... TO DELETE SUBSTRING 'B' FROM STRING 'A', THE POSITIONS IN 'A'
C     MATCHING 'B' ARE REPLACES WITH EITHER "BLANK" OR "STAR".
C     ROUTINE 'HHADJF' IS THEN USED TO SHIFT THE REMAINDER OF 'A' TO
C     THE LEFT SUCH THAT THE '*' OR ' ' ARE WIPED OUT.  IF B='*' AND
C     A='***** THIS IS IT *****', AND THE NUMBER OF DELETION REPEATS
C     IS N=2, THEN THE FIRST 2 CHARACTERS OF 'A' MUST BE CHANGED TO
C     "BLANK" BEFORE 'HHADF' CAN SHIFT THE 'A' SUBFIELD.  OTHERWISE,
C     ALL 5 LEADING '*' CHARACTERS WOULD BE LOST.
C
         J  = J+K-1
         NN = J+LENB
         if(nn.gt.lena) cycle
C
         IF ( A(NN:NN) .EQ. STAR ) THEN
            XCH = BLANK
         ELSE
            XCH = STAR
         ENDIF
C
C ...... DELETE THIS OCCURRENCE OF SUBSTRING 'B' FROM STRING 'A'.
C
         ND = ND + 1
C
         DO M=1,LENB
            NN = J+M-1
            A(NN:NN) = XCH
         ENDDO
C
         CALL HHADJF ( A(J:L), XCH, FCH, 'L', NS, IER )
C
         K  = J
         L  = L - NS
         IF (L.LT.K) GO TO 900
C
      ENDDO
C
C ... IF WE FALL THROUGH THE 'DO' LOOP, THEN ALL 'N' REQUESTED
C     DELETIONS WERE PERFORMED, AND 'ND' IS SET TO 'N'.
C     IF WE GET TO 900 THROUGH A 'GOTO', THEN LESS THAN 'N'
C     DELETIONS WERE PERFORMED.
C
  900 CONTINUE
C
      RETURN
      END
