
      SUBROUTINE INSHUR(AMAT,IROW,JCOLST,NZERO,XVEC,XLWR,XUPR,
     $    BLWR,BUPR,WORK,BIGBND,TOLCON,MCON,MDIM,MEQUAL,NDIM,
     $    NSTD,XSTD,BSTD,BLWSTD,BUPSTD,SFEZ,IVSTAT,ISTART)
C
C ======================================================================
C     INSHUR===>inshur   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         PURPOSE:  INITIALIZE THE SCHUR-COMPLEMENT QP VARIABLES
C                   FROM THE USER SPECIFIED QUANTITIES
C
C         INPUT:
C
C           AMAT    JACOBIAN NONZERO ARRAY (NZERO)
C           IROW    INTEGER ROW INDEX ARRAY (NZERO)
C           JCOLST  INTEGER COLUMN START ARRAY (NDIM+1)
C           NZERO   NUMBER OF NONZEROS IN JACOBIAN
C           XVEC    REAL VARIABLES (NDIM)
C           XLWR    REAL VARIABLE LOWER BOUNDS (NDIM)
C           XUPR    REAL VARIABLE UPPER BOUNDS (NDIM)
C           BLWR    LOWER BOUNDS -- EQUALITY CONSTRAINTS FIRST FOLLOWED 
C                   BY INEQUALITIES (MDIM)
C           BUPR    UPPER BOUNDS -- STORED LIKE BLWR (MDIM)
C           WORK    WORK ARRAY OF LENGTH (MDIM)
C           BIGBND  SCALAR BIG BOUND VALUE
C           TOLCON  CONSTRAINT TOLERANCE
C           MCON    NUMBER OF CONSTRAINTS (.LE.MDIM)
C           MDIM    DIMENSION OF CONSTRAINT ARRAYS (.GE.1)
C           MEQUAL  NUMBER OF EQUALITY CONSTRAINTS
C           NDIM    NUMBER OF VARIABLES
C           NSTD    NUMBER OF STANDARD FORM VARIABLES 
C                   = MINEQL + 1 + NDIM
C           XSTD    STANDARD FORM PROBLEM VARIABLES -- SLACK VARIABLES
C                   MUST BE INPUT WHEN ISTART = 0 (WARM START) (NSTD)
C           IVSTAT  INTEGER VARIABLE STATUS VECTOR (MCON+1+NDIM)
C                   SLACK VARIABLE STATUS MUST BE INPUT WHEN ISTART = 0
C           ISTART  INTEGER START OPTION FLAG
C                     = 0 --- WARM START
C                     = 1 --- COLD START
C
C         OUTPUT:
C
C           XSTD    STANDARD FORM PROBLEM VARIABLES -- SLACK VARIABLES
C                   FIRST, THEN FEASIBILITY SLACK, THEN REAL VARIABLES
C                   (NSTD)
C           BSTD    RIGHT HAND SIDE FOR STANDARD FORM EQUALITIES (MDIM)
C           BLWSTD  LOWER BOUNDS FOR STANDARD FORM VARIABLES (NSTD)
C           BUPSTD  UPPER BOUNDS FOR STANDARD FORM VARIABLES (NSTD)
C           SFEZ    FEASIBILITY RESIDUAL VECTOR (MDIM)
C           IVSTAT  INTEGER VARIABLE STATUS VECTOR (MCON+1+NDIM)
C
      DIMENSION AMAT(NZERO),IROW(NZERO),JCOLST(NDIM+1),XVEC(NDIM),
     $    XLWR(NDIM),XUPR(NDIM),BLWR(MDIM),BUPR(MDIM),WORK(MDIM),
     $    XSTD(NSTD),BSTD(MDIM),BLWSTD(NSTD),BUPSTD(NSTD),
     $    SFEZ(MDIM),IVSTAT(MCON+1+NDIM)
C
      PARAMETER (ZERO=0.D0,ONE=1.D0)
C
C     ===================================================================
C
      MINEQL = MCON - MEQUAL
      MIP1 = MINEQL + 1
      MIP2 = MIP1 + 1
      MEP1 = MEQUAL + 1
C
C         CONSTRUCT STANDARD FORM REAL VARIABLE FROM XVEC SUCH THAT
C         XSTD IS FEASIBLE.  ALSO LOAD CORRESPONDING BOUNDS
C
      DO I = 1,NDIM
        II = MIP1 + I
        JJ = MCON + I + 1
        BLWSTD(II) = XLWR(I)
        BUPSTD(II) = XUPR(I)
C
        IF(ISTART.EQ.0) THEN
C
C         WARM START -- CONSTRUCT VARIABLE FROM IVSTAT
C
          IF(IVSTAT(JJ).EQ.1) THEN
C
C         VARIABLE FIXED ON LOWER BOUND
C
            XSTD(II) = BLWSTD(II)
C
          ELSEIF(IVSTAT(JJ).GE.2) THEN
C
C         VARIABLE FIXED ON UPPER BOUND OR FIXED AND NEVER
C         CHANGED WHEN IVSTAT = 3
C
            XSTD(II) = BUPSTD(II)
C
          ELSE
C
C         VARIABLE IS FREE, STRICTLY FEASIBLE, AND AS
C         CLOSE AS POSSIBLE TO INPUT VALUE
C
            XSTD(II) = MIN( MAX( BLWSTD(II)+TOLCON , XVEC(I)) 
     $                                  , BUPSTD(II)-TOLCON)
C
          ENDIF
C
        ELSE
C
C         COLD START
C
          XSTD(II) = MIN( MAX( XLWR(I) , XVEC(I)) , XUPR(I) )
C
        ENDIF
C
      enddo  
C
C         CONSTRUCT THE PRODUCT WORK = AMAT*XSTD
C
      CALL MVPSPR(1,MCON,NDIM,AMAT,IROW,JCOLST,XSTD(MIP2),WORK)
C
C         LOAD RIGHT HAND SIDE FOR REAL EQUALITY CONSTRAINTS
C
      BSTD(1:MEQUAL) = BLWR(1:MEQUAL)
C
      DO I = MEP1,MCON
C
        II = I - MEQUAL 
C
        IF(BLWR(I).GT.-BIGBND) THEN
C
C         LOWER BOUND IS FINITE -- CHECK UPPER BOUND
C
          IF(BUPR(I).LT.BIGBND) THEN
C
C         UPPER BOUND IS ALSO FINITE--SHIFT TO THE CLOSEST BOUND
C
            IF(ABS(BLWR(I)-WORK(I)).LT.ABS(BUPR(I)-WORK(I))) THEN
              BLWSTD(II) = BLWR(I) - BUPR(I)
              BUPSTD(II) = ZERO
              BSTD(I) = BLWR(I)
            ELSE
              BLWSTD(II) = ZERO
              BUPSTD(II) = BUPR(I) - BLWR(I)
              BSTD(I) = BUPR(I)
            ENDIF
C
          ELSE
C
C         UPPER BOUND IS INFINITE (UNBOUNDED)
C
            BLWSTD(II) = -BIGBND
            BUPSTD(II) = ZERO
            BSTD(I) = BLWR(I)
C
          ENDIF
C
        ELSE
C
C         LOWER BOUND IS NEGATIVE INFINITY (UNBOUNDED)
C
          BLWSTD(II) = ZERO
          BUPSTD(II) = BIGBND
          BSTD(I) = BUPR(I)
C
        ENDIF
C
      enddo
C
C         CONSTRUCT STANDARD FORM SLACK VARIABLE SUCH THAT
C         XSTD IS FEASIBLE.  
C
      DO I = 1,MINEQL
        II = MEQUAL + I
        IF(ISTART.EQ.0) THEN
C
C         WARM START -- CONSTRUCT SLACK FROM IVSTAT
C
          IF(IVSTAT(II).EQ.1) THEN
C
C         SLACK FIXED ON LOWER BOUND
C
            XSTD(I) = BLWSTD(I)
C
          ELSEIF(IVSTAT(II).EQ.2) THEN
C
C         SLACK FIXED ON UPPER BOUND
C
            XSTD(I) = BUPSTD(I)
C
          ELSE
C
C         SLACK IS FREE, STRICTLY FEASIBLE, AND AS
C         CLOSE AS POSSIBLE TO INPUT VALUE
C
            XSTD(I) = MIN( MAX( BLWSTD(I)+TOLCON , XSTD(I)) 
     $                                  , BUPSTD(I)-TOLCON)
C
          ENDIF
C
        ELSE
C
C         COLD START
C
          XSTD(I) = BSTD(II) - WORK(II)
          XSTD(I) = MIN( MAX( BLWSTD(I) , XSTD(I)) , BUPSTD(I) )
C
        ENDIF
C 
      enddo
C
C         COMPUTE THE FEASIBLITY RESIDUAL VECTOR/NORM
C
      RESNRM = ZERO
      DO I = 1,MEQUAL
        SFEZ(I) = BSTD(I) - WORK(I)
        RESNRM = MAX(RESNRM,ABS(SFEZ(I)))
      enddo
C
      DO I = MEP1,MCON
        SFEZ(I) = BSTD(I) - WORK(I) - XSTD(I-MEQUAL)
        RESNRM = MAX(RESNRM,ABS(SFEZ(I)))
      enddo
C
      IF(RESNRM.LT.TOLCON) THEN
C
C         CONSTRAINTS ARE ALL FEASIBLE
C
        XSTD(MIP1) = ZERO
        SFEZ(1:MCON) = ZERO
C
      ELSE
C
C         CONSTRAINTS ARE NOT FEASIBLE
C
        XSTD(MIP1) = ONE
C
      ENDIF
C
C         SAVE FEASIBILITY SLACK BOUNDS AND DEFAULT SLACK PENALTY
C
      BLWSTD(MIP1) = ZERO
      BUPSTD(MIP1) = ONE
C
C         INITIALIZE THE VARIABLE STATUS FLAG
C
C         -- EQUALITIES
C
      IVSTAT(1:MEQUAL) = -1
C
      IF(ISTART.EQ.0) THEN
C
C        ---- WARM START 
C
        DO I = 1,MIP1+NDIM
          II = MEQUAL + I
C
          IF(I.GT.MIP1.AND.BLWSTD(I).EQ.BUPSTD(I)) THEN
C 
C         -- VARIABLE PERMANENTLY FIXED
C
            IVSTAT(II) = 3
C
          ELSEIF(XSTD(I).GT.BUPSTD(I)-TOLCON) THEN
C
C         -- VARIABLES FIXED ON UPPER BOUND
C
            IVSTAT(II) = 2
C
          ELSEIF(XSTD(I).LT.BLWSTD(I)+TOLCON) THEN
C
C         -- VARIABLES FIXED ON LOWER BOUND
C
            IVSTAT(II) = 1
C
          ELSE
C
C         -- FREE VARIABLES 
C
            IVSTAT(II) = 0
C
          ENDIF
C
        enddo
C
      ELSE
C
C        ---- COLD START 
C
C         -- SLACK VARIABLES FREE
C
        IVSTAT(MEP1:MEP1+MINEQL-1) = 0
C
C         -- ARTIFICIAL VARIABLE 
C
        IF(RESNRM.LT.TOLCON) THEN
C
C         CONSTRAINTS ARE ALL FEASIBLE
C
          IVSTAT(MCON+1) = 1
C
        ELSE
C
C         CONSTRAINTS ARE NOT FEASIBLE
C
          IVSTAT(MCON+1) = 2
C
        ENDIF
C
C         -- REAL VARIABLES DEFAULT FREE
C
        IVSTAT(MCON+2:MCON+1+NDIM) = 0
C
        DO I = MIP2,MIP1+NDIM
C
          IF(BLWSTD(I).EQ.BUPSTD(I)) THEN
C 
C         -- VARIABLE PERMANENTLY FIXED
C
            IVSTAT(MEQUAL+I) = 3
C
          ELSEIF(XSTD(I).GE.BUPSTD(I)) THEN
            JCL = I - MIP1
            NROWEQ = 0
            DO J=JCOLST(JCL),JCOLST(JCL+1)-1
              IF (IROW(J).LE.MEQUAL)  NROWEQ = NROWEQ + 1
            ENDDO
C
C         IF THE EQUALITY CONSTRAINTS ARE NOT AFFECTED BY THIS
C         VARIABLE, NROWEQ WILL BE ZERO -- FIX THE REAL VARIABLE
C
            IF(NROWEQ.EQ.0) IVSTAT(MEQUAL+I) = 2
C
          ELSEIF(XSTD(I).LE.BLWSTD(I)) THEN
            JCL = I - MIP1
            NROWEQ = 0
            DO J=JCOLST(JCL),JCOLST(JCL+1)-1
              IF (IROW(J).LE.MEQUAL)  NROWEQ = NROWEQ + 1
            ENDDO
C
C         IF THE EQUALITY CONSTRAINTS ARE NOT AFFECTED BY THIS
C         VARIABLE, NROWEQ WILL BE ZERO -- FIX THE REAL VARIABLE
C
            IF(NROWEQ.EQ.0) IVSTAT(MEQUAL+I) = 1
C
          ENDIF
C
        enddo        
C
      ENDIF
C
C         COUNT THE NUMBER OF FREE REAL VARIABLES.  IF THERE ARE
C         NONE MAKE THE FIRST ONE FREE
C
      NUMFRE = 0
      DO I=1,NDIM
        IF (IVSTAT(MCON+1+I).EQ.0)  NUMFRE = NUMFRE + 1
      ENDDO
      IF(NUMFRE.EQ.0) IVSTAT(MCON+2) = 0
C
      RETURN
C 
      END     
