

      SUBROUTINE INSNLP(STRING)
C
C ======================================================================
C     INSNLP===>INSNLP   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         PURPOSE:  LOAD VALUES INTO THE NLPSPR.CMN COMMON
C                   GIVEN A CHARACTER STRING INPUT
C
C         INPUT:
C
C           STRING  CHARACTER VARIABLE STRING OF LENGTH
C                   NOT TO EXCEED 80 CHARACTERS.  THE STRING
C                   IS ASSUMED TO HAVE THE FOLLOWING FORMAT
C                   '  SYMBOL  =  VALUE '.  THE SYMBOL MUST
C                   BE ONE OF THE NMEMONICS IN THE NLPSPR
C                   COMMONS.  THE CHARACTER STRING MUST HAVE
C                   AN EQUALS SIGN "=" TO SEPARATE THE SYMBOL
C                   FROM THE VALUE.  THE ONLY EXCEPTIONS TO THIS
C                   RULE ARE WHEN SYMBOL = 'SPARSE DEFAULT',
C                   'DENSE DEFAULT','OPTION', OR
C                   'FULL OPTIONS'.  THE "VALUE"
C                   PORTION OF THE STRING CAN CONTAIN INTEGER,
C                   REAL (SINGLE OR DOUBLE PRECISION), OR CHARACTER
C                   VALUES.
C
C         COMMONS:
C
C           NPSPRR  NLPSPR REAL VARIABLE INPUTS
C           NPSPRI  NLPSPR INTEGER VARIABLE INPUTS
C           NPSPRC  NLPSPR CHARACTER VARABLE INPUTS
C                   
C         USAGE:
C
C           (1)     SETTING DEFAULTS.  CALL INSNLP(`SPARSE DEFAULT')
C           (2)     SETTING VALUES. EXAMPLES;
C                   CALL INSNLP('NITMAX = 127')
C                   CALL INSNLP('  contol = 1.2d-5')
C                   CALL INSNLP(' Algopt = fwrm')
C           (3)     IF DEFAULTS HAVE NEVER BEEN SET THE INTEGER
C                   VARIABLE INNPER=-1.  THE FIRST CALL TO SET
C                   ANY VALUE (INTEGER, REAL, CHARACTER) WILL
C                   FIRST SET DEFAULTS, AND THEN SET THE VALUE.
C           (4)     ERRORS IN THE INPUT STRING WILL CAUSE 
C                   A) INTEGER VARIABLE INNPER TO BE INCREMENTED,
C                   B) INVALID CHARACTER STRING LOADED INTO THE 
C                   CHARACTER(LEN=52) BUFFER INPBUF AND DISPLAYED 
C                   ON THE DEFAULT OUTPUT UNIT BY HHERRX
C           (5)     CALLING PROGRAM SHOULD TEST FOR INNPER .GT. 0
C                   AND IF POSITIVE TERMINATE
C
C         ERROR RETURNS
C
C           IER     =  0  NORMAL RETURN--DATA HAS BEEN LOADED
C                   = -1  STRING TOO LONG (GT. 80 CHARACTERS)
C                   = -2  REPLACEMENT ERROR DURING CAPITALIZATION
C                   = -3  EQUAL SIGN "=" MISSING FROM STRING
C                   = -4  INVALID REAL VALUE
C                   = -5  INVALID INTEGER VALUE
C                   = -6  INVALID CHARACTER VALUE
C                   = -7  INVALID SYMBOL NAME
C         
      CHARACTER(LEN=*) STRING
C
C
      LOGICAL FOUND
      PARAMETER (NRSYM=11,NISYM=35,NCSYM=3)
      PARAMETER (NBRSYM=5,NBISYM=3,NBCSYM=0)
      PARAMETER (NSYMBL=NRSYM+NISYM+NCSYM)
      PARAMETER (NBSMBL=NBRSYM+NBISYM+NBCSYM)
      CHARACTER(LEN=80) BLANK,INPWRK
      CHARACTER(LEN=52) INPBUF
      CHARACTER(LEN=6)  SYMBUL(NSYMBL)
      CHARACTER(LEN=6)  BSYMBL(NBSMBL)
C
C-------------------------------------------------------------
      INCLUDE '../commons/NLPSPR.CMN'
      INCLUDE '../commons/BARNLP.CMN'
C-------------------------------------------------------------
C
      DATA (SYMBUL(I),I=1,NSYMBL) /
     $    'ALFLWR', 'ALFUPR', 'CONTOL', 'EPSRLF', 'OBJTOL', 
     $    'PGDTOL', 'SLPTOL', 'SFZTOL', 'TOLFIL', 'TOLKTC', 
     $    'TOLPVT', 'IHESHN', 'IOFLAG', 'IOFLIN', 'IOFMFR',      
     $    'IOFPAT', 'IOFSHR', 'IOFSRC', 'IPUDRF', 'IPUFZF',   
     $    'IPUMF1', 'IPUMF2', 'IPUMF3', 'IPUMF4', 'IPUMF5',    
     $    'IPUMF6', 'IPUMF7', 'IPUNLP', 'IPUSTF', 'IRELAX',       
     $    'ITDRQP', 'ITFZQP', 'IT1MAX', 'JACPRM', 'LYNFNC',    
     $    'LYNOUT', 'LYNPLT', 'LYNPNT', 'LYNVAR', 'MAXLYN',    
     $    'MAXNFE', 'MNSAME', 'NEWTON', 'NITMAX', 'NITMIN', 
     $    'NORMAL', 'ALGOPT', 'KTOPTN', 'QPOPTN' /
      DATA (BSYMBL(I),I=1,NBSMBL) /
     $    'BIGCON', 'FEATOL', 'PMULWR', 'PTHTOL', 'RHOLWR',  
     $    'IMAXMU', 'MUCALC', 'MXQPIT' /
      DATA BLANK(1:80) / ' '/
C
C-------------------------------------------------------------
C
C
C         IF JHSN74(1) = -1, THE DEFAULTS HAVE NEVER BEEN SET.  SET
C         THEM AND THEN MODIFY THEM WITH THE INPUT
C
      IF(JHSN74(1).EQ.-1) CALL SPRDFL
C
C         COMPUTE LENGTH OF INPUT CHARACTER STRING
C
      LNINPT = LEN(STRING)
C
C         SAVE FIRST 52 CHARACTERS OF INPUT STRING IN BUFFER FOR 
C         POSSIBLE DIAGNOSTIC
C
      IER = 0
      INPBUF = BLANK(1:52)
      LNBUF = MIN(LNINPT,52)
      INPBUF = STRING(1:LNBUF)
C
C         IF INPUT STRING IS TOO LONG EXIT
C
      IF(LNINPT.GT.80) THEN
        IER = -1
        GO TO 10000
      ENDIF
C
C         STORE INPUT STRING INTO LOCAL WORK ARRAY
C
      INPWRK = BLANK
      INPWRK(1:LNINPT) = STRING(1:LNINPT)
C
C         CAPITALIZE ALL THE LOWER CASE SYMBOLS IN THE INPUT STRING
C
      CALL CAPTUL(INPWRK,LNINPT,IERREP)
C
      IF(IERREP.NE.0) THEN
        IER = -2
        GO TO 10000
      ENDIF
C
C         FIRST SCAN THE STRING FOR THE CHARACTERS 'SPARSE DEFAULT'
C
      CALL HHLSTR(INPWRK,'SPARSE DEFAULT',1,LOCDEF)
C
C         IF LOCDEF IS NONZERO THEN DEFAULT VALUES HAVE TO BE SET
C
      IF(LOCDEF.NE.0) THEN
C
C             ALGORITHM DEFAULTS.
C
        CALL SPRDFL
C
        GO TO 10000
C
      ENDIF
C
C         SCAN THE STRING FOR THE CHARACTERS 'DENSE DEFAULT'
C
      CALL HHLSTR(INPWRK,'DENSE DEFAULT',1,LOCDNS)
C
C         IF LOCDNS IS NONZERO THEN DEFAULT VALUES HAVE TO BE SET
C
      IF(LOCDNS.NE.0) THEN
C
C             ALGORITHM DEFAULTS.
C
        CALL DNSDFL
C
        GO TO 10000
C
      ENDIF
C
C         SCAN THE STRING FOR THE CHARACTERS 'BARRIER'
C
      CALL HHLSTR(INPWRK,'BARRIER',1,LOCBAR)
C
C         IF LOCBAR IS NONZERO THEN BARRIER OPTIONS HAVE TO BE SET
C
      IF(LOCBAR.NE.0) THEN
C
        CALL HHLSTR(INPWRK(LOCBAR+7:LNINPT),'DEFAULT',1,LOCFUL)
C
C         IF LOCFUL IS NONZERO THEN DEFAULT VALUES HAVE TO BE SET
C
        IF(LOCFUL.NE.0) THEN
C
C             ALGORITHM DEFAULTS.
C
          CALL BARDFL
C
          GO TO 10000
C
        ENDIF
C
        CALL HHLSTR(INPWRK(LOCBAR+7:LNINPT),'FULL OPTION',1,LOCFUL)
C
        IF(LOCFUL.NE.0) THEN
C
C              FULL OPTIONS
C
          CALL BOPSHN(2)
C
          GO TO 10000
C
        ENDIF
C
        CALL HHLSTR(INPWRK(LOCBAR+7:LNINPT),'OPTION',1,LOCFUL)
C
        IF(LOCFUL.NE.0) THEN
C
C              SHORT OPTIONS
C
          CALL BOPSHN(1)
C
          GO TO 10000
C
        ENDIF
C
        CALL HHLSTR(INPWRK(LOCBAR+7:LNINPT),'SUMMARY',1,LOCFUL)
C
        IF(LOCFUL.NE.0) THEN
C
C             SUMMARY
C
          CALL BOPSHN(0)
C
          GO TO 10000
C
        ENDIF
C
      ENDIF
C
C             NEXT SCAN THE STRING FOR THE CHARACTERS 'OPTION'.
C
      CALL HHLSTR(INPWRK,'OPTION',1,LOCOPT)
C
C             IF LOCOPT IS NONZERO THEN OPTIONS HAVE BEEN REQUESTED.
C
      IF (LOCOPT.NE.0) THEN
C
C             OPTIONS HAVE BEEN REQUESTED.  DETERMINE WHETHER FULL
C             OR SHORT FORMAT IS REQUESTED, I.E. SCAN FOR THE STRING
C             'FULL'
C
        CALL HHLSTR(INPWRK(1:LOCOPT-1),'FULL',1,LOCFUL)
C
        IF(LOCFUL.NE.0) THEN
C
C              FULL OPTIONS
C
          CALL OPSHUN(16)
C
        ELSE
C
C              SHORT OPTIONS
C
          CALL OPSHUN(1)
C
        ENDIF
C
        GO TO 10000
C
      ENDIF
C
C         SCAN THE STRING FOR THE CHARACTERS 'SUMMARY'
C
      CALL HHLSTR(INPWRK,'SUMMARY',1,LOCSUM)
C
      IF(LOCSUM.NE.0) THEN
C
        CALL OPSHUN(-1)
C
        GO TO 10000
C
      ENDIF
C
C
C         FIND THE EQUAL SIGN IN THE INPUT STRING.  AFTER CALL
C         TWO POSSIBLITIES EXIST:
C         (1) LOCEQL .GT.0 AND INPWRK(LOCEQL:LOCEQL) CONTAINS 
C             THE EQUAL SIGN
C         (2) LOCEQL = 0
C
      CALL HHISCN(INPWRK,'=',1,LOCEQL,LCDUM)
C
C         CHECK FOR INVALID STRING
C
      IF(LOCEQL.EQ.0) THEN
        IER = -3
        GO TO 10000
      ENDIF
C
C         COMPRESS THE BLANKS OUT OF THE STRING TO IDENTIFY THE
C         SYMBOL. AFTER CALL THE SYMBOL IS CONTAINED IN 
C         INPWRK(1:LOCEQL-1)
C
      CALL HHSDEL(INPWRK(1:LOCEQL-1),' ',' ',LOCEQL-1,ND,IER)
C
C         FIND AND LOAD THE REAL VARIABLES--NOTE THE VARIABLES
C         ARE LOADED BEGINNING AT "ALFLWR", I.E. THE FIRST
C         REAL VARIABLE NAME
C
      CALL EVSYMR(INPWRK(1:6),INPWRK(LOCEQL+1:LNINPT),NRSYM,SYMBUL,
     $    ALFLWR,FOUND,IERER)
C
C         CHECK TO SEE IF A REAL VALUE WAS FOUND
C
      IF(FOUND) THEN
C
        IF(IERER.EQ.0) THEN
C
C         REAL VALUE FOUND AND LOADED
C
          GO TO 10000
C
        ELSE
C
          IER = -4
          GO TO 10000
C
        ENDIF
C
      ENDIF
C
C         FIND AND LOAD THE REAL BARRIER VARIABLES--NOTE THE VARIABLES
C         ARE LOADED BEGINNING AT "BIGCON", I.E. THE FIRST
C         REAL VARIABLE NAME
C
      CALL EVSYMR(INPWRK(1:6),INPWRK(LOCEQL+1:LNINPT),NBRSYM,BSYMBL,
     $    BIGCON,FOUND,IERER)
C
C         CHECK TO SEE IF A REAL VALUE WAS FOUND
C
      IF(FOUND) THEN
C
        IF(IERER.EQ.0) THEN
C
C         REAL VALUE FOUND AND LOADED
C
          GO TO 10000
C
        ELSE
C
          IER = -4
          GO TO 10000
C
        ENDIF
C
      ENDIF
C
C         FIND AND LOAD THE INTEGER VARIABLES.  NOTE THE VARIABLES
C         ARE LOADED INTO AN INTEGER ARRAY BEGINNING AT THE NAME
C         OF THE FIRST INTEGER VARIABLE IHESHN.
C
      CALL EVSYMI(INPWRK(1:6),INPWRK(LOCEQL+1:LNINPT),NISYM,
     $    SYMBUL(NRSYM+1),IHESHN,FOUND,IERER)
C
C         CHECK TO SEE IF AN INTEGER VALUE WAS FOUND
C
      IF(FOUND) THEN
C
        IF(IERER.EQ.0) THEN
C
C         INTEGER VALUE FOUND AND LOADED
C
          GO TO 10000
C
        ELSE
C
          IER = -5
          GO TO 10000
C
        ENDIF
C
      ENDIF
C
C         FIND AND LOAD THE BARRIER INTEGER VARIABLES.  NOTE THE VARIABLES
C         ARE LOADED INTO AN INTEGER ARRAY BEGINNING AT THE NAME
C         OF THE FIRST INTEGER VARIABLE IMAXMU
C
      CALL EVSYMI(INPWRK(1:6),INPWRK(LOCEQL+1:LNINPT),NBISYM,
     $    BSYMBL(NBRSYM+1),IMAXMU,FOUND,IERER)
C
C         CHECK TO SEE IF AN INTEGER VALUE WAS FOUND
C
      IF(FOUND) THEN
C
        IF(IERER.EQ.0) THEN
C
C         INTEGER VALUE FOUND AND LOADED
C
          GO TO 10000
C
        ELSE
C
          IER = -5
          GO TO 10000
C
        ENDIF
C
      ENDIF
C
C         FIND AND LOAD THE CHARACTER VARIABLES
C
      CALL EVSYMC(INPWRK(1:6),INPWRK(LOCEQL+1:LNINPT),NCSYM,
     $    SYMBUL(NRSYM+NISYM+1),ALGOPT,FOUND,IERER)
C
C         CHECK TO SEE IF A CHARACTER VALUE WAS FOUND
C
      IF(FOUND) THEN
C
        IF(IERER.EQ.0) THEN
C
C         CHARACTER VALUE FOUND AND LOADED
C
          GO TO 10000
C
        ELSE
C
          IER = -6
          GO TO 10000
C
        ENDIF
C
      ENDIF
C
C         AT THIS POINT NO VALID CHARACTER STRINGS WHERE FOUND
C         SET THE ERROR FLAG
C
      IER = -7
C
10000 CONTINUE
      IF (IER.LT.0) THEN
        INNPER = INNPER + 1
        CALL HHERR(3,'INSNLP  ',IER,0)
        CALL HHERRX(INPBUF,XDUM,0)
      ENDIF
C
      RETURN
      END
