
      SUBROUTINE LINSRC(VECP,TVEC,UVEC,XBAR,XVEC,XOLD,NDIM,DF0,D2F0,
     $    FBAR,FXTRAP,FREDUC,F0,ALFA,SLPTOL,SNORM,IT,MAXIT,CURVLN,
     $    EXTRAP,GOODGR,KHNCHK,IFUNER,IFC,IOFLAG,IPU,IERLIN)
C
C ======================================================================
C     LINSRC===>linsrc   J.T. BETTS
C ======================================================================
C     MODIFICATIONS:   13-APR-99 DSN  ADDED OVERFLOW PROTECTION TO
C                                     CALCULATION OF DISCR
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      SAVE
C
C
C         PURPOSE:  COMPUTE AN ESTIMATE ALFA, OF THE MINIMUM OF THE
C                   FUNCTION FBAR(ALFA) FOR 0 .LE. ALFA .LE. 1.
C                   WHEN FBAR(ALFA) CANNOT BE EVALUATED FOR ALFA .GE. ALFCLF
C                   BECAUSE THE CONSTRAINTS CANNOT BE ELIMINATED
C                   THE VALUE OF ALFA DETERMINED IS AN ESTIMATE OF THE 
C                   VALUE ALFCLF.  SPECIFICALLY THE ALGORITHM ATTEMPTS
C                   TO FIND A POINT WHERE THE SUFFICIENT REDUCTION 
C                   TEST IS MET; I.E.
C                     FBAR - F0 .LT. REDTOL*ALFA*F'(0)
C                   IN ADDITION NORMAL TERMINATION REQUIRES THE SLOPE
C                   REDUCTION TEST 
C                     |F'(ALFA)| .LT. -SLPTOL*F'(0)
C                   WHERE 1 > SLPTOL > REDTOL > 0.  A "CLIFF" SATISFIES
C                   THE SUFFICIENT REDUCTION TEST, BUT INSTEAD HAS A
C                   MORE NEGATIVE SLOPE THAN THE REFERENCE POINT, I.E.
C                     F'(ALFA) < MIN(-1,CLFTOL*F'(0))
C                   THE PARAMETERS REDTOL AND CLFTOL ARE DEFINED BELOW.
C                   SLPTOL CAN BE SPECIFIED TO CONTROL THE ACCURACY
C                   OF THE LINE SEARCH.
C
C         INPUT:
C
C            VECP   SEARCH DIRECTION VECTOR (NDIM)
C            TVEC   SECOND ORDER SEARCH CORRECTION VECTOR (NDIM)
C            UVEC   THIRD ORDER SEARCH CORRECTION VECTOR (NDIM)
C            XBAR   CORRECTED VARIABLES (NDIM)
C            XVEC   VARIABLES AT ALFA=0 (NDIM)
C            XOLD   OLD VARIABLE VALUES (NDIM)
C            NDIM   NUMBER OF VARIABLES
C            DF0    THE SLOPE OF FBAR AT ALFA=0, I.E. DF(ALFA=0)/DALFA
C                   IT IS REQUIRED THAT DF0 < 0
C            D2F0   THE CURVATURE OF FBAR AT ALFA=0, I.E. D2F(ALFA=0)/DALFA2
C                   NORMALLY WE EXPECT D2F0 > 0
C            FBAR   THE VALUE OF THE FUNCTION AT ALFA.
C            F0     THE VALUE OF FBAR AT THE INITIAL POINT ALFA=0
C            ALFA   AN ESTIMATE (GT.0) OF THE OPTIMUM VALUE
C            SLPTOL TOLERANCE FOR SLOPE REDUCTION TEST
C                   |F'(ALFA)| .LT. -SLPTOL*F'(0)
C                   1 > SLPTOL > REDTOL
C            SNORM  LENGTH OF SEARCH VECTOR
C            IT     ITERATION NUMBER. (INITIALIZED TO 1)
C            MAXIT  MAXIMUM NUMBER OF ITERATIONS
C            CURVLN LOGICAL VARIABLE: SET TRUE FOR CURVILINEAR LINE SEARCH
C            EXTRAP LOGICAL VARIABLE: SET TRUE BEFORE
C                   FUNCTION EVALUATION AT EXTRAPOLATED POINT.
C                   MUST BE SET FALSE IF EXTRAPOLATION IS
C                   REASONABLE.
C            GOODGR LOGICAL FLAG SET TRUE IF GOOD GRADIENTS ARE USED AT THE
C                   CURRENT POINT
C            KHNCHK LOGICAL FLAG SET TRUE TO PERMIT
C                   REDUCTION IN KUHN-TUCKER CONDITIONS WITHOUT IMPROVEMENT
C                   IN MERIT FUNCTION
C            IFUNER FUNCTION ERROR FLAG
C                   = 0    FUNCTION EVALUATED
C                   = 1    FUNCTION EVALUTION IMPOSSIBLE
C                   = 2    CONSTRAINT ELIMINATION IMPOSSIBLE
C                   .LT. 0 TERMINATE IMMEDIATELY
C            IOFLAG OUTPUT CONTROL FLAG
C                   =0   NO OUTPUT
C                   =10  NORMAL OUTPUT
C            IPU    OUTPUT UNIT NO.
C
C         OUTPUT:
C
C            TVEC   SECOND ORDER SEARCH CORRECTION VECTOR (NDIM)
C            UVEC   THIRD ORDER SEARCH CORRECTION VECTOR (NDIM)
C            FBAR   THE VALUE OF FBAR AT THE MINIMUM POINT
C            FXTRAP PREDICTED FUNCTION VALUE AT EXTRAPOLATED POINT
C            FREDUC FUNCTION REDUCTION, FBAR-F0
C            ALFA   THE OPTIMUM POINT
C            IT     ITERATION NUMBER
C            IFC    INTEGER VARIABLE:  IFC = 1 WHEN RETURNING TO THE
C                   CALLING ROUTINE TO EVALUATE FBAR(ALFA)
C                   IFC = 0 WHEN ALGORITHM TERMINATES
C            IERLIN INTEGER ERROR FLAG (MUST BE CHECKED WHEN IFC=0)
C                   = 0     NORMAL RETURN, WHEN IFC=0
C                   ----WARNING ERRORS
C                   = 1     NEGATIVE CURVATURE AT ALFA=0
C                   = 2     SMALL STEPS (ALFA*SNORM .LE. ZEROOT)
C                   = 3     MAXIMUM NUMBER OF FUNCTION ERRORS (MAXFER
C                           SET IN PARAMETER STATEMENT BELOW)
C                   = 4     LINEAR OBJECTIVE FUNCTION
C                   = 5     POSITIVE CURVATURE AT ALFA=0, CLIFF TERMINATION
C                   = 6     INTERPOLATION FAILED (SMALL STEPS)
C                   = 7     MAX. NUMBER OF F.E.
C                   ----FATAL ERRORS
C                   = -1    DF0 .GT. 0
C                   = -2    SLPTOL .GE. 1 .OR. SLPTOL .LE. REDTOL
C
C         INTERNAL: THE "SAVE" STATEMENT IS USED TO SAVE QUANTITIES FROM
C                   ITERATION TO ITERATION.  
C
      DIMENSION  ACMAT(2,2), ALPVEC(2), RHSVEC(2)
C
      COMMON /KONSTN/ 
     *  ZEROMN  ,ZEROOT  ,BIGNUM  ,BGROOT  ,BIGBND  ,BIGCND
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0,TWO=2.0D0,ONEEP3=1.0D3,
     $    ONEEM1=1.0D-1,ONEEM2=1.0D-2,ONEEM5=1.0D-5,POINT5=5.0D-1,
     $    THREE=3.0D0,SIX=6.0D0)
      PARAMETER (MAXFER=5,REDTOL=ONEEM5,CLFTOL=TWO)
      PARAMETER (MAXFEV=25,MXFEFR=MAXFEV+MAXFER)
      DIMENSION ALFAVC(MXFEFR),FUNMRT(MXFEFR),ALFOUT(MXFEFR)
     $    ,INDXVC(MXFEFR),NUMEVL(MXFEFR)
      CHARACTER(LEN=60) LYNEDY(MXFEFR)
      CHARACTER(LEN=60) BLANK,CHWORK
C
      DIMENSION VECP(NDIM),TVEC(NDIM),UVEC(NDIM),XBAR(NDIM),XVEC(NDIM)
     $    ,XOLD(NDIM)
      DIMENSION ALFMAT(2,2),ALFRHS(2),FCLOSE(3),ACLOSE(3)
      LOGICAL CLIFF,CUBPRF,CURVLN,EXTRAP,FIRCOR,FNDCLF,GOODGR,KHNCHK
      LOGICAL FUNCTN
      CHARACTER(LEN=16) MODEL,BSTMOD
      CHARACTER(LEN=14) LYNE
      CHARACTER(LEN=30) TYTLE
      DATA BLANK(1:60) / ' '/
C
C
C     ******************************************************************
C
      IF (IFC.EQ.1) THEN
        IF (IFESR.EQ.1) THEN
          GO TO 501
        ELSEIF (IFESR.EQ.2) THEN
          GO TO 502
        ENDIF
      ENDIF
C
C ----------------------------------------------------------------------
C
C         INITIALIZATION
C
      IERLIN = 0
      SMALTL = ONEEP3*ZEROMN
C
C         CHECK SLOPE CONDITIONS AT THE INITIAL POINT
C
      IF(.NOT.KHNCHK) THEN
        IF(DF0.GT.ZERO.AND.SNORM.GT.ZEROOT) THEN
          IF(GOODGR) THEN
            IERLIN = -1
          ELSE
            GOODGR = .TRUE.
          ENDIF
          RETURN
        ENDIF
      ENDIF
      IF(SLPTOL.GE.ONE.OR.SLPTOL.LE.REDTOL) THEN
        IERLIN = -2
        RETURN
      ENDIF
      MODEL(1:16) = 'Quadratic       '
      LYNE(1:14) = 'Line Search   '
      CLIFF = .FALSE.
      FNDCLF = .FALSE.
      FIRCOR = .TRUE.
      DO I=1,MAXFEV
        FUNMRT(I) = ZERO
        ALFAVC(I) = BIGNUM
      ENDDO
      NFEVAL = 1
      NUMEVL(NFEVAL) = NFEVAL
      ALFAVC(NFEVAL) = ZERO
      FUNMRT(NFEVAL) = F0
      FSML = F0
      FBAR = F0
      FBRLST = F0
      FREDUC = ZERO
      ALFLST = ZERO
      ALFEXT = ZERO
      ALFSML = ZERO
      BNDMAX = ONE
      BNDMIN = ZERO
      BRKUPR = BIGNUM
      BRKLWR = ZERO
      NUMUPR = 0
      NUMLWR = 0
C
C         COMPUTE SLOPE THAT DEFINES A "CLIFF"
C
      CLFSLP = MIN(-ONE,CLFTOL*DF0)
C
C         INITIALIZE QUADRATIC AND CUBIC ESTIMATES FOR MINIMUM VALUE
C
      FMIN2 = BIGNUM
      FMIN3 = BIGNUM
C
C         COMPUTE FUNCTION ERROR REDUCTION FACTOR
C
      RMAXFE = DBLE(MAXFER)
      REDFAC = POINT5*(ONE+RMAXFE)*RMAXFE
      REDFAC = EXP(LOG(ALFA/ZEROMN)/REDFAC)
C
C ----------------------------------------------------------------------
C
C         BEGIN ITERATION
C
 110  CONTINUE
C
C         SET EXTRAPOLATION FLAG AND COMPUTE EXTRAPOLATED FUNCTION
C
      EXTRAP = ALFA.GT.ALFEXT
      IF(EXTRAP) FXTRAP = F0 + (DF0 + POINT5*D2F0*ALFA)*ALFA
C
C         FUNCTION EVALUATION SEQUENCE
C
C
C         PRINT STEP LENGTH
C
      TYTLE(1:30) = MODEL(1:16)//LYNE(1:14)
      CALL HHCPRS(TYTLE,' ','.')
      IF(IOFLAG.GE.10) WRITE(IPU,1003) TYTLE(1:30),IT,ALFA
      IFC = 1
      IFESR = 1
C
C         RETURN FOR FUNCTION (AND GRADIENT) INFORMATION
C
      RETURN
 501  CONTINUE
C
C         THE FUNCTION HAS BEEN EVALUATED
C
      IFC = 0
C
C         SAVE EVALUATION INFORMATION
C
      NFEVAL = NFEVAL + 1
      NUMEVL(NFEVAL) = NFEVAL
C
      FUNCTN = .FALSE.
      IF(IFUNER.GT.0.OR.IFUNER.EQ.-100) THEN
        FUNCTN = .TRUE.
      ELSEIF((FBAR-FBRLST)*ZEROMN.GT.ONE) THEN
        FUNCTN = .TRUE.
      ENDIF
C
      IF(IFUNER.EQ.-100) THEN
C
        IERLIN = 7
        GO TO 210
C
      ELSEIF(FUNCTN) THEN
C
        ALFAVC(NFEVAL) = -ALFA
C
      ELSE
C
        INTHAV = 0
        FUNMRT(NFEVAL) = FBAR
        ALFAVC(NFEVAL) = ALFA
C
      ENDIF
C
C ----------------------------------------------------------------------
C
C         IF FUNCTION COULD NOT BE EVALUATED BYPASS FURTHER STEPS
C         IF FUNCTION INCREASED TOO MUCH RESPOND LIKE A FUNCTION ERROR
C
      IF(FUNCTN) THEN
C
C         >>> FUNCTION ERROR RESPONSE
C
        IF(IOFLAG.GE.10) WRITE(IPU,1001)
C
C         CONSTRAINT ELIMINATION FAILED--IF IFUNER = 1, A USER DEFINED
C         FUNCTION ERROR OCCURED;  RESPOND BY REDUCING BOTH THE STEP 
C         AND THE BOUND.  IF IFUNER = 2, THE CONSTRAINT ELIMINATION 
C         FAILED;  SINCE THIS IS A "SOFT" BOUND REDUCE THE STEP, BUT
C         DO NOT REDUCE THE BOUND, HOPING THAT A BETTER EXTRAPOLATION
C         MAY PERMIT SOLUTION OF THE CONSTRAINTS ON A LATER STEP.
C
        IF(FNDCLF) THEN
C
C         THIS IS THE SECOND ATTEMPT TO LOCATE THE CLIFF THAT FAILED.
C         IF THIS IS NOT THE FIRST ITERATION TERMINATE THE SEARCH 
C         IMMEDIATELY; OTHERWISE REDUCE THE STEP LIKE A STANDARD
C         FUNCTION ERROR, BUT DO NOT CHANGE THE UPPER BOUND
C
          IF(IT.GT.1) THEN
            CLIFF = .TRUE.
            GO TO 130
          ENDIF
C
        ELSE
C
C         THIS IS THE FIRST TIME THE POSSIBILITY OF A CLIFF IS DETECTED.
C         INITIATE THE CLIFF FINDING LOGIC BY SETTING FNDCLF = TRUE
C
          IF(CURVLN) FNDCLF = .TRUE.
C
        ENDIF
C
        INTHAV = INTHAV + 1
C
C         IF MAXIMUM NUMBER OF FUNCTION ERRORS, TERMINATE.
C
        IF(INTHAV.GE.MAXFER) THEN
          IERLIN = 3
          GO TO 210
        ENDIF
C
C         REDUCE STEP AND POSSIBLY THE UPPER BOUND
C
        RMX = ZERO
        BNDVAL = BIGNUM
        DO I = 1,NFEVAL
          IF(ALFAVC(I).GE.ZERO) THEN
            RMX = MAX(RMX,ALFAVC(I))
          ELSE
            BNDVAL = MIN(BNDVAL,-ALFAVC(I))
          ENDIF
        ENDDO
        MODEL(1:16) = 'Backtrack       '
        ALFA = RMX + (BNDVAL-RMX)/(REDFAC**INTHAV)
        GO TO 110
C 
C         >>> END OF FUNCTION ERROR RESPONSE
C
      ENDIF
C
C       IF EXTRAPOLATION WAS EXCESSIVE REPEAT WITH SMALLER STEP
C       (RESPOND LIKE A FUNCTION ERROR, EXCEPT DO NOT CHANGE BOUND)
C
      IF (EXTRAP.AND.IFUNER.GE.0.AND.NFEVAL.LT.MXFEFR) THEN
C
C           REDUCE STEP BUT DO NOT ALTER BOUND
C
        MODEL(1:16) = 'Backtrack       '
        ALFA = ONEEM1*ALFA
        GO TO 110
C
      ENDIF
C
C ----------------------------------------------------------------------
C
C         ITERATION PRINT
C
 130  CONTINUE
C
      IF(IFUNER.LE.0.AND.IFUNER.GT.-100) THEN
        FREDUC = FBAR - F0
        IF(IOFLAG.GE.10.AND..NOT.CLIFF) WRITE(IPU,1002) FBAR,FREDUC
      ENDIF
C
C         MAXIMUM ITERATION COUNT, STEPSIZE TOO SMALL, PREDICTED
C         CHANGE TOO SMALL, OR USER ABORT
C
      IF(IT.GE.MAXIT) GO TO 210
      IF(NFEVAL.GE.MAXFEV) GO TO 210
      IF(ABS(ALFA*SNORM).LT.SMALTL.AND.SNORM.GT.SMALTL) THEN
        IERLIN = 2
        GO TO 210
      ENDIF
C
C         SPECIAL TREATMENT AFTER A KUHN-TUCKER CHECK POINT
C
      IF(KHNCHK) THEN
        IF(IFUNER.LT.0) THEN
C
C         KUHN-TUCKER CONDITIONS SATISFIED--TERMINATE
C
          GO TO 210
C
        ELSE
C
C         CHECK SLOPE CONDITIONS 
C
          IF(DF0.GT.ZERO.AND.SNORM.GT.ZEROOT) THEN
            IF(GOODGR) THEN
              IERLIN = -1
              RETURN
            ELSE
              GOODGR = .TRUE.
              RETURN
            ENDIF
          ENDIF
        ENDIF
      ENDIF
C
C         CHECK IF THE CURRENT POINT IS A CLIFF 
C
      IF(CLIFF) THEN
C
C         TERMINATE SEARCH ON THE CLIFF
C
        ALFA = ALFLST
        GO TO 210
C
      ENDIF
C
C ----------------------------------------------------------------------
C
C         SAVE THE FUNCTION VALUES, AND SORT THE DATA TO CONSTRUCT
C         THE ARRAY OF FUNCTION VALUES CLOSEST TO THE MINIMUM POINT.
C         ALSO DEFINE AND/OR ADJUST THE BOUNDS (BNDMAX AND BNDMIN) TO
C         BRACKET THE MINIMUM
C
C
C         SORT ALFAVC ARRAY INTO ASCENDING ORDER
C
      CALL HDSRTN(ALFAVC,MAXFEV,0,1,INDXVC,IERSRT)
C
C         PERMUTE FUNMRT ARRAY INTO THE SAME ORDER
C
      CALL HDPRMX(FUNMRT,MAXFEV,INDXVC,IERSRT)
C
C         PERMUTE NUMEVL ARRAY INTO THE SAME ORDER
C
      CALL HJPRMX(NUMEVL,MAXFEV,INDXVC,IERSRT)
C
C         SCAN THE FUNCTION ARRAY TO COMPUTE:
C         (A) THE CONVEX REGION CLOSEST TO ZERO
C         (B) THE SMALLEST FUNCTION VALUE
C         (C) THE FUNCTION ERROR BOUND
C
C         THE CONVEX REGION IS CENTERED ABOUT "LOWEST", I.E.
C           FUNMRT(LOWEST-1) .GE. FUNMRT(LOWEST) .LE. FUNMRT(LOWEST+1)
C
C         THE SMALLEST FUNCTION VALUE IS FUNMRT(LSMALL), I.E.
C           FUNMRT(LSMALL) = MIN (FUNMRT(I))
C
C         THE FUNCTION IS COMPUTABLE FOR
C           0 .LE. ALFA .LE. FUNBND
C
      FUNBND = BIGNUM
      LOWEST = 0
      LSMALL = 0
      LFNBND = 0
      BNDMIN = ZERO
      BNDMAX = BIGNUM
      DO I = 1,MAXFEV-2
C
        IF(ALFAVC(I).GE.ZERO) THEN
C
          IF(ALFAVC(I+1).LT.BIGNUM.AND.ALFAVC(I+2).LT.BIGNUM) THEN
            IF(FUNMRT(I).GE.FUNMRT(I+1).AND.
     $       FUNMRT(I+1).LE.FUNMRT(I+2).AND.LOWEST.EQ.0) THEN
              LOWEST = I+1
              BNDMIN = ALFAVC(LOWEST-1)
              BNDMAX = ALFAVC(LOWEST+1)
            ENDIF
          ENDIF
C
        ELSE
C
          FUNBND = MIN(FUNBND,-ALFAVC(I))
          LFNBND = I
C
        ENDIF
C
      ENDDO
C
C         LCFZER = LOCATION OF F(0) IN FUNMRT ARRAY
C
      LCFZER = LFNBND + 1
C
      FSMALL = BIGNUM
      DO I = LCFZER,NFEVAL
        IF(FUNMRT(I).LT.FSMALL) THEN
          FSMALL = FUNMRT(I)
          LSMALL = I
        ENDIF
      ENDDO
C
C         CHECK FOR FUNCTION ERROR "HOLES"
C
      IF(ALFAVC(NFEVAL).GT.FUNBND) THEN
        IF(IOFLAG.GE.10) WRITE(IPU,1010) FUNBND
      ENDIF
C
C         CONSTRUCT BOUND ON COMPUTABLE REGION
C
      BNDALF = MIN(ONE,BNDMAX,FUNBND)
C
      BSTMOD = MODEL
C
      IF (IT.EQ.1) THEN
C
C          SAVE SMALLEST FBAR
C
        ALFSML = ALFAVC(LSMALL)
        FSML = FUNMRT(LSMALL)
C
C         SAVE CLOSEST FUNCTION VALUE ARRAYS
C
        ITP1 = IT + 1
        DO I=1,ITP1
          ACLOSE(I) = ALFAVC(LCFZER+I-1)
          FCLOSE(I) = FUNMRT(LCFZER+I-1)
        ENDDO
C
      ELSEIF (IT.EQ.2) THEN
C
C         SAVE FUNCTION VALUES FOR CLOSEST FIT QUADRATIC MODEL
C
        ITP1 = IT + 1
        DO I=1,ITP1
          ACLOSE(I) = ALFAVC(LCFZER+I-1)
          FCLOSE(I) = FUNMRT(LCFZER+I-1)
        ENDDO
C
C         COMPUTE SMALLEST FBAR AND SAVE CORRESPONDING ALFA.
C
        ALFSML = ALFAVC(LSMALL)
        FSML = FUNMRT(LSMALL)
C
C         DEFINE CUBIC INTERPOLANT VALUES
C
        ACUBE1 = ACLOSE(2)
        FCUBE1 = FCLOSE(2)
        ACUBE2 = ACLOSE(3)
        FCUBE2 = FCLOSE(3)
C
      ELSE
C
C         ITERATIONS GREATER THAN 2.
C
        IF(LOWEST.GT.0) THEN
          IF(FUNMRT(LOWEST).LE.F0) THEN
C
C         OPTIMAL POINT IS BRACKETED AND SMALLER THAN F(0)
C
            FCLOSE(1:3) = FUNMRT(LOWEST-1:LOWEST+1)
            ACLOSE(1:3) = ALFAVC(LOWEST-1:LOWEST+1)
            ALFSML = ALFAVC(LOWEST)
            FSML = FUNMRT(LOWEST)
            IF(ACLOSE(3).EQ.BRKUPR) THEN
              NUMUPR = NUMUPR + 1
            ELSE
              BRKUPR = ACLOSE(3)
              NUMUPR = 1
            ENDIF
            IF(ACLOSE(1).EQ.BRKLWR.AND.ACLOSE(1).GT.ZERO) THEN
              NUMLWR = NUMLWR + 1
            ELSE
              BRKLWR = ACLOSE(1)
              NUMLWR = 1
            ENDIF
          ENDIF
C
        ELSE
C
C         OPTIMAL POINT IS NOT BRACKETED
C
          LCLOWR = MAX(LCFZER,LSMALL-2)
          FCLOSE(1:3) = FUNMRT(LCLOWR:LCLOWR+2)
          ACLOSE(1:3) = ALFAVC(LCLOWR:LCLOWR+2)
          ALFSML = ALFAVC(LSMALL)
          FSML = FUNMRT(LSMALL)
C
        ENDIF
C
C         DEFINE CUBIC INTERPOLANT VALUES; INCLUDE THE BEST POINT
C         AND THE NEXT CLOSEST POINT TO GET LOCAL INFORMATION
C
        IF(ACLOSE(1).GT.ZERO) THEN
          IF(ALFSML.NE.ACLOSE(1)) THEN
            IF((ACLOSE(3)-ALFSML).LT.(ALFSML-ACLOSE(1))) THEN
              ACUBE1 = ACLOSE(2)
              FCUBE1 = FCLOSE(2)
              ACUBE2 = ACLOSE(3)
              FCUBE2 = FCLOSE(3)
            ELSE
              ACUBE1 = ACLOSE(1)
              FCUBE1 = FCLOSE(1)
              ACUBE2 = ACLOSE(2)
              FCUBE2 = FCLOSE(2)
            ENDIF
          ELSE
            ACUBE1 = ACLOSE(1)
            FCUBE1 = FCLOSE(1)
            ACUBE2 = ACLOSE(2)
            FCUBE2 = FCLOSE(2)
          ENDIF
        ELSE
          ACUBE1 = ACLOSE(2)
          FCUBE1 = FCLOSE(2)
          ACUBE2 = ACLOSE(3)
          FCUBE2 = FCLOSE(3)
        ENDIF
C
      ENDIF
C
      IF(CURVLN) THEN
C
C ----------------------------------------------------------------------
C
C         UPDATE SEARCH CORRECTION VECTORS TVEC AND UVEC FROM THE CURRENT
C         INFORMATION
C
        IF(FIRCOR) THEN
C
C         FIRST CORRECTION
C
          FIRCOR = .FALSE.
C
          ALFSQR = ALFA**2
          DO I = 1,NDIM
            TVEC(I) = (XBAR(I) - XVEC(I) - ALFA*VECP(I))/ALFSQR
          ENDDO
C
        ELSE
C
C         SUBSEQUENT CORRECTIONS
C
          DENOM = ALFLST - ALFA
          ALFMAT(1,1) = ALFLST/(DENOM*ALFA**2)
          ALFMAT(1,2) = -ALFA/(DENOM*ALFLST**2)
          ALFMAT(2,1) = -ONE/(DENOM*ALFA**2)
          ALFMAT(2,2) = ONE/(DENOM*ALFLST**2)
C
C         COMPUTE THE SOLUTION FOR ALL RIGHT HAND SIDES 
C
          DO I = 1,NDIM
C
C         DEFINE RIGHT HAND SIDE
C
            ALFRHS(1) = XBAR(I) - XVEC(I) - ALFA*VECP(I)
            ALFRHS(2) = XOLD(I) - XVEC(I) - ALFLST*VECP(I)
C
C         STORE THE SOLUTION INTO TVEC AND UVEC
C
            TVEC(I) = ALFMAT(1,1)*ALFRHS(1) + ALFMAT(1,2)*ALFRHS(2)
            UVEC(I) = ALFMAT(2,1)*ALFRHS(1) + ALFMAT(2,2)*ALFRHS(2)
C
          ENDDO
C
        ENDIF
C
C ----------------------------------------------------------------------
C
      ENDIF
C
C         COMPUTE FOUR QUANTITIES:
C
C         (1) A NEW ESTIMATE OF THE LOCATION OF THE MINIMUM
C         (2) AN ESTIMATE OF THE SLOPE AT THE CURRENT POINT
C         (3) AN ESTIMATE OF THE PREDICTED OBJECTIVE FUNCTION
C         (4) AN ESTIMATE OF THE CURVATURE AT ALFA=0
C
C         COMPUTE BRACKET BISECTION POINT FOR USE WHEN POLYNOMIAL
C         MODELS FAIL.
C
      IF(FNDCLF.AND.ALFSML.GT.ZERO) THEN
C
        BISECT = MIN(TWO*ALFSML,POINT5*(BNDALF+ALFSML))
C
      ELSEIF(LOWEST.GT.0) THEN
        IF(FUNMRT(LOWEST).LE.F0) THEN
C
C       OPTIMUM IS BRACKETED--BISECT THE LARGEST INTERVAL IN THE 
C       BRACKETED REGION
C
          BISINT = ZERO
          DO I = LOWEST-1,LOWEST
            BINTRV = ALFAVC(I+1) - ALFAVC(I)
            IF(BINTRV.GT.BISINT) THEN
              BISINT = BINTRV
              BISECT = POINT5*(ALFAVC(I+1)+ALFAVC(I))
            ENDIF
          ENDDO
C
        ELSE
C
C       FUNCTION VALUE AT THE CENTER OF THE CONVEX REGION IS NOT AN
C       IMPROVED POINT--STEP BACK TO THE ORIGIN
C
          BISECT = ONEEM1*ALFAVC(LCFZER+1)
C       
        ENDIF
C
      ELSE
C
C       OPTIMUM IS NOT BRACKETED--IF THE SMALLEST CURRECT VALUE
C       IS AT ZERO, THEN STEP BACK TO THE ORIGIN.  IF THE SMALLEST
C       VALUE IS NOT AT THE ORIGIN THEN PLACE BISECTION POINT IN THE
C       LARGEST INTERVAL (WITH TIES FAVORING THE LEFTMOST)
C
        IF(LSMALL.EQ.LCFZER) THEN
          BISECT = ONEEM1*ALFAVC(LCFZER+1)
        ELSE
          BISINT = ZERO
          DO I = LCFZER,NFEVAL-1
            BINTRV = ALFAVC(I+1) - ALFAVC(I)
            IF(BINTRV.GT.BISINT) THEN
              BISINT = BINTRV
              BISECT = POINT5*(ALFAVC(I+1)+ALFAVC(I))
            ENDIF
          ENDDO
          IF(FUNBND.GT.ALFAVC(NFEVAL).AND.FUNBND.LT.BIGNUM) THEN
            BINTRV = FUNBND - ALFAVC(NFEVAL)
            IF(BINTRV.GT.BISINT) THEN
              BISINT = BINTRV
              BISECT = POINT5*(FUNBND+ALFAVC(NFEVAL))
            ENDIF
          ENDIF
        ENDIF
C
      ENDIF
C
C         COMPARE CURRENT FUNCTION VALUE WITH PREDICTED VALUES
C         FROM THE PREVIOUS ITERATION, IN ORDER TO ESTABLISH A 
C         PREFERRED MODEL FOR THIS ITERATION
C
      IF(ABS(FBAR-FMIN2).LT.ABS(FBAR-FMIN3)) THEN
        CUBPRF = .FALSE.
      ELSE
        CUBPRF = .TRUE.
      ENDIF
C
C         COMPUTE SMALLEST CONTRACTION LIMIT FOR ALFA
C
      ALFLMT = BNDMIN + ONEEM2*ALFA
C
C         A PREFERRED MODEL HAS BEEN DETERMINED FOR THIS ITERATION.
C         CLEAN UP THE PREDICTIONS TO GET READY FOR NEXT ITERATION.
C         FMIN2 = SECOND ORDER ESTIMATE OF OBJECTIVE
C         FMIN3 = THIRD ORDER ESTIMATE OF OBJECTIVE
C         FPQUAD = SLOPE OF QUADRATIC MODEL AT CURRENT POINT
C         FPCUBE = SLOPE OF CUBIC MODEL AT CURRENT POINT
C
      FMIN2 = BIGNUM
      FMIN3 = BIGNUM
      FPQUAD = BIGNUM
      FPCUBE = BIGNUM
C
      IF (IT.GE.2) THEN
C
C         IF ONE OF THE BOUNDS HAS NOT CHANGED FOR THREE ITERATIONS
C         INCREASE (OR DECREASE) THE POLYNOMIAL PREDICTION TO ACCELERATE
C         TOWARD THE BOUND
C
        POLYFC = ONE
        IF(NUMUPR.GE.3) POLYFC = TWO**(NUMUPR-1)
        IF(NUMLWR.GE.3) POLYFC = ONE/TWO**(NUMLWR-1)
C
C         QUADRATIC MODEL FOR CLUSTERED POINTS (EXPAND ABOUT ACLOSE(1))
C
        RHSVEC(1) = FCLOSE(2) - FCLOSE(1)
        RHSVEC(2) = FCLOSE(3) - FCLOSE(1)
        ACMAT(1,1) = ACLOSE(2) - ACLOSE(1)
        ACMAT(1,2) = ACMAT(1,1)**2
        ACMAT(2,1) = ACLOSE(3) - ACLOSE(1)
        ACMAT(2,2) = ACMAT(2,1)**2
C
        CALL TWOSLV(ACMAT,RHSVEC,ALPVEC,IERSLV)
C
        IF(IERSLV.EQ.0) THEN
          DF1C = ALPVEC(1)
          D2F1C= TWO*ALPVEC(2)
        ELSE
          IERLIN = 6
          GO TO 210
        ENDIF
        DELALF = ALFA - ACLOSE(1)
C
C         CUBIC FIT COEFFICIENTS
C
        RHSVEC(1) = FCUBE1 - F0 - DF0*ACUBE1
        RHSVEC(2) = FCUBE2 - F0 - DF0*ACUBE2
        ACMAT(1,2) = ACUBE1**2
        ACMAT(1,1) = ACMAT(1,2)*ACUBE1
        ACMAT(2,2) = ACUBE2**2
        ACMAT(2,1) = ACMAT(2,2)*ACUBE2
C
        CALL TWOSLV(ACMAT,RHSVEC,ALPVEC,IERSLV)
C
        IF(IERSLV.EQ.0) THEN
          ACUBE = ALPVEC(1)
          BCUBE = ALPVEC(2)
        ELSE
          IERLIN = 6
          GO TO 210
        ENDIF
C
C         SLOPE OF CUBIC MODEL AT CURRENT POINT
C
        FPCUBE = DF0 + (TWO*BCUBE + THREE*ACUBE*ALFA)*ALFA
C
C         SLOPE OF CLUSTERED QUADRATIC MODEL AT CURRENT POINT
C
        FPQUAD = DF1C + D2F1C*DELALF
C
        IF (ABS(BCUBE) .GT. SQRT(HDMCON(3)) .OR. 
     *     ABS(ACUBE) .GT. (HDMCON(3)/THREE)/MAX(1.0D0, ABS(DF0))) THEN 
           DISCR = -1.0D0
        ELSE
           DISCR = BCUBE**2 - THREE*ACUBE*DF0
        ENDIF
C
C         CHECK DISCRIMINANT OF QUADRATIC (DERIVATIVE OF CUBIC 
C         INTERPOLANT) FOR THE EXISTENCE OF MINIMIZING ROOTS
C
        IF(DISCR.GE.ZERO) THEN
C
          IF(ABS(ACUBE).GT.ZEROMN) THEN
C
C         LEGITIMATE CUBIC MINIMIZER
C
            P3ALF = (-BCUBE + SQRT(DISCR))/(THREE*ACUBE)
C 
          ELSE
C
C         CUBIC IS A QUADRATIC
C
            P3ALF = -DF0/(TWO*BCUBE)
C
          ENDIF
C
C         BOTH QUADRATIC AND CUBIC MODELS WILL PREDICT A POSSIBLE
C         MINIMUM.  COMPUTE PREDICTION BASE ON PREFERRED MODEL
C
          IF(CUBPRF) THEN
C
C         ---CUBIC IS THE PREFERRED MODEL
C
C         FIRST CHECK TO SEE IF CUBIC PREDICTION LIES WITHIN BOUNDS
C         IF SO USE IT.  IF THAT FAILS, TRY TO USE THE CLUSTER QUADRATIC.
C         IF THAT ALSO FAILS, AND THE CLIFF FINDING LOGIC IS IN AFFECT
C         TRY TO LOCATE THE CLIFF.  IF ALL OF THE STRATEGIES FAIL TO 
C         PRODUCE A POINT WITHIN THE BOUNDS RESORT TO BISECTION.
C
            IF(BNDMIN.LT.P3ALF.AND.P3ALF.LT.BNDALF) THEN
              MODEL(1:16) = 'Cubic           '
              ALFMIN = MAX(ALFLMT,P3ALF)
              IF(FNDCLF.AND.ALFSML.GT.ZERO) ALFMIN = 
     $                         MIN(ALFMIN,TWO*ALFSML)
              D2F0 = TWO*BCUBE
            ELSEIF(D2F1C.GT.ZEROMN) THEN
              P2ALF = ACLOSE(1) - POLYFC*DF1C/D2F1C
              IF(BNDMIN.LT.P2ALF.AND.P2ALF.LT.BNDALF) THEN
                MODEL(1:16) = 'Quadratic       '
                ALFMIN = MAX(ALFLMT,P2ALF)
                IF(FNDCLF.AND.ALFSML.GT.ZERO) ALFMIN = 
     $                           MIN(ALFMIN,TWO*ALFSML)
                D2F0 = D2F1C
              ELSE
                ALFMIN = BISECT
                D2F0 = TWO*BCUBE
              ENDIF
            ELSEIF(FNDCLF) THEN
              DISCL = BCUBE**2 - THREE*ACUBE*(DF0 - CLFSLP)
              IF(DISCL.GE.ZERO.AND.ABS(ACUBE).GT.ZEROMN) THEN
                MODEL(1:16) = 'Cubic Cliff     '
                ALFMIN = (-BCUBE - SQRT(DISCL))/(THREE*ACUBE)
                IF(ALFMIN.LE.BNDMIN.OR.ALFMIN.GE.BNDALF) ALFMIN = BISECT
                D2F0 = TWO*BCUBE
              ELSEIF(D2F1C.LT.-ZEROMN) THEN
                MODEL(1:16) = 'Quadratic Cliff '
                ALFMIN = ACLOSE(1) + (CLFSLP - DF1C)/D2F1C
                IF(ALFMIN.LE.BNDMIN.OR.ALFMIN.GE.BNDALF) ALFMIN = BISECT
                D2F0 = D2F1C
              ELSE
                ALFMIN = BISECT
                D2F0 = TWO*BCUBE
              ENDIF
            ELSE
              ALFMIN = BISECT
              D2F0 = TWO*BCUBE
            ENDIF
C
          ELSE
C
C         ---QUADRATIC IS THE PREFERRED MODEL
C
C         FIRST CHECK TO SEE IF QUADRATIC PREDICTION LIES WITHIN BOUNDS;
C         IF SO USE IT.  IF THAT FAILS, TRY CUBIC MODEL AND IF THAT ALSO
C         FAILS TO PREDICT A POINT WITHIN BOUNDS SEE IF CLIFF FINDING
C         LOGIC IS ACTIVE.  IF SO, ATTEMPT TO LOCATE A CLIFF, AND IF IT 
C         ALSO LIES OUTSIDE OF BOUNDS USE BISECTION
C
            IF(D2F1C.GT.ZEROMN) THEN
              P2ALF = ACLOSE(1) - POLYFC*DF1C/D2F1C
              IF(BNDMIN.LT.P2ALF.AND.P2ALF.LT.BNDALF) THEN
                MODEL(1:16) = 'Quadratic       '
                ALFMIN = MAX(ALFLMT,P2ALF)
                IF(FNDCLF.AND.ALFSML.GT.ZERO) ALFMIN = 
     $                           MIN(ALFMIN,TWO*ALFSML)
                D2F0 = D2F1C
              ELSE
                ALFMIN = BISECT
                D2F0 = TWO*BCUBE
              ENDIF
            ELSEIF(BNDMIN.LT.P3ALF.AND.P3ALF.LT.BNDALF) THEN
              MODEL(1:16) = 'Cubic           '
              ALFMIN = MAX(ALFLMT,P3ALF)
              IF(FNDCLF.AND.ALFSML.GT.ZERO) ALFMIN = 
     $                         MIN(ALFMIN,TWO*ALFSML)
              D2F0 = TWO*BCUBE
            ELSEIF(FNDCLF) THEN
              DISCL = BCUBE**2 - THREE*ACUBE*(DF0 - CLFSLP)
              IF(D2F1C.LT.ZEROMN) THEN
                MODEL(1:16) = 'Quadratic Cliff '
                ALFMIN = ACLOSE(1) + (CLFSLP - DF1C)/D2F1C
                IF(ALFMIN.LE.BNDMIN.OR.ALFMIN.GE.BNDALF) ALFMIN = BISECT
                D2F0 = D2F1C
              ELSEIF(DISCL.GE.ZERO.AND.ABS(ACUBE).GT.ZEROMN) THEN
                MODEL(1:16) = 'Cubic Cliff     '
                ALFMIN = (-BCUBE - SQRT(DISCL))/(THREE*ACUBE)
                IF(ALFMIN.LE.BNDMIN.OR.ALFMIN.GE.BNDALF) ALFMIN = BISECT
                D2F0 = TWO*BCUBE
              ELSE
                ALFMIN = BISECT
                D2F0 = TWO*BCUBE
              ENDIF
            ELSE
              ALFMIN = BISECT
              D2F0 = TWO*BCUBE
            ENDIF
C
          ENDIF
C
        ELSE
C
C         CUBIC MODEL HAS NO LOCAL MINIMIZER--TRY CLUSTERED QUADRATIC,
C         AND IF THAT FAILS RESORT TO BISECTION
C
          IF(D2F1C.GT.ZEROMN) THEN
            P2ALF = ACLOSE(1) - POLYFC*DF1C/D2F1C
            IF(BNDMIN.LT.P2ALF.AND.P2ALF.LT.BNDALF) THEN
              MODEL(1:16) = 'Quadratic       '
              ALFMIN = MAX(ALFLMT,P2ALF)
              IF(FNDCLF.AND.ALFSML.GT.ZERO) ALFMIN = 
     $                         MIN(ALFMIN,TWO*ALFSML)
              D2F0 = D2F1C
            ELSE
              ALFMIN = BISECT
              D2F0 = TWO*BCUBE
            ENDIF
          ELSEIF(FNDCLF) THEN
            IF(CUBPRF) THEN
              DISCL = BCUBE**2 - THREE*ACUBE*(DF0 - CLFSLP)
              IF(DISCL.GE.ZERO.AND.ABS(ACUBE).GT.ZEROMN) THEN
                MODEL(1:16) = 'Cubic Cliff     '
                ALFMIN = (-BCUBE - SQRT(DISCL))/(THREE*ACUBE)
                IF(ALFMIN.LE.BNDMIN.OR.ALFMIN.GE.BNDALF) ALFMIN = BISECT
                D2F0 = TWO*BCUBE
              ELSEIF(D2F1C.LT.ZEROMN) THEN
                MODEL(1:16) = 'Quadratic Cliff '
                ALFMIN = ACLOSE(1) + (CLFSLP - DF1C)/D2F1C
                IF(ALFMIN.LE.BNDMIN.OR.ALFMIN.GE.BNDALF) ALFMIN = BISECT
                D2F0 = D2F1C
              ELSE
                ALFMIN = BISECT
                D2F0 = TWO*BCUBE
              ENDIF
            ELSE
              DISCL = BCUBE**2 - THREE*ACUBE*(DF0 - CLFSLP)
              IF(D2F1C.LT.-ZEROMN) THEN
                MODEL(1:16) = 'Quadratic Cliff '
                ALFMIN = ACLOSE(1) + (CLFSLP - DF1C)/D2F1C
                IF(ALFMIN.LE.BNDMIN.OR.ALFMIN.GE.BNDALF) ALFMIN = BISECT
                D2F0 = D2F1C
              ELSEIF(DISCL.GE.ZERO.AND.ABS(ACUBE).GT.ZEROMN) THEN
                MODEL(1:16) = 'Cubic Cliff     '
                ALFMIN = (-BCUBE - SQRT(DISCL))/(THREE*ACUBE)
                IF(ALFMIN.LE.BNDMIN.OR.ALFMIN.GE.BNDALF) ALFMIN = BISECT
                D2F0 = TWO*BCUBE
              ELSE
                ALFMIN = BISECT
                D2F0 = TWO*BCUBE
              ENDIF
            ENDIF
          ELSE
            ALFMIN = BISECT
            D2F0 = TWO*BCUBE
          ENDIF
C
        ENDIF
C
C         COMPUTE QUADRATIC AND CUBIC PREDICTIONS FOR THE VALUE OF 
C         THE OBJECTIVE AT ALFMIN
C
        ALFSTP = ALFMIN - ACLOSE(1)
        FMIN2 = FCLOSE(1) + (DF1C + POINT5*D2F1C*ALFSTP)*ALFSTP
        FMIN3 = F0 + (DF0 + (BCUBE + ACUBE*ALFMIN)*ALFMIN)*ALFMIN
C
      ELSE
C
C         QUADRATIC FIT COEFFICIENTS (EXPAND ABOUT ALFA=0)
C
        D2F0 = TWO*(FBAR - F0 - DF0*ALFA)/ALFA**2
C
C         SLOPE OF MODEL AT CURRENT POINT
C
        FPQUAD = D2F0*ALFA + DF0
C
        IF(D2F0.GT.ZEROMN) THEN
          MODEL(1:16) = 'Quadratic       '
          ALFMIN = MAX(ALFLMT,-DF0/D2F0)
          IF(FNDCLF.AND.ALFSML.GT.ZERO) ALFMIN = 
     $                          MIN(ALFMIN,TWO*ALFSML)
          IF(ALFMIN.LE.BNDMIN.OR.ALFMIN.GE.BNDALF) ALFMIN = BISECT
        ELSEIF(FNDCLF) THEN
          IF(D2F0.LT.ZEROMN) THEN
            MODEL(1:16) = 'Quadratic Cliff '
            ALFMIN = (CLFSLP - DF0)/D2F0
            IF(ALFMIN.LE.BNDMIN.OR.ALFMIN.GE.BNDALF) ALFMIN = BISECT
          ELSE
            ALFMIN = BISECT
          ENDIF
        ELSE
          MODEL(1:16) = 'Backtrack       '
          ALFMIN = ONEEM1*ALFA
        ENDIF
C
C         PREDICTED MINIMUM VALUE
C
        FMIN2 = F0 + (DF0 + POINT5*D2F0*ALFMIN)*ALFMIN
C
C         SET MINIMUM VALUE ESTIMATE SO THAT CUBIC WILL BE THE 
C         PREFERRED MODEL FOR THE NEXT ITERATION
C
        FMIN3 = FMIN2
C
      ENDIF
C
      IF(ALFMIN.EQ.BISECT) MODEL(1:16) = 'Bisection       '
C
C         DIAGNOSTIC OUTPUT
C
      IF(IOFLAG.GE.20) THEN
        DO II = 1,NFEVAL
          LYNEDY(II) = BLANK
          WRITE(LYNEDY(II)(2:3),'(I2)') NUMEVL(II)
          ALFOUT(II) = ABS(ALFAVC(II))
          IF(ALFAVC(II).LT.ZERO) THEN
            WRITE(LYNEDY(II)(10:26),'(1PE16.6)') ABS(ALFAVC(II))
            LYNEDY(II)(30:46) = '        ---     '
          ELSE
            WRITE(LYNEDY(II)(10:26),'(1PE16.6)') ALFAVC(II)
            WRITE(LYNEDY(II)(30:46),'(1PE16.6)') FUNMRT(II)-F0
            IF(II.EQ.LSMALL) LYNEDY(II)(47:47) = '<'
            IF(II.EQ.LOWEST) LYNEDY(II)(47:47) = '*'
          ENDIF
        ENDDO
C
        CALL HDSRTN(ALFOUT,NFEVAL,0,1,INDXVC,IERSRT)
        CALL HHPRMX(LYNEDY,NFEVAL,INDXVC,CHWORK,IERSRT)
C
        WRITE(IPU,1007)
        CHWORK = BLANK
        CHWORK(1:4) = 'Eval'
        CHWORK(18:21) = 'alfa'
        CHWORK(34:45) = 'f(alfa)-f(0)'
        WRITE(IPU,1011) CHWORK
        WRITE(IPU,1011) (LYNEDY(II),II = 1,NFEVAL)
        WRITE(IPU,1007)
        WRITE(IPU,1006) 'f''',ZERO,DF0,'f''''',ZERO,D2F0
        WRITE(IPU,1006) 'f2''',ALFA,FPQUAD,'f3''',ALFA,FPCUBE
        WRITE(IPU,1007)
      ENDIF
C
C ----------------------------------------------------------------------
C
C         CONVERGENCE TESTS
C
      IF(FREDUC.LT.REDTOL*ALFA*DF0) THEN
C
C         SATISFACTORY REDUCTION IN THE OBJECTIVE
C         CHECK SLOPE CONDITION
C
        FPRIME = MIN(ABS(FPQUAD),ABS(FPCUBE))
C
C         LINE SEARCH MINIMUM RESOLUTION
C
        RESALF = ONEEM1*SNORM*MIN(ONE,ABS(BNDALF-BNDMIN))
C
        IF(FPRIME.LE.-SLPTOL*DF0.AND.FBAR.EQ.FSML) THEN
C
C         NORMAL TERMINATION
C
          IF(D2F0.LT.ZEROMN) IERLIN = 1
          GO TO 210
C
        ELSEIF(ALFA.EQ.ONE) THEN
C
          FPRIME = MIN(FPQUAD,FPCUBE)
          IF(FPRIME.LE.SLPTOL*DF0.AND.FBAR.EQ.FSML) THEN
C
C         NORMAL TERMINATION ON UPPER BOUND
C
            IF(D2F0.LT.ZEROMN) IERLIN = 1
            GO TO 210
C
          ENDIF
C
        ELSEIF(RESALF.LT.ZEROOT) THEN
C
C         MINIMUM STEP RESOLUTION TERMINATION
C
          IF(D2F0.LT.ZEROMN) IERLIN = 1
C
C         QUADRATIC MODEL FOR CLOSEST POINTS (EXPAND ABOUT FIRST NON-NEGATIVE ALFA)
C
          ALFALOOP: DO KK = 1,MXFEFR
            IF(ALFAVC(KK).LT.ZERO) THEN
              CYCLE ALFALOOP
            ELSE
              LCALF1 = KK
              EXIT ALFALOOP
            ENDIF
          ENDDO ALFALOOP
          LCALF2 = LCALF1 + 1
          LCALF3 = LCALF2 + 1
C
          RHSVEC(1) = FUNMRT(LCALF2) - FUNMRT(LCALF1)
          RHSVEC(2) = FUNMRT(LCALF3) - FUNMRT(LCALF1)
          ACMAT(1,1) = ALFAVC(LCALF2) - ALFAVC(LCALF1)
          ACMAT(1,2) = ACMAT(1,1)**2
          ACMAT(2,1) = ALFAVC(LCALF3) - ALFAVC(LCALF1)
          ACMAT(2,2) = ACMAT(2,1)**2
C
          CALL TWOSLV(ACMAT,RHSVEC,ALPVEC,IERSLV)
C
          IF(IERSLV.EQ.0) THEN
            DF1CHK = ALPVEC(1)
            D2F1CK = TWO*ALPVEC(2)
          ELSE
            IERLIN = 6
            GO TO 210
          ENDIF
          IF(IOFLAG.GE.10) WRITE(IPU,1004) DF0-DF1CHK
          GO TO 210
C
        ELSEIF(FNDCLF) THEN
C
          FPRIME = MIN(FPQUAD,FPCUBE)
          IF(FPRIME.LE.CLFSLP) THEN
C
C         TERMINATE ON A CLIFF
C
            IERLIN = 5
            GO TO 210
C
          ENDIF
C
        ENDIF
C
      ELSEIF(FREDUC.LT.SMALTL.AND.SNORM.LT.ZEROOT) THEN
C
C         SPECIAL TEST FOR ZERO LENGTH SEARCH DIRECTION
C
        IF(D2F0.LT.ZEROMN) IERLIN = 1
        GO TO 220
C
      ENDIF
C
C ----------------------------------------------------------------------
C
C         UPDATE ALL INFORMATION PRIOR TO THE NEXT STEP
C
C         SAVE XBAR IN XOLD
C
      XOLD(1:NDIM) = XBAR(1:NDIM)
C
C         SAVE LAST VALUE OF ALFA AND FBAR
C
      FBRLST = FBAR
      ALFLST = ALFA
C
C         FUNCTION WAS EVALUATED;  UPDATE EXTRAPOLATION STEP LENGTH
C
      ALFEXT = MAX(ALFEXT,ALFA)
C
C         DEFINE NEW STEP LENGTH, ALFA
C
      ALFA = ALFMIN
C
      IT = IT + 1
C
C         END OF ITERATION
C
      GO TO 110
C
C ----------------------------------------------------------------------
C
C         TERMINATION PROCEDURES
C
 210  CONTINUE
C
C         ERROR RETURN FOR LINEAR OBJECTIVE FUNCTIONS
C
      IF (ABS(D2F0).LT.ONEEP3*ZEROMN*ABS(DF0).AND.SNORM.GT.ZERO) THEN
        IERLIN = 4
        IF (IOFLAG.GE.10) WRITE(IPU,1008)
      ENDIF
C 
      IF( (IFUNER.EQ.0.AND.FBAR.LE.FSML.AND.INTHAV.LE.MAXFER)
     $  .OR.IFUNER.LT.0) GO TO 220
C
C             REEVALUATE FBAR AT SMALLEST VALUE.
C
      ALFA = ALFSML
C
C         PRINT STEP LENGTH
C
      IF (IOFLAG.GE.20) WRITE(IPU,1009)
      TYTLE(1:30) = BSTMOD(1:16)//LYNE(1:14)
      CALL HHCPRS(TYTLE,' ','.')
      IF(IOFLAG.GE.10) WRITE(IPU,1003) TYTLE(1:30),IT,ALFA
C
      IFC = 1
      IFESR = 2
      RETURN
C
 502  CONTINUE
      IFC = 0
      FREDUC = FBAR - F0
      IF(IOFLAG.GE.10) WRITE(IPU,1002) FBAR,FREDUC
C
 220  CONTINUE
C
 1001 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.........................Functi
     $on Error',T106,'*')
 1002 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.........................Index
     $=',1PG16.8,5X,'Change =',1PG16.8,T106,'*')
 1003 FORMAT(T3,'*',T106,'*'/T3,'*',T11,A30,'Step:',I3,'.....ALFA =',
     $   1PG16.8,T106,'*')
 1004 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'...............Slope Discrepanc
     $y: (f''(0) - [Delta f]) =',1PG16.8,T106,'*')
 1006 FORMAT(T3,'*',T11,'|',A4,'(',1PG10.3,') =',1PG16.6,
     $    T54,'|',A4,'(',1PG10.3,') =',1PG16.6,T98,'|',T106,'*')
 1007 FORMAT(T3,'*',T11,88('-'),T106,'*')
 1008 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'OBJECTIVE FUNCTION IS LINEAR'
     $    ,T106,'*')
 1009 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'REEVALUATE OBJECTIVE FUNCTION A
     $T BEST POINT',T106,'*')
 1010 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'.....FUNCTION EVALUATION HOLE A
     $T ALFA =',1PG16.6,T106,'*')
 1011 FORMAT(T3,'*',T11,'|',T20,A60,T98,'|',T106,'*')
      RETURN
      END
