

      LOGICAL FUNCTION LSAME ( CA, CB )
*     .. SCALAR ARGUMENTS ..
      CHARACTER(LEN=1)       CA, CB
*     ..
*
*  PURPOSE
*  =======
*
*  LSAME  TESTS IF CA IS THE SAME LETTER AS CB REGARDLESS OF CASE.
*  CB IS ASSUMED TO BE AN UPPER CASE LETTER. LSAME RETURNS .TRUE. IF
*  CA IS EITHER THE SAME AS CB OR THE EQUIVALENT LOWER CASE LETTER.
*
*  N.B. THIS VERSION OF THE ROUTINE IS ONLY CORRECT FOR ASCII CODE.
*       INSTALLERS MUST MODIFY THE ROUTINE FOR OTHER CHARACTER-CODES.
*
*       FOR EBCDIC SYSTEMS THE CONSTANT IOFF MUST BE CHANGED TO -64.
*
*  PARAMETERS
*  ==========
*
*  CA     - CHARACTER(LEN=1)
*  CB     - CHARACTER(LEN=1)
*           ON ENTRY, CA AND CB SPECIFY CHARACTERS TO BE COMPARED.
*           UNCHANGED ON EXIT.
*
*
*  AUXILIARY ROUTINE FOR LEVEL 2 BLAS.
*
*  -- WRITTEN ON 20-JULY-1986
*     RICHARD HANSON, SANDIA NATIONAL LABS.
*     JEREMY DU CROZ, NAG CENTRAL OFFICE.
*
*     .. PARAMETERS ..
      INTEGER                IOFF
      PARAMETER            ( IOFF=32 )
*     .. INTRINSIC FUNCTIONS ..
      INTRINSIC              ICHAR
*     .. EXECUTABLE STATEMENTS ..
*
*     TEST IF THE CHARACTERS ARE EQUAL
*
      LSAME = CA .EQ. CB
*
*     NOW TEST FOR EQUIVALENCE
*
      IF ( .NOT.LSAME ) THEN
         LSAME = ICHAR(CA) - IOFF .EQ. ICHAR(CB)
      END IF
*
      RETURN
      END
