
      SUBROUTINE LSQRQP(NDIM,QVEC,QLWR,QUPR,MCON,
     $    BLWR,BUPR,GMAT,IROWG,JSTRG,NONZG,NRES,
     $    RMAT,IROWR,JSTRR,NONZR,VMAT,IROWV,JSTRV,
     $    NONZV,GVEC,WORK,NWORK,IWORK,NIWORK,NEEDED,IPC,IPU,
     $    ISTART,IT,VECMU,VECNU,ISTATC,ISTATV,CNDNUM,
     $    QUAD,IERLSQ)
C
C ======================================================================
C     LSQRQP===>lsqrqp   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C
C         PURPOSE:  COMPUTE THE SEARCH DIRECTION VECTOR PVEC FOR A 
C                   LEAST SQUARES OBJECTIVE, USING AN AUGMENTED
C                   FORM OF THE QP SUBPROBLEM.  THE GENERAL NONLINEAR
C                   LEAST SQUARES PROBLEM IS TO MINIMIZE
C
C                        .5*[r(x)**T]r(x)
C
C                   SUBJECT TO THE CONSTRAINTS 
C
C                       CLWR < c(x) < CUPR
C                
C                   AND BOUNDS
C
C                       XLWR < x < XUPR
C
C                   THE DIRECTION IS COMPUTED BY SOLVING THE PROBLEM
C
C                   MIN  .5*(q**T)HBAR*q + [(g,0)**T]q
C
C
C                              | p |             | V   R |
C                   WHERE q =  |   |  AND HBAR = |       |
C                              | w |             | R  -I |
C
C
C                   SUBJECT TO THE CONSTRAINTS
C
C                   BLWR < | G    0 |q < BUPR
C 
C                   AND SIMPLE BOUNDS
C
C                   XLWR - x <  p  < XUPR - x
C
C                   THE BOUND VECTORS ARE:
C
C                     BLWR = | CLWR - CVEC |
C                            
C                     BUPR = | CUPR - CVEC |
C
C                   AND THE RESIDUAL HESSIAN MATRIX
C
C                   V = SUM(r_k DEL^2 r_k) - SUM(LAMDA_K DEL^2 c_k)
C
C         INPUT:
C
C             ----    INDEPENDENT VARIABLE DATA
C
C            NDIM   NUMBER OF VARIABLES
C            QVEC   VECTOR OF INDEPENDENT VARIABLES (NDIM+NRES)
C            QLWR   VARIABLE LOWER BOUND (NDIM+NRES)
C            QUPR   VARIABLE UPPER BOUND (NDIM+NRES)
C
C             ----    CONSTRAINT DATA 
C
C            MCON   NUMBER OF CONSTRAINTS  
C            BLWR   CONSTRAINT LOWER BOUND (MCON)
C            BUPR   CONSTRAINT UPPER BOUND (MCON)
C            GMAT   JACOBIAN MATRIX STORED AS AN ARRAY (NONZG)
C            IROWG  ROW INDEX OF NONZERO IN GMAT (NONZG)
C            JSTRG  COLUMN START INDEX (NDIM+1)
C            NONZG  NUMBER OF NONZEROS IN GMAT
C                   NOTE: NONZG  = JSTRG(NDIM+1)-1
C
C             ----    OBJECTIVE FUNCTION DATA
C
C            NRES   NUMBER OF RESIDUALS
C            RMAT   RESIDUAL JACOBIAN MATRIX STORED AS AN ARRAY (NONZR)
C            IROWR  ROW INDEX OF NONZERO IN RMAT (NONZR)
C            JSTRR  COLUMN START INDEX (NDIM+1)
C            NONZR  NUMBER OF NONZEROS IN RMAT
C                   NOTE: NONZR  = JSTRR(NDIM+1)-1
C            VMAT   NONZERO ELEMENTS IN LOWER TRIANGLE OF RESIDUAL 
C                   HESSIAN (NONZV)
C            IROWV  INTEGER ROW INDEX VECTOR (NONZV)
C            JSTRV  INTEGER COLUMN START VECTOR (NDIM+1)
C            NONZV  NUMBER OF HESSIAN NONZEROS = JSTRV(NDIM+1)-1
C            GVEC   GRADIENT VECTOR (NDIM)
C            
C             ----    ALGORITHM RELATED DATA
C
C            WORK   WORK ARRAY (NWORK)
C            NWORK  LENGTH OF WORK ARRAY (GT. 
C                   7*NDIM + 11*MCON + NONZG
C            IWORK  INTEGER WORK ARRAY (NIWORK)
C            NIWORK LENGTH OF INTEGER WORK ARRAY (GT. 2*NDIM + MCON 
C                    + 5*NRES + NONZG + NONZR + NONZV + 1 
C                    + MAX(NONZG+NONZR+NRES,NDIM+NRES+1) ) 
C            IPC    ITERATION PRINT CONTROL
C            IPU    OUTPUT UNIT NO.
C            ISTART SCHUR-COMPLEMENT START FLAG
C            IT     ITERATION NUMBER
C
C         OUTPUT:
C
C            VECMU  LAGRANGE MULTIPLIERS FOR REAL CONSTRAINTS
C            VECNU  LAGRANGE MULTIPLIERS FOR REAL BOUNDS
C            ISTATC CONSTRAINT STATUS VECTOR (MCON)
C            ISTATV VARIABLE STATUS VECTOR (NDIM)
C            CNDNUM CONDITION NUMBER OF KT MATRIX
C            QUAD   MINIMUM VALUE OF OBJECTIVE FUNCTION
C            IERLSQ INTEGER ERROR RETURN FLAG
C            NEEDED STORAGE REQUIRED WHEN NWORK OR NIWORK IS TOO SMALL
C            QVEC   THE SOLUTION POINT
C
C     ******************************************************************
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0)
C
      INCLUDE '../commons/NLPSPR.CMN'
C
      COMMON /ITEREF/ MAXREF,MAXRFN,IREFIN
      COMMON /INERVL/ INREQD
C
      COMMON /KONSTN/ 
     *  ZEROMN  ,ZEROOT  ,BIGNUM  ,BGROOT  ,BIGBND  ,BIGCND
C
      DIMENSION QVEC(NDIM+NRES),QLWR(NDIM+NRES),QUPR(NDIM+NRES),
     $    BLWR(*),BUPR(*),
     $    GMAT(NONZG),IROWG(NONZG),JSTRG(NDIM+1),RMAT(NONZR),
     $    IROWR(NONZR),JSTRR(NDIM+1),VMAT(NONZV),IROWV(NONZV),
     $    JSTRV(NDIM+1),GVEC(NDIM),WORK(NWORK),IWORK(NIWORK),
     $    VECMU(*),VECNU(NDIM),ISTATC(*),ISTATV(NDIM)
C
C         INITIALIZE OUTPUT CONTROL FOR SCHUR-QP ALGORITHM
C
      IF(IOFSHR.EQ.0) THEN
        IPCSHR = 0
        IF(IPC.GE.30) IPCSHR = IPC
      ELSE
        IPCSHR = IOFSHR
      ENDIF
C
C         DEFINE NUMBER OF VARIABLES FOR AUGMENTED QP PROBLEM
C
      NVARA = NDIM + NRES
C
C         DEFINE NUMBER OF CONSTRAINTS FOR AUGMENTED QP PROBLEM
C
      MCONA = MCON
C
C         COMPUTE POINTERS FOR REAL WORK ARRAY
C     ---ALLOCATE THE ARRAYS (I.E. CONSTRUCT THE POINTERS)
C
      LNHMAT = NONZV + NONZR + NRES
      LCHMAT = 1
      LCCVCT = LCHMAT + LNHMAT
      LCGZRO = LCCVCT + NVARA
      LCCNML = LCGZRO + NVARA
      LCVRML = LCCNML + MCONA
      LCGMAT = LCVRML + NVARA
      LNGMAT = NONZG + NRES
      LCWORK = LCGMAT + LNGMAT
      LNWORK = NWORK - LCWORK + 1
C
      IF(LNWORK.LT.0) THEN
        NEEDED = LCWORK - 1
        IF(IPC.GE.10) WRITE(IPU,1001) NWORK,NEEDED
        IERLSQ = -1
        RETURN
      ENDIF
C
C         COMPUTE POINTERS FOR INTEGER WORK ARRAY
C     ---ALLOCATE THE ARRAYS (I.E. CONSTRUCT THE POINTERS)
C
      LCIRWH = 1
      LCJSTH = LCIRWH + LNHMAT
      LCIRWG = LCJSTH + NVARA+1
      LCJSTG = LCIRWG + LNGMAT
      LNJSTG = MAX(LNGMAT,(NVARA+1))
      LCISTC = LCJSTG + LNJSTG
      LCISTV = LCISTC + MCONA
      LCIWRK = LCISTV + NVARA
      LNIWRK = NIWORK - LCIWRK + 1
C
      IF(LNIWRK.LT.0) THEN
        NEEDED = LCIWRK - 1
        IF(IPC.GE.10) WRITE(IPU,1001) NIWORK,NEEDED
        IERLSQ = -2
        RETURN
      ENDIF
C
C         DEFINE AUGMENTED HESSIAN MATRIX 
C
      NONZHA = 0
      IWORK(LCJSTH) = 1
C
      DO JCOL = 1,NDIM
C
        LNJCOL = 0
C
        DO II = JSTRV(JCOL),JSTRV(JCOL+1)-1
C
          NONZHA = NONZHA + 1
          LNJCOL = LNJCOL + 1
C
          IWORK(LCIRWH+NONZHA-1) = IROWV(II)
          WORK(LCHMAT+NONZHA-1) = VMAT(II)
C
        ENDDO
C
        DO II = JSTRR(JCOL),JSTRR(JCOL+1)-1
C
          NONZHA = NONZHA + 1
          LNJCOL = LNJCOL + 1
C
          IWORK(LCIRWH+NONZHA-1) = IROWR(II) + NDIM
          WORK(LCHMAT+NONZHA-1) = RMAT(II)
C
        ENDDO
C
        IWORK(LCJSTH+JCOL) = IWORK(LCJSTH+JCOL-1) + LNJCOL
C
      ENDDO
C
C         DEFINE DIAGONAL HESSIAN MATRIX 
C
      DO JCOL = NDIM+1,NDIM+NRES
C
        NONZHA = NONZHA + 1
C
        IWORK(LCIRWH+NONZHA-1) = JCOL
        WORK(LCHMAT+NONZHA-1) = -ONE
C
        IWORK(LCJSTH+JCOL) = IWORK(LCJSTH+JCOL-1) + 1
C        
      ENDDO
C
C         INPUT OBJECTIVE FUNCTION LINEAR TERM 
C
      WORK(LCCVCT:LCCVCT+NDIM-1) = GVEC(1:NDIM)
      WORK(LCCVCT+NDIM:LCCVCT+NVARA-1) = ZERO
C
C         CONSTRUCT JACOBIAN FOR AUGMENTED PROBLEM
C
      NONZGA = 0
      IWORK(LCJSTG) = 1
C
      DO JCOL = 1,NDIM
C
        LNJCOL = 0
C
        DO II = JSTRG(JCOL),JSTRG(JCOL+1)-1
C
          NONZGA = NONZGA + 1
          LNJCOL = LNJCOL + 1
C
          IWORK(LCIRWG+NONZGA-1) = IROWG(II)
          WORK(LCGMAT+NONZGA-1) = GMAT(II)
C
        ENDDO
C
        IWORK(LCJSTG+JCOL) = IWORK(LCJSTG+JCOL-1) + LNJCOL
C
      ENDDO
C
      DO JCOL = NDIM+1,NDIM+NRES
C
        IWORK(LCJSTG+JCOL) = IWORK(LCJSTG+JCOL-1)
C
      ENDDO
C
C         INITIALIZE CONSTRAINT STATUS ARRAYS
C
      IF(MCON.GT.0) IWORK(LCISTC:LCISTC+MCON-1) = ISTATC(1:MCON)
      IWORK(LCISTV:LCISTV+NDIM-1) = ISTATV(1:NDIM)
      IWORK(LCISTV+NDIM:LCISTV+NDIM+NRES-1) = 4
C
      IF(IT.EQ.ITDRQP) THEN
C
C         WRITE DATA FOR QUADRATIC PROGRAMMING SUBPROBLEM
C
        CALL FILSHR(NVARA,MCONA,WORK(LCHMAT),IWORK(LCIRWH),
     $    IWORK(LCJSTH),NONZHA,WORK(LCCVCT),WORK(LCGZRO),WORK(LCGMAT),
     $    IWORK(LCIRWG),IWORK(LCJSTG),NONZGA, 
     $    BUPR,BLWR,QVEC,
     $    QUPR,QLWR,WORK(LCWORK),LNWORK,
     $    BIGBND,IPU,IPCSHR,ISTART,IPUDRF,.TRUE.,'SRCHDRQP.FIL')
C
        RETURN
C
      ENDIF
C
C         PROHIBIT ITERATIVE REFINEMENT
C
      IREFIN = 0
C
C         SET INERTIA SHIFT 
C
      INREQD = NRES
C
      CALL SHURQP(NVARA,MCONA,WORK(LCHMAT),IWORK(LCIRWH),
     $    IWORK(LCJSTH),NONZHA,WORK(LCCVCT),WORK(LCGZRO),QUAD,
     $    WORK(LCGMAT),IWORK(LCIRWG),IWORK(LCJSTG),NONZGA, 
     $    BUPR,BLWR,WORK(LCCNML),IWORK(LCISTC),QVEC,QUPR,QLWR,
     $    WORK(LCVRML),IWORK(LCISTV),WORK(LCWORK),LNWORK,
     $    IWORK(LCIWRK),LNIWRK,NEEDED,BIGBND,IPU,IPCSHR,
     $    ISTART,CNDNUM,IERLSQ)
C
      IF(IERLSQ.GE.0.AND.IERLSQ.LE.2) THEN
C
C       UNLOAD SOLUTION INTO CORRECT ARRAYS
C
        DO I=1,MCON
          ISTATC(I) = IWORK(LCISTC+I-1)
          VECMU(I)  = WORK(LCCNML+I-1)
        ENDDO
C
        DO I=1,NDIM
          ISTATV(I) = IWORK(LCISTV+I-1)
          VECNU(I)  = WORK(LCVRML+I-1)
        ENDDO
C
      ENDIF
C
      IF(IERLSQ.EQ.-1014) THEN
        NEEDED = LCWORK + NEEDED - 1
      ELSEIF(IERLSQ.EQ.-1019) THEN
        NEEDED = LCIWRK + NEEDED - 1
      ENDIF
C
      RETURN
C
 1001 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'REAL WORK ARRAY FOR LSQRQP DIME
     $NSIONED ',I6,' NEED ',I6,T106,'*')
C
      END
