
      SUBROUTINE MERIT (VECLAM,VECNU,VECS,PENVEC,OBJFUN,CVEC,
     $    XVEC,MCON,NDIM,FMERIT)
C
C ======================================================================
C     MERIT ===>merit   J.T. BETTS
C ======================================================================
C     MODIFICATIONS:   13-APR-99 DSN, ADJUSTIBLE ARRAY DIMENSION FIX
C                                     FOR VAX-VMS
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         PURPOSE:  EVALUATE THE AUGMENTED LAGRANGIAN MERIT FUNCTION
C
C         INPUT:
C
C           VECLAM  LAGRANGE MULTIPLIERS (MCON)
C           VECNU   BOUND MULTIPLIERS (NDIM)
C           VECS    SLACK VARIABLES (MCON+NDIM)
C           PENVEC  PENALTY WEIGHT VECTOR (MCON+NDIM)
C           OBJFUN  OBJECTIVE FUNCTION
C           CVEC    CONSTRAINT VECTOR (MCON)
C           XVEC    INDEPENDENT VARIABLES (NDIM)
C           MCON    NUMBER OF CONSTRAINTS
C
C         OUTPUT:
C
C           FMERIT  LAGRANGIAN MERIT FUNCTION
C
      DIMENSION VECLAM(*),VECNU(NDIM),VECS(MCON+NDIM),
     $    PENVEC(MCON+NDIM),CVEC(*),XVEC(NDIM)
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0,POINT5=5.0D-1)
C
      FMERIT = OBJFUN
C
C         CONSTRUCT CONTRIBUTION FOR NONLINEAR CONSTRAINTS
C
      DO I = 1,MCON
        TERM2 = CVEC(I) - VECS(I)
        TERM1 = POINT5*PENVEC(I)*TERM2 - VECLAM(I)
        FMERIT = FMERIT + TERM1*TERM2
      ENDDO
C
C         CONSTRUCT CONTRIBUTION FOR BOUNDS
C
      DO I = 1,NDIM
        TERM2 = XVEC(I) - VECS(MCON+I)
        TERM1 = POINT5*PENVEC(MCON+I)*TERM2 - VECNU(I)
        FMERIT = FMERIT + TERM1*TERM2
      ENDDO
C
      RETURN
      END
