
      SUBROUTINE MPDNEC(IFUNER,CVEC,MSUBE,MAXCON,ETAVEC,CMAT,IROWC,
     $    JCOLC,NONZC,BVEC,MSUBB,MAXBND,VLAMDA,BMAT,IROWB,JCOLB,NONZB,
     $    GVEC,NVAR,PENMU,RWORK,LNRWRK,GRADL,GRDLNM,CLAMNM,
     $    ERPTHB,DELFNM,ERREQL,ETANRM)
C
C
C ======================================================================
C     MPDNEC===>mpdnec   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         PURPOSE:  COMPUTE THE MODIFIED PRIMAL-DUAL NECESSARY CONDITIONS
C                   AND ASSOCIATED QUANTITIES 
C
C         INPUT:
C
C           IFUNER  FUNCTION ERROR FLAG; NONZERO VALUE MEANS
C                   FUNCTIONS AND/OR GRADIENTS CAN'T BE COMPUTED
C           CVEC    EQUALITY CONSTRAINTS AT YVEC (MAXCON)
C           MSUBE   NUMBER OF EQUALITY CONSTRAINTS MSUBE 
C           MAXCON  MAXIMUM NUMBER OF CONSTRAINTS
C           ETAVEC  LAGRANGE MULTIPLIERS FOR CONSTRAINTS (MAXCON)
C           CMAT    CONSTRAINT DERIVATIVES AT YVEC (NONZC)
C           IROWC   ROW INDICES OF JACOBIAN NONZEROS (NONZC)
C           JCOLC   COLUMN INDICES OF JACOBIAN NONZEROS (NVAR+1)
C           NONZC   NUMBER OF JACOBIAN NONZEROS
C           BVEC    BOUND INEQUALITIES (MAXBND)
C           MSUBB   NUMBER OF BOUNDS
C           MAXBND  MAXIMUM NUMBER OF BOUNDS MAX(MSUBB,1)
C           VLAMDA  LAGRANGE MULTIPLIERS FOR BOUNDS (MAXBND)
C           BMAT    BOUND DERIVATIVES AT YVEC (NONZB)
C           IROWB   ROW INDICES OF BOUND JACOBIAN NONZEROS (NONZB)
C           JCOLB   COLUMN INDICES OF BOUND JACOBIAN NONZEROS (NVAR+1)
C           NONZB   NUMBER OF BOUND JACOBIAN NONZEROS
C           GVEC    GRADIENT AT YVEC (NVAR)
C           NVAR    NUMBER OF VARIABLES
C           PENMU   INTERIOR POINT (BARRIER) PARAMETER 
C           RWORK   REAL WORK ARRAY (LNRWRK)
C           LNRWRK  LENGTH OF RWORK; LNRWRK .GE. NVAR
C
C         OUTPUT:
C
C           GRADL   GRADIENT OF LAGRANGIAN (NVAR)
C           GRDLNM  NORM OF GRADIENT OF LAGRANGIAN
C           CLAMNM  NORM OF (C^T) lambda
C           ERPTHB  ERROR IN BOUND CONSTRAINT CENTRAL PATH
C           DELFNM  NORM OF GRADIENT
C           ERREQL  ERROR IN EQUALITY CONSTRAINTS
C           ETANRM  NORM OF ETAVEC
C
      DIMENSION CVEC(MAXCON)   ,ETAVEC(MAXCON) ,CMAT(NONZC)
     $         ,IROWC(NONZC)   ,JCOLC(NVAR+1)  ,BVEC(MAXBND)
     $         ,VLAMDA(MAXBND) ,BMAT(NONZB)    ,IROWB(NONZB)
     $         ,JCOLB(NVAR+1)  ,GVEC(NVAR)     ,GRADL(NVAR)
     $         ,RWORK(LNRWRK)
C
      COMMON /KONSTN/ 
     *  ZEROMN  ,ZEROOT  ,BIGNUM  ,BGROOT  ,BIGBND  ,BIGCND
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0)
C
      ERPTHB = ZERO
C
      IF(IFUNER.NE.0.AND.IFUNER.NE.-101) THEN
        GRDLNM = BIGNUM
        CLAMNM = BIGNUM
        DELFNM = BIGNUM
        ETANRM = BIGNUM
        ERREQL = BIGNUM
        RETURN
      ENDIF
C
      GRADL(1:NVAR) = ZERO
C
C         COMPUTE (CMAT**T)(ETAVEC) AND STORE IN GRADL
C
      CALL MVPSPR(11,NVAR,MSUBE,CMAT,IROWC,JCOLC,ETAVEC,GRADL)
C
C         COMPUTE (BMAT**T)(VLAMDA) AND STORE IN RWORK
C
      CALL MVPSPR(11,NVAR,MSUBB,BMAT,IROWB,JCOLB,VLAMDA,RWORK)
C
      CLAMNM = ZERO
      GRDLNM = ZERO
      DELFNM = ZERO
      DO I = 1,NVAR
        CVCLAM = GRADL(I) + RWORK(I)
        CLAMNM = MAX(CLAMNM,ABS(CVCLAM))
        GRADL(I) = GVEC(I) - CVCLAM
        GRDLNM = MAX(GRDLNM,ABS(GRADL(I)))
        DELFNM = MAX(DELFNM,ABS(GVEC(I)))
      enddo
C
      ETANRM = ZERO
      ERREQL = ZERO
      DO I = 1,MSUBE
        ETANRM = MAX(ETANRM,ABS(ETAVEC(I)))
        ERREQL = MAX(ERREQL,ABS(CVEC(I)))
      ENDDO
C
C         COMPUTE THE BOUND CONSTRAINT CENTRAL PATH CONDITION
C         ERBVEC = BVEC(I)*VLAMDA(I) - PENMU
C
      ERPTHB = COMPLM(MSUBB,PENMU,BVEC,VLAMDA)
C
      RETURN
      END
