


      SUBROUTINE MSLOPE(CVEC,MSUBE,MAXCON,ETAVEC,CMAT,IROWC,
     $    JCOLC,NONZC,BVEC,MSUBB,MAXBND,VLAMDA,BMAT,IROWB,JCOLB,   
     $    NONZB,WMAT,IROWW,JSTRW,NONZW,GVEC,NVAR,NFREE,NRES,MAXRES,
     $    ADDHSS,PENMU,CDELY,BDELY,WDELY,DELYVC,DELZVC,DELETA,DELLAM,
     $    FMRT,SAMSCL,FMIN,SLOPEL,DELTAH,DELTAR,DELTAX,SLOPEB,
     $    ALFEST,ALFLIM,GAMEST)
C
C
C ======================================================================
C     MSLOPE===>MSLOPE   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         PURPOSE:  COMPUTE THE SLOPE, AND PREDICTED STEPS FOR
C                   THE CURRENT SEARCH DIRECTION
C
C         INPUT:
C
C           CVEC    EQUALITY CONSTRAINTS AT YVEC (MAXCON)
C           MSUBE   NUMBER OF EQUALITY CONSTRAINTS MSUBE 
C           MAXCON  MAXIMUM NUMBER OF CONSTRAINTS
C           ETAVEC  LAGRANGE MULTIPLIERS FOR CONSTRAINTS (MAXCON)
C           CMAT    CONSTRAINT DERIVATIVES AT YVEC (NONZC)
C           IROWC   ROW INDICES OF JACOBIAN NONZEROS (NONZC)
C           JCOLC   COLUMN INDICES OF JACOBIAN NONZEROS (NVAR+1)
C           NONZC   NUMBER OF JACOBIAN NONZEROS
C           BVEC    BOUND INEQUALITIES (MAXBND)
C           MSUBB   NUMBER OF BOUNDS
C           MAXBND  MAXIMUM NUMBER OF BOUNDS MAX(MSUBB,1)
C           VLAMDA  LAGRANGE MULTIPLIERS FOR BOUNDS (MAXBND)
C           BMAT    BOUND DERIVATIVES AT YVEC (NONZB)
C           IROWB   ROW INDICES OF BOUND JACOBIAN NONZEROS (NONZB)
C           JCOLB   COLUMN INDICES OF BOUND JACOBIAN NONZEROS (NVAR+1)
C           NONZB   NUMBER OF BOUND JACOBIAN NONZEROS
C           WMAT    HESSIAN OF THE LAGRANGIAN (NONZW).
C                   NOTE THAT 
C                               wmat = | hmat  0 |
C                                      | 0     0 |
C                   WHERE HMAT IS THE HESSIAN WITH RESPECT TO THE NFREE
C                   REAL VARIABLES
C           IROWW   INTEGER ROW INDEX VECTOR FOR LOWER TRIANGLE OF WMAT (NONZW)
C           JSTRW   INTEGER COLUMN START VECTOR (NVAR+1)
C           NONZW   NUMBER OF NONZEROS IN THE HESSIAN (NONZW = JSTRW(NVAR+1)-1)
C           GVEC    GRADIENT AT YVEC (NVAR)
C           NVAR    NUMBER OF VARIABLES
C           NFREE   NUMBER OF FREE (NON-SLACK) VARIABLES
C           NRES    NUMBER OF RESIDUALS (FOR LEAST SQUARES OBJECTIVE)
C           MAXRES  DIMENSION OF DELZVC
C           ADDHSS  LEVENBERG MODIFICATION TO THE HESSIAN DIAGONAL, 
C                   I.E. tau*(|sigma| + 1)
C           PENMU   INTERIOR POINT (BARRIER) PARAMETER 
C           CDELY   SCRATCH ARRAY HOLDING THE PRODUCT (C)(del y) (MAXCON)
C           BDELY   SCRATCH ARRAY HOLDING THE PRODUCT (B)(del y) (MAXBND)
C           WDELY   SCRATCH ARRAY HOLDING THE PRODUCT (W)(del y) (NFREE)
C           DELYVC  YVEC SEARCH DIRECTION (NVAR)
C           DELZVC  RESIDUAL SEARCH DIRECTION (MAXRES)
C           DELETA  ETAVEC SEARCH DIRECTION (MAXCON)
C           DELLAM  VLAMDA SEARCH DIRECTION (MAXBND)
C           FMRT    LOG-BARRIER FUNCTION AT CURRENT POINT
C           SAMSCL  LOGICAL FLAG:  = TRUE FOR SAME PRIMAL-DUAL STEP SCALING
C
C         OUTPUT:
C
C           FMIN    PREDICTED MINIMUM OF LOG-BARRIER FUNCTION
C           SLOPEL  SLOPE OF THE LAGRANGIAN
C           DELTAH  THE TERM alfa**2(del x)^T W (del x)
C           DELTAR  THE TERM alfa**2(R del x)^T(R del x)
C           DELTAX  THE TERM alfa**2(del x)^T(del x) 
C           SLOPEB  SLOPE OF THE LOG-BARRIER FUNCTION, I.E. B'(0)
C           ALFEST  ESTIMATE OF FIRST PRIMAL STEP LENGTH
C           ALFLIM  LINEAR ESTIMATE OF STEP TO NEAREST INEQUALITY BOUNDARY
C           GAMEST  ESTIMATE OF FIRST DUAL STEP LENGTH
C
C
      DIMENSION CVEC(MAXCON)   ,ETAVEC(MAXCON) ,CMAT(NONZC)
     $         ,IROWC(NONZC)   ,JCOLC(NVAR+1)  ,BVEC(MAXBND)
     $         ,VLAMDA(MAXBND) ,BMAT(NONZB)    ,IROWB(NONZB)
     $         ,JCOLB(NVAR+1)  ,WMAT(NONZW)    ,IROWW(NONZW)
     $         ,JSTRW(NVAR+1)  ,GVEC(NVAR)     ,CDELY(MAXCON)
     $         ,BDELY(MAXBND)  ,WDELY(NFREE)   ,DELYVC(NVAR)   
     $         ,DELZVC(MAXRES) ,DELETA(MAXCON) ,DELLAM(MAXBND) 
C
      LOGICAL SAMSCL
C
      COMMON /KONSTN/ 
     *  ZEROMN  ,ZEROOT  ,BIGNUM  ,BGROOT  ,BIGBND  ,BIGCND
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0,ONEEP2=1.0D2,
     $           ONEEM2=1.0D-2,POINT5=5.0D-1)
C
C     ------------------------------------------------------------
C     ------------------------------------------------------------
C
C         COMPUTE THE VECTOR C(del y) IN CDELY
C         COMPUTE THE VECTOR B(del y) IN BDELY
C
      CALL MVPSPR(1,MSUBE,NVAR,CMAT,IROWC,JCOLC,DELYVC,CDELY)
      CALL MVPSPR(1,MSUBB,NVAR,BMAT,IROWB,JCOLB,DELYVC,BDELY)
C
C     ------------------------------------------------------------
C         COMPUTE ESTIMATE OF THE FIRST STEP IN THE LINESEARCH
C     ------------------------------------------------------------
C
C         COMPUTE LINEAR ESTIMATE OF DISTANCE TO NEAREST BOUND (ALFLIM)
C         AND ESTIMATE OF DISTANCE TO VLAMDA = 0 BOUNDARY (GAMLIM).
C
      ALFLIM = BIGNUM
      GAMLIM = BIGNUM
C
      DO I = 1,MSUBB
        IF(BDELY(I).LT.ZERO) THEN
          ALFNEW = -BVEC(I)/BDELY(I)
          ALFLIM = MIN(ALFLIM,ALFNEW)
        ENDIF
        IF(DELLAM(I).LT.ZERO) THEN
          GAMNEW = -VLAMDA(I)/DELLAM(I)
          GAMLIM = MIN(GAMLIM,GAMNEW)
        ENDIF
      enddo
C
C             SAFETY MARGIN
C
      TAU = ONE - MIN(ONEEM2,ONEEP2*PENMU**2)
C
C             PRIMAL VARIABLE LIMIT AND STEP
C
      ALFEST = MIN(ONE,TAU*ALFLIM)
C
C             DUAL VARIABLE LIMIT AND STEP
C
      GAMEST = MIN(ONE,TAU*GAMLIM)
C
      IF(SAMSCL) THEN
C
C             SAME (PRIMAL-DUAL) STEP SCALING 
C
        ALFEST = MIN(ALFEST,GAMEST)
        GAMEST = ALFEST
C
      ENDIF
C
C     ------------------------------------------------------------
C     ------------------------------------------------------------
C
C         BEGIN ACCUMULATION OF THE COEFFICIENTS
C
      GDOTDY = dot_product(gvec(1:nvar),delyvc(1:nvar))
C
C         COMPUTE THE TERM ((del y)**T)(W)(del y) 
C         (EXCLUDING LEVENBERG PORTION) 
C
      CALL SYMMVP(WMAT,IROWW,JSTRW,NFREE,DELYVC,WDELY)
      DYTWDY = dot_product(delyvc(1:nfree),wdely(1:nfree))
C
C         COMPUTE THE TERM (del z)**T(del z) = (R DELY)**T(R DELY) 
C         FOR LEAST SQUARE OBJECTIVES
C
      DZVTDZ = dot_product(delzvc(1:nres),delzvc(1:nres))
C
C         COMPUTE THE LEVENBERG PORTION TAU((del y)**T)_F(del y)_F 
C
      DELTAX = dot_product(delyvc(1:nfree),delyvc(1:nfree))
      TAUDY = ADDHSS*DELTAX
C
C         CONSTRUCT THE TERMS INVOLVING THE EQUALITY CONSTRAINTS
C
      ETACDY = ZERO
      CDLETA = ZERO
C
      DO I = 1,MSUBE
C
        ETACDY = ETACDY + ETAVEC(I)*CDELY(I)
C
        CDLETA = CDLETA + CVEC(I)*DELETA(I)
C
      enddo
C
C         CONSTRUCT THE TERMS INVOLVING THE BOUNDS
C
      PIBBDY = ZERO
      BDYLAM = ZERO
      BDELAM = ZERO
      DBBDLY = ZERO
C
      DO I = 1,MSUBB
C
        PIB = PENMU/BVEC(I)
C
        PIBBDY = PIBBDY + PIB*BDELY(I)
C
        BDYLAM = BDYLAM + BDELY(I)*VLAMDA(I)
C
        BDELAM = BDELAM + DELLAM(I)*BVEC(I)
C
        DBBDLY = DBBDLY + PENMU*(BDELY(I)/BVEC(I))**2
C
      enddo
C
C         COMPUTE THE SLOPE OF THE LAGRANGIAN
C
      SLOPEL = ALFEST*(GDOTDY - ETACDY - BDYLAM) 
     $       - GAMEST*(CDLETA + BDELAM)
C
C         COMPUTE THE SLOPE OF THE LOG-BARRIER FUNCTION (FULL LENGTH STEP)
C
      SLOPEB = GDOTDY - PIBBDY
C
C         COMPLETE THE CALCULATION OF THE CURVATURE TERMS
C
      CURVEL = DYTWDY + DZVTDZ + TAUDY 
      ALFSQR = ALFEST**2
      CURVEL = CURVEL*ALFSQR
C
      DELTAH = DYTWDY*ALFSQR
      DELTAR = DZVTDZ*ALFSQR
      DELTAX = DELTAX*ALFSQR
C
C         CURVATURE OF THE LOG-BARRIER FUNCTION
C
      CURVEB = CURVEL + DBBDLY 
C
C         COMPUTE PREDICTED MINIMUM OF BARRIER FUNCTION
C
      FMIN = FMRT - SLOPEB - POINT5*CURVEB
C
      RETURN
      END
