
      INTEGER FUNCTION NDOFQP(IVSTAT,MEQUAL,MINEQL,NDIM)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION IVSTAT(MEQUAL+MINEQL+1+NDIM)
C
C        COMPUTE THE NUMBER OF DEGREES OF FREEDOM 
C
      LNIVST = MEQUAL+MINEQL+1+NDIM
      IFREE = 0
      DO I=1,LNIVST
        IF (IVSTAT(I).EQ.0)  IFREE = IFREE + 1
      ENDDO
      IFIX = LNIVST - IFREE
      IF(IVSTAT(MEQUAL+MINEQL+1).EQ.0) THEN
        NDOFQP = NDIM - IFIX
      ELSE
        NDOFQP = NDIM + 1 - IFIX
      ENDIF
C
      RETURN
      END
