
      SUBROUTINE PRJGRD(CVEC,DELF,GMAT,IROWG,JSTRG,
     $    NONZG,ISTATC,ISTATV,RHSWRK,WORK,NWORK,WORK2,IWORK,
     $    LNIWRK,NEEDED,MCON,MEQUAL,NDIM,NCALPG,PGRAD,XLAM,VECNU,
     $    ITEMP,IFIXVR,IAROW,DELFNM,PGNORM,IPC,IPU,IREDER)
C
C ======================================================================
C     PRJGRD===>prjgrd   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C
C         PURPOSE:  COMPUTE THE PROJECTED GRADIENT VECTOR AND LAGRANGE
C                   MULTIPLIERS FOR A SET OF EQUALITY CONSTRAINTS
C
C         INPUT:
C
C            CVEC   CONSTRAINT VECTOR (MCON)
C            DELF   GRADIENT VECTOR OF PERFORMANCE INDEX F (NDIM)
C            GMAT   NONZERO ELEMENTS OF JACOBIAN MATRIX (NONZG)
C            IROWG  ROW INDICES OF NONZERO JACOBIAN ELEMENTS (NONZG)
C            JSTRG  COLUMN START INDEX (NDIM+1)
C                   NONZG  = JSTRG(NDIM+1)-1
C            ISTATC CONSTRAINT STATUS ARRAY (MCON)
C            ISTATV VARIABLE STATUS ARRAY (NDIM)
C            RHSWRK RIGHT HAND SIDE WORK ARRAY (4*NDIM)
C            WORK   WORK ARRAY (NWORK)
C            NWORK  LENGTH OF WORK ARRAY 
C            WORK2  WORK ARRAY (NDIM)
C            IWORK  INTEGER WORK ARRAY (LNIWRK)
C            MCON   NUMBER OF CONSTRAINTS
C            MEQUAL NUMBER OF EQUALITY CONSTRAINTS 
C            NDIM   NUMBER OF VARIABLES
C            NCALPG CALL NUMBER FOR PROJECTED GRADIENT FACTORIZATION
C            IPC    OUTPUT CONTROL FLAG
C            IPU    OUTPUT UNIT NO.
C
C         OUTPUT:
C
C            PGRAD  PROJECTED GRADIENT VECTOR (NDIM)
C            XLAM   LAGRANGE MULTIPLIERS (MCON)
C            VECNU  LAGRANGE MULTIPLIERS FOR VARIABLES (NDIM)
C            ITEMP  INTEGER TEMPORARY ARRAY (MCON)
C            IFIXVR INTEGER FIXED VARIABLE ARRAY (NDIM)
C            IAROW  INTEGER ACTIVE ROW ARRAY (MCON)
C            DELFNM NORM OF DELF
C            PGNORM NORM OF PROJECTED GRADIENT
C            NWORK  LENGTH OF WORK ARRAY NEEDED WHEN IREDER .NE. 0
C            IREDER INTEGER ERROR RETURN FLAG
C
C
C         SUBROUTINES USED:
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0)
      DIMENSION CVEC(MCON),DELF(NDIM),GMAT(NONZG),
     $    IROWG(NONZG),JSTRG(NDIM+1),PGRAD(NDIM),
     $    XLAM(MCON),VECNU(NDIM),ISTATC(MCON),
     $    ISTATV(NDIM),RHSWRK(4*NDIM),WORK(NWORK),WORK2(NDIM),
     $    IWORK(LNIWRK),ITEMP(MCON),IFIXVR(NDIM),IAROW(MCON)
C
      IER = 0
      NEEDED = 0
C
C         COMPUTE NORM OF GRADIENT VECTOR
C         COPY GRADIENT INTO WORK ARRAY
C
      DELFNM = ZERO
      DO KK = 1,NDIM
        DELFNM = MAX(DELFNM,ABS(DELF(KK)))
        PGRAD(KK) = DELF(KK)
        WORK2(KK) = DELF(KK)
      ENDDO
C
      IF(MEQUAL.GT.0) THEN
C
C         DEFINE CONSTRAINT POINTER ARRAY
C
        DO I = 1,MCON
          IF(ISTATC(I).EQ.3) THEN
            ITEMP(I) = -1
          ELSE
            ITEMP(I) = 0
          ENDIF
        ENDDO
C
C         DEFINE FIXED VARIABLE POINTER
C
        NFIXVR = 0
        DO I = 1,NDIM
          IF(ISTATV(I).EQ.3) THEN
            NFIXVR = NFIXVR + 1
            IFIXVR(I) = 1
          ELSE
            IFIXVR(I) = 0
          ENDIF
        ENDDO
C
C         COMPUTE PROJECTED GRADIENT SEARCH DIRECTION AND LAGRANGE
C         MULTIPLIERS
C
        NCALL = NCALPG
C
        CALL MFRNLD(MCON,NDIM,GMAT,IROWG,JSTRG,NONZG,WORK2
     $    ,CVEC,ITEMP,IFIXVR,PGRAD,XLAM,VECNU,RHSWRK
     $    ,WORK,NWORK,IWORK,LNIWRK,NEEDED
     $    ,IAROW,NCALL,IPU,IPC,CNDNUM,IER)
C
C         END OF MEQUAL .GT. 0 TEST
C
      ENDIF
C
      IREDER = 0
C
      IF(IER.EQ.0) THEN
C       
C         EXPAND MULTIPLIERS TO FULL SIZE
C
        DO KK = 1,MEQUAL
          WORK2(KK) = XLAM(KK)
        ENDDO
        II = 0
        DO I = 1,MCON
          IF(ISTATC(I).EQ.3) THEN
            II = II + 1
            XLAM(I) = WORK2(II)
          ELSE
            XLAM(I) = ZERO
          ENDIF
        ENDDO
C
        DO KK = 1,NFIXVR
          WORK2(KK) = VECNU(KK)
        ENDDO
C         COMPUTE NORM OF PROJECTED GRADIENT
        II = 0
        PGNORM = ZERO
        DO I = 1,NDIM
          PGNORM = MAX(PGNORM,ABS(PGRAD(I)))
          IF(ISTATV(I).EQ.3) THEN
            II = II + 1
            VECNU(I) = WORK2(II)
          ELSE
            VECNU(I) = ZERO
          ENDIF
        ENDDO
C
      ELSE
C
        IREDER = IER
C
      ENDIF
C
      IF(IREDER.NE.0.AND.IPC.GE.20) THEN
        WRITE(IPU,1001) IREDER
      ENDIF
C
 1001 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'PRJGRD FAILED --- IREDER ='
     $  ,I5,T106,'*')
C
      RETURN
      END
