
      SUBROUTINE QPPRNT(STRIN1,VALUE1,STRIN2,VALUE2,IPU)
C
C
C ======================================================================
C     QPPRNT===>qpprnt   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      CHARACTER(LEN=*) STRIN1,STRIN2
      CHARACTER(LEN=*) VALUE1,VALUE2
      CHARACTER(LEN=36) LFTOUT,RITOUT,BLANK
      DATA BLANK(1:36) / ' '/
C
C         COMPUTE LENGTH OF INPUT CHARACTER STRING 1
C
      LNINPT = LEN(STRIN1)
      LNIP1 = LNINPT + 1
C
C         IF INPUT STRIN1 IS TOO LONG EXIT
C
      LNSWID = 20
      LNVWID = 16
      IF(LNINPT.GT.LNSWID) THEN
        PRINT *,'OUTPUT STRIN1 TOO LARGE'
        RETURN
      ENDIF
C
      LFTOUT = BLANK
      LFTOUT(1:LNINPT) = STRIN1(1:LNINPT)
C
C         COMPUTE LENGTH OF INPUT CHARACTER VALUE 1
C
      LNIVAL = LEN(VALUE1)
      IF(LNIVAL.GT.LNVWID) THEN
        PRINT *,'OUTPUT VALUE1 TOO LARGE'
        RETURN
      ENDIF
C
C         LOAD THE FIRST STRING VALUE
C
      LFTOUT(LNIP1:LNIP1+LNVWID) = BLANK(1:LNVWID)
      LFTOUT(LNIP1:LNIP1+LNIVAL) = VALUE1
C
      CALL HHADJF(LFTOUT(LNIP1:LNIP1+LNVWID),' ',' ','L',NS,IERSH)
      CALL HHADJF(LFTOUT(LNIP1:LNSWID+LNVWID),' ','.','R',NS,IERSH)
C
C         COMPUTE LENGTH OF INPUT CHARACTER STRING 2
C
      LNINPT = LEN(STRIN2)
      LNIP1 = LNINPT + 1
C
C         IF INPUT STRIN2 IS TOO LONG EXIT
C
      IF(LNINPT.GT.LNSWID) THEN
        PRINT *,'OUTPUT STRIN2 TOO LARGE'
        RETURN
      ENDIF
C
      RITOUT = BLANK
      RITOUT(1:LNINPT) = STRIN2(1:LNINPT)
C
C         COMPUTE LENGTH OF INPUT CHARACTER VALUE 2
C
      LNIVAL = LEN(VALUE2)
      IF(LNIVAL.GT.LNVWID) THEN
        PRINT *,'OUTPUT VALUE2 TOO LARGE'
        RETURN
      ENDIF
C
C         LOAD THE SECOND STRING VALUE
C
      RITOUT(LNIP1:LNIP1+LNVWID) = BLANK(1:LNVWID)
      RITOUT(LNIP1:LNIP1+LNIVAL) = VALUE2
C
      CALL HHADJF(RITOUT(LNIP1:LNIP1+LNVWID),' ',' ','L',NS,IERSH)
      CALL HHADJF(RITOUT(LNIP1:LNSWID+LNVWID),' ','.','R',NS,IERSH)
C
C         WRITE OUT THE WHOLE STRING
C
      WRITE(IPU,1001) LFTOUT,RITOUT
C
 1001 FORMAT(T3,'*',T15,A36,T54,'|',T59,A36,T106,'*')
      RETURN
      END
