




      SUBROUTINE RELXQP(GMAT,IROWG,JSTRG,NONZG,MCON,NDIM,
     $    WORK,NWORK,IWORK,NIWORK,NEEDED,CLWR,CUPR,CVEC,
     $    PVEC,XLWR,XUPR,XVEC,IPC,IPU,ISTART,
     $    IT,ISTATC,ISTATV,CNDNUM,NUMKTF,IERELX)
C
C ======================================================================
C     RELXQP===>relxqp   J.T. BETTS
C ======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C
C         PURPOSE:  COMPUTE THE SEARCH DIRECTION VECTOR PVEC, USING
C                   A RELAXED FORM OF THE QP SUBPROBLEM.  THE 
C                   DIRECTION IS COMPUTED BY SOLVING THE PROBLEM
C
C                   MIN  .5*(P**T)P + .5*GAMMA*(R**T)R 
C
C                   SUBJECT TO THE CONSTRAINTS
C
C                          | GP + R |
C                   BLWR < |        | < BUPR
C                          |    P   |
C
C                   WHERE THE SLACK OR RESIDUAL VECTOR R IS INTRODUCED
C                   FOR ALL GENERAL CONSTRAINTS.  THE SCALAR GAMMA IS
C                   A PARAMETER (SET TO 1.D6).  THE BOUND VECTORS ARE:
C
C                            | CLWR - CVEC |
C                     BLWR = |             |
C                            | XLWR - XVEC |
C
C                            | CUPR - CVEC |
C                     BUPR = |             |
C                            | XUPR - XVEC |
C
C         INPUT:
C
C            GMAT   JACOBIAN MATRIX STORED AS AN ARRAY (NONZG)
C            IROWG  ROW INDEX OF NONZERO IN GMAT (NONZG)
C            JSTRG  COLUMN START INDEX (NDIM+1)
C            NONZG  NUMBER OF NONZEROS IN GMAT
C                   NOTE: NONZG  = JSTRG(NDIM+1)-1
C            MCON   NUMBER OF CONSTRAINTS  (GT.0)
C            NDIM   NUMBER OF VARIABLES
C            WORK   WORK ARRAY (NWORK)
C            NWORK  LENGTH OF WORK ARRAY (GT. 
C                   7*NDIM + 11*MCON + NONZG
C            IWORK  INTEGER WORK ARRAY (NIWORK)
C            NIWORK LENGTH OF INTEGER WORK ARRAY (GT. 3*NDIM + 6*MCON 
C                    + NONZG + 1 + MAX(NONZG+MCON,NDIM+MCON+1) ) 
C            CLWR   CONSTRAINT LOWER BOUND (MCON)
C            CUPR   CONSTRAINT UPPER BOUND (MCON)
C            CVEC   CONSTRAINTS AT XVEC (MCON)
C            PVEC   SEARCH VECTOR (NDIM)
C            XLWR   VARIABLE LOWER BOUND (NDIM)
C            XUPR   VARIABLE UPPER BOUND (NDIM)
C            XVEC   ESTIMATE OF INDEPENDENT VARIABLES (NDIM)
C            IPC    ITERATION PRINT CONTROL
C            IPU    OUTPUT UNIT NO.
C            ISTART SCHUR-COMPLEMENT START FLAG
C            IT     ITERATION NUMBER
C
C         OUTPUT:
C
C            ISTATC CONSTRAINT STATUS VECTOR
C            ISTATV VARIABLE STATUS VECTOR
C            CNDNUM CONDITION NUMBER OF KT MATRIX
C            NUMKTF NUMBER OF MATRIX FACTORIZATIONS
C            IERELX INTEGER ERROR RETURN FLAG
C            NEEDED STORAGE REQUIRED WHEN NWORK AND NIWORK ARE TOO SMALL
C            PVEC   THE SOLUTION POINT
C
C     ******************************************************************
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0)
C
      INCLUDE '../commons/NLPSPR.CMN'
C
      COMMON /ITEREF/ MAXREF,MAXRFN,IREFIN
      COMMON /INERVL/ INREQD
C
      COMMON /KONSTN/ 
     *  ZEROMN  ,ZEROOT  ,BIGNUM  ,BGROOT  ,BIGBND  ,BIGCND
C
      DIMENSION  GMAT(NONZG),IROWG(NONZG),JSTRG(NDIM+1),WORK(NWORK),
     $    IWORK(NIWORK),CVEC(MCON),PVEC(NDIM),
     $    XVEC(NDIM),CLWR(MCON),CUPR(MCON),XLWR(NDIM),XUPR(NDIM),
     $    ISTATC(MCON),ISTATV(NDIM)
C
      GAMMA = BIGCND**.45
C
C         DEFINE NUMBER OF VARIABLES FOR RELAXED QP PROBLEM
C
      NVAR = NDIM + MCON
C
C         COMPUTE POINTERS FOR REAL WORK ARRAY
C
      LCHMAT = 1
      LCCVCT = LCHMAT + NVAR
      LCGZRO = LCCVCT + NVAR
      LCCUPR = LCGZRO + NVAR
      LCCLWR = LCCUPR + MCON
      LCXUPR = LCCLWR + MCON
      LCXLWR = LCXUPR + NVAR
      LCCNML = LCXLWR + NVAR
      LCVRML = LCCNML + MCON
      LCGMAT = LCVRML + NVAR 
      LCVARP = LCGMAT + (NONZG+MCON)
      LCWORK = LCVARP + NVAR
      LNWORK = NWORK - LCWORK + 1
C
C         COMPUTE LENGTH OF REAL WORK ARRAY 
C
      IF(LNWORK.LE.0) THEN
        IF(IPC.GE.10) WRITE(IPU,1001) NWORK,LCWORK
        NEEDED = LCWORK 
        IERELX = -1
        RETURN
      ENDIF
C
C         COMPUTE POINTERS FOR INTEGER WORK ARRAY
C
      LCIRWH = 1
      LCJSTH = LCIRWH + NVAR
      LCIRWG = LCJSTH + (NVAR+1)
      LCJSTG = LCIRWG + (NONZG+MCON)
      LCISTC = LCJSTG + MAX(NONZG+MCON,(NVAR+1))
      LCISTV = LCISTC + MCON
      LCIWRK = LCISTV + NVAR
      LNIWRK = NIWORK - LCIWRK + 1
C
C         COMPUTE LENGTH OF INTEGER WORK ARRAY 
C
      IF(LNIWRK.LE.0) THEN
        IF(IPC.GE.10) WRITE(IPU,1002) NIWORK,LNIWRK
        NEEDED = LCIWRK 
        IERELX = -2
        RETURN
      ENDIF
C
C         DEFINE DIAGONAL HESSIAN MATRIX (LDP)
C
      DO I = 1,NVAR
        IWORK(LCIRWH+I-1) = I
        IWORK(LCJSTH+I-1) = I
      ENDDO
      IWORK(LCJSTH+NVAR) = NVAR + 1
C
C         DEFINE DIAGONAL HESSIAN MATRIX 
C
      WORK(LCHMAT:LCHMAT+NDIM-1) = ONE
      WORK(LCHMAT+NDIM:LCHMAT+NDIM+MCON-1) = GAMMA
C
C         INPUT OBJECTIVE FUNCTION LINEAR TERM AS ZERO
C
      WORK(LCCVCT:LCCVCT+NVAR-1) = ZERO
C
C         INITIALIZE VARIABLES FOR QP CALL
C
      WORK(LCVARP:LCVARP+NVAR-1) = ZERO
C
C         DEFINE LOWER AND UPPER BOUNDS
C
      DO I = 1,MCON
C
        IF(CLWR(I).EQ.CUPR(I)) THEN
C
C         EQUALITY CONSTRAINT
C
          WORK(LCCLWR+I-1) = CLWR(I)-CVEC(I)
          WORK(LCCUPR+I-1) = CUPR(I)-CVEC(I)
C
        ELSE
C
C         INEQUALITY CONSTRAINT
C
          IF(CLWR(I).LE.-BIGBND) THEN
            WORK(LCCLWR+I-1) = -BIGBND
          ELSE
            WORK(LCCLWR+I-1) = CLWR(I)-CVEC(I)
          ENDIF
C
          IF(CUPR(I).GE.BIGBND) THEN
            WORK(LCCUPR+I-1) = BIGBND
          ELSE
            WORK(LCCUPR+I-1) = CUPR(I)-CVEC(I)
          ENDIF
C
        ENDIF
C
      ENDDO
C
C         DEFINE LOWER AND UPPER BOUNDS FOR VARIABLES
C
      DO I = 1,NDIM
C
        IF(XLWR(I).EQ.XUPR(I)) THEN
C
C         EQUALITY CONSTRAINT
C
          WORK(LCXLWR+I-1) = XLWR(I)-XVEC(I)
          WORK(LCXUPR+I-1) = XUPR(I)-XVEC(I)
C
        ELSE
C
C         INEQUALITY CONSTRAINT
C
          IF(XLWR(I).LE.-BIGBND) THEN
            WORK(LCXLWR+I-1) = -BIGBND
          ELSE
            WORK(LCXLWR+I-1) = XLWR(I)-XVEC(I)
          ENDIF
C
          IF(XUPR(I).GE.BIGBND) THEN
            WORK(LCXUPR+I-1) = BIGBND
          ELSE
            WORK(LCXUPR+I-1) = XUPR(I)-XVEC(I)
          ENDIF
C
        ENDIF
C
      ENDDO
C
C         DEFINE LOWER AND UPPER BOUNDS FOR SLACK VARIABLES
C
      DO I=0,MCON-1
        WORK(LCXLWR+NDIM+I) = -BIGBND
        WORK(LCXUPR+NDIM+I) = BIGBND
      ENDDO
C
C         CONSTRUCT JACOBIAN FOR AUGMENTED PROBLEM
C
C         ---FIRST NDIM COLUMNS
C
      DO I=1,NONZG
        WORK(LCGMAT+I-1) = GMAT(I)
        IWORK(LCIRWG+I-1) = IROWG(I)
      ENDDO
      IWORK(LCJSTG:LCJSTG+NDIM-1) = JSTRG(1:NDIM)
C
C         ---NEXT MCON COLUMNS
C
      NONZA = NONZG
      DO I = 1,MCON
        NONZA = NONZA + 1
        WORK(LCGMAT+NONZA-1) = ONE
        IWORK(LCIRWG+NONZA-1) = I
        IWORK(LCJSTG+NDIM+I-1) = NONZA
      ENDDO
      IWORK(LCJSTG+NVAR) = NONZA+1
C
C         DEFINE INITIAL STATUS ARRAYS
C
      IWORK(LCISTV:LCISTV+NDIM-1) = ISTATV(1:NDIM)
      DO I=1,MCON
        IWORK(LCISTC+I-1) = ISTATC(I)
        IWORK(LCISTV+NDIM+I-1) = 0
      ENDDO
C
      IF(IT.EQ.ITFZQP) THEN
C
C         WRITE DATA FOR QUADRATIC PROGRAMMING SUBPROBLEM
C
        CALL FILSHR(NVAR,MCON,WORK(LCHMAT),IWORK(LCIRWH),
     $    IWORK(LCJSTH),NVAR,WORK(LCCVCT),WORK(LCGZRO),WORK(LCGMAT),
     $    IWORK(LCIRWG),IWORK(LCJSTG),NONZA, 
     $    WORK(LCCUPR),WORK(LCCLWR),WORK(LCVARP),
     $    WORK(LCXUPR),WORK(LCXLWR),WORK(LCWORK),LNWORK,
     $    BIGBND,IPU,IPC,ISTART,IPUFZF,.TRUE.,'SRCHFZQP.FIL')
C
        RETURN
C
      ENDIF
C
C         PERMIT ITERATIVE REFINEMENT
C
      IREFIN = 1
C
C         SET INERTIA SHIFT 
C
      INREQD = 0
C
      CALL SHURQP(NVAR,MCON,WORK(LCHMAT),IWORK(LCIRWH),
     $    IWORK(LCJSTH),NVAR,WORK(LCCVCT),WORK(LCGZRO),QUAD,
     $    WORK(LCGMAT),IWORK(LCIRWG),IWORK(LCJSTG),NONZA, 
     $    WORK(LCCUPR),WORK(LCCLWR),WORK(LCCNML),IWORK(LCISTC),
     $    WORK(LCVARP),WORK(LCXUPR),WORK(LCXLWR),WORK(LCVRML),
     $    IWORK(LCISTV),WORK(LCWORK),LNWORK,IWORK(LCIWRK),
     $    LNIWRK,NEEDED,BIGBND,IPU,IPC,ISTART,CNDNUM,IERELX)
C
      IF(IERELX.EQ.0.OR.IERELX.EQ.1) THEN
C
C       UNLOAD SOLUTION INTO SEARCH DIRECTION VECTOR
C
        PVEC(1:NDIM) = WORK(LCVARP:LCVARP+NDIM-1)
C
        ISTATC(1:MCON) = IWORK(LCISTC:LCISTC+MCON-1)
        ISTATV(1:NDIM) = IWORK(LCISTV:LCISTV+NDIM-1)
C
      ENDIF
C
      IF(IERELX.EQ.-1014) THEN
        NEEDED = LCWORK + NEEDED - 1
      ELSEIF(IERELX.EQ.-1019) THEN
        NEEDED = LCIWRK + NEEDED - 1
      ENDIF
C
      CALL CLKOUT(13,TIMKTF,XNMKTF)
      NUMKTF = XNMKTF
C
      RETURN
C
 1001 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'REAL WORK ARRAY FOR SPARSE SEAR
     $CH DIMENSIONED ',I6,' NEED ',I6,T106,'*')
 1002 FORMAT(T3,'*',T106,'*'/T3,'*',T11,'INTEGER WORK ARRAY FOR SPARSE S
     $EARCH DIMENSIONED ',I6,' NEED ',I6,T106,'*')
C
      END
