C
C
C
      SUBROUTINE SHURDN( J, NEQNS, NX, K, KMAX, IPC, IPU, SHURC,
     $                   SHRCSV, IDNTYP, IFREE0, INSHUR,
     $                   IFREKT, ITPSHR, MXNZUM,
     $                   JSTRU, IROWU, UMAT, W, IER            )
C
C ======================================================================
C     SHURDN===>shurdn   J.T. BETTS
C ======================================================================
C
C     ROUTINE TO UNDO THE J-TH SCHUR-COMPLEMENT UPDATE (THUS REDUCING
C     K TO K-1). THIS IS ACCOMPLISHED BY MOVING INFO RELATED
C     TO UPDATES J+1 THROUGH K AS IF UPDATE J HAD NOT OCCURRED.
C
      INTEGER NEQNS, IER, J, IDNTYP
      INTEGER IPC, IPU, K, JCOL, JVAR
      INTEGER IVAR, JUP, JUPM2
      INTEGER INONZ, NZUVEC
      INTEGER KMAX, NX, MXNZUM
C
      INTEGER INSHUR(KMAX), IFREKT(NX), IFREE0(NX)
      INTEGER JSTRU(KMAX+1), IROWU(MXNZUM), ITPSHR(KMAX)
C
      DOUBLE PRECISION RHSNEW, SHURC(KMAX,KMAX), SHRCSV(KMAX,KMAX)
      DOUBLE PRECISION W(KMAX), UMAT(MXNZUM)
C
      IER = 0
C
      IF ( .NOT. ( J .GE. 1 .AND. J .LE. K ) ) THEN
        IER = 1
        IF ( IPC .GT. 0) THEN
          WRITE(IPU,*) ' SHURDN: DOWNDATE INDEX OUT OF RANGE = ', J,
     $                 ' K =', K
C
        ENDIF
        GO TO 999
      ENDIF
C
      IVAR = ABS( INSHUR(J) )
C
      IF ( IFREKT(IVAR) .EQ. 0 ) THEN
        IER = 2
        IF ( IPC .GT. 0) THEN
          WRITE(IPU,*) ' SHURDN: IFREKT = 0 FOR VAR NO. ', IVAR
C
        ENDIF
        GO TO 999
      ELSEIF( IFREKT(IVAR) .GT. 0 .AND. IFREE0(IVAR) .GE. 0 ) THEN
        IER = 3
        IF ( IPC .GT. 0) THEN
          WRITE(IPU,*) ' SHURDN: IFREKT>0 AND IFREE0>=0 FOR ',
     $                 'VAR NO. ', IVAR
C
        ENDIF
        GO TO 999
      ELSEIF( IFREKT(IVAR) .LT. 0 .AND. IFREE0(IVAR) .LE. 0 ) THEN
        IER = 4
        IF ( IPC .GT. 0) THEN
          WRITE(IPU,*) ' SHURDN: IFREKT<0 AND IFREE0<=0 FOR ',
     $                 'VAR NO. ', IVAR
C
        ENDIF
        GO TO 999
      ELSEIF ( IFREE0(IVAR) .EQ. -1 .AND. IDNTYP .EQ. -2 ) THEN
C       VARIABLE IVAR WAS INITIALLY FIXED AT ITS LOWER BOUND AND
C       FREED BY AN UPDATE ( SINCE IFREKT(IVAR) > 0 ). A DOWNDATE
C       IS ONLY BE ALLOWED TO RETURN IT TO ITS LOWER BOUND.
        IER = 5
        IF ( IPC .GT. 0) THEN
          WRITE(IPU,*) ' SHURDN: ATTEMPT TO DOWNDATE LB TO UB FOR ',
     $                 'VAR NO. ', IVAR
C
        ENDIF
        GO TO 999
      ELSEIF ( IFREE0(IVAR) .EQ. -2 .AND. IDNTYP .EQ. -1 ) THEN
C       VARIABLE IVAR WAS INITIALLY FIXED AT ITS UPPER BOUND AND
C       FREED BY AN UPDATE ( SINCE IFREKT(IVAR) > 0 ). A DOWNDATE
C       IS ONLY ALLOWED TO RETURN IT TO ITS UPPER BOUND.
        IER = 6
        IF ( IPC .GT. 0) THEN
          WRITE(IPU,*) ' SHURDN: ATTEMPT TO DOWNDATE UB TO LB FOR ',
     $                 'VAR NO. ', IVAR
C
        ENDIF
        GO TO 999
      ENDIF 
C
C     UNDO THE J-TH UPDATE SO THAT UPDATE JUP, FOR JUP > J, BECOMES
C     UPDATE JUP - 1. THUS, K <-- K - 1 AFTER THE J-TH UPDATE IS UNDONE.
C     NOTE: IF THE K-TH UPDATE IS BEING UNDONE THE ONLY CHANGE NEEDED
C           IS TO SET K = K - 1.
C
      DO JUP = J + 1, K
C
C       ...DOWNDATE MATRIX SHRCSV.
C
C       MAKE THE OLD ROW AND COLUMNS JUP OF MATRIX SHRCSV
C       BECOME THE NEW ROW AND COLUMNS JUP - 1.
C
        SHRCSV(1:K,JUP-1) = SHRCSV(1:K,JUP)
        SHRCSV(JUP-1,1:K) = SHRCSV(JUP,1:K)
C
C       PERFORM NEW STORAGE UPDATE FOR OLD K = (JUP - 2).
C       THUS, NEW K WILL BE = (JUP - 1).
C
        RHSNEW = W(JUP)
C
C       "VIRTUAL" UVEC <-- COLUMN JUP OF UMAT. THAT IS, THE
C       INFO FOR THE SPARSE STORAGE OF VECTOR UVEC (CORRES TO THE
C       UPDATE JUP) IS EXTRACTED FROM THE UMAT SPARSE MATRIX.
C       UMAT IS THEN UPDATED BY SUBROUTINE STORUP SUCH THAT
C       OLD COLUMN JUP BECOMES NEW COLUMN JUP - 1. HOPEFULLY,
C       THE STORAGE CORRES TO OLD UMAT COLUMNS > JUP WILL NOT BE
C       ALTERED IN THIS PROCESS.
C
        NZUVEC = JSTRU(JUP+1) - JSTRU(JUP)
        INONZ = JSTRU(JUP)
C
        JUPM2 = JUP - 2
        CALL STORUP( NEQNS, JUPM2, KMAX, RHSNEW,
     $               UMAT(INONZ), NZUVEC, IROWU(INONZ),
     $               W, MXNZUM, JSTRU, IROWU, UMAT )
C
C       NOTE: SUPPOSE THERE WERE NZJ ETNRIES IN UMAT FOR UPDATE
C             J. AFTER UPDATE JUP (WHERE JUP>J) HAS BEEN
C             DOWNDATED TO BECOME UPDATE JUP-1, THE UMAT ENTRIES
C             FOR OLD UPDATE JUP ARE NOW COPIED INTO UMAT BETWEEN
C             JSTRU(JUP-1) AND JSTRU(JUP). (ROUTINE STORUP CHANGES
C             THE VALUE OF JSTRU(JUP) SUCH THAT NEW UPDATE JUP-1
C             HAS THE SAME NUMBER OF ENTRIES AS OLD UPDATE JUP.)
C             AS A RESULT, THERE ARE NZJ "GARBAGE" ENTRIES IN UMAT
C             BETWEEN JSTRU(JUP) AND JSTRU(JUP+1). THESE "GARBAGE"
C             ENTRIES ARE THE FINAL NZJ ENTRIES IN THE UMAT STORAGE
C             FOR OLD UPDATES J THROUGH JUP. AT THE COMPLETION OF
C             THIS LOOP THE NZJ GARBAGE ENTRIES "BUBBLE UP" TO 
C             POSITIONS JSTRU(K) THROUGH JSTRU(K+1). THIS IS OK
C             SINCE SHURDN REDEFINES K AS K-1, WHICH MAKES JSTRU(K)
C             THE TERMINATION FOR STORAGE OF UMAT.
C             
      enddo
C
C
C     NOW UPDATE INFO RELATED TO THE HISTORY OF SCHUR-COMPLEMENT
C     UPDATES SUCH THAT IT APPEARS THAT UPDATE J NEVER TOOK PLACE.
C     NOTE: VARIABLE NUMBER IVAR WAS AFFECTED BY THE J-TH UPDATE.
C
      IFREKT(IVAR) = 0
      DO JVAR = 1, NX
        IF ( ABS(IFREKT(JVAR)) .GT. J ) THEN
C
          IFREKT(JVAR) = SIGN( ABS(IFREKT(JVAR)) - 1,
     $                          IFREKT(JVAR) )
C
        ENDIF
      enddo
C
      DO JUP = J, K - 1
        ITPSHR(JUP) = ITPSHR(JUP+1)
        INSHUR(JUP) = INSHUR(JUP+1)
      enddo
C
      K = K - 1
C
C
C     THE  NEW, SMALLER K BY K  MATRIX SHURC <-- SHRCSV
C
      DO JCOL = 1, K
        SHURC(1:K,JCOL) = SHRCSV(1:K,JCOL)
      enddo
C
      IF ( IPC .GT. 0 ) THEN
        WRITE(IPU,*) ' AFTER DOWNDATE: K=', K
      ENDIF
C
      IF ( K.GT. 0 ) THEN
C
        IF ( IPC .GT. 100 ) THEN
          CALL MATPRN( SHURC, KMAX, K, K, 'SHURC', 5, 6 )
        ENDIF
      ENDIF
C
C
 999  CONTINUE
C
      RETURN
      END
