
      SUBROUTINE SHURDV( NROW, NDIM, MINEQL, MEQUAL, NX, KMAX, 
     $                    NEQNS, IPC, IPU, NFREE0, IFREE0,
     $                    MXNZAM, IROWA, JSTRA, AMAT,
     $                    MXNZHM, IROWH, JSTRH, HMAT,
     $                    NWKKT, WORKKT, IVSTAT, CVCT,
     $                    BL, BU, X0, GRAD0, F0, AKIVF0, SFEZ,
     $                    MXNZUM, NROWSZ, IROWU, JSTRU, UMAT,
     $                    IFREKT, ITPSHR, INSHUR, 
     $                    IRWUVC, UVEC, SHURC, SHRCSV,
     $                    KPVT, WRKSML, WRKBIG, INDX, IDROP, DRPLAM,
     $                    W, Z, Y, ALMSHR, PSTEP, QSTEP, 
     $                    ATPI, U, V, T, 
     $                    RHO, GOTRHO, CHI, GOTCHI, GRAD,
     $                    PI, ALMBDA, X, 
     $                    NDUMAT, CNDTOL, IRETCD, IER              )
C
C ======================================================================
C     SHURDV===>shurdv   J.T. BETTS
C ======================================================================
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C     ----PURPOSE: DRIVER SUBROUTINE FOR SCHUR-COMPLEMENT
C                  UPDATES, AS PART OF A SOLVER FOR LARGE 
C                  SPARSE QP PROBLEMS USING THE KT MATRIX
C                  SOLUTION APPROACH. EXCEPT FOR THE CASE OF
C                  FATAL ERRORS, THIS ROUTINE RETURNS
C                  EITHER WITH A QP SOLUTION OR A REQUEST
C                  FOR A NEW FACTORIZATION OF THE KT SYSTEM.
C
C     ----DEFINITIONS OF ARGUMENT LIST VARIABLES:
C
C         NOTE: IN THE DEFINITIONS BELOW THE "ORIGINAL
C               PROBLEM" DENOTES THE PROBLEM AS VIEWED BY THE
C               USER. IN PARTICULAR, IT ONLY CONTAINS THE "REAL"
C               VARIABLES SPECIFIED BY THE USER. IN CONTRAST,
C               THE "EXPANDED PROBLEM" REFERS TO THE QP IN STANDARD
C               FORM, WITH SLACK VARIABLES AND THE FEASIBILITY
C               VARIABLE.
C
C     ***INPUTS:
C
C        NROW      NUMBER OF GENERAL LINEAR CONSTRAINTS.
C
C        NDIM      NUMBER OF VARIABLES IN THE ORIGINAL QP PROBLEM.
C
C        MINEQL    NUMBER OF GENERAL LINEAR INEQUALITY CONSTRAINTS.
C
C        MEQUAL    NUMBER OF GENERAL LINEAR EQUALITY CONSTRAINTS.
C
C        NX        NUMBER OF VARIABLES IN STANDARD FORM PROBLEM.
C                  NX MUST BE SET TO MINEQL + 1 + NDIM BY THE CALLER.
C        
C        KMAX      MAXIMUM NUMBER OF SCHUR-COMPLEMENT UPDATES THAT
C                  WILL BE ALLOWED. 
C        
C        NEQNS     NUMBER OF EQUATIONS IN THE KT SYSTEM WHICH
C                  WAS FACTORED PRIOR TO THIS CALL TO SHURDV.
C        
C        IPC       PRINT CODE.
C        
C        IPU       PRINT UNIT.
C        
C        NFREE0    NUMBER OF VARIABLES (INCLUDING SLACKS AND
C                  FEASIBILITY) THAT WERE FREE WHEN THE KT SYSTEM
C                  WAS FACTORED PRIOR TO THIS CALL TO SHURDV.
C                  NOTE: NEQNS SHOULD = NFREE0 + NROW
C        
C        IFREE0    VECTOR INDICATING FREE VARIABLES AT KT
C                  FACTORIZATION. IFREE0 IS PARTITIONED
C                  AS ( MINEQL, 1, NDIM ).
C                              {  -1, VAR I WAS FIXED AT LOW BOUND
C                  IFREE0(I) = {  -2, VAR I WAS FIXED AT UPPER BOUND
C                              { J>0, VAR I WAS THE J-TH FREE VAR
C                                    AMONG THE NFREE0 TOTAL FREE VARS
C
C        MXNZAM    MAXIMUM NUMBER OF NONZEROS IN THE ORIGINAL PROBLEM
C                  CONSTRAINT MATRIX AMAT.
C        
C        IROWA     ROW INDICES OF THE CONSTRAINT MATRIX NONZEROS.
C        
C        JSTRA     START LOCATIONS FOR COLUMNS IN THE CONSTRAINT
C                  MATRIX. JSTRA(J) = I MEANS THAT THE FIRST NONZERO
C                  IN COLUMN J IS THE I-TH ENTRY IN THE MATRIX AMAT.
C                  THUS, TOTAL NONZEROS IN
C                  COL J = JSTRA(J+1)-JSTRA(J), FOR J=1 TO NDIM.
C        
C        AMAT      SPARSE FORMAT STORAGE VECTOR FOR THE NONZEROS
C                  OF THE ORIGINAL PROBLEM CONSTRAINT MATRIX.
C        
C        MXNZHM    MAXIMUM NUMBER OF NONZEROS IN THE ORIGINAL PROBLEM
C                  HESSIAN MATRIX UMAT.
C        
C        IROWH     ROW INDICES OF THE HESSIAN MATRIX NONZEROS.
C        
C        JSTRH     START LOCATIONS FOR COLUMNS IN THE HESSIAN
C                  MATRIX. JSTRH(J) = I MEANS THAT THE FIRST NONZERO
C                  IN COLUMN J IS THE I-TH ENTRY IN THE MATRIX HMAT.
C                  THUS, TOTAL NONZEROS IN
C                  COL J = JSTRH(J+1)-JSTRH(J), FOR J=1 TO NDIM.
C        
C        HMAT      SPARSE FORMAT STORAGE VECTOR FOR THE NONZEROS
C                  OF THE ORIGINAL PROBLEM HESSIAN MATRIX.
C        
C        NWKKT     NUMBER OF ENTRIES IN THE WORKKT VECTOR, WHERE
C                  THE WORRKT VECTOR SPECIFIES THE KT SYSTEM
C                  FACTORIZATION.
C        
C        WORKKT    STORAGE FOR THE KT SYSTEM FACTORIZATION COMPUTED
C                  PRIOR TO CALLING SHURDV.
C
C        IVSTAT    STATUS VECTOR FOR THE GENERAL CONSTRAINTS AND
C                  BOUNDS ON THE VARIABLES. IVSTAT IS PARTITIONED
C                  AS ( MEQUAL, MINEQL, 1, NDIM ). 
C                              { -1, EQUALITY CONSTRAINT
C                  IVSTAT(I) = {  0, FREE VARIABLE
C                              {  1, VARIABLE FIXED AT LOWER BOUND
C                              {  2, VARIABLE FIXED AT UPPER BOUND
C                              {  3, VARIABLE FIXED FOR THIS QP RUN
C        
C        CVCT      LINEAR TERM COEFFICIENTS IN OBJECTIVE OF THE
C                  ORIGINAL QP PROBLEM.
C        
C        BL        LOWER BOUNDS FOR THE EXPANDED PROBLEM VARIABLES.
C        
C        BU        UPPER BOUNDS FOR THE EXPANDED PROBLEM VARIABLES.
C        
C        X0        THE VECTOR OF UNKNOWNS FOR THE EXPANDED QP PROBLEM.
C
C        GRAD0     GRADIENT OF THE QP PROBLEM WITH RESPECT THE SUBSET
C                  OF X0 REPRESENTING ORIGINAL QP PROBLEM VARIABLES.
C        
C        F0        RIGHT-HAND-SIDE (RHS) VECTOR FOR THE KT SYSTEM IN
C                  VOGUE WHEN SHURDV IS CALLED.
C
C                    -1
C        AKIVF0    K0  F0, WHERE K0 IS THE INPUT KT MATRIX.
C        
C        
C        SFEZ      INFEASIBILITY VECTOR FOR THE KT SYSTEM IN VOGUE
C                  WHEN SHURDV IS CALLED.
C        
C        MXNZUM    MAXIMUM NUMBER OF NONZEROS IN THE KT SYSTEM
C                  AUGMENTATION  MATRIX, UMAT.
C        
C        NROWSZ    MAX(1,NROW). USED TO PREVENT 0 AS A DIMENSION.
C
C     ***LOCAL VARIABLES REQUIRING WORKING STORAGE:
C        
C        IROWU     ROW INDICES FOR UMAT (SEE BELOW).
C        
C        JSTRU     START LOCATIONS FOR COLUMNS OF MATRIX UMAT.
C                  JSTRU(J) = I MEANS THAT THE FIRST NONZERO
C                  IN COLUMN J IS THE I-TH ENTRY IN THE MATRIX AMAT.
C                  THUS, TOTAL NONZEROS IN
C                  COL J = JSTRU(J+1)-JSTRU(J), FOR J=1 TO K, WHERE
C                  K IS THE CURRENT NUMBER OF UPDATES.
C        
C        UMAT      SPARSE FORMAT STORAGE VECTOR FOR THE NONZEROS
C                  OF THE KT SYSTEM AUGMENTATION MATRIX.        
C        
C        IFREKT    SCHUR-COMPLEMENT UPDATE HISTORY FROM THE POINT
C                  OF VIEW OF THE VARIABLES.
C                              { -KK, VAR I FIXED AT UPDATE KK
C                  IFREKT(I) = {   0, VAR I NOT AFFECTED BY AN UPDATE
C                              {  KK, VAR I FREED AT UPDATE KK
C        
C        ITPSHR    SCHUR-COMPLEMENT UPDATE HISTORY BY UPDATE TYPE.
C                               {  1, A VAR FREED AT UPDATE KK
C                  ITPSHR(KK) = { -1, A VAR SET TO LB AT UPDATE KK
C                               { -2, A VAR SET TO UB AT UPDATE KK
C        
C        INSHUR    SCHUR-COMPLEMENT UPDATE HISTORY INDICATING WHICH
C                  VARIABLE WAS INVOLVED.
C                  INSHUR(KK) = { -J, VAR J FIXED AT UPDATE KK
C                               {  J, VAR J FREED AT UPDATE KK
C
C        IRWUVC    ROW INDICATOR FOR UVEC, THE SPARSE FORMAT VERSION
C                  OF THE KT SYSTEM UPDATE VECTOR U.
C        
C        UVEC      THE SPARSE FORMAT VERSION OF THE KT SYSTEM UPDATE
C                  VECTOR U.
C        
C        SHURC     STORES THE SCHUR-COMPLEMENT MATRIX UNTIL IT IS
C                  FACTORED; THEN IT STORES THE FACTORED MATRIX.
C
C        SHRCSV    PRESERVES A COPY OF THE SCHUR-COMPLEMENT MATRIX.
C                  THIS COPY IS UNAFFECTED BY FACTORIZATION AND THUS
C                  CAN BE USED TO COMPUTED UPDATED AND DOWNDATED
C                  SCHUR-COMPLEMENT MATRICES.
C
C        KPVT      THE LINPACK PIVOT VECTOR. KPVT(K) IS THE
C                  INDEX OF THE K-TH PIVOT ROW AND COLUMN.
C        
C        WRKSML    WORKING STORAGE FOR KMAX SIZE STUFF.
C        
C        WRKBIG    WORKING STORAGE FOR NEQNS SIZE STUFF.
C        
C        INDX      STORAGE FOR SWAP INDICES WHEN SORTING LAGRANGE
C                  MULTIPLIER MAGNITUDES OF DROP CANDIDATES.
C
C        IDROP     STORAGE FOR THE INDICES OF DROP CANDIDATES.
C
C        DRPLAM    STORAGE FOR THE LAGRANGE MULTIPLIER MAGNITUDES OF
C                  DROP CANDIDATES.
C
C        W         PORTION OF RHS OF AUGMENTED KT SYSTEM REPRESENTING
C                  SCHUR-COMPLEMENT UPDATES.
C        
C        Z         PORTION OF SOLUTION OF AUGMENTED KT SYSTEM
C                  REPRESENTING SCHUR-COMPLEMENT UPDATES.
C        
C        Y         PORTION OF SOLUTION OF AUGMENTED KT SYSTEM
C                  REPRESENTING THE KT SYSTEM PASSED-IN TO SHURDV.
C        
C        ALMSHR    LAGRANGE MULTIPLIERS FOR VARS FIXED BY UPDATES.
C        
C        PSTEP     STEP FROM THE CURRENT X (THE EXPANDED PROBLEM X).
C        
C        QSTEP     STEP FROM X0. I.E., X + PSTEP = X0 + QSTEP.
C                   T
C        ATPI      A PI, WHERE A IS AMAT AND PI REPRESENTS THE
C                  LAGRANGE MULTIPLIERS FOR THE ORIGINAL
C                  PROBLEM EQUALITY CONSTRAINTS.
C        
C        U         THE DENSE VERSION OF THE KT SYSTEM UPDATE
C                  VECTOR U.
C        
C        V         UPDATE VECTOR V FOR THE AUGMENTATION MATRIX V
C                  IN THE LOWER-RIGHT OF THE AUGMENTED KT SYSTEM.
C        
C        T         UPDATE VECTOR FOR THE SCHUR-COMPLEMENT MATRIX.
C        
C
C     ***OUTPUTS:
C        
C        RHO       FEASIBILITY VARIABLE PENALTY WEIGHT, LINEAR TERM.
C
C        GOTRHO    TRUE IF SHURDV HAS COMPUTED A VALUE FOR RHO.
C                  SHURDV SETS THIS VALUE THE FIRST TIME IT
C                  TAKES A FULL STEP TO THE KT MATRIX SOLUTION.
C                  (I.E., WHEN NO BOUND IS ADDED.)
C                  NOTE!!! GOTRHO MUST BE INITIALIZED TO .FALSE.
C                  BY THE CALLER OF SHURDV. ON A GIVEN PROBLEM,
C                  IT SHOULD NOT SUBSEQUENTLY BE CHANGED BY THE USER.
C        
C        CHI       FEASIBILITY VARIABLE PENALTY WEIGHT, QUADRATIC TERM.
C
C        GOTCHI    TRUE IF SHURDV HAS COMPUTED A VALUE FOR CHI.
C                  SHURDV SETS THIS VALUE THE FIRST TIME IT
C                  FREES THE FEASIBILITY VAR AND UPDATES THE
C                  FACTORIZATION OF THE SCHUR-COMPLEMENT.
C                  NOTE!!! GOTCHI MUST BE INITIALIZED TO .FALSE.
C                  BY THE CALLER OF SHURDV. ON A GIVEN PROBLEM,
C                  IT SHOULD NOT SUBSEQUENTLY BE CHANGED BY THE USER.
C        
C        GRAD      GRADIENT OF THE ORIGINAL QP AT X.
C
C        PI        LAGRANGE MULTIPLIERS FOR THE GENERAL EQUALITY
C                  CONSTRAINTS.
C        
C        ALMBDA    LAGRANGE MULTIPLIERS FOR THE BOUNDS ON THE
C                  VARIABLES OF THE EXPANDED PROBLEM.
C        
C        X         CURRENT VALUES FOR THE EXPANDED PROBLEM VARIABLES.
C        
C        NDUMAT    WHEN NDUMAT > 0 THEN NDUMAT MORE STORAGE
C                  LOCATIONS ARE NEEDED TO STORE THE NEXT
C                  UPDATE IN UMAT AND IROWU. IN THIS CASE, IRETCD = 9
C                  AND SHURDV RETURNS FOR A NEW KT FACTORIZATION.
C        
C        CNDTOL    TOLERANCE ON SMALLEST ALLOWABLE RECIPROCAL CONDITION 
C                  NUMBER OF SCHUR-COMPLEMENT
C        
C        IRETCD    RETURN CODE FOR SHURDV. IRETCD IS DEFINED AS
C                  FOLLOWS: (NOTE: COMPUTING A NEW KT FACTORIZATION
C                                  INCLUDES RECOMPUTING THE
C                                  FEASIBILITY VECTOR AND THE STATE
C                                  OF THE FEASIBILITY VARIABLE.)
C                  
C                  -1    IER NOT 0, A FATAL ERROR: STOP.
C
C                   0    OPTIMAL (STRONG) SOLUTION FOUND: STOP.
C
C                   1    OPTIMAL WEAK SOLUTION FOUND: STOP.
C
C                   2    RESERVED FOR FUTURE DISASTERS.
C
C                   3    RHO EXCEEDS RHOMAX. PROBLEM MAY BE INFEASIBLE.
C
C                   4    HIT UPDATE LIMIT KMAX: COMPUTE A NEW KT
C                        FACTORIZATION.
C
C                   5    TOO SMALL AN INVERSE CONDITION NUMBER HAS
C                        BEEN ESTIMATED FOR THE SCHUR-COMPLEMENT
C                        FACTORIZATION: COMPUTE A NEW KT FACTORIZATION. 
C
C                   6    EXCESSIVE BOUNDS VIOLATION IN UPDATE PROCESS:
C                        COMPUTE A NEW KT FACTORIZATION.
C
C                   7    NUMERICAL ERROR CAUSED TOO LARGE A STEP FOR
C                        A SUPPOSEDLY FIXED VARIABLE: COMPUTE A NEW
C                        KT FACTORIZATION.
C
C                   8    TOO LARGE A LAGRANGE MULTIPLIER MISMATCH
C                        MAY BE DUE TO INSTABILITY IN THE
C                        SCHUR-COMPLEMENT SYSTEM. THUS, RETURN
C                        FOR A NEW KT FACTORIZATION.
C
C                   9    TOO LITTLE SPACE IN UMAT AND IROWU TO
C                        PERFORM THE NEXT UPDATE. (NDUMAT MORE
C                        ENTRIES WOULD BE REQUIRED.) THUS, RETURN
C                        FOR A NEW KT FACTORIZATION.
C
C                   10   HIT UPDATE/DOWNDATE ITERATION LIMIT:
C                        POSSIBLE CYCLING.
C
C                   11   INERTIA OF SCHUR-COMPLEMENT HAS BECOME
C                        WRONG BY 1.
C
C                   12   NUMERICAL ERROR ENCOUNTERED WITH K = 0,
C                        PROBABLY BECAUSE OF ILL-CONDITIONED KT MATRIX
C
C                   13   THE FEASIBILITY VAR IS FREE AND, TOO SMALL
C                        AN INVERSE CONDITION NUMBER HAS
C                        BEEN ESTIMATED FOR THE SCHUR-COMPLEMENT
C                        FACTORIZATION.
C
C                   14   SOLVE FAILED (ATTRIBUTED TO ILL-CONDITIONING)
C                  
C        IER       ERROR RETURN CODE. IF IER NOT 0 THEN A FATAL
C                  ERROR HAS BEEN DETECTED.
C        
C        
C        
C        
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
C
      DOUBLE PRECISION ZERO, ONE
      PARAMETER ( ZERO = 0.0D0, ONE = 1.0D0 )
C
      LOGICAL UPLIM, BADCND, ALMERR 
      LOGICAL SMLMLT, BNDVIO, GOTRHO, GOTCHI
      LOGICAL DPFSUP, DRPFES
C
      INTEGER ITNSHR, IER, NFREE0, NEQNS
      INTEGER NROW, NDIM, MEQUAL, MINEQL, NX, I
      INTEGER KMAX, K, IPC, IPU, NWKKT
      INTEGER IRETCD, IUPTYP, IADD, JUP
      INTEGER MAXITN, NSHURS, INRTER
      INTEGER IOPT, NDROP, JVAR, KPAST, ITYPE0
      INTEGER JER1, JER2, JER3, JER4, JER5, JER6, JER7, JER8
      INTEGER NZUVEC, MXNZUM, MXNZHM, MXNZAM
      INTEGER NZUMAT, NDUMAT, NROWSZ
C
      INTEGER IFREE0(NX), IFREKT(NX)
      INTEGER ITPSHR(KMAX), INSHUR(KMAX)
      INTEGER KPVT(KMAX)
      INTEGER IVSTAT(MEQUAL+NX)
      INTEGER IROWU(MXNZUM), JSTRU(KMAX+1)
      INTEGER IROWH(MXNZHM), JSTRH(NDIM+1)
      INTEGER IROWA(MXNZAM), JSTRA(NDIM+1)
      INTEGER IRWUVC(NEQNS) 
      INTEGER IDROP(NX), MAXDRP, LWLOOP, INDX(NX)
C
      DOUBLE PRECISION DAMAX, CNDTOL, EQLMTL, ALMNOI
      DOUBLE PRECISION HDMCON, CMPERR, SMLSTP, SOLVTL, OBJ
      DOUBLE PRECISION RHSNEW, TEMP, ALPHA, XI, RHO, CHI, ALMBIG
      DOUBLE PRECISION ALFNOI, SIGMA, GAMMA, RCOND, RHOMAX, BNDTOL
C
      DOUBLE PRECISION WORKKT(NWKKT), GRAD0(NDIM)
      DOUBLE PRECISION X0(NX), X(NX)
      DOUBLE PRECISION SHURC(KMAX,KMAX), SHRCSV(KMAX,KMAX)
      DOUBLE PRECISION AKIVF0(NEQNS), F0(NEQNS)
      DOUBLE PRECISION UMAT(MXNZUM), AMAT(MXNZAM), HMAT(MXNZHM)
      DOUBLE PRECISION WRKSML(KMAX), WRKBIG(NEQNS)
      DOUBLE PRECISION W(KMAX), Z(KMAX), Y(NEQNS)
      DOUBLE PRECISION ALMBDA(NX), ALMSHR(NX)
      DOUBLE PRECISION PSTEP(NX), QSTEP(NX)
      DOUBLE PRECISION BL(NX), BU(NX)
      DOUBLE PRECISION PI(NROWSZ), CVCT(NDIM)
      DOUBLE PRECISION ATPI(NDIM), GRAD(NDIM), SFEZ(NROWSZ)
      DOUBLE PRECISION U(NEQNS), UVEC(NEQNS), V(KMAX)
      DOUBLE PRECISION T(KMAX), DRPLAM(NX)
CBUG      DOUBLE PRECISION STPERR, PIERR
C
      INTEGER ISQPER
      COMMON /PERCOM/ ISQPER(20)
C
C
C
C     ---INITIALIZATION
C
C      NOTE: GOTRHO AND GOTCHI ARE TRUE IF THE FEASIBLE VARIABLE
C            OBJECTIVE FUNCTION WEIGHTINGS RHO AND CHI HAVE
C            BEEN GIVEN VALUES. THEY ARE FALSE OTHERWISE.
C            SHURDV ASSUMES GOTRHO AND GOTCHI HAVE BEEN INITIALIZED
C            IN THE CALLING PROGRAM.
C
C     IF NO VALUE HAS BEEN COMPUTED FOR THE PENALTY FACTOR OF
C     THE FEASIBILITY QUADRATIC TERM THEN SET IT (CHI) TO 1.0
C
      IF ( .NOT. GOTCHI ) THEN
        CHI = ONE
      ENDIF
C
      MAXITN = MAX( 5*KMAX, 5*NX )
      MAXITN = MAX( MAXITN, 200 )
C
C
      IF ( IPC .GT. 0 ) THEN
        WRITE(IPU,910)  NDIM, NROW, NX, NEQNS, NFREE0, MEQUAL, MINEQL
 910    FORMAT( /, 2X, 'ON ENTRY TO SHURDV:', /, 4X,
     $          'NDIM=', I5, 3X, 'NROW=', I5, 3X, 'NX=', I5, 3X,  
     $          'NEQNS=', I5, /, 4X, 'NFREE0=', I5, 3X,
     $          'MEQUAL=', I5, 3X, 'MINEQL=', I5, // )
C
        IF(IPC.GT.10) CALL VPRIN ( NX, X0, 'INITIAL X', 9, IPU )
        IF(IPC.GT.10) CALL IVPRIN( NX, IVSTAT(MEQUAL+1), 
     $     'STATE OF INITIAL X',18,IPU )
        IF(IPC.GT.10) CALL VPRIN ( NX, BL, 'BL', 2, IPU )
        IF(IPC.GT.10) CALL VPRIN ( NX, BU, 'BU', 2, IPU )
        IF(IPC.GT.10) CALL VPRIN ( NROW, SFEZ, 'SFEZ', 4, IPU )
      ENDIF
C
      ITNSHR = 0
      IER = 0
      UPLIM = .FALSE.
      BADCND = .FALSE.
      DRPFES = .FALSE.
      NFREE0 = NEQNS - NROW
      EQLMTL = SQRT(HDMCON(6))
      CMPERR = 10.0D0 * HDMCON(6)
      ALMNOI = SQRT(HDMCON(6))
      ALFNOI = 1.0D3 * HDMCON(6)
      RHOMAX = 1.0D-4 * (ONE/HDMCON(6))
C
      SMLSTP = SQRT(HDMCON(6))
      SOLVTL = 1.0D-3*SQRT(HDMCON(6))
      BNDTOL = 10.0D0 * SMLSTP
      MAXDRP = 1
C
C     IFREKT <-- 0
C
      DO I = 1, NX
        IFREKT(I) = 0
      enddo
C
C     ITPSHR <-- 0 AND INSHUR <-- 0 
C
      DO I = 1, KMAX
        ITPSHR(I) = 0
        INSHUR(I) = 0
      enddo
C
C
C     X <-- X0
      X(1:NX) = X0(1:NX)
C
      IF ( IPC .GT. 0 ) THEN
        CALL GETOBJ( NDIM, X(MINEQL+2), MXNZHM, IROWH,
     $               JSTRH, HMAT, CVCT, WRKBIG, OBJ   )
C
        WRITE(IPU,*) ' OBJECTIVE AT X0=', OBJ
C
C
        CALL MVPSPR( 1, MEQUAL+MINEQL, NDIM, AMAT,
     $               IROWA, JSTRA, X(MINEQL+2), WRKBIG )
C
        IF(IPC.GT.10) CALL VPRIN ( MEQUAL+MINEQL,WRKBIG,'A*X',3,IPU )
      ENDIF
C
C     NOTE: K IS THE NUMBER OF SCHUR-COMPLEMENT UPDATES.
C           EACH DOWNDATE DECREMENTS K. IT IS POSSBILE
C           (BUT UNLIKELY) THAT K=0 WHEN ITNSHR NOT 0.
C
      K = 0
C
C
C**** START OF SCHUR-COMPLEMENT QP SOLUTION LOOP.
 110  CONTINUE
C
C
C     ---SOLVE KT SYSTEM BELOW FOR THE VECTORS Y AND Z:
C
C           |  K0    U | |Y| = |F0|
C           | (U)TR  V | |Z|   |W |
C
C        (NOTE: IF K=0 THEN Z DOESN'T EXIST AND Y = AKIVF0,
C                                -1
C               WHERE AKIVF0 = K0  F0 IS AN INPUT TO SHURDV)
C
      IF ( K .GT. 0 ) THEN
        IF ( IPC .GT. 100 ) CALL VPRIN ( K, W, 'W', 1, IPU )
C
        CALL YZSOLV( NEQNS, K, IPC, IPU, KMAX, SOLVTL, SHURC,
     $               KPVT, MXNZUM, IROWU, JSTRU, UMAT,
     $               AKIVF0, F0, W, NWKKT, WORKKT, 
     $               WRKSML,WRKBIG, DRPFES, INSHUR,  
     $               RHO, RHOMAX, MINEQL, Z, Y, JER1         )
C
        IF ( IPC .GT. 100 ) CALL VPRIN ( K, Z, 'Z', 1, IPU)
C
C
        IF ( JER1 .NE. 0 ) THEN
C
          IRETCD = 14
          IF ( IPC .GT. 0 ) THEN
            WRITE(IPU,*) ' SHURDV: AFTER YZSOLV JER=', JER1
          ENDIF
          GO TO 999
        ENDIF
C
      ELSE
C       Y <-- AKIVF0
C
        Y(1:NEQNS) = AKIVF0(1:NEQNS)
      ENDIF
C
C     ----DECODE THE KT SOLUTION VECTORS Y AND Z TO GET
C     QSTEP (THE STEP FROM X0), PI (LAGRANGE MULTIPLIERS
C     FOR THE GENERAL CONSTRAINTS) AND ALMSHR (LAGRANGE
C     MULTIPLIERS FOR THE VARS FIXED BY UPDATES).
C
      CALL DCODYZ( MINEQL, NROW, NDIM, NFREE0, IFREE0, 
     $            INSHUR, K, KMAX, NEQNS, NX, IPC, IPU,
     $            Y, Z, X0, X, QSTEP, PI, ALMSHR, JER2 )
C
        IF ( IPC .GT. 100 ) CALL VPRIN ( NX, QSTEP, 'QSTEP', 5, IPU )
C
C
      IF ( JER2 .NE. 0 ) THEN
C
        IER = 1105 + JER2
        IRETCD = -1
        IF ( IPC .GT. 0 ) THEN
          WRITE(IPU,*) ' SHURDV: AFTER DCODYZ JER=', JER2
        ENDIF
        GO TO 999
      ENDIF
C
C
C     ---COMPUTE PSTEP, THE KT SOLUTION STEP FROM X.
C
      DO I = 1, NX
C
        IF ( IVSTAT(MEQUAL+I) .EQ. 0 ) THEN
C
C         FREE VARIABLE
C
          PSTEP(I) = X0(I) - X(I) + QSTEP(I)
        ELSE
C
C         FIXED VARIABLE
C
          TEMP = X0(I) - X(I) + QSTEP(I)
C
          IF ( IFREKT(I) .LT. 0 ) THEN
C
C           VARIABLE WAS SET TO A BOUND BY AN UPDATE.
C           IF NUMERICAL ERRORS CAUSE THE STEP IN THIS
C           VARIABLE TO BE TOO LARGE, RETURN FOR A NEW
C           KT FACTORIZATION.
C
            IF ( ABS(TEMP) .GT. SMLSTP ) THEN
              IF(K.GT.0) THEN
                IRETCD = 7
              ELSE
                IRETCD = 12
              ENDIF
              GO TO 999
            ELSE
C             FORCE THE STEP TO ZERO.
              TEMP = ZERO
            ENDIF
C
          ELSE
C
C           VARIABLE WAS FIXED AT KT FACTORIZATION.
C           THUS, STEP SHOULD BE ZERO TO (ALMOST) MACHINE PRECISION.
C
            IF ( ABS(TEMP) .GT. CMPERR ) THEN
              IER = 1110
              IRETCD = -1
              IF ( IPC .GT. 0 ) THEN
                WRITE(IPU,*) ' SHURDV: STEP TOO LARGE FOR',
     $                       ' FIXED (AT PRIOR KT FACT.) VAR NO. ', I
              ENDIF
              GO TO 999
            ELSE
C             FORCE THE STEP TO ZERO.
              TEMP = ZERO
            ENDIF
          ENDIF
C
          PSTEP(I) = TEMP
C
        ENDIF
C
      enddo
C
C
      IF ( IPC .GT. 100 ) THEN
          CALL VPRIN ( NX, PSTEP, 'SHURDV:PSTEP', 13, IPU )
          CALL VPRIN ( NROW, PI, 'SHURDV:PI', 10, IPU )
      ENDIF
C
CBUG
C     CALL THE DEBUGGER ROUTINE WHICH USES DENSE LINEAR ALGEBRA.
C
C      CALL BRUTFR( NROW, NDIM, NX, MEQUAL, MINEQL, IVSTAT,
C     $              MXNZHM, JSTRH, IROWH, HMAT, 
C     $              MXNZAM, JSTRA, IROWA, AMAT, 
C     $              CVCT, SFEZ, RHO, X, PSTEP, PI,
C     $              IPC, IPU, STPERR, PIERR                )
C
CBUG
C
C     ---DETERMINE 1.0>=ALPHA>=0.0 SUCH THAT
C     XNEW <-- X + ALPHA*P, WHERE ALPHA<1.0 ONLY
C     IF AN INACTIVE BOUND IS HIT. GETALF ALSO SETS IUPTYP,
C
C                      { 1 IF NO BOUND IS HIT, I.E. ALPHA=1.0
C     WHERE IUPTYP =   {-1 IF VARIABLE IADD HITS IT LOWER BOUND
C                      {-2 IF VARIABLE IADD HITS IT UPPER BOUND
C
      CALL GETALF( NX, ALFNOI, SMLSTP, PSTEP, X, BL, BU,
     $             IUPTYP, IADD, ALPHA                     )
C
C
      IF ( IPC .GT. 0 ) THEN 
        WRITE(IPU,*)
        WRITE(IPU,*) ' AFTER GETALF--ALPHA,IADD',ALPHA,IADD
        WRITE(IPU,*)' ||PSTEP|| = ', DAMAX( NX, PSTEP, 1 )
      ENDIF
C
      IF ( IPC .GT. 100 ) THEN
        CALL VPRIN ( NX, X, 'X BEFORE STEP', 13, IPU )
      ENDIF
C
C
C     X <-- X + ALPHA*P
C
      DO I=1,NX
        X(I) = X(I) + ALPHA*PSTEP(I)
      ENDDO
C
      IF ( IPC .GT. 100 ) THEN
         CALL VPRIN ( NX, X, 'X AFTER STEP', 12, IPU )
      ENDIF
C
      IF ( IPC .GT. 0 ) THEN
        CALL GETOBJ( NDIM, X(MINEQL+2), MXNZHM, IROWH,
     $               JSTRH, HMAT, CVCT, WRKBIG, OBJ   )
C
        WRITE(IPU,*) ' OBJECTIVE AT X = X + ALPHA*P : ', OBJ
C
      ENDIF
C
C
C     ---DETERMINE IF BOUNDS HAVE BECOME EXCESSIVELY VIOLATED.
C
      CALL BNDCHK( NX, X, BL, BU, BNDTOL, BNDVIO )
C
      IF ( BNDVIO ) THEN
C
C       EXCESSIVE BOUNDS VIOLATION. RETURN
C       FOR A NEW FEASIBILITY VECTOR AND KT FACTORIZATION.
C
        IF(K.GT.0) THEN
          IRETCD = 6
        ELSE
          IRETCD = 12
        ENDIF
        GO TO 999
      ENDIF
C
C
      IF ( IUPTYP .GT. 0 ) THEN
C
C       ---DETERMINE WHICH, IF ANY, VARIABLE'S BOUND SHOULD
C          BE DROPPED. THUS, LAGRANGE MULTIPLIERS (ALMBDA)
C          FOR THE FIXED VARIABLES MUST BE COMPUTED.
C
C       GRAD <-- GRADIENT OF ORIGINAL QP PROBLEM.
C
        CALL GETGRD( NDIM, NX, X(MINEQL+2), MXNZHM, IROWH,
     $                JSTRH, HMAT, CVCT, GRAD                )
C
C                 T
C       ATPI <-- A PI FOR THE ORIGINAL PROBLEM VARIABLES.
C
        IOPT = 11
        CALL MVPSPR( IOPT, NDIM, NROW, AMAT, IROWA, JSTRA,
     $               PI, ATPI                              )
C
C       ALMBDA <-- LAGRANGE MULTIPLIERS FOR BOUNDS ON VARIABLES.
C
        XI = X(MINEQL+1)
        CALL GETLAM( NX, MEQUAL, MINEQL, NROW, NDIM,
     $               IVSTAT, PI, GRAD, ATPI, SFEZ,
     $               XI, GOTRHO, RHO, CHI, ALMBDA        )
C
C
C       DETERMINE WHETHER OR NOT THERE IS TOO LARGE A
C       DISCREPENCY BETWEEN THE LAGRANGE MULTIPLIERS
C       COMPUTED AS PART OF THE KT SYSTEM AND THOSE COMPUTED
C                                                 T
C       DIRECTLY FROM ALMBDA = (G(X+P))FX - (A)FX PI
C       
        CALL LAMERR( NX, EQLMTL, IFREKT, ALMSHR,
     $               ALMBDA, ALMERR                  )
C
C       TOO LARGE A LAGRANGE MULTIPLIER MISMATCH MAY BE DUE TO
C       INSTABILITY IN THE SCHUR-COMPLEMENT SYSTEM. THUS, RETURN
C       FOR A NEW KT FACTORIZATION.
C
        IF ( ALMERR ) THEN
          IF(K.GT.0) THEN
            IRETCD = 8
          ELSE
            IRETCD = 12
          ENDIF
          GO TO 999
        ENDIF
C
C
C       CALL GETDRP TO DETERMINE THE NDROP DROP CANDIDATES.
C       THE DROP CANDIDATE MULTIPLIER MAGNITUDES ARE STORED
C       IN ASCENDING ORDER IN DRPLAM, WITH THE CORESPONDING
C       INDICES STORED IN IDROP.
C 
        CALL GETDRP( NX, MINEQL, MEQUAL, IVSTAT, ALMNOI, IPC,
     $               IPU, ALMBDA, INDX, SMLMLT, NDROP, IDROP,
     $               DRPLAM, ALMBIG, JER7                   )
C
        IF ( JER7 .NE. 0 ) THEN
C
          IER = 1115 + JER7
          IRETCD = -1
          IF ( IPC .GT. 0 ) THEN
             WRITE(IPU,*) ' SHURDV: AFTER GETDROP JER=', JER7
          ENDIF
          GO TO 999
        ENDIF
C
C
        IF ( IPC .GT. 0 ) THEN
          WRITE(IPU,*)
          WRITE(IPU,*)' AFTER GETDRP--NDROP,ALMBIG,RHO',
     $                  NDROP,ALMBIG,RHO
        ENDIF
C
        IF ( NDROP .EQ. 0 ) THEN
C         OPTIMALITY CONDITIONS ARE SATISFIED.
C
          IF ( IVSTAT(MEQUAL+MINEQL+1) .EQ. 1 .OR.
     $         ABS(X(MINEQL+1)) .LE. CMPERR ) THEN
C
C           OPTIMAL AND FEASIBLE.
C          
            IF ( .NOT. SMLMLT ) THEN
C             SOLUTION WITH "REASONABLE" MAGNITUDE MULTIPLIERS.
              IRETCD = 0
            ELSE
C             WEAK SOLUTION.
              IRETCD = 1
            ENDIF
C
C           RETURN
            GO TO 999
C
          ELSE
C
C           OPTIMAL SOLUTION FOR MODIFIED QP, BUT FEASIBILITY
C           VARIABLE IS NOT ZERO. INCREASE THE PENALTY WEIGHT RHO.
C
            ISQPER(6) = ISQPER(6) + 1
            RHO = 1.0D2 * RHO
C
            IF(IPC.GT.100) WRITE(IPU,947) RHO, X(MINEQL+1)
 947        FORMAT( //, 2X, ' SHURDV: INCREASING RHO TO BE=', G14.6,
     $                  3X, 'XFEAS=', G14.6, // )
C
C           UNLESS RHOMAX IS EXCEEDED, REDFINE X0, F0 AND
C           AKINVF0 TO REFLECT THE NEW RHO. THEN RE-SOLVE
C           FOR PSTEP, PI AND MULTIPLIERS FOR BOUNDS FIXED BY UPDATES.
C
            IF ( RHO .LE. RHOMAX ) THEN
C
C             X0 <-- X
C
              X0(1:NX) = X(1:NX)
              IF(IPC.GT.100) THEN
                CALL VPRIN ( NX, X0, 'NEW X0: RHO INCREASED', 21, IPU )
              ELSEIF( IPC .GT. 0 ) THEN
                WRITE(IPU,*) 'NEW X0: RHO INCREASED'
              ENDIF
C
C             CHANGE GRAD0, F0, AKIVF0 AND W TO REFLECT
C             THEIR VALUES AT THE CURRENT X: NOW, THE "NEW" X0.
C
C             GRAD0 <-- GRADIENT AT THE NEW X0 WR/ORIGINAL
C                       PROBLEM VARS.
C
              CALL GETGRD( NDIM, NX, X0(MINEQL+2), MXNZHM, IROWH,
     $                      JSTRH, HMAT, CVCT, GRAD0                 )
C
              CALL HSTMOD( K, NX, NEQNS, NDIM, KMAX, MINEQL, IPC, IPU,
     $                     GOTRHO, RHO, CHI, X0, IFREE0, BL, BU, INSHUR,
     $                     ITPSHR, F0, GRAD0,W, AKIVF0, SOLVTL, NWKKT,
     $                     WORKKT, JER6         )
C
C
              IF ( JER6 .NE. 0 ) THEN
C
                IER = 1120 + JER6
                IRETCD = -1
                IF ( IPC .GT. 0 ) THEN
                  WRITE(IPU,*) ' SHURDV: 1ST HSTMOD JER=', JER6
                ENDIF
                GO TO 999
              ENDIF
C
C             RE-SOLVE FOR PSTEP, PI AND UPDATE-FIXED MULTIPLIERS.
C
              GO TO 110
C
            ELSE
C             RETURN WITH RETURN CODE FOR WHAT MAY BE AN
C             INFEASIBLE PROBLEM.
C
              IRETCD = 3
              GO TO 999
            ENDIF
C           END OF ( RHO .LT. RHOMAX ) BLOCK
C
          ENDIF
C         END OF "ELSE" BLOCK FOR OPTIMAL BUT NOT YET FEASIBLE.
C
        ENDIF
C       END OF IF ( NDROP .EQ. 0 ) BLOCK. NOTE: EVERY PATH IN THIS
C       BLOCK SHOULD LEAD EITHER TO A RETURN FROM SHURDV OR A SOLVE
C       WITH THE CURRENT SCHUR-COMPLEMENT. 
C
C       TO REACH THE CODE BELOW THERE SHOULD BE NDROP > 0 
C       ENTRIES IN THE DROP QUEUE, IDROP.
C
        IF ( NDROP .GT. 0 ) THEN
          NSHURS = NDROP
        ELSE
          IF ( IPC .GT. 0 ) THEN
            WRITE(IPU,*) ' SHURDV: NEED TO DROP BUT NDROP<=0'
          ENDIF
          IRETCD = -1
          GO TO 999
        ENDIF
C     
      ELSE
C
C       IUPTYP IS -1 OR -2, SO VAR BOUND IADD WILL BE ADDED.
C       THERE WILL BE ONLY ONE SCHUR-COMPLEMENT UPDATE/DOWNDATE.
C
        NSHURS = 1
C
      ENDIF
C     END OF THE IF ( IUPTYP .GT. 0 ) BLOCK
C
C        
C&&&  START OF UPDATE/DOWNDATE SCHUR-COMPLEMENT FACTORIZATION LOOP.
C
      ISQPER(7) = MAX(ISQPER(7),MAXDRP)
      IF(IUPTYP.GT.0) THEN
        ISQPER(8) = MAX(ISQPER(8),NSHURS)
        ISQPER(9) = ISQPER(9) + 1
        ISQPER(11) = ISQPER(11) + NSHURS
      ENDIF
C
C
C     ENSURE THAT A MAXIMUM OF MAXDRP VARS ARE DROPPED
C
      LWLOOP = MAX( 1, NSHURS - MAXDRP + 1 )
C
C     DRPFES INDICATES THAT THE FEASIBILITY VAR WAS FREED FROM
C     ITS UPPER BOUND (1.0) AS PART OF THE CURRENT SET OF UPDATES.
C
      DRPFES = .FALSE.
C
      DO I = NSHURS, LWLOOP, -1
C
        ITNSHR = ITNSHR + 1
C
        IF ( IUPTYP .GT. 0 ) THEN
C
C         DROP CONSTRAINT IDROP(I). THUS, JVAR <-- IDROP(I),
C         WHERE JVAR IS THE VARIABLE BOUND TO UPDATE.
C         ALSO, UPDATE IVSTAT.
C
          JVAR = IDROP(I)
          IVSTAT( MEQUAL + JVAR ) = 0
C
C
          IF ( IPC .GT. 0 )THEN
            WRITE(IPU,*)
            WRITE(IPU,*) ' DROP LOOP--JVAR, ABS(LAMBDA)' 
     $         , JVAR, DRPLAM(I)
            WRITE(IPU,*)
          ENDIF
C
        ELSE
C
C         IUPTYP IS -1 OR -2, SO VAR BOUND IADD WILL BE ADDED.
C         THUS, JVAR <-- IADD, WHERE JVAR IS THE VARIABLE BOUND
C         TO UPDATE. ALSO, UPDATE IVSTAT.
C
          JVAR = IADD
          IVSTAT( MEQUAL + JVAR ) = ABS(IUPTYP)
C
        ENDIF
C
        IF ( IPC .GT. 100 ) THEN
          CALL IVPRIN( NX, IVSTAT(MEQUAL+1), 'STATE OF X AFTER CHANGE',
     $                 23, IPU )
        ENDIF
C
C       ---DETERMINE WHETHER TO PERFORM AN UPDATE OR A DOWNDATE
C       TO THE SCHUR-COMPLEMENT FACTORIZATION. THEN, DO IT.
C
C               {-KK, IF JVAR WAS SET TO A BOUND AT UPDATE KK
C       KPAST = {  0, IF JVAR NOT CURRENTLY UPDATED.
C               { KK, IF JVAR WAS FREED AT UPDATE KK
C
        KPAST = IFREKT(JVAR)
C
C       ITYPE0 <-- THE VALUE OF IFREE0(JVAR), WHERE
C                  IFREE0 INDICATES STATUS AT X0.
C
        ITYPE0 = IFREE0(JVAR)
C
        IF ( KPAST .EQ. 0 .AND. K .LT. KMAX ) THEN
C
C         ---PERFORM AN UPDATE.
C
C         CALL UVGET  WHICH GIVES VALUES TO SIGMA AND THE VECTORS
C         U AND V FOR A SCHUR-COMPLEMENT UPDATE WITH TYPE INDICATED
C         BY THE VALUE OF IUPTYP. IN ADDITION A SPARSE STORAGE
C         VERSION OF U, WITH NZUVEC NONZEROS, IS STORED IN UVEC
C         AND IRWUVC.
C
          CALL UVGET ( IUPTYP, JVAR, MINEQL, MEQUAL, NROW,
     $                NDIM, IPC, IPU, NEQNS, NX, K, KMAX,
     $                NFREE0, IFREE0, IFREKT, SFEZ,
     $                MXNZAM, JSTRA, IROWA, AMAT,
     $                MXNZHM, JSTRH, IROWH, HMAT, U, NZUVEC,
     $                UVEC, IRWUVC, V, CHI, SIGMA, JER3  )
C
C
          IF ( JER3 .NE. 0 ) THEN
C
            IER = 1130 + JER3
            IRETCD = -1
            IF ( IPC .GT. 0 ) THEN
              WRITE(IPU,*) ' SHURDV: AFTER UVGET JER=', JER3
            ENDIF
            GO TO 999
          ENDIF
C
C         QUIT IF THERE WILL NOT BE ENOUGH ROOM IN UMAT AND IROWU
C         FOR THE NEW UPDATE.
C
          IF ( K .EQ. 0 ) THEN
            NZUMAT = 0
          ELSE
            NZUMAT = JSTRU(K+1) - JSTRU(1) 
          ENDIF
C
          NDUMAT = NZUMAT + NZUVEC + 1 - MXNZUM
C
          IF ( NDUMAT .GT. 0 ) THEN
            IRETCD = 9
            IF ( IPC .GT. 0 ) THEN
              WRITE(IPU,*) ' SHURDV: WARNING, UPDATES STOPPED! ',
     $                      'UMAT AND IROWU NEEDED ',
     $                      NDUMAT, ' MORE STORAGE'
            ENDIF
            GO TO 999
          ENDIF
C
C
C         DROPPING THE FEASIBILITY VAR REQUIRES SETTING A
C         NEW VALUE FOR CHI, SO DETECT THIS CASE. DPFSUP
C         IS TRUE IF THE FEASIBILITY VAR IS DROPPED AT THE 
C         CURRENT UPDATE. DRPFES IS TRUE IF ANY ONE OF THE
C         NDROP DROPS IS THE FEASIBILITY VARIABLE.
C
          IF ( IUPTYP .GT. 0 .AND. JVAR .EQ. MINEQL+1 ) THEN
            DPFSUP = .TRUE.
            DRPFES = .TRUE.
          ELSE
            DPFSUP = .FALSE.
          ENDIF
C
C         CALL SHURUP TO UPDATE THE SCHUR-COMPLEMENT MATRIX SHURC
C         AND PRESERVE A COPY IN SHRCSV. THE COPY IS NEEDED BECAUSE
C         THE FACTORIZATION ROUTINE MODIFIES SHURC.
C
          CALL SHURUP( NEQNS, IPC, IPU, K, KMAX, U, V, SIGMA, SOLVTL,
     $                 DPFSUP, KPVT, SHRCSV, SHURC, MXNZUM,
     $                 IROWU, JSTRU, UMAT, WRKBIG, NWKKT, WORKKT,  
     $                 T, GAMMA, CHI, GOTCHI, JER4  )
C
C
          IF ( JER4 .NE. 0 ) THEN
C
            IER = 1140 + JER4
            IRETCD = -1
            IF ( IPC .GT. 0 ) THEN
              WRITE(IPU,*) ' SHURDV: AFTER SHURUP JER=', JER4
            ENDIF
            GO TO 999
          ENDIF
C
C
C         COMPUTE RHSNEW, THE RHS ENTRY CORRESPONDING TO THE
C         CURRENT UPDATE.
C
          IF ( IUPTYP .GT. 0 ) THEN
C
C           FREEING VARIABLE JVAR. RHSNEW IS COMPONENT JVAR
C           OF THE GRADIENT AT X0 OF EXPANDED PROBLEM.
C
            IF ( JVAR .LE. MINEQL ) THEN
              RHSNEW = ZERO
            ELSEIF ( JVAR .EQ. MINEQL+1 ) THEN
C             NOTE: GOTRHO MUST BE TRUE IF THIS BRANCH IS TAKEN.
              RHSNEW = RHO + CHI*X0(MINEQL+1)
            ELSE
C             AN ORIGINAL PROBLEM VARIABLE.
              RHSNEW = GRAD0( JVAR - (MINEQL+1) )
            ENDIF
C
          ELSEIF ( IUPTYP .LT. 0 ) THEN
C
C           FIXING VARIABLE JVAR.
C
            RHSNEW = X0(JVAR) - X(JVAR)
C
          ENDIF
C
C         CALL STORUP TO UPDATE THE STORAGE FOR UMAT AND
C         W (THE RIGHT-HAND-SIDE ENTRIES CORRESPONDING TO
C         THE UPDATES.) AS A FINAL STEP K IS SET TO K+1.
C
          CALL STORUP( NEQNS, K, KMAX, RHSNEW,
     $                 UVEC, NZUVEC, IRWUVC,
     $                 W, MXNZUM, JSTRU, IROWU, UMAT )
C
C
C         NOW UPDATE THE VECTORS THAT STORE SCHUR-COMPLEMENT UPDATE
C         INFO; ITPSHR, INSHUR AND IFREKT.
C
          ITPSHR(K) = IUPTYP
          INSHUR(K) = SIGN( JVAR, IUPTYP )
          IFREKT(JVAR) = SIGN( K, IUPTYP )
C
C
C                        T
C         COMPUTE THE RDR  FACTORIZATION OF THE SCHUR-COMPLEMENT
C                             T    -1
C         MATRIX SHURC = V - U (K0)  U, WHERE SHURC IS K BY K,
C         U IS AN NEQNS BY K MATRIX AND V IS A K BY K MATRIX.
C
          ISQPER(4) = ISQPER(4) + 1
          ISQPER(5) = MAX(ISQPER(5),K)
          CALL DSICO( SHURC, KMAX, K, KPVT, RCOND, WRKSML )
C
          IF ( IPC .GT. 0 ) THEN
            WRITE(IPU,*) ' RCOND AFTER UPDATE:', RCOND, '  K=', K
          ENDIF
C
          IF ( RCOND .LT. CNDTOL ) THEN
C                                          T
C           INVERSE CONDITION NUMBER OF RDR  IS TOO SMALL. RETURN
C           FOR A NEW KT FACTORIZATION AND HOPE THAT IT IS OK.
C
            BADCND = .TRUE.
          ENDIF
C
C
C         IS THE KT SYSTEM INERTIA STILL OK?
C
          CALL INRTCK( K, KMAX, IPU, IPC, SHURC, KPVT,
     $                  ITPSHR, INRTER )
C
          IF ( INRTER .NE. 0 ) THEN
            IRETCD = 11
            IF ( IPC .GT. 0 ) THEN
              WRITE(IPU,*) ' SHURDV: KT INERTIA WENT BAD, IRETCD = 11'
            ENDIF
            GO TO 999
          ENDIF
C
C
        ELSEIF ( KPAST .EQ. 0 .AND. K .EQ. KMAX ) THEN
C
C         AN UPDATE IS NEEDED BUT WILL EXCEED THE LIMIT ON UPDATES.
C
          UPLIM = .TRUE.
C
        ELSEIF( (KPAST .GT. 0 .AND. IUPTYP .LT. 0) .OR. 
     $          (KPAST .LT. 0 .AND. IUPTYP .GT. 0) ) THEN
C
C         ---PERFORM A DOWNDATE
C
C         TEST TO SEE IF A "HISTORY CHANGE" MUST BE PERFORMED
C         PRIOR TO DOWNDATING. (THIS IS THE PRICE OF SAVING ONE
C         KT SYSTEM SOLVE PER UPDATE).
C         A HISTORY CHANGE IS NEEDED IF A VAR WAS FIXED AT
C         BOUND AT X0, THEN FREED AND WAS JUST SET TO THE
C         OPPOSITE BOUND. A HISTORY CHANGE IS ALSO NEEDED IF
C         A VAR WAS FIXED AT X0, THEN A HISTORY CHANGE OCURRED,
C         AND THEN THE VAR WAS FIXED AGAIN (AT EITHER BOUND).
C         TO BE SAFE, A HISTORY CHANGE IS DONE WHENEVER
C         AN INITIALLY FIXED VAR RETURNS TO THE FIXED STATE.
C         A HISTORY CHANGE AFFECTS X0, GRAD0, IFREE0, F0,
C         AKIVF0 AND W.
C
          IF ( IUPTYP .LT. 0 ) THEN
C
C           MUST PERFORM A "HISTORY CHANGE".
C
            IFREE0(JVAR) = IUPTYP
C
C           X0 <-- X
C
            X0(1:NX) = X(1:NX)
C
            IF ( IPC .GT. 100 ) THEN
              CALL VPRIN ( NX, X0, 'NEW X0: HIST MOD', 16, IPU )
            ELSEIF ( IPC .GT. 0 ) THEN
              WRITE(IPU,*) 'NEW X0: HIST MOD'
            ENDIF
C
C           CHANGE GRAD0, F0, AKIVF0 AND W TO REFLECT THEIR VALUES AT
C           THE CURRENT X: NOW, THE "NEW" X0.
C
C           GRAD0 <-- GRADIENT AT THE NEW X0 WR/ORIGINAL PROBLEM VARS.
C
            CALL GETGRD( NDIM, NX, X0(MINEQL+2), MXNZHM, IROWH,
     $                    JSTRH, HMAT, CVCT, GRAD0                 )
C
            CALL HSTMOD( K, NX, NEQNS, NDIM, KMAX, MINEQL, IPC, IPU,
     $                   GOTRHO, RHO, CHI, X0, IFREE0, BL, BU, INSHUR,
     $                   ITPSHR, F0, GRAD0, W, AKIVF0, SOLVTL,
     $                   NWKKT, WORKKT, JER8   )
C
C
            IF ( JER8 .NE. 0 ) THEN
C
              IER = 1150 + JER8
              IRETCD = -1
              IF ( IPC .GT. 0 ) THEN
                WRITE(IPU,*) ' SHURDV: 2ND CALL TO HSTMOD JER=', JER8
              ENDIF
              GO TO 999
            ENDIF
C
          ENDIF
C
C
C         CALL SHURDN TO UNDO THE JUP-TH SCHUR-COMPLEMENT
C         UPDATE (THUS REDUCING K TO K-1). SHURDN DELETES
C         ROW AND COLUMN JUP FROM MATRICES SHURC AND SHRCSV
C         RESULTING IN K-1 DIMENSIONAL MATRICES. SHURDN ALSO
C         DOWNDATES STORAGE FOR W, UMAT, IFREKT, ITPSHR
C         AND INSHUR. AS A FINAL STEP, SHURDN SETS K = K-1.
C   
C         CALL SHURDN TO DOWNDATE THE SCHUR-COMPLEMENT MATRIX SHURC
C         AND PRESERVE A COPY IN SHRCSV. THE COPY IS NEEDED BECAUSE
C         THE FACTORIZATION ROUTINE MODIFIES SHURC.
C
          JUP = ABS(KPAST)
C
          IF ( IPC .GT. 0 ) THEN
            WRITE(IPU,*)
            WRITE(IPU,*) ' UNDOING UPDATE NUMBER =', JUP
            WRITE(IPU,*)
          ENDIF
C
          CALL SHURDN( JUP, NEQNS, NX, K, KMAX, IPC, IPU, SHURC,
     $                 SHRCSV, IUPTYP, IFREE0, INSHUR,
     $                 IFREKT, ITPSHR, MXNZUM,
     $                 JSTRU, IROWU, UMAT, W, JER5               )
C
C
          IF ( JER5 .NE. 0 ) THEN
C
            IER = 1160 + JER5
            IRETCD = -1
            IF ( IPC .GT. 0 ) THEN
              WRITE(IPU,*) ' SHURDV: AFTER SHURDN JER=', JER5
            ENDIF
            GO TO 999
          ENDIF
C
C
          IF ( K .GT. 0 ) THEN
C
CBUG
C           COMPUTE AND PRINT THE DENSE (DEBUG) VERSION OF
C           THE SCHUR COMPLEMENT FOR DEBUGGING.
C
C            CALL SHURBUG( NEQNS, IPC, IPU, K, KMAX,
C     $                    NWKKT, WORKKT           )
C
CBUG
C
C                          T
C           COMPUTE THE RDR  FACTORIZATION OF THE SCHUR-COMPLEMENT
C                               T    -1
C           MATRIX SHURC = V - U (K0)  U, WHERE SHURC IS K BY K,
C           U IS AN NEQNS BY K MATRIX AND V IS A K BY K MATRIX.
C
            ISQPER(4) = ISQPER(4) + 1
            ISQPER(5) = MAX(ISQPER(5),K)
            CALL DSICO( SHURC, KMAX, K, KPVT, RCOND, WRKSML )
C  
            IF( IPC .GT. 0 ) THEN
              WRITE(IPU,*) ' RCOND AFTER DOWNDATE:', RCOND, '  K=', K
            ENDIF
C
            IF ( RCOND .LT. CNDTOL ) THEN
C                                            T
C             INVERSE CONDITION NUMBER OF RDR  IS TOO SMALL. RETURN
C             FOR A NEW KT FACTORIZATION AND HOPE THAT IT IS OK.
C
              BADCND = .TRUE.
            ENDIF
C
C
C           IS THE KT SYSTEM INERTIA STILL OK?
C
            CALL INRTCK( K, KMAX, IPU, IPC, SHURC, KPVT,
     $                    ITPSHR, INRTER )
C
            IF ( INRTER .NE. 0 ) THEN
              IRETCD = 11
              IF ( IPC .GT. 0 ) THEN
                WRITE(IPU,*)' SHURDV: KT INERTIA WENT BAD, IRETCD = 11'
              ENDIF
              GO TO 999
            ENDIF
C
          ENDIF
C
        ELSEIF ( KPAST .GT. 0 .AND. IUPTYP .GT. 0 ) THEN
C
C         ERROR: FREEING A VARIABLE FREED PREVIOUSLY BY AN UPDATE.
C                (A DOWNDATE SHOULD HAVE "ERASED" THE UPDATE
C                 WHEN THE VAR WAS FIXED AGAIN. )
C
          IER = 1170
          IRETCD = -1
          IF ( IPC .GT. 0 ) THEN
            WRITE(IPU,*) ' SHURDV: 2 FREEING UPDATES IN A ROW FOR VAR',
     $                   ' NO. =', JVAR
          ENDIF
          GO TO 999
C
        ELSEIF ( KPAST .LT. 0 .AND. IUPTYP .LT. 0 ) THEN
C
C         ERROR: FIXING A VARIABLE FIXED PREVIOUSLY BY AN UPDATE.
C                (A DOWNDATE SHOULD HAVE "ERASED" THE UPDATE
C                 WHEN THE VAR WAS FREED AGAIN. )
C
          IER = 1175
          IRETCD = -1
          IF ( IPC .GT. 0 ) THEN
            WRITE(IPU,*) ' SHURDV: 2 FIXING UPDATES IN A ROW FOR VAR',
     $                   ' NO. =', JVAR
          ENDIF
          GO TO 999
C
        ENDIF
C
C
C
C       ---DECIDE WHETHER TO CONTINUE IN THE SCHUR-COMPLEMENT
C       UPDATE-DOWNDATE LOOP OR RETURN FOR A NEW KT MATRIX
C       FACTORIZATION.
        IF ( UPLIM ) THEN
C
C         HIT UPDATE LIMIT. RETURN FOR A NEW KT FACTORIZATION.
C
          IRETCD = 4
          GO TO 999
C
        ELSEIF ( ITNSHR .GE. MAXITN ) THEN
C
C         HIT INNER UPDATE/DOWNDATE ITERATION LIMIT.
C         POSSIBLE CYCLING, RETURN FOR REMEDIAL ACTION.
C
          IRETCD = 10
          GO TO 999
C
        ELSEIF ( BADCND ) THEN
C
C         TOO SMALL AN INVERSE CONDITION NUMBER HAS BEEN
C         ESTIMATED FOR THE SCHUR-COMPLEMENT FACTORIZATION.
C         RETURN FOR A NEW KT FACTORIZATION.
C
C         DETERMINE IF THIS IS A CASE WHERE THE FEASBILITY VAR IS FREE.
C         THE RESULT COULD BE DUE TO THE FAILURE OF THE INCLUSION OF
C         SFEZ INTO THE JACOBIAN IN PREVENTING ILL-CONDITIONING, WHEN
C         NEW "REAL" CONSTRAINTS WERE ADDED TO THE ACTIVE SET.
C
          IF ( IVSTAT(MEQUAL+MINEQL+1) .EQ. 0 ) THEN
            IRETCD = 13
          ELSE
            IRETCD = 5
          ENDIF
C
          GO TO 999
C
        ENDIF
C
      enddo
C&&&  END OF UPDATE/DOWNDATE SCHUR-COMPLEMENT FACTORIZATION LOOP.
C         
      GO TO 110
C**** END OF SCHUR-COMPLEMENT QP SOLUTION LOOP.
C
C
 999  CONTINUE
C
      ISQPER(2) = ISQPER(2) + ITNSHR
C
      IF ( IPC .GT. 0 ) THEN
        WRITE(IPU,*)
        WRITE(IPU,*)' SHURDV: IRETCD =', IRETCD
        WRITE(IPU,*)
C
        CALL GETOBJ( NDIM, X(MINEQL+2), MXNZHM, IROWH,
     $                 JSTRH, HMAT, CVCT, WRKBIG, OBJ   )
C
        WRITE(IPU,*) ' OBJECTIVE AT XFINAL = ', OBJ
C
        IF(IPC.GT.10) CALL VPRIN ( NX, X, 'FINAL X', 7, IPU )
      ENDIF  
C
      RETURN
      END
