
C
C
C
      SUBROUTINE STORUP( NEQNS, K, KMAX, RHSNEW,
     .                   UVEC, NZUVEC, IRWUVC,
     .                   W, MXNZUM, JSTRU, IROWU, UMAT )
C
C ======================================================================
C     STORUP===>storup   J.T. BETTS
C ======================================================================
C
C     ROUTINE TO UPDATE THE STORAGE FOR UMAT AND
C     W (THE RIGHT-HAND-SIDE ENTRIES CORRESPONDING TO
C     THE UPDATES.) AS A FINAL STEP K IS UPDATED TO K+1.
C     NOTE: IT IS ASSUME THAT THE NEW COLUMN OF UMAT IS INPUT
C           IN SPARSE STORAGE FORM IN VECTOR UVEC.
C
      DOUBLE PRECISION ZERO
      PARAMETER ( ZERO = 0.0D0 )
C
      INTEGER K, INONZ, NEQNS, I
      INTEGER NZUVEC
      INTEGER KMAX, MXNZUM
C
      INTEGER IRWUVC(NEQNS)
      INTEGER JSTRU(KMAX+1), IROWU(MXNZUM)
C
      DOUBLE PRECISION RHSNEW
      DOUBLE PRECISION UVEC(NEQNS), W(KMAX)
      DOUBLE PRECISION UMAT(MXNZUM)
C
C
      W(K+1) = RHSNEW
C
C
      IF ( K .EQ. 0 ) THEN 
        JSTRU(1) = 1
      ENDIF
C
      INONZ = JSTRU(K+1) - 1
C
      DO I = 1, NZUVEC
          INONZ = INONZ + 1
          IROWU(INONZ) = IRWUVC(I)
          UMAT(INONZ) = UVEC(I)
      enddo
C
C     JSTRU(K+1) WAS 1 LOCATION BEYOND THE STORAGE FOR THE NONZEROS
C     OF UMAT. JSTRU(K+1) IS NOW THE START LOCATION FOR STORING THE
C     IN COLUMN K+1 OF UMAT. JSTRU(K+2), WHICH WILL BECOME
C     JSTRU(K+1) WHEN K IS INCREASED BY ONE, IS NOW SET 1 LOCATION
C     BEYOND THE STORAGE FOR UMAT.
C
      JSTRU(K+2) = INONZ + 1
C
      K = K + 1
C
C
      RETURN
      END
