      subroutine   xdslvg   ( unsym , savea , nsuper, nnzero, xsup  ,
     1                        xrelin, relind, rowlst, values,
     2                        sqfile, sqtrn , error )

c
c
c     ==================================================================
c     ====  xdslvg -- restores matrices written to disk             ====
c     ==================================================================
c     ==================================================================
c
c     purpose
c     -------
c
c     xdslvg restores matrices written to disk by the out-of-memory 
c     processing performed by subroutine xdslvo.
c
c     created         15-oct-97   -- rgg --
c     last modified   
c
c     input arguments
c     ---------------
c
c     unsym       l   symmetric/unsymmetric logical flag
c     savea       l   save matrix logical flag
c     nsuper      i   number of super nodes
c     nnzero      i   size of relind, rowlst and values arrays.
c     xsup        i   supernode partition array
c     xrelin      i   pointer array into relative assembly indices
c     sqfile      i   sequential i/o unit which holds the
c                     matrix representation generated by xdslvo
c
c     input/output arguments
c     ----------------------
c
c     sqtrn       d   amount of i/o transfers on sqfile
c
c     output arguments
c     ----------------
c
c     relind      i   relative assembly indices
c     rowlst      i   permuted row indicies     
c     values      d   buffer to hold the permuted matrix values
c     error       i   error flag, = -1 data being read exceeds
c                                 = -2 i/o error on sqfile
c
c     ==================================================================
 
c     --------------
c     ... parameters
c     --------------
 
      integer             nsuper, nnzero, sqfile, error

      logical             unsym , savea
 
      integer             xsup   (*), xrelin (*),
     1                    relind (*), rowlst (*)

      double precision    sqtrn  

      double precision    values (*)

c     -------------------
c     ... local variables
c     -------------------
 
      integer             innz  , isuper, jbgn  , jend  , k     , 
     2                    nnz   

      integer             xdslni

      external            xdslni
 
c     ==================================================================

      error  = 0

      call xislrw ( sqfile, error )
      if ( error .ne. 0 ) go to 8100

c     -----------------------------
c     ... loop over all super nodes
c     -----------------------------

      do isuper = 1, nsuper

          jbgn   = xsup(isuper)
          jend   = xsup(isuper+1) - 1

          k      = xrelin(jbgn)
          nnz    = xrelin(jend+1) - xrelin(jbgn)

          if ( nnz .eq. 0 ) cycle

c.debug
c     write(6,'("in xdslvg at start of 600 loop")')
c     write(6,'("isuper, k    , nnz     = ", 3i8)')
c    1            isuper, k    , nnz
c     write(6,'("sqfile                 = ", 3i8)')
c    1            sqfile    
c     write(6,'("jbgn  , jend           = ", 3i8)') 
c    1            jbgn  , jend          
c.debug

          if ( k + nnz - 1 .gt. nnzero ) go to 8000

c         --------------------------------
c         ... read in the data from sqfile
c         --------------------------------

          innz = xdslni(nnz)

          if ( savea ) then 

              call xislvr ( sqfile, nnz, rowlst(k), error )
              if ( error .ne. 0 ) go to 8100

              sqtrn = sqtrn + innz 

          end if

          call xislvr ( sqfile, nnz, relind(k), error )
          if ( error .ne. 0 ) go to 8100

          call xdslvr ( sqfile, nnz, values(k), error )
          if ( error .ne. 0 ) go to 8100
c.debug
c         write(6,'("data for super node ", i8)') isuper
c         if ( savea ) then
c         call xislp3 ( 'row      indicies', nnz, rowlst(k), 6 )
c         end if
c         call xislp3 ( 'relative indicies', nnz, relind(k), 6 )
c         call xdslp5 ( 'values           ', nnz, values(k), 6 )
c.debug

          sqtrn = sqtrn + innz + nnz

      enddo

      go to 9000

c-----------------------------------------------------------------------

c     -------------------------------------------------------
c     ... amount of data to be read exceeds allocated storage
c     -------------------------------------------------------

 8000 continue
      error = -1
      go to 9000

c     -----------------------
c     ... i/o error on sqfile
c     -----------------------

 8100 continue
      error = -2
      go to 9000

c-----------------------------------------------------------------------

 9000 return
      end
